- src/components/BaseModal/BaseModal.js
- src/components/__snapshots__/StorybookSnapshots-test.js.snap
**Summary**
- See bug 15
- fix(basemodal): only render helpText if its passed
- Closes IBM/carbon-addons-iot-react#15
- Make sure the helpText paragraph doesn't render if no helpText is passed
> fix(modal): if helptext isn't set don't render it

- src/components/Table/Table-story.js
- src/components/Table/Table.js
- src/components/__snapshots__/StorybookSnapshots-test.js.snap
- src/styles/styles.js
- yarn.lock
**Summary**
Support for "row actions" (buttons in last column of table).  The overflow design is still being finalized, so with this implementation all buttons are visible.
(see PR)
(none)
- View stateful story and `row expansion and actions` story and verify.
> feat(table): row actions

- src/components/BaseModal/BaseModal-story.js
- src/components/BaseModal/BaseModal.js
- src/components/__snapshots__/StorybookSnapshots-test.js.snap
**Summary**
- add prop, icondescription, that provides ability to enter translated strings.
- <BaseModal>
- go to the story that add an icon description and hover over close icon.
> Add ability to provide translation strings to close icon

- src/components/Table/Table.js
- src/components/__snapshots__/StorybookSnapshots-test.js.snap
**Summary**
- Only show row actions on table row hover, or when the row is expanded
- Run stateful example in storybook and verify behavior.
> feat(table): only show row extra options on row hover or expansion

- package.json
- src/components/Table/Table-story.js
- src/components/Table/Table.js
- src/components/__snapshots__/StorybookSnapshots-test.js.snap
- src/styles/styles.js
- yarn.lock
**Summary**
- Adds an empty state to the table, configurable via a custom node if desired.
- Include `@carbons/icons-react` for access to new `Bee` icon
-  This should be our new source of truth for icons. It can live alongside existing `carbon-icons` until we fully update to Carbon v10
- Add Empty state to table
- Update stories
- Update snapshots
- Closes IBM/carbon-addons-iot-react#8
- Storybook Stateful example should show proper empty state when all items are deleted
- Storybook `with no data` story should also properly render empty state with default action
> feat(table): add empty state

- .github/CODEOWNERS
- src/components/ProgressIndicator/ProgressIndicator.jsx
- src/components/ProgressIndicator/ProgressStep.jsx
- src/components/WizardModal/WizardModal.jsx
- src/components/WizardModal/WizardModal.test.jsx
- src/components/__snapshots__/StorybookSnapshots.test.js.snap
**Summary**
Add interactivity to the steps of the wizardmodal.
- Refactor the ProgressStep component to more easily be replaced by the Carbon one once they integrate my interactivity PR
- Refactor the WizardModal to use the ProgressIndicator/ProgressStep with Interactivity
- Verify that the WizardModal can now click on the ProgressSteps to advance.
> refactor(wizardmodal): reuse the progressindicator with interactivity

- src/components/HeaderMenu/__snapshots__/HeaderMenu.test.jsx.snap
- src/components/Table/StatefulTable.jsx
- src/components/Table/StatefulTable.test.jsx
- src/components/Table/Table.jsx
- src/components/Table/Table.story.jsx
- src/components/Table/TablePropTypes.js
- src/components/Table/TableToolbar/TableToolbar.jsx
- src/components/Table/tableActionCreators.js
- src/components/Table/tableReducer.js
- src/components/Table/tableReducer.test.js
- src/components/__snapshots__/StorybookSnapshots.test.js.snap
**Summary**
- Use options.hasSearch to enable a simple quick search in both the presentation layer and stateful table layer
- feat(tableReducer): add new action and reducer for simple search
- feat(Table): Add simple search
- Closes IBM/carbon-addons-iot-react#52
- Test the new quick search box in the Stateful Table story
> feat(table): add quick search capability

- src/components/Table/Table.jsx
- src/components/Table/TableBody/TableBodyRow/TableBodyRow.jsx
- src/components/Table/baseTableReducer.js
- src/components/Table/tableActionCreators.js
- src/components/Table/tableReducer.js
- src/components/Table/tableReducer.test.js
- src/index.js
- yarn.lock
**Summary**
- Split out the exported table reducer into two:
- *baseTableReducer* contains all simple view logic (everything but sorting, filtering, searching)
- *tableReducer* handles sorting/filtering/searching, and passes actions down to baseTableReducer
(see commits in PR)
n/a
- Verify stateful component behaves as expected.
> feat(table): split out table reducer functionality

- src/components/Table/StatefulTable.jsx
**Summary**
- Fixes if consumers have empty array of data that is updated with real data array, which currently causes a `Warning: The final argument passed to useEffect changed size between renders. The order and size of this array must remain constant.`
> fix(table): correct usage of useEffect for stateful table

- src/components/Table/TableBody/TableBodyRow/TableBodyRow.test.jsx
- src/components/Table/TableCellRenderer/TableCellRenderer.jsx
**Summary**
- Allow `undefined` to be passed as column data for a row.  Example:
```
{
id: 'row-1',
values: {
'column1': 42,
'column2': undefined,
'column3': 'abc'
}
}
```
(see commit list)
> fix(table): table won't render if data in row for a column is undefined

- src/components/BaseModal/BaseModal.jsx
- src/components/Table/StatefulTable.jsx
- src/components/Table/StatefulTable.test.jsx
- src/components/Table/tableActionCreators.js
- src/components/Table/tableReducer.js
- src/components/Table/tableReducer.test.js
**Summary**
- Taylor found a bug where if you change the data passed to the table after it renders the first time, it never updates to show the new data
- Fixed the tableRegister action to take the current data as a payload and update accordingly
- Added a testcase to cover this scenario
- Run through the automated testcases
> fix(statefultable): tableRegister action should dispatch payload with latest data

- src/components/Table/TablePropTypes.js
**Summary**
We need the ability to specify a custom icon not available in Carbon's library
- allows us to specify icons for row actions by string, object, or pass a node directly
- this is the same proptypes as defined by carbon's button, which ultimately receives these props
> fix(tablerowaction): icon proptype accepts same as carbon Button

- src/components/StructuredList/StructuredList.jsx
- src/components/StructuredList/StructuredList.story.jsx
- src/index.js
**Summary**
- I have added the ability, like in the Table, to provide a per-column width in order to provide greater rendering control to the component user.
Example in context:
- Verify the new 'fixed width' story.
> feat(list): add fixed column width option

- src/components/NavigationBar/NavigationBar.jsx
- src/styles/styles.js
**Summary**
- the navigation area wasn't extending the tab content all the way down to the bottom of the screen, leading to a color mismatch
- Test the navigation bar fixtures and notice the tab content color should now extend down to the bottom of the screen and not map to the content
> fix(navigation): small fix to page styles

- src/components/BaseModal/BaseModal.jsx
- src/components/BaseModal/BaseModal.story.jsx
- src/components/BaseModal/BaseModal.test.jsx
- src/components/Table/tableReducer.js
**Summary**
- feat(basemodal): simplify error props for basemodal and fix tablereducer bug.
- feat(basemodal): Instead of taking two sets of error props only take one for base modal
- fix(tablereducer): check for null values before searching
- Verify the searching of table still works and the error props still work in the basemodal
> refactor(modal): update props to simplify it

- src/components/Table/Table.jsx
- src/components/Table/Table.story.jsx
**Summary**
- Just turning on pagination on the horizontal scrolling examples so we can show how that renders relative to the table container contents
> docs(scrolling): add pagination to horizontal scrolling storybook

- src/components/Table/Table.jsx
- src/components/Table/Table.test.jsx
- src/components/Table/tableReducer.js
- src/components/Table/tableReducer.test.js
- src/utils/__tests__/componentUtilityFunctions.test.js
- src/utils/componentUtilityFunctions.js
**Summary**
- test(reducer): add testcases that confirm that sort works on numeric correctly
- fix(table): after initial search table is empty
- fix(table): should clear both search and filter from empty state
- Closes IBM/carbon-addons-iot-react#51
- you can just run the testcases
> fix(table): after initial search table is empty and clear search from empty state not working

- package.json
- src/components/WizardInline/StatefulWizard.test.jsx
- src/components/WizardInline/StatefulWizardInline.jsx
- src/components/WizardInline/WizardHeader/WizardHeader.jsx
- src/components/WizardInline/WizardInline.jsx
- src/components/WizardInline/WizardInline.story.jsx
- src/index.js
**Summary**
- It's up to the consuming component to either set the new WizardInline error prop to indicate the form error to the user, or perhaps to indicate the error next to the failed form element itself.
- Check the testcases which validate the step doesn't change if validate fails
- View the new example error story for WizardInline
> feat(wizardinline): add optional validation that can be executed for each step

- package.json
- src/components/TileCatalog/StatefulTileCatalog.jsx
- src/components/TileCatalog/StatefulTileCatalog.test.jsx
- src/components/TileCatalog/tileCatalogReducer.js
- src/components/TileCatalog/tileCatalogReducer.test.js
- src/index.js
- yarn.lock
**Summary**
- refactor(tilecatalog): use reducer instead of useEffect and useState for the state management.  This fixes bugs where the tilecatalog wasn't working correctly when you were on the second page
- regression test the TileCatalog stories in the storybook
> refactor(tilecatalog): use reducer for state management

- src/components/TileCatalog/tileCatalogReducer.js
- src/components/TileCatalog/tileCatalogReducer.test.js
**Summary**
- Bug on the tile selections where if you were on the secondary page of a tile catalog, the selection wasn't being preserved
- Verify the tile catalog stories for search and page behavior with selection
> fix(tilecatalog): selections don't work correctly

- src/components/TileCatalog/StatefulTileCatalog.jsx
- src/components/TileCatalog/StatefulTileCatalog.test.jsx
- src/components/TileCatalog/tileCatalogReducer.js
- src/components/TileCatalog/tileCatalogReducer.test.js
**Summary**
- Unfortunately the auto select behavior that I started with wasn't working because I couldn't get it to call back to the parent listener correctly.  For now we need to force the user to actually select the tile
- Verify the updates to the Search and Pages story, you have to manually select the tile
> fix(tilecatalog): auto select on page and search wasn't calling back to parent listener

- src/components/TileCatalog/StatefulTileCatalog.jsx
- src/components/TileCatalog/TileGroup.jsx
- src/components/TileCatalog/tileCatalogReducer.js
- src/components/WizardInline/WizardInline.jsx
**Summary**
- Needed to override the default carbon styles with our styled component styles so needed the extra layer of specificity
- fix(tilecatalog): need to generate selection event for initial selection
- fix(wizardinline): should take up full available width for content
- It's pretty hard to test without consuming this in another project unfortunately.
> fix(tilegroup): small fix for styles to work with carbon

- src/components/WizardInline/WizardInline.jsx
**Summary**
- Luke says the wizard should always stay the same size on screen regardless of content
> fix(wizardinline): feedback that it should stay a fixed size regardless of content

- src/components/Page/PageHero.jsx
- src/components/Page/PageTitle.jsx
**Summary**
- Feedback on styles of the page hero, adjust the top padding of the title and top align all the pagehero content
- Closes IBM/carbon-addons-iot-react#157
- Check that the Page Hero stories look good
> fix(pagehero): feedback styles too much space between the title and the content

- src/components/SimplePagination/SimplePagination.jsx
- src/components/TileCatalog/StatefulTileCatalog.test.jsx
- src/components/TileCatalog/TileCatalog.jsx
**Summary**
- Add "Page 1 of 3" text option to Pagination component.  Mirror the Table PaginationV2 prop model.
- If the pageOfPagesText function is specified as a prop, call it to decide to display the text
- Don't show pagination if loading, empty or in the error state. 
- Verify the TileCatalog stories
> feat(tilecatalog): add page of pages label option

- src/components/Header/Header.story.jsx
- src/components/Page/PageHero.jsx
- src/components/Page/PageHero.story.jsx
**Summary**
- Added a feature for the blockchain team to position an image to the left of the PageHero
- feat(pagehero): add new leftContent prop
- fix(pagehero): fix positioning of the rightContent prop
- Verify the latest pagehero stories
> feat(pagehero): add optional left content for blockchain

- src/components/TileCatalog/StatefulTileCatalog.jsx
- src/components/TileCatalog/StatefulTileCatalog.test.jsx
- src/components/TileCatalog/TileCatalog.story.jsx
- src/components/TileCatalog/tileCatalogReducer.js
**Summary**
- There was a bug in statefultilecatalog where changing the selectedTileId wouldn't update the page number
- To test, view the TileCatalog with pages story and change the selectedTileId and once you try and select a selectedTileId that is past the first page, it should automatically page to the second page for you
> fix(tilecatalog): should page to the selected tile id

- src/components/Table/TableToolbar/TableToolbar.jsx
**Summary**
- fix(table): batch actions are not sending the icon description through 
- pass through all batch action props to the BatchAction
- Verify if we mouseover the batch action icons in the Table Toolbar with batch actions story that the correct alt tag shows on hover
> fix(tabletoolbar): batch actions are missing icon description

- src/components/Table/TableBody/TableBodyRow/TableBodyRow.jsx
- src/components/Table/TableHead/TableHead.jsx
**Summary**
- fixes alignment for checkboxes by just deferring the padding to the carbon styles
- remove our extra padding overrides and defer to the carbon styles 
- Closes IBM/carbon-addons-iot-react#195
- Verify that all of the stories with checkboxes align appropriately, see the bug for the previous issues with alignment.
> fix(table): checkboxes don't align in all stories between header and data

- src/components/TileCatalog/StatefulTileCatalog.jsx
- src/components/TileCatalog/TileCatalog.story.jsx
- src/components/TileCatalog/tileCatalogReducer.js
- src/components/TileCatalog/tileCatalogReducer.test.js
**Summary**
- Subtle bug where the TileCatalog was flashing the blank No Data tile before rendering the real contents when the data is loaded asynchronously.
- View the new async loaded story and make sure the No Data bee doesn't flash for a second before rendering the real data
> fix(tilecatalog): asynchronous loaded data flashes the blank tile before showing

- src/components/Table/tableReducer.js
- src/components/Table/tableReducer.test.js
**Summary**
- Fix search and filter to be case insensitive
- Closes an internal bug
- Test that the filter and search in both table and tilecatalog stories are case insensitive
> fix(table): search should be case insensitive

- src/components/Table/TableToolbar/TableToolbar.jsx
- src/components/TileCatalog/StatefulTileCatalog.jsx
**Summary**
- Refix of my previous issue to fix the flash between loading data in the tile catalog.  Also cleaning up a console error in the batch actions
- fix(table): batch actions were throwing a React warning due to passing an extra parameter to the button
- Closes IBM/carbon-addons-iot-react#197
> fix(tilecatalog): fix flash between loading data asynchronously

- src/components/Table/TableBody/TableBodyRow/TableBodyRow.jsx
**Summary**
- Due to a change for the nested table rows, the normal expanded rows have lost their background color, looks like this: 
But should have a blue background
- small fix to correctly render the background for normal expanded rows
- Verify the expanded
> fix(table): expanded rows have lost their background color

- src/components/TileCatalog/StatefulTileCatalog.jsx
- src/components/TileCatalog/tileCatalogReducer.js
- src/components/TileCatalog/tileCatalogReducer.test.js
**Summary**
- two bugs related to tile catalog with searching and paging
- fix(tilecatalog): searching and paging no longer working because of changes to selectedTileId, the fix is to no longer reset the selectedtileid on search and paging
- fix(tilecatalog): allowed to page past the final page whenever you've searched the results
- Closes internal bug on the stateful tile catalog not searching any more
- Verify that the TileCatalog stories with searching and paging work correctly
> fix(tilecatalog): search and paging is not working

- src/components/WizardInline/StatefulWizard.test.jsx
- src/components/WizardInline/WizardFooter/WizardFooter.jsx
- src/components/WizardInline/WizardFooter/WizardFooter.test.jsx
- src/components/WizardModal/WizardModal.test.jsx
**Summary**
- Hide the cancel button unless we're on the first page of the wizards
- Hide the cancel button if we're not on the first page
- Closes IBM/carbon-addons-iot-react#169
- Verify that the Wizard only shows the Cancel button if we're on the first page
> fix(wizard): hide the cancel button

- src/components/Table/AsyncTable/AsyncTable.jsx
- src/components/Table/Table.jsx
- src/components/Table/TableBody/TableBody.jsx
- src/components/Table/TableBody/TableBodyRow/TableBodyRow.jsx
- src/components/Table/TableHead/ColumnHeaderRow/ColumnHeaderRow.jsx
- src/components/Table/TableHead/ColumnHeaderRow/ColumnHeaderRow.test.jsx
- src/components/Table/TableHead/FilterHeaderRow/FilterHeaderRow.jsx
- src/components/Table/TableHead/TableHead.jsx
- src/components/Table/TableSkeletonWithHeaders/TableSkeletonWithHeaders.jsx
- src/components/Table/TableToolbar/TableToolbar.jsx
**Summary**
- Existing consumers of the table with `hasRowSelection: false` were getting proptypes errors due to an empty string as proptypes, instead of `false`
- modify proptypes to be `oneOf(["multi", "single", false])`
- modify defaultprops to be `false` instead of `''`
- check out the single selection and multi selection story. Nothing really should change here as this is a really minor fix
> fix(table): hasRowSelection false proptype instead of empty string

- package.json
- src/components/Header/__snapshots__/HeaderMenu.test.jsx.snap
- src/components/SideNav/__snapshots__/SideNav.test.jsx.snap
- src/components/Table/EmptyTable/EmptyTable.jsx
- src/components/Table/Table.jsx
- src/components/Table/Table.story.jsx
- src/components/Table/TableHead/FilterHeaderRow/FilterHeaderRow.jsx
- src/components/Table/TablePropTypes.js
- src/components/Table/TableToolbar/TableToolbar.jsx
- src/components/TileCatalog/TileCatalog.jsx
- yarn.lock
**Summary**
- summary_here
- chore(carbon-icons): upgrade to latest carbon-icons and update EmptyState and TileCatalog components to use non-built versions
- feat(Table): detect the size of the table and hide aspects of the pagination component.  Remove min-widths so our table can get narrower if it needs to
- fix(Table): passthrough the style prop to the parent component so the whole thing can be resized
- Closes IBM/carbon-addons-iot-react#221
- Closes IBM/carbon-addons-iot-react#220
- Verify the new small width table
> feat(table): add small table support with smaller pagination component

- src/components/Table/TableHead/FilterHeaderRow/FilterHeaderRow.jsx
**Summary**
- The column filter value contents overlap the filter controls when the table is in RTL mode
- small change to reserve enough padding on the right to display the Clear and dropdown button
- Closes IBM/carbon-addons-iot-react#167
- Verify that when you switch to RTL that the Table with filters story doesn't overlap the text
> fix(table): column filter value overlaps the clear and dropdown button when in RTL

- src/components/Table/StatefulTable.jsx
- src/components/Table/Table.jsx
- src/components/Table/Table.story.jsx
- src/components/Table/TableBody/RowActionsCell/RowActionsCell.jsx
- src/components/Table/TableBody/RowActionsCell/RowActionsError.jsx
- src/components/Table/TableBody/TableBody.jsx
- src/components/Table/TableBody/TableBodyRow/TableBodyRow.jsx
- src/components/Table/TableBody/TableBodyRow/TableBodyRow.story.jsx
- src/components/Table/TableBody/TableBodyRow/TableBodyRow.test.jsx
- src/components/Table/TablePropTypes.js
- src/components/Table/baseTableReducer.js
- src/components/Table/tableActionCreators.js
- src/components/Table/tableReducer.js
- src/components/Table/tableReducer.test.js
**Summary**
- Adds actions, reducers and props and StatefulTable support to allow for async row actions
- Closes IBM/carbon-addons-iot-react#128 
- Closes IBM/carbon-addons-iot-react#129 
- Verify the new async row actions story runs the spinner for 3 seconds before completing
> feat(table): add async row action support

- src/components/Table/tableReducer.js
- src/components/Table/tableReducer.test.js
**Summary**
- Clear multiple selection row when data changes
Closes #236
- Verify that if you select rows then delete other rows, that the selection is cleared
> fix(table): clear selection when data changes

- src/components/Table/tableReducer.js
- src/components/Table/tableReducer.test.js
- src/components/TileCatalog/StatefulTileCatalog.jsx
- src/components/TileCatalog/StatefulTileCatalog.test.jsx
**Summary**
- bug where the initial tile selection callback isn't being made when the data changes
- need to fire the onSelection callback event if the default selection is made
- Validate on any story where we're not passing a selectedTileID, that the initial render generates a selection callback in the actions panel.  For example in the TileCatalog async loaded one:
> Fix tilecatalog selection

- src/components/Table/Table.jsx
- src/components/Table/Table.story.jsx
**Summary**
Added a prop `hasOnlyPageData` that allows a user to pass just the `data` that is currently in the page view, rather than passing the entire set and letting the Table do pagination.  Useful for cases where the table has massive datasets and everything should be lazily-loaded.
- Closes IBM/carbon-addons-iot-react#186
- Verify paging works in the stateful examples, and the new example ("with hasOnlyPageData") looks good
> feat(table): add option to only pass data in visible page

- src/components/Table/StatefulTableMockReducers.test.jsx
- src/components/Table/baseTableReducer.js
- src/components/Table/tableActionCreators.js
**Summary**
In cases where applications consume the Table's baseTableReducer (in redux, for example) to customize sorting and filtering logic, there are often cases where multiple table instance states reside in the same store.  This PR adds an `instanceId` property to each action creator function, and (if `instanceId` is passed in to the baseTableReducer state) will process actions only if the `instanceId` matches.
- Verify that the StatefulTable behaves as expected.  No `instanceId` was provided in the reducer used by this component.
> feat(table): add optional filtering actions by instance id

- src/components/Table/TableHead/FilterHeaderRow/FilterHeaderRow.jsx
- src/components/Table/TableHead/FilterHeaderRow/FilterHeaderRow.test.jsx
- src/components/Table/TablePropTypes.js
**Summary**
Prior work has added an `isFilterable` boolean property type for each `column` object passed in as properties to the `TableHeaderRow` component. This value is dynamically set to true or false by the `Table` component, determined by whether or not the `column.filters` property is present.
However, the value of this property was not actually being honoured in any way; meaning that it is not possible to enable filtering for a subset of columns (it was either ALL or NONE). This PR resolves this issue.
- Closes IBM/carbon-addons-iot-react#253
- New component test added to verify filter input is omitted when `TableHeaderRow` column.isFitlerable is set to false.
- Snapshots of Table story verified and updated accordingly. …
> Fix table column is filterable

- src/components/Table/TableBody/TableBody.jsx
**Summary**
- Remove skeleton when lazy rendering Table component.
- Closes IBM/carbon-addons-iot-react#257
> fix(table): remove skeleton when lazy rendering data tables

- src/components/Dashboard/Dashboard.jsx
- src/components/Dashboard/Dashboard.story.jsx
- src/constants/LayoutConstants.js
**Summary**
- This PR adds a 16-column grid layout in the Dashboard story and fixes a bug where the `dashboardColumns` prop wasn't be propagated down to the card for layout calculation
- View the new dashboard 16-col story
> Add 16 column grid to dashboard

- package.json
- rollup.config.js
**Summary**
- fix so that carbon-addons-iot-react can be used by downstream components again
- fix(package.json): set d3 as peer dep
- fix(rollup): exclude d3 from build process as it was breaking it
https://stackoverflow.com/questions/35560305/d3-js-uncaught-typeerror-cannot-read-property-document-of-undefined
> fix(linechart): build process need to exclude d3

- src/components/Dashboard/Dashboard.jsx
**Summary**
- The filter props wasn't being exposed through the Dashboard, so couldn't set an filter element into the DashboardHeader
> fix(dashboard): expose filter prop

- src/components/Table/StatefulTable.jsx
**Summary**
- If the stateful table was consumed externally, it would lose the single selection indicator.  This is because the registerTable action was being dispatched everytime the parent rendered (due to not really comparing the data rows)
- items_here
- Tough to verify, it showed up in our EntityDetailsTable in Analytics Service, so if you pull this latest version you should see the table render and maintain it's selections
> fix(stateful): loses selection in single select

- jest.config.js
- src/components/Card/Card.jsx
- src/components/Card/Card.test.jsx
- src/components/Dashboard/Dashboard.story.jsx
- src/components/ValueCard/ValueCard.jsx
- src/components/ValueCard/ValueCard.story.jsx
- src/components/ValueCard/ValueCard.test.jsx
- src/components/ValueCard/ValueRenderer.jsx
- src/constants/PropTypes.js
**Summary**
- Added secondaryValue content prop for ValueCard, allowing a string or a object (value, trend direction, color).
- Verify the new `xsmall` storybook cases render appropriately
> Added secondary value render to ValueCard (and some cleanup)

- src/components/BarChartCard/BarChartCard.jsx
- src/components/BarChartCard/BarChartCard.story.jsx
- src/components/Card/Card.jsx
- src/components/Card/Card.story.jsx
- src/components/Dashboard/Dashboard.jsx
- src/components/Dashboard/Dashboard.story.jsx
- src/components/DonutCard/DonutCard.jsx
- src/components/PieCard/PieCard.jsx
- src/components/PieCard/PieCard.story.jsx
- src/components/TimeSeriesCard/TimeSeriesCard.jsx
- src/components/TimeSeriesCard/TimeSeriesCard.story.jsx
- src/constants/PropTypes.js
**Summary**
- Added basic loading/empty state to Card.  We can improve on the visuals in the future.
- Included new stories for Card for each state, and a "size gallery" to render all sizes of a card hooked up to the same prop knobs, to see how loading/empty scale up and down as size changes
> Add isEmpty and isLoading states to Card

- src/components/TimeSeriesCard/TimeSeriesCard.jsx
- src/components/TimeSeriesCard/TimeSeriesCard.story.jsx
- src/components/ValueCard/Attribute.jsx
- src/components/ValueCard/ValueCard.jsx
- src/components/ValueCard/ValueCard.story.jsx
- src/constants/PropTypes.js
**Summary**
- Refactoring to pass both the line chart and value card values as a flat object.  This allows each card to easily determine if it's empty or not for the current data range
- Verify the Line Chart and Value Card stories
> refactor(valuecard): change prop types to pass values as flat object

- src/components/Table/StatefulTable.jsx
- src/components/Table/StatefulTableMockReducers.test.jsx
- src/components/Table/Table.story.jsx
- src/components/Table/tableReducer.js
Co-authored-by: Filipe Corrêa <filipecorrea@me.com>
**Summary**
- allow passing in selectedIds from outside the statefultable
- Set selected ids in the statefultable story and watch the table update from the outside in
> feat(table): support passing selected ids from the outside for URL

- .travis.yml
**Summary**
- Travis deploy is no longer needed for gh-pages deployment
- remove deploy settings from .travis.yml
- #305
> refactor(deploy): remove travis deploy settings in favor of netlify

- src/components/Card/Card.jsx
- src/components/Card/Card.story.jsx
- src/components/Dashboard/Dashboard.jsx
**Summary**
- Add isLoading per card that can be used instead of the global dashboard state, and add a per card error state
- check stories for card errors
> feat(card): add per card error state and loading

- src/components/Table/Table.story.jsx
- src/components/Table/TableBody/TableBodyRow/TableBodyRow.jsx
**Summary**
- Nested rows didn't include the styling for single select. It silently fails currently - table row is selected but no visual change.
- add single select styling conditions to expanded/nested table rows
- slightly refactor single select for non-nested rows to have same styling approach as nested table rows
- Check out the deploy preview storybook for new `with single select and nested table rows`
> feat(table): single selection support for nested table rows

- src/components/ValueCard/ValueCard.jsx
**Summary**
- If our Value card gets pulled into projects with css-resets, we need to override their global line-height for our labels
- Verify the value card stories
> fix(valuecard): explicitly set line height for labels

- src/components/FileDrop/FileDrop.jsx
- src/components/FileDrop/FileDrop.story.jsx
**Summary**
- add multiple prop to support only "single file" uploads using this widget.  Also new prop to make the file list optional
- Check the new acceptance tests
> feat(filedrop): support single file requirement

- src/components/Dashboard/Dashboard.jsx
- src/components/Dashboard/Dashboard.story.jsx
- src/index.js
**Summary**
- Export the dashboard sizes and layout callbacks so downstream components (i.e. Editors) can listen to them
- Check actions tab of Stateful Dashboard story
> fix(dashboard): export sizes and layout callbacks

- src/components/Card/Card.jsx
- src/components/Dashboard/Dashboard.story.jsx
- src/components/TimeSeriesCard/TimeSeriesCard.jsx
**Summary**
- Removed size calculation of line chart wrapper, instead it will render at 100% width/height inside the CardContent (added relative position)
> fix(timeseriescard): layout adjustments to render chart at 100% height

- src/components/Dashboard/Dashboard.jsx
**Summary**
- small fix to the onLayoutChange callback to pass back all the updated layouts
- Just pass the additional parameter
- You can verify that as you resize the main Dashboard story, if it's in the Editable state it calls out to onLayoutChange
> fix(dashboard): onLayoutChange needs allLayouts param

- .storybook/TitleAddon.js
- .storybook/addons.js
- .storybook/config.js
- .storybook/theme.js
- README.MD
- package.json
- yarn.lock
**Summary**
- A few items towards the storybook theming. Doesn't completely resolve - will update the linked issue with remaining items.
- add carbon themes dep
- add storybook theme override
- add title addon for dynamic page titles
- update readme w/ beta install instructions
- IBM/carbon-addons-iot-react#309
- View the deploy preview, theme should look like it does in my dev env, also the document.title should be updated per story.
> docs(storybook): update theme, page titles, readme beta install

- src/components/ValueCard/ValueCard.jsx
**Summary**
- very small fix to always center the value on a small card regardless of width
- Check the single value Small card story
> fix(valuecard): center the value for small cards if theres only one

- src/components/FileDrop/FileDrop.jsx
- src/components/FileDrop/FileDrop.story.jsx
- src/components/Page/EditPage.jsx
- src/components/Page/EditPage.story.jsx
- src/components/Page/PageHeader.jsx
- src/components/Page/PageHeader.story.jsx
**Summary**
- fix, FileDrop drag and drop wouldn't trigger the upload on the second drop of the same file if we used the upload button
- feat(EditPage): add isLoading styles to the EditPage
- Verify in the FileDrop story that you can upload files and it always triggers the onData action even without clearing the files
- Verify the new isLoading Edit page stories
> fix(filedrop): support multiple tries with same file

- src/components/TimeSeriesCard/TimeSeriesCard.jsx
- src/components/TimeSeriesCard/TimeSeriesCard.story.jsx
**Summary**
- Use locale for x-axis date
- Use useDeepCompareEffect instead of useEffect
- items_here
- tests here
> chore(locale): locale x-axis date format, use useDeepCompareEffect

- src/components/TimeSeriesCard/TimeSeriesCard.jsx
**Summary**
- reduce the number of ticks for smaller cards, they're not fitting on real dashboards
- Verify the smaller card stories (in a real dashboard layout ideally)
> fix(timeseries): reduce ticks for smaller cards

- src/components/Table/StatefulTable.jsx
- src/components/Table/StatefulTableMockReducers.test.jsx
- src/components/Table/tableActionCreators.js
- src/components/Table/tableReducer.js
**Summary**
- If you late loaded a table, subsequent attempts to page through its data would fail.  This is because the totalItems bit wasn't being stored on the pagination widget
- Added a fix to pass along the totalItem count every time we called TABLE_REGISTER
- Hard to verify locally unfortunately, but we saw this error in our dashbaord
> fix(table): bug on late loading tables not paging

- src/components/NavigationBar/NavigationBar.jsx
- src/components/NavigationBar/NavigationBar.story.jsx
**Summary**
- summary_here
- items_here
- Verify that the hero is now on top of the Navigation bar
> fix(navbar): flip page hero to the top of the tabs

- src/components/Hero/index.js
- src/components/SecondaryNavigator/index.js
- src/index.js
**Summary**
- Added missing export on index.js for Hero and SecondaryNavigator
> Add export to hero and secondary navigator

- src/components/Hero/Hero.jsx
- src/components/Hero/Hero.story.jsx
**Summary**
-  Tooltip in hero
- CSS property update
- `BreadcrumbItem` with `<a href="">`in  content
> feat(tooltip): add tooltip in hero

- src/components/Hero/Hero.jsx
- src/components/Hero/Hero.story.jsx
**Summary**
- Change breadcrumb props to accept a node (to allow passing custom content as links, i.e. `Link` from react-router-dom)
- Clean up unused CSS
- Check out the breadcrumb story in Hero
> fix(hero): allow passing custom links as breadcrumbs

- package.json
- src/components/ImageCard/ImageCard.jsx
- src/components/ImageCard/ImageCard.story.jsx
- yarn.lock
**Summary**
- Restrict card sizes for ImageCard
- Closes IBM/carbon-addons-iot-react#395
- The smaller sizes shouldn't be accepted for ImageCard
> fix(imagecard): restrict sizes

- src/components/TableCard/TableCard.jsx
- src/components/TableCard/TableCard.story.jsx
- src/components/TimeSeriesCard/timeSeriesUtils.js
- src/components/TimeSeriesCard/timeSeriesUtils.test.js
**Summary**
- feat(tablecard) show sample values while the tablecard is being edited
- fix(tablecard): support empty column array by default (as the first time a tablecard is added to a dashboard it may not have columns)
- Try out the new isEditable story for tablecard and make sure it shows sample data
> feat(tablecard): support editing dashboard with table cards

- README.MD
**Summary**
- Add a netlify badge to our `beta` readme as a thanks for Netlify upgrading our team to the [free open source plan](https://www.netlify.com/legal/open-source-policy/)
> chore(readme): add netlify badges to beta

- src/components/TimeSeriesCard/TimeSeriesCard.jsx
**Summary**
- Makes the x-axis on Firefox look the same as the x-axis on Chrome (i.e. not rotated)
- small style override
- Verify all the TimeSeries stories in Chrome and Firefox
> fix(timeseries): stop the x-axis label overlap on firefox

- package.json
- yarn.lock
**Summary**
- ImageCard shouldn't show zoom controls for images that are smaller than container.
- Closes https://github.ibm.com/wiotp/monitoring-dashboard/issues/184
- Specify an image smaller than container size for ImageCard
> fix(imagecard): hide controls for small images

- src/components/ImageCard/ImageHotspots.jsx
**Summary**
- Add Carbon icon to zoom to fit button.
- Run ImageCard storybook and check if there's a Carbon icon in zoom to fit button.
> fix(imagecard): add Carbon icon to zoom to fit

- src/components/ImageCard/Hotspot.jsx
**Summary**
- Change hotspots position in ImageCard to center them instead of using top left.
- Check if hotspots position is relative to their center and not top left.
> fix(imagecard): change hotspots position to center

- src/components/ImageCard/ImageCard.jsx
- src/components/ImageCard/ImageCard.story.jsx
- src/components/ImageCard/ImageHotspots.jsx
**Summary**
- Users can optionally specify a max zoom for their images. If not specified the image will zoom in until its size is equal to the original image size.
- Change `zoomMax` property using storybook and zoom in.
> feat(imagecard): support max zoom spec

- rollup.config.js
**Summary**
- Fixes a typo - vendor folder doesn't have an underscore. Was preventing consumers from importing partials, vendor files weren't resolving.
- modify rollup config
- Closes #505 
- pull down and run `yarn`, `./lib/scss/globals/scss` folder should now contain the `vendor` folder and associated partials
> fix(rollup): copy carbon-components vendor folder for publish

- src/components/Page/EditPage.jsx
**Summary**
- If onSave returns false, edit page didn't pass validation, so we should stop the Saving spinner
> fix(editpage): turn off the saving bit if onSave returns false

- src/components/TableCard/TableCard.jsx
- src/components/TableCard/TableCard.story.jsx
**Summary**
- small fix to use numbers in the filter column text and as the labeled spans in the severity column
> [tablecard]: i18n fixes for the Table card severity strings.  use numbers instead

- src/components/Dashboard/DashboardHeader.jsx
- src/components/Dashboard/DashboardHeader.story.jsx
Add capability to pass custom icon to dashboard header (and fix the description) to use the labelText
> feat(dashboard): add capability to pass custom icon

- src/components/Dashboard/Dashboard.story.jsx
- src/components/ImageCard/Hotspot.jsx
- src/components/ImageCard/ImageCard.story.jsx
**Summary**
- Make non-icon hotspots have transparent background and no border -- this supports a "heat map" use case by default.
- Check ImageCard and Dashboard (basic) stories for an example. (or look at the image above)
> fix(imagecard): make non-icon hotspots transparent

- rollup.config.js
**Summary**
- Modify how Notification styles are added to final build to preserve folder structure for imports.
- disinclude Notifications from going through the sanitize/camelCase function
Final output from copy logging on my local build:
```
src/components/Notification/_inline-notification.scss → lib/scss/components/Notification/_inline-notification.scss
src/components/Notification/_toast-notification.scss → lib/scss/components/Notification/_toast-notification.scss
```
> fix(notification): sass entrypoint and build styles

- src/components/Card/Card.jsx
**Summary**
- Remove min-width calculation from cards... not necessary when rendered inside of a Dashboard, and the values were off (resulting in some horizontal overlap at the edges of breakpoints)
> Fix card overlap

- src/components/ImageCard/Hotspot.jsx
**Summary**
- Added opacity, solid white border to non-icon hotspots (circles)
- added `cursor: pointer` to all hotspot tooltip buttons
> fix(imagecard): non-icons need white border

- src/components/PageTitleBar/PageTitleBar.jsx
- src/components/PageTitleBar/PageTitleBar.test.jsx
**Summary**
- Improve PageTitleBar to not render tooltip icon when no description is given. Added tests to cover this as well.
- Closes #552 
- This small fix to logic didn't need a new story, so it's not "visible" in the storybook. For temporary testing, remove the `description` prop from the PageTitleBar `with tabs as children` story and view the result. It shouldn't render the tooltip icon.
> fix(pagetitlebar): tooltip rendering logic when no description

- src/components/TableCard/TableCard.jsx
- src/components/TableCard/TableCard.test.jsx
- src/components/TimeSeriesCard/TimeSeriesCard.jsx
- src/components/ValueCard/Attribute.jsx
- src/components/ValueCard/ValueCard.story.jsx
- src/index.js
In the value and Image Card, thresholds were triggering even if the value was null.
I fixed the Value card in Attribute,  but for the Image Card, I'm doing some of the work downstream.  I've exported the findMatchingThresholds helper function so that external consumers can use it.
> fix(card): thresholds shouldn't apply if the value is null

- src/components/TableCard/TableCard.jsx
table card is overlaying other cards when empty.
The original fix was to try and make the border line inside the table go away. This just unsets the border
> fix(tablecard): don't override height when empty

- src/components/Card/Card.jsx
- src/index.js
turning off placeholders allows downstream consumers to use these components in their testcases
> fix(sizeme): turn off placeholders

- src/components/Dashboard/CardRenderer.jsx
- src/components/Dashboard/Dashboard.jsx
- src/components/Dashboard/Dashboard.story.jsx
feat(cardrenderer): add caching layer on top of the memoized cardRenderer to cache old style and the old onCardAction methods
refactor(dashboard): remove the dashboard template from state and instead just use expandedId.  This will allow us to memoize callbacks depending on a much more granular state
> fix(dashboard): improve performance by memoizing the CardRenderer

- src/components/ImageCard/ImageHotspots.jsx
- src/components/ResourceList/ResourceList.story.jsx
- src/components/ResourceList/ResourceList.test.jsx
**Summary**
- Fixes a few lingering prop types issues from the v10 upgrade.
- remove src as a required prop of ImageHotspots - it correctly handles not being provided a src
- fix ResourceList icon usage story and test - only need to pass the icon component, not an instance of it
- You should see locally or in travis that we no longer have console warnings for these components when `yarn test` is ran.
> fix(proptypes): warnings for minor invalid props

- src/components/Table/Table.jsx
- src/components/Table/TableBody/RowActionsCell/RowActionsCell.jsx
- src/components/Table/TableBody/RowActionsCell/RowActionsCell.test.jsx
- src/components/Table/TableBody/TableBody.jsx
- src/components/Table/TableBody/TableBodyRow/TableBodyRow.jsx
- src/components/Table/TableBody/TableBodyRow/TableBodyRow.story.jsx
- src/components/Table/TableBody/TableBodyRow/TableBodyRow.test.jsx
- src/components/Table/TableBody/TableBodyRow/__snapshots__/TableBodyRow.story.storyshot
**Summary**
- Before, the unique table ID was being prepended to the rowId for use in `TableBodyRow` and `RowActionsCell`.
- Now, the `tableId` is passed as a prop along with the row ID (prop: `id`) to `TableBodyRow` and `RowActionsCell`.  The row ID is used in callbacks, and the table ID is used with row ID (`${tableId}-${rowId}`) to provide a unique DOM ID.
- Closes IBM/carbon-addons-iot-react#612
- Verify the tests pass (there is a test case covering the 'table-scoped' DOM ID)
- Do a quick check on the storybook actions resulting from clicking on a table row and row action.
> fix(table): pass tableId down to build DOM ID

- .storybook/webpack.config.js
- babel.config.js
- package.json
- yarn.lock
**Summary**
There were issues with stories that use moment that was causing them not to render due to storybook's webpack config ignoring locales. 
I also removed a babel config setting which was a fix for a previous error that seems to only need the addition of `core-js` package with version < 3 to fix. 
you should see all stories render in the storybook preview
> Fix failing stories

- src/components/PageTitleBar/PageTitleBar.jsx
- src/components/PageTitleBar/PageTitleBar.story.jsx
- src/components/PageTitleBar/__snapshots__/PageTitleBar.story.storyshot
- src/components/PageTitleBar/_page-title-bar.scss
- src/components/Table/Table.jsx
- src/components/TableCard/__snapshots__/TableCard.story.storyshot
**Summary**
- Fixes to alignment and styling for PageTitleBar and Table (pagination)
- Added `extraContent` prop in PageTitleBar, added deprecation comment for `rightContent`
* PageTitleBar styling / `extraContent` alignment
* Fixed alignment issue in pagination select indicator
- Closes IBM/carbon-addons-iot-react#618
- Verify all permutations of the PageTitleBar story
- Verify a Table story with pagination
> style/alignment updates: PageTitleBar, Table (pagination)

- src/components/Dashboard/CardRenderer.jsx
- src/components/ImageCard/ImageCard.jsx
- src/components/ImageCard/ImageCard.story.jsx
**Summary**
- Small bug where if the image card setup throws an error, it isn't shown to the user
- correctly handle the error if the setupCard throws an error
- Test the new imagecard error loading src story
> fix(imagecard): handle when imagecard setup throws error

- src/components/Table/EmptyTable/EmptyTable.jsx
There is a [defect](https://github.com/carbon-design-system/carbon/issues/4339) in underlining Carbon component that causes table cells to grow to match  size of table with explicitly set height in Firefox browser. See our storybook for table card empty table story.
added styles to empty table component for now as it seems to only happen when there is no data for the table. May be worth applying these styles to tables as a whole. Will be pushing up to the carbon repo as well. 
- Closes https://github.ibm.com/wiotp/monitoring-dashboard/issues/422
- tests here
> fix visual defect in ff for empty tables

- src/components/Card/Card.jsx
- src/components/ImageCard/ImageCard.jsx
- src/components/ImageCard/ImageHotspots.jsx
- src/components/ImageCard/ImageHotspots.test.jsx
- src/components/TimeSeriesCard/TimeSeriesCard.jsx
Closes #638
**Summary**
- Internal Bug reported where the Image Card didn't collapse from full screen correctly on firefox
- refactor(ImageHotspots): pretty large refactor to remove the local container state from ImageHotspots and instead inherit the size from the Card content parent (which correctly handles Firefox)
- fix(TimeSeriesCard): isEditable is no longer showing fake data
- Verify in Firefox the full screen image card dashboard story.  Expand and then collapse the image and ensure it is correctly positioned
> fix(imagecard): expansion and collapse doesn't work on firefox

- package.json
- rollup.config.js
- src/components/TimeSeriesCard/TimeSeriesCard.jsx
- yarn.lock
need to remove the custom tooltip for now because downstream teams can't consume as the rolled up build doesn't work.
> fix(timeseries): remove the cheeriojs because it's breaking rollup

- .babelrc
- package.json
- rollup.config.js
- src/components/TimeSeriesCard/TimeSeriesCard.jsx
Unfortunately cheeriojs throws errors when we try and use it downstream with rollup (due to htmlparser2) so I had to remove it and implement our own html parser
For some bizarre reason, I also had to adjust our polyfills in babelrc because the library started throwing an error
> fix(tooltip): write our own parse since cheeriojs has issues with rollup

- src/components/TimeSeriesCard/TimeSeriesCard.jsx
- src/components/TimeSeriesCard/TimeSeriesCard.story.jsx
- src/components/TimeSeriesCard/timeSeriesUtils.js
- src/components/TimeSeriesCard/timeSeriesUtils.test.js
x-axis wasn't being formatted correctly with the new graphs, adds a testcase to validate and ensure this formatting.
refactor(TimeSeriesCard): split the formatting utility to be sharable between components
> fix(timeseries): bug where the x-axis isn't formatting correctly with the new graphs

- jest.config.js
Closes #621 
**Summary**
- Reimplements test coverage thresholds we had set before the dashboard component migration from 1.x to 2.x. `Branches` increases, but will remain below 80% until `PageWizard` stabilizes and is covered in tests.
- Validate the Travis CI checks take into account the new thresholds. The current coverage amounts in `master` meet these thresholds.
> chore(tests): re-increase test coverage thresholds

- src/components/Table/TableHead/TableHead.jsx
- src/components/TableCard/TableCard.jsx
- src/components/TableCard/TableCard.story.jsx
- src/constants/PropTypes.js
- src/utils/schemas/tableCardContent.json
Supports new width string proptype and field that can be passed in to limit a column width
> feat(tablecard): add width to proptypes that can be passed in for columns

- package.json
- src/components/TableCard/TableCard.jsx
- src/components/TimeSeriesCard/TimeSeriesCard.jsx
- yarn.lock
Closes #
**Summary**
- You can see the basic problem here:
- All the changes were on our local branch of carbon-charts
- The x-axis domain of these charts is much better now.  Verify all the x-axis in the line charts
> Chore charts upgrade

- src/components/Header/HeaderMenu.test.jsx
**Summary**
- This PR contains tests that trigger and validate the expanded/unexpanded state of the `HeaderMenu` (icon triggering dropdown list for use in the `Header`).  You can see examples of using `@testing-library/react` to trigger keyboard and mouse events, validate based on aria properties, etc.
- If the checks pass, it's good to go.
> test(headermenu): event handlers

- src/components/PageWizard/PageWizard.story.jsx
- src/components/PageWizard/PageWizard.test.jsx
**Summary**
- Adds wizard button click and validation tests using @testing-library/react.  Example:
```
test('validation in first step', () => {
const mocks = {
onNext: jest.fn(),
};
const i18n = {
back: 'Back',
submit: 'Submit',
next: 'Next',
cancel: 'Cancel',
};
const { getByTestId, getByText } = render(
<PageWizard currentStepId="step1" {...mocks} i18n={i18n}>
<StepValidation id="step1" label="Step with validation" />
{content[1]}
{content[2]}
</PageWizard>
);
// validation should fail if only first name is entered
fireEvent.change(getByTestId('first-name'), { target: { value: 'First Name' } });
fireEvent.click(getByText(i18n.next));
expect(mocks.onNext).toHaveBeenCalledTimes(0);
// validation should succeed if both fields are entered
fireEvent.change(getByTestId('last-name'), { …
```
> test(pagewizard): wizard buttons and validation

- src/components/Dashboard/CardRenderer.jsx
- src/components/Dashboard/Dashboard.jsx
- src/components/Dashboard/Dashboard.story.jsx
- src/components/Dashboard/__snapshots__/Dashboard.story.storyshot
- src/components/ImageCard/Hotspot.jsx
- src/components/ImageCard/ImageCard.jsx
- src/components/ImageCard/ImageCard.story.jsx
- src/components/ImageCard/ImageHotspots.jsx
- src/components/ImageCard/__snapshots__/ImageCard.story.storyshot
- src/components/ValueCard/Attribute.jsx
- src/components/ValueCard/ValueCard.jsx
- src/components/ValueCard/ValueCard.story.jsx
- src/components/ValueCard/__snapshots__/ValueCard.story.storyshot
- src/constants/PropTypes.js
- src/utils/bundledIcons.js
**Summary**
`<Dashboard>` now accepts a render prop for icons `renderIcon` that can be used to allow the parent component to override the default icon rendering logic (i.e. matching to one of the "bundled" icons).  This is available at the card level as well, to `ValueCard` and `ImageCard` (which render dynamic icons for thresholds).
Example:
```
<ValueCard
title={text('title', 'Alert Count')}
id="facilitycard"
renderIcon={(name, props = {}) => name === 'bee' ? (
<Bee16 {...props}>
<title>{props.title}</title>
</Bee16>
) : null}
/>
```
- Verify the added stories under Dashboard, ValueCard, and ImageCard for custom renderIcon
> Add render prop to dashboard/cards for icons

- src/components/Dashboard/Dashboard.story.jsx
- src/components/TimeSeriesCard/TimeSeriesCard.jsx
- src/utils/schemas/dashboardContent.json
need to allow additional data prop in input grain card
fix(timeseries): shouldn't change the dot to fill in editable mode
feat(timeseries): if expanded show table underneath with raw data
> fix(dashboard): need to allow additional data prop

- src/components/ValueCard/Attribute.jsx
- src/components/ValueCard/__snapshots__/ValueCard.story.storyshot
**Summary**
- small fix from renderIcon work, pass `tabIndex` in attribute as camelcase to fix warning
- tests pass
> fix(attribute): camelCase tabIndex to fix warning

- src/constants/PropTypes.js
- src/utils/schemas/dashboardContent.json
- src/utils/schemas/imageCardContent.json
- src/utils/schemas/valueCardContent.json
Add additional minute and quarter support for data ranges
remove redundant validation rules from the image and value card so there's only one place
> feat(range): support minute and quarter ranges for data

- src/components/Card/Card.jsx
- src/components/TimeSeriesCard/TimeSeriesCard.jsx
Closes #
**Summary**
- add an isLazyLoading property to Cards so that I can defer large datapoints while they're offscreen.  Then use it inside the TimeSeriesCard for large datasets
> feat(card): support lazyLoading for large timeseries graphs

- src/components/Card/Card.jsx
- src/components/Card/CardRangePicker.jsx
- src/components/Card/CardToolbar.jsx
Makes the card range picker better match the PAL library version of the range picker:
It's not a one to one match, but it's close.
> feat(cardrange): simplify range picker UX

- src/components/Dashboard/CardRenderer.jsx
small fix, we should allow cards to reload when they're in error and show if there's a setupError passed to a card.
> fix(cardrenderer): don't prevent loading when a card is in error

- yarn.lock
#776 - will close after we can verify the publish succeeds in CI
**Summary**
- The publish step of semantic-release is failing. Based on feedback from semantic-release, https://github.com/semantic-release/npm/issues/232, this could be caused by our yarn.lock keeping transient (sub) dependencies locked to older versions. 
- Ran `yarn remove semantic-release`, which removed all semantic release deps from yarn.lock
- Then I discarded the changes to `package.json`, effectively re-adding semantic-release
- Ran `yarn install` to update the yarn.lock
This should ensure semantic release sub-deps are up to date.
> fix(semantic-release): update transient dependencies of semantic-release

- src/components/Table/tableReducer.js
Closes Internal bug
[Internal tracking issue #158](https://github.ibm.com/Watson-IoT/pal-tracking/issues/158)
**Summary**
- Page size is being reset to the default anytime the data within the table changes
- Small change to preserve the existing pagesize when the data changes.
- Set the pagesize in a table, then change it's data
> fix(tablereducer): preserve the pagesize even if the data changes

- src/components/Table/Table.jsx
- src/components/Table/Table.story.jsx
- src/components/Table/TableHead/ColumnHeaderRow/ColumnHeaderRow.jsx
- src/components/Table/TableHead/ColumnHeaderRow/ColumnHeaderRow.test.jsx
- src/components/Table/TableHead/ColumnHeaderSelect/ColumnHeaderSelect.jsx
- src/components/Table/TableHead/TableHead.jsx
- src/components/Table/TableHead/_table-head.scss
- src/components/Table/TablePropTypes.js
- src/components/Table/_table.scss
- src/styles.scss
Closes #786, Internal tracking [issue #16](https://github.ibm.com/Watson-IoT/pal-tracking/issues/16) 
**Summary**
- Add a columnSelectionConfig button option to support advanced configuration of columns
- Add button, associated sass partials/styles
- refactor ColumnHeaderSelect from styled-components to sass (also now we'll have a table partial!)
- add tests, improve coverage
- Modify and rename the story, add a knob to enable the button
- View the `with column selection` story
> feat(tablehead): add column selection config button

- rollup.config.js
**Summary**
- Fixes an error in the build where sass paths were not correct.
- run `yarn`. in your `lib/scss` folder, you should now see that the TableHead folder is nested within the Table folder, instead of beside it.
Error reported from consuming product (thanks @dennynguyen!):
```
ERROR in ./src/sass/main.scss (./node_modules/css-loader??ref--8-1!./node_modules/sass-loader/lib/loader.js??ref--8-2!./src/sass/main.scss)
Module build failed (from ./node_modules/sass-loader/lib/loader.js):
@import 'TableHead/table-head';
^
File to import not found or unreadable: TableHead/table-head.
in /Users/denny/workspace-git/common-core-external-dashboard/node_modules/carbon-addons-iot-react/lib/scss/components/Table/_table.scss (line 1, column 1)
@ …
```
> fix(table-head): sass build paths

- src/components/Dashboard/DashboardGrid.jsx
Closes #794
Closes #782
**Summary**
Small fix to allow a single card to be passed to a dashboardgrid
- Convert the children to an array so all the code support it
- Pass just one card to a dashbaord
> fix(dashboardgrid): support non-array children

- src/components/PageWizard/PageWizard.jsx
- src/components/PageWizard/PageWizard.test.jsx
Closes #
**Summary**
- add onClearError prop
- add new onClearError prop so that the parent components can clear the error
- add Close button label to the i18n prop
- See new testcases
> feat(pagewizard): add onClearError prop

- src/components/TileCatalog/StatefulTileCatalog.jsx
- src/components/TileCatalog/StatefulTileCatalog.test.jsx
- src/components/TileCatalog/TileCatalog.story.jsx
- src/components/TileCatalog/__snapshots__/TileCatalog.story.storyshot
- src/components/TileCatalog/tileCatalogReducer.js
Closes #809 
**Summary**
- Added new property that allows tile catalogs to start off unselected
- feat(StatefulTileCatalog): add new isSelectedByDefault prop and only invoke onSelection if set true (true by default)
- feat(tileCatalogReducer): only select by default (in initial state) if isSelectedByDefault is true
- Check the new story and testcases and confirm the tile catalog is actually unselected
> feat(tilecatalog): isSelectedByDefault prop that determines whether to force a selection or not

- .github/CODEOWNERS
- src/components/Table/tableReducer.js
- src/components/TimeSeriesCard/TimeSeriesCard.jsx
- src/components/WizardInline/WizardFooter/WizardFooter.jsx
Closes #
**Summary**
- Because the full list of column names might not be known when data is loaded asynchronously, we need to reinitialize the ordering in our table state once the table Register method is called.  tableRegister gets called when data is refreshed.
- fix(tableReducer): reload table columns if a table data reloads
- fix(WizardModal): the footer styled component wasn't working due to not passing the classname prop through
> fix(table): for async tables, the column names may not be known

- src/components/Dashboard/__snapshots__/Dashboard.story.storyshot
- src/components/Table/tableReducer.js
- src/components/TableCard/TableCard.jsx
- src/components/TableCard/__snapshots__/TableCard.story.storyshot
Closes #
**Summary**
- https://github.ibm.com/wiotp/monitoring-dashboard/issues/661 Internal issue, more rows should be available in the tablecard
- fix(tableReducer): update the pageSize in our reduced state if it changes as a prop
- fix(TableCard): show the page selector if the card is expanded 
- fix(TableCard): allow tables to internally scroll on the card if the card isExpanded. Fix some pagination styles to allow this scrolling without scrolilng the pagination widget
- fix(TableCard): increase the default page size choices from 10,20, 30 to 10, 25, 100.
- tests here
> fix(tablecard): increase the available rows in a tablecard

- .storybook/__snapshots__/Welcome.story.storyshot
- src/components/TimeSeriesCard/TimeSeriesCard.jsx
- src/components/TimeSeriesCard/TimeSeriesCard.story.jsx
- src/components/TimeSeriesCard/__snapshots__/TimeSeriesCard.story.storyshot
- src/constants/LayoutConstants.js
- src/constants/PropTypes.js
- src/index.js
Closes #https://github.ibm.com/wiotp/monitoring-dashboard/issues/307
**Summary**
- Add a new chart type prop to allow the time series to render a bar rather than a line chart
- feat(TimeSeriesCard): update the handleTooltip method to handle the data values that a bar chart sends from carbon
- feat(TimeSeriesCard): switch the StackedBarChart in instead of the LineChart component
- verify the new story for bar chart types
> feat(bar): allow time series to show bars

- src/components/ProgressIndicator/ProgressIndicator.jsx
- src/components/ProgressIndicator/__snapshots__/ProgressIndicator.story.storyshot
- src/components/WizardModal/__snapshots__/WizardModal.story.storyshot
Closes #
**Summary**
- fix(progressindicator): according to Luke we should show labels on future progress steps by default
- items_here
- Verify the WizardModal stories
> fix(progressindicator): show step labels by default

- package.json
- rollup.config.js
- src/styles.scss
- yarn.lock
**Summary**
- Our build was putting the TableToolbar scss in the incorrect place preventing anyone downstream from using carbon-addons-iot-react with this build error
- fix(package): upgrade rollup-copy-plugin to support nested directories
- fix(rollup.config.js): remove custom renaming pathing code 
- refactor(styles.scss): just moving our custom table one down
- Make sure that after you build carbon-addons you can include it's scss in a downstream project without build failures
> fix(build): addons cannot be included due to incorrect scss build paths

- src/components/TableCard/TableCard.jsx
Closes #838
**Summary**
- Re-added `cachedOnCardAction` to the TableCard -> CardToolbar prop. The `cardAction` was not receiving the id correctly, resulting in the `expand` functionality not working.
- src/components/TableCard/TableCard.jsx
1. Go to Dashboard -> full table story
2. Click on 'Expand' button
3. See the card expand
> fix(tablecard): re-added cachedoncardaction to cardtoolbar

- src/components/Table/StatefulTable.jsx
- src/components/Table/Table.story.jsx
- src/components/Table/TablePropTypes.js
- src/components/Table/tableReducer.js
- src/components/Table/tableReducer.test.js
Closes #https://github.com/IBM/carbon-addons-iot-react/issues/251
**Summary**
Allows the StatefulTable consumers to pass a custom sortFunction prop on their column.
- feat(StatefulTable): pass the columns to the reducer so it can custom sort if a custom sort function is passed for that column
- test(Table.story): add a customSortFunction on the Status field of the table so we can integration test it
- feat(TablePropTypes): new sortFunction property
- feat(tableReducer): take the custom sort function into account in the filterSearchAndSort (which resorts the table when a new filter is applied)
- feat(tableReducer): use the custom sort function instead of our default getSortedData if it exists on the column
**Acceptance Test (how to verify the …
> feat(statefultable): add sortFunction prop for custom column sorts

- src/components/Header/HeaderAction/HeaderAction.jsx
- src/components/Header/HeaderAction/HeaderActionPanel.jsx
- src/components/Header/HeaderActionGroup.jsx
Closes #850 
Old behavior: 
**Summary**
- The `onBlur` and `onClick` events were both being fired if another HeaderAction was already in focus. This behavior was unpredictable and it is believed that the `onBlur` was causing a re-render, which would "throw away" the second event
- The `isExpanded` state was moved into the HeaderAction rather than the HeaderActionGroup in an effort to avoid the event where the `expandedItems` object was getting overwritten by other events. By moving it to the action itself, it became unaware of other action's events.
- src/components/Header/HeaderAction/HeaderAction.jsx
- src/components/Header/HeaderActionGroup.jsx
- src/components/Header/HeaderAction/HeaderActionPanel.jsx
**Acceptance Test (how to verify the …
> fix(header): moved state lower for event handling

- src/components/Table/Table.story.jsx
- src/utils/sample.jsx
Closes #244
**Summary**
The storybook sample table with filters always use the verb 'Pick'. It should be updated to 'Enter' in case it's a non-picker type of field.
Verify that on ?path=/story/watson-iot-table--with-filters there's 'enter' as majority of the filter placeholders. There should be only a 'pick' on the Select dropdown
> test(table): update filter placeholders

- src/components/Card/Card.jsx
- src/components/Card/Card.story.jsx
- src/components/Card/Card.test.jsx
- src/components/Card/__snapshots__/Card.story.storyshot
Closes #781
**Summary**
The size object passed to card children did not consider the height of the card title which made it incorrect. This PR fixes that problem.
tested with title
tested without title
tested expanded
tested as custom card
- items_here
Create a card with
```
children={childSize => (
<p>
Content width is {childSize.width} and height is {childSize.height}
</p>
)}
```
and verify that the printed size corresponds to the actual size of the card content using the DOM inspector. Verify the following scenarios for different cards sizes:
card with title
card without title
card expanded
card as custom card
> fix(card): fixed bug with incorrect child size prop

- .storybook/__snapshots__/Welcome.story.storyshot
- src/components/Card/Card.jsx
- src/components/Card/Card.story.jsx
- src/components/Card/Card.test.jsx
- src/components/Card/__snapshots__/Card.story.storyshot
- src/components/Dashboard/CardRenderer.jsx
- src/components/Dashboard/Dashboard.jsx
- src/components/TableCard/TableCard.jsx
- src/constants/PropTypes.js
Closes #
**Summary**
- Need to be able to receive the full list of props downstream in custom cards
- feat(Card): pregenerate the card toolbar so it can be passed downstream to custom card components
- feat(Card): pass the main props of the card and the generated toolbar downstream to the custom card component
- feat(Card): add hideHeader prop instead of just relying on the title of the card to hide the header
- fix(CardRenderer): allow custom cards to show an Expand button if they pass it
- Verify that no major changes occurred to the existing Dashboard and Card stories except for the Custom Card story which I extended to be more like my usage inside Monitor
> feat(card): pass full props and toolbar to custom cards

- src/components/AddCard/AddCard.jsx
- src/components/AddCard/__snapshots__/AddCard.story.storyshot
- src/components/AddCard/_add-card.scss
Closes #474 
**Summary**
- Made more descriptive class name for title
- Added `$text-01` to the title's class to match icon
**Before**
**After**
- src/components/AddCard/AddCard.jsx
- src/components/AddCard/_add-card.scss
- Go to AddCard story and see that the title color matches the icon
> fix(AddCard) added proper color to title

- .storybook/__snapshots__/Welcome.story.storyshot
- src/components/PageWizard/PageWizard.jsx
- src/components/PageWizard/PageWizard.story.jsx
- src/components/PageWizard/PageWizard.test.jsx
- src/components/PageWizard/PageWizardStep/PageWizardStep.jsx
- src/components/PageWizard/PageWizardStep/PageWizardStepContent.jsx
- src/components/PageWizard/PageWizardStep/PageWizardStepDescription.jsx
- src/components/PageWizard/PageWizardStep/PageWizardStepExtraContent.jsx
- src/components/PageWizard/PageWizardStep/PageWizardStepTitle.jsx
- src/components/PageWizard/StatefulPageWizard.jsx
- src/components/PageWizard/__snapshots__/PageWizard.story.storyshot
- src/components/PageWizard/_page-wizard.scss
- src/index.js
Closes #874
**Summary**
- Added `isProgressIndicatorVertical` boolean to toggle the vertical vs horizontal layouts
- Refactored PageWizardStep into smaller components
- Added comments to props
- Corrected props
- Added tests to get more test coverage
- Added knobs to all applicable stories
- Check the PageWizard stories and toggle the horizontal layout by using the knob
> [PageWizard] Add horizontal layout

- .storybook/__snapshots__/Welcome.story.storyshot
- src/components/Dashboard/DashboardGrid.jsx
- src/components/Dashboard/DashboardGrid.test.jsx
- src/utils/__tests__/componentUtilityFunctions.test.js
- src/utils/componentUtilityFunctions.js
Closes #https://github.ibm.com/wiotp/monitoring-dashboard/issues/717
This is to fix this bug where if the user hasn't been to a layout breakpoint before (i.e. they added a card but didn't visit all the possible layout sizes to generate the layout), the cards were assuming that they were SMALL instead of using their true size.
**Summary**
- refactor(DashboardGrid): extract the layout generation to another function
- fix(DashboardGrid): add validation of layout to make sure all cards exist
- test(DashboardGrid): added testcases to validate the layout gets regenerated if a card is missing
> fix(dashboardgrid): if card is missing from layout regenerate the layout

- src/components/Dashboard/CardRenderer.jsx
- src/components/Dashboard/CardRenderer.test.jsx
- src/components/Dashboard/Dashboard.jsx
- src/components/Dashboard/Dashboard.story.jsx
- src/components/Dashboard/Dashboard.test.jsx
- src/components/Dashboard/__snapshots__/Dashboard.story.storyshot
Closes #
**Summary**
- If you specified a card without a datasource, it would hang in the loading state forever (and never be updated)
- fix(CardRenderer): only cards with dataSources are loaded
- Flip the new isLoading knobs on the main Dashboard story and notice that the only cards that show loading spinners are the ones with dataSources specified (i.e. the timeseries graph)
> fix(dashboard): only set loading if a datasource is specified

- src/components/Dashboard/DashboardGrid.jsx
- src/components/Dashboard/__snapshots__/DashboardGrid.story.storyshot
Closes #780 
**Summary**
Dashboard Grid (dashboard,isEditable) : Tiles on dashboard grid is jump (animated) while rending the page.
src/components/Dashboard/DashboardGrid.jsx
src/components/Dashboard/snapshots/DashboardGrid.story.storyshot
Click on Dashboard (dashboard,isEditable) link, Dashboard tiles should be rendering static without animation
> fix(dashboardgrid): 6277-Dashboard-Grid-Tile-Jump

- src/components/Card/Card.jsx
- src/components/TimeSeriesCard/TimeSeriesCard.story.jsx
- src/components/TimeSeriesCard/timeSeriesUtils.js
- src/components/TimeSeriesCard/timeSeriesUtils.test.js
Closes #
**Summary**
- Now that we support dataFilters being attached to each line, we need to generate extra data to match each dataFilter
- fix(timeSeriesUtils): need to generate a row of data for each unique dataFilter.  If they leave off the dataFilter, than find the existing row and update it.
- I added a new isEditable bit to the dataFilter TimeSeriesCard story so you could test this.  It used to be when you set the card to isEditable, the card would show empty because no data would match it's filters.  Now it is showing sample data correctly
> fix(timeseries): generate sample values needs to use dataFilter

- src/components/Card/Card.jsx
- src/components/Card/Card.story.jsx
- src/components/Card/__snapshots__/Card.story.storyshot
- src/components/Card/_card.scss
- src/components/Dashboard/Dashboard.story.jsx
- src/components/Dashboard/__snapshots__/Dashboard.story.storyshot
- src/components/Dashboard/__snapshots__/DashboardGrid.story.storyshot
- src/components/ImageCard/__snapshots__/ImageCard.story.storyshot
- src/components/TimeSeriesCard/__snapshots__/TimeSeriesCard.story.storyshot
- src/components/ValueCard/__snapshots__/ValueCard.story.storyshot
Closes #
**Summary**
Allow to showing tooltip on mouse hover when the card title has ellipsis
src/components/Card/Card.jsx
src/components/Card/_card.scss
src/components/Dashboard/Dashboard.story.jsx
Showing tooltip when the card title has text overflow has ellipsis
> feat:GRAPHITE-6186: #AllowHeader-Tooltip-Overflow

- src/components/Table/Table.story.jsx
Closes #576
**Summary**
To get the floating menu to scroll together with the page, it should be attached to its parent element instead of `<body>` itself. To do that, you just need to add `data-floating-menu-container` to the element you want the menu to attach to (in this case the storybook container)
Verify it on ?path=/story/watson-iot-table--stateful-example-with-secondary-title
Please not that our storybook has a wrapping element with the styling `position: fixed` wrapping the stories, so the menu offset calculation fails sometimes. It's not a problem in normal apps.
> fix(floating-menu): add floating menu container to Storybook

- src/components/MultiSelect/_multi-select.scss
Closes #791
**Summary**
The css padding and margin of the multiselect selection badge were not right.
Check RTL on ?path=/story/multiselect--with-initial-selected-items
> fix(multiselect): improve RTL rendering for selected items badge

- src/components/Card/Card.jsx
- src/components/Dashboard/__snapshots__/Dashboard.story.storyshot
- src/components/TimeSeriesCard/TimeSeriesCard.jsx
- src/components/TimeSeriesCard/TimeSeriesCard.story.jsx
- src/components/TimeSeriesCard/__snapshots__/TimeSeriesCard.story.storyshot
- src/components/TimeSeriesCard/timeSeriesUtils.js
- src/components/TimeSeriesCard/timeSeriesUtils.test.js
- src/constants/LayoutConstants.js
Closes #
**Summary**
Improve the tooltip and markup to allow multiple alert ranges to match a given datapoint for a TimeSeriesCard
- fix(timeseriescard): fix style lint issue with the style
- feat(TimeSeriesCard): add support for multiple matching alert ranges for one datapoint
- feat(timeSeriesUtils): add support for matching multiple alert ranges
- tests here
> feat(timeseriescard): allow multiple alerts to match the same timeseries datapoint

- .travis.yml
- jest.config.js
- src/components/TableCard/__snapshots__/TableCard.story.storyshot
Related to #904 , #898 
**Summary**
- In #898 the testing thresholds weren't being met, yet CI didn't catch this. #904 updated the thresholds to get the build passing locally. 
- I suspect that CI builds passed while local builds failed because the testing script ran by travis piped the text results of `jest` directly to `yarn run coveralls`. Due to this, error codes from `jest` were being swallowed and not causing build failures when coverage thresholds were not met.
- Modify jest config to output lcov coverage reporter file
- Modify travis script to pipe the lcov coverage reporter file to coveralls, instead of directly piping lcov text output from jest.
> fix(ci): reconfigure coveralls to not swallow error exit codes

- src/components/List/HierarchyList/HierarchyList.jsx
- src/components/List/ListItem/ListItem.jsx
- src/components/List/ListItem/_list-item.scss
Closes #927 
**Summary**
- Fixed prop re-render comparison bug
- Fixed spacing issue
- Added `useDeepCompareEffect` with the `items` dependency to properly re-render
- Changed listItem style to use `padding-right` vs `margin-right` as the node was being moved when the text was too wide
- Open HierarchyList story in local dev environment
- Change one of the item prop values
- See that the element re-renders
- Proper testing needs a full implementation such as in Monitor
> [HierarchyList] re-render on prop change and fix styling

- .storybook/__snapshots__/Welcome.story.storyshot
- src/components/GaugeCard/_gauge-card.scss
- src/index.js
Closes #911 closes #921 
**Summary**
Needed to export the GaugeCard component and fixed styles when extra small card gets too small. 
Added GaugeCard to index.js and changed styles in _gauge-card.scss for defects on larger cards
Look at both the gaugecard story and change the size of the container in dev tools to be smaller than current. This will cause trend to drop to next line. Also check out basic dashboard story to see on large cards. Gauge should still look good in both cases.
> Export gauge

- src/components/ComposedModal/ComposedModal.jsx
- src/components/ComposedModal/ComposedModal.story.jsx
**Summary**
- Allows dialog users to disable the primary button with a new isPrimaryButtonDisabled property
- 
- Test out the primary button hidden story and see that the isPrimaryButtonDisabled can be set to disable the button
> feat(modal): add new isPrimaryButtonDisabled property

- src/components/List/ListItem/ListItem.jsx
- src/components/List/ListItem/_list-item.scss
Closes #931 
**Summary**
- Added `flex-grow: 0, flex-shrink: 0` to ListItem to fix broken width
- Add a nested item to List that is wider than the list width and see that the spacing is correct
- Can also verify by inspecting the &nbsp div is set at 30px (it was not before)
> fix(listitem): flex width is corrected

- src/components/Card/__snapshots__/Card.story.storyshot
- src/components/Dashboard/__snapshots__/Dashboard.story.storyshot
- src/components/Table/Table.story.jsx
- src/components/Table/TableHead/TableHead.jsx
- src/components/Table/TableHead/TableHead.test.jsx
- src/components/TableCard/__snapshots__/TableCard.story.storyshot
Closes #933
**Summary**
- Fixes a bug where if the columns array was initially empty, and then subsequently updated with new data - I was able to write a unit test against this bug
- Also refactored a bit while I was in there
- combination of some null checks and adding appropriate dependencies to the dependency array of a few hooks
- refactor a couple functions to useCallback, since they have dependencies and can be memoized without affecting functionality
- conditionally apply mouse event handlers for only when `useResize=true`
- refactor an abstracted function that was only used in `useLayoutEffect` to be inline there
- Check out the `with resize and no initial columns` story
> fix(tablehead): column resizing bug when columns initially empty

- src/components/List/List.jsx
- src/components/List/ListHeader/ListHeader.jsx
- src/components/List/ListHeader/ListHeader.test.jsx
**Summary**
- When title is `null` (or empty string) and no buttons are provided, hide the header.  This is needed to use List for navigation in some scenarios.
- fix(list): hide header when no title or search is present <-- note: I meant to say "buttons" instead of search here... search is rendered below the title/buttons section
- In the **basic (single column)** story, set the title to an empty string and verify the header is hidden.
> fix(list): hide header when no title or buttons are present

- src/components/Accordion/AccordionItem.jsx
- src/components/Accordion/AccordionItem.test.jsx
Closes #950 
**Summary**
onClick handler should have been onHeaderClick which is the prop Carbon accordion uses to trigger.
- Switched onClick to onHeaderClick in AccordionItem
- Open accordion story and try clicking on the content of the accordion.
> fix(accordionitem): change onClick to onHeaderClick

- src/components/Card/Card.jsx
- src/components/Card/Card.story.jsx
- src/components/Card/Card.test.jsx
- src/components/Card/__snapshots__/Card.story.storyshot
- src/components/Dashboard/Dashboard.story.jsx
- src/components/Dashboard/DashboardGrid.story.jsx
- src/components/Dashboard/DashboardGrid.test.jsx
- src/components/Dashboard/__snapshots__/Dashboard.story.storyshot
- src/components/Dashboard/__snapshots__/DashboardGrid.story.storyshot
- src/components/GaugeCard/GaugeCard.story.jsx
- src/components/ImageCard/ImageCard.jsx
- src/components/ImageCard/ImageCard.story.jsx
- src/components/ListCard/ListCard.story.jsx
- src/components/TableCard/TableCard.jsx
- src/components/TableCard/TableCard.story.jsx
- src/components/TableCard/TableCard.test.jsx
- src/components/TableCard/__snapshots__/TableCard.story.storyshot
- src/components/TimeSeriesCard/TimeSeriesCard.jsx
- src/components/TimeSeriesCard/TimeSeriesCard.story.jsx
- src/components/TimeSeriesCard/TimeSeriesCard.test.jsx
- src/components/TimeSeriesCard/__snapshots__/TimeSeriesCard.story.storyshot
- src/components/ValueCard/Attribute.jsx
- src/components/ValueCard/ValueCard.jsx
- src/components/ValueCard/ValueCard.story.jsx
- src/components/ValueCard/ValueRenderer.jsx
- src/components/ValueCard/__snapshots__/ValueCard.story.storyshot
- src/constants/LayoutConstants.js
- src/constants/PropTypes.js
- src/utils/__tests__/cardUtilityFunctions.test.js
- src/utils/cardUtilityFunctions.js
Closes #
**Summary**
This PR addresses this issue:
https://github.ibm.com/wiotp/monitoring-dashboard/issues/774
The card sizes and size names have been updated to reflect the latest design/implementation.
-Updated the constants CARD_SIZES, CARD_DIMENSIONS, and DASHBOARD_BREAKPOINTS.
-Updated each use of these constants throughout the repo to reflect the changes.
-Added a getUpdatedCardSize utility function to warn the user of deprecated size names and change their specified card size to the one that most closely matches it in the new set.
View any card in the story and see the names/sizes are updated.
> fix(card-sizes): Update card sizes and card names

- src/components/Breadcrumb/Breadcrumb.jsx
- src/components/Breadcrumb/Breadcrumb.story.jsx
Closes #924
**Summary**
This allows for children to update component. 
- change breadcrumb to update when Children prop changes
- changed stories to have knobs to change text. 
checkout story for resize and change knobs. Text should update.
> Breadcrumb knobs

- src/components/Dashboard/CardRenderer.jsx
- src/components/Dashboard/__snapshots__/Dashboard.story.storyshot
Closes #
**Summary**
- Small fix where for custom card types, the content prop was being passed downstream to the div that was being rendered and it was throwing an exception to the javascript console.
- Verify in the Dashboard stories with Custom cards, no exceptions logged to the javascript console.
> fix(cardrenderer): custom cards should not pass content to div

- src/components/PageWizard/PageWizard.jsx
- src/components/PageWizard/PageWizard.story.jsx
- src/components/PageWizard/PageWizardStep/PageWizardStep.jsx
- src/components/PageWizard/StatefulPageWizard.jsx
- src/components/PageWizard/__snapshots__/PageWizard.story.storyshot
**Summary**
- Add additional prop to pass custom content to footer
- Verify that the new **With additional footer content** story renders appropriately, and existing stories (without the new prop) render as expected.
> fix(pagewizard): add ability to pass extra buttons in footer

- src/components/Table/Table.story.jsx
- src/components/TableCard/__snapshots__/TableCard.story.storyshot
Closes #818
**Summary**
The positioning calculation of anything that uses in Carbon (Tooltip, Dropdown, etc) has some serious limitations (and it's [known and on the roadmap](https://github.com/carbon-design-system/carbon/issues/2907)).
This is especially true when needed inside a table with sticky header.
As a workaround, one can use `menuOffset` as explained [here](https://github.com/carbon-design-system/carbon/issues/4755#issuecomment-558131945)
A new story has been added: ?path=/story/watson-iot-table--with-sticky-header-and-cell-tooltip-calculation
> test(table): add story for sticky header and tooltip positioning

- src/components/Dashboard/__snapshots__/Dashboard.story.storyshot
- src/components/Table/Table.story.jsx
- src/components/Table/Table.test.jsx
- src/components/Table/TablePropTypes.js
- src/components/Table/TableToolbar/TableToolbar.jsx
- src/components/Table/TableToolbarSearch/TableToolbarSearch.jsx
- src/components/Table/TableToolbarSearch/_table-toolbar-search.scss
- src/components/TableCard/__snapshots__/TableCard.story.storyshot
- src/index.js
- src/styles.scss
#429
Closes #429
**Summary**
While we wait for Carbon 10 to be released and referenced, this is a port of their fix: https://github.com/carbon-design-system/carbon/commit/e97a7ed9be2911707066c406544310f6cb76f273
The default value can now be set with `view.toolbar.search.defaultValue`
- Added a wrapper around TableToolbarSearch
- Added a new story on ?path=/story/watson-iot-table--with-pre-filled-search
> fix(table): allow default values to be set

- src/globals/_charts.scss
Closes #986 
**Summary**
- added some css specific to the legend items
- check any chart with a legend (ie. ?path=/story/watson-iot-timeseriescard--largewide-multi-line-no-x-y-label) and switch to RTL: nothing should change
> fix(charts): legend labels should render correctly on RTL

- src/components/TimeSeriesCard/TimeSeriesCard.jsx
Closes #984 
**Summary**
It's very likely related to a bug on carbon-charts I just reported: https://github.com/carbon-design-system/carbon-charts/issues/521
- ?path=/story/watson-iot-dashboard--full-screen-bar-chart-card should render correctly
> fix(timeseries): set the right amout of chart labels

- src/components/TableCard/TableCard.test.jsx
- src/constants/PropTypes.js
- src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Closes #766
**Summary**
The objects in the column array can now contain a render-function called renderDataFunction.
Prop was incorrectly called `renderer` but should have been `renderDataFunction` to work with the underlying Table component. Renamed prop and added unit test.
Add a renderDataFunction function to a TableColumnsProp in content.columns[colItem] the same way you would do for a table.
> fix(tablecard): render data function now working

- src/components/Dashboard/__snapshots__/Dashboard.story.storyshot
- src/components/ValueCard/ValueCard.jsx
- src/components/ValueCard/ValueCard.test.jsx
- src/components/ValueCard/__snapshots__/ValueCard.story.storyshot
Closes #997
**Summary**
The ValueCard had stopped passing down the ID to te underlying Card.
This fix solves that.
-Pass down ID prop to Card
-Add unit test to prevent future regression
Check the ValueCard stories and make sure the underlying Cardwrapper has an id in the DOM
> fix(valuecard): add back id to be passed down to the card (#997)

- src/components/TableCard/TableCard.test.jsx
- src/components/TableCard/__snapshots__/TableCard.story.storyshot
- src/utils/__tests__/componentUtilityFunctions.test.js
- src/utils/componentUtilityFunctions.js
- src/utils/sample.jsx
Closes #1015 
**Summary**
- The integer 0 was being treated as falsy, which caused the 0 to be omitted. This PR adds an explicit check for `=== 0`
- Added 0 values to mock table data for future testing
- Added explicit check for integer 0 in CSV utility function
- Added test for use-case
- Added more comments about the utility functions
- Updated old test to reflect new 0 value
- Updated snapshots
1. Go to `/?path=/story/watson-iot-tablecard--size-large` and download the CSV
2. See that the 0 values appear in the pressure column
Old:
Updated:
> fix(tablecard): added explicit check for 0

- src/components/TableCard/TableCard.jsx
- src/components/TableCard/TableCard.story.jsx
- src/components/TableCard/TableCard.test.jsx
Closes #1021 
**Summary**
- Threshold columns were being render based off the `uniqueThreshold` array's index, rather than the values within. This meant that if the thresholds were defined in the wrong order, the columns would render in the incorrect position which was extremely fragile
**With Bug**
**With Fix**
- Changed `generateThresholdColumn` to return based on dataSourceId index
- Added more comments and documentation to story and code
- Re-ordered the thresholds in the story to show that it can be done
- Added a test for this bug
1. Go to https://deploy-preview-1022--carbon-addons-iot-react.netlify.com/?path=/story/watson-iot-tablecard--table-with-thresholds-precision-and-expanded-rows
2. See …
> fix(tablecard): thresholds render regardless of order

- src/components/Table/Table.jsx
Closes #
**Summary**
- show table toolbar when there is custom content but no other options
- Table Toolbar
- table with custom content in toolbar and no other options
- toolbar should be rendered
> fix(table): show toolbar if has custom content

- src/components/TableCard/TableCard.jsx
- src/components/TableCard/TableCard.story.jsx
- src/components/TableCard/TableCard.test.jsx
- src/components/TableCard/ThresholdIcon.jsx
- src/components/TableCard/__snapshots__/TableCard.story.storyshot
- src/components/TableCard/_threshold-icon.scss
- src/constants/CardPropTypes.js
- src/styles.scss
- src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Closes #1032 
**Summary**
- There was previously no way to customize the label strings or hide the label strings completely. This PR enables both of those use-cases
- added `showSeverityLabel` boolean prop that optionally hides the label text
- added `severityLabel` string prop that allows for custom strings to be rendered in place of the default *Critical, Moderate, Low* labels
- added tests for each use case
- added knobs for both props to all threshold stories
- added universal knobs to all TableCard stories
- removed 2 redundant stories
- converted `ThresholdIcons` styled-component to scss
- Go to each threshold story and use the knobs to verify that both use-cases work
> [TableCard] Thresholds labels are customizable and optionally hidden

- src/components/TileCatalog/TileCatalog.jsx
- src/components/TileCatalog/TileCatalog.test.jsx
- src/components/TileCatalog/__snapshots__/TileCatalog.story.storyshot
- src/components/TileCatalog/_tile-catalog.scss
- src/styles.scss
**Summary**
Migrate TileCatalog to scss from styled components.
Created an scss file for TileCatalog
Removed StyledComonents from TileCatalog
Updated test to accommodate for new className.
See that TileCatalog is still styled as expected.
> Migrate TileCatalog to scss

- src/components/Breadcrumb/Breadcrumb.jsx
- src/components/Breadcrumb/Breadcrumb.story.jsx
- src/components/Breadcrumb/Breadcrumb.test.jsx
- src/components/Breadcrumb/__snapshots__/Breadcrumb.story.storyshot
- src/utils/componentUtilityFunctions.js
Closes #1017
**Summary**
- Breadcrumb stories weren't rendering at all in Safari because we don't polyfill ResizeObserver and we also weren't disabling `hasOverflow` in environments with no ResizeObserver support
- Conditionally assign the ref used for `hasOverflow` based on ResizeObserver support
- In documentation, refactor usage of `useResizeObserver` prop to `hasOverflow`
- Add dev warning for no ResizeObserver support when using `hasOverflow`
- Add test, Update snapshot
- Breadcrumb stories don't work in Safari here (existing previous build): 
- https://deploy-preview-1008--carbon-addons-iot-react.netlify.com/?path=/story/watson-iot-breadcrumb--default
- Whereas now this should work in Safari …
> fix(breadcrumb): disable hasOverflow functionality when ResizeObserver not supported

- src/components/Dashboard/Dashboard.story.jsx
- src/components/Dashboard/__snapshots__/Dashboard.story.storyshot
- src/components/ValueCard/DataStateRenderer.jsx
- src/components/ValueCard/__snapshots__/ValueCard.story.storyshot
Closes #1040
**Summary**
GRAPHITE team has implemented the data-state-error value cards in Reference application Dashboard. Since it has multiple tiles/cards on the page. here if we are clicking on the no data or error icon the tooltip is opening behind other cards. As per discussion with team, they are mentioning that they are not directly using the IOT component and not modifying tooltip in GRAPHITE hence it seems to be fixed in IOT.
-Removed the tooltip wrapper which had the 'data-floating-menu-container' attribute. This wrapper was originally added as a fix recommended by carbon to handle the offset when the tooltip container was scrolling and there was a parent with position:fixed. That scenario is considered a corner case and non of the …
> fix(valuecard): data state tooltip opens behind other cards

- src/components/TableCard/__snapshots__/TableCard.story.storyshot
- src/components/TimePickerSpinner/TimePickerSpinner.jsx
- src/components/TimePickerSpinner/TimePickerSpinner.story.jsx
- src/components/TimePickerSpinner/TimePickerSpinner.test.jsx
- src/components/TimePickerSpinner/_time-picker-spinner.scss
- src/index.js
- src/styles.scss
- src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Needed for #854 
**Summary**
- The new DateTimePicker component requested on #854 needs some new components, like an inline calendar and a TimePicker with a numeric spinner. This PR takes care of the latter.
- Overridden and extended TimePicker so we can increment hours and minutes with the spinner buttons and/or keyboard
- Works with RTL
- Doesn't throw any a11y error
- new basic test suite available here: ?path=/story/watson-iot-experimental-timepicker--with-spinner
> feat(timepicker): add spinner support for TimePicker

- src/components/Dashboard/__snapshots__/Dashboard.story.storyshot
- src/components/ValueCard/Attribute.jsx
- src/components/ValueCard/UnitRenderer.jsx
- src/components/ValueCard/ValueCard.jsx
- src/components/ValueCard/ValueCard.story.jsx
- src/components/ValueCard/ValueRenderer.jsx
- src/components/ValueCard/__snapshots__/ValueCard.story.storyshot
- src/components/ValueCard/_unit-renderer.scss
Summary
This PR references these issues:
https://github.ibm.com/wiotp/monitoring-dashboard/issues/693
#1027
The original, closed PR can be found here: https://github.com/IBM/carbon-addons-iot-react/pull/1028
Long strings in ValueCards were not very accessible with only one line of text before the ellipsis. This PR allows long strings to wrap to a max of 2 lines.
Change List (commits, features, bugs, etc)
Added styling to ValueRenderer
Created new ValueCard story with a long string
Acceptance Test (how to verify the PR)
Navigate to ValueCard 'small / long string' and see the text wrap to two lines before the ellipsis.
> fix(value-card-wrap): wrap long strings to two lines

- src/components/Table/TableHead/ColumnHeaderRow/ColumnHeaderRow.test.jsx
- src/components/Table/TableHead/ColumnHeaderSelect/ColumnHeaderSelect.jsx
- src/components/Table/TableHead/_table-head.scss
Closes #1006
**Summary**
The table updates “realtime” while the user is dragging a column and it can cause sluggish and buggy behaviour because of all the processing that is going on per render.
- Update the columns on drop instead of hover
- Updated unit tests
- Try to reorder columns and verify that nothing changes (visually nor onChangeOrdering) until the column is dropped.
> fix(table): column ordering slow

- jest.config.js
- package.json
- src/components/TimeSeriesCard/TimeSeriesCard.jsx
- src/components/TimeSeriesCard/TimeSeriesCard.story.jsx
- src/components/TimeSeriesCard/TimeSeriesCard.test.jsx
- src/constants/CardPropTypes.js
- src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
- src/utils/sample.jsx
- yarn.lock
Closes #1048 
**Summary**
- Allows user to hide zero, meaning the data can be focused and be easier to read
**Before**
**After**
- Upgraded carbon version to pick up the `showZero` prop
- Added `includeZeroOnXaxis` and `includeZeroOnYaxis` props which default to true
- Added knobs to each TimeSeriesCard story
- Go to any TimeSeriesCard story that has data high above 0 and change the `content` JSON object's `includeZeroOnYaxis` prop to false to see the change. The stories' data is randomized so this may take a few clicks between stories or refreshes.
> [TimeSeriesCard] enable hiding zero

- src/components/TableCard/TableCard.jsx
- src/components/TableCard/TableCard.test.jsx
Closes #1052 
**Summary**
- Column indices were being referenced from the incorrect column array in a loop causing the indices to be off on each iteration
Apologies for 2 different photos, but you can see the threshold column differences
**Before**
**After**
- Updated variable names to be more specific
- Updated `generateThresholdColumn` to iterate on the `uniqueThresholds` vs the `columns` as its less complex and will require fewer iterations
- Updated column update splicing and indexing to use `columnsUpdated` vs `columns` as `columnsUpdated` is whats actually being manipulated
1. Go to TableCard with thresholds story and add a third threshold for hours with the following additional threshold: 
``` …
```
> [TableCard] - columns render in correct order regardless or quantity

- src/components/TileCatalog/CatalogContent.jsx
- src/components/TileCatalog/__snapshots__/TileCatalog.story.storyshot
- src/components/TileCatalog/_catalog-content.scss
- src/globals/_vars.scss
- src/styles.scss
**Summary**
Migrate `CatalogContent` from styled-components to scss
Navigate to TileCatalog and see that the content is still styled correctly.
> chore(catalog-content): migrate to scss

- src/components/TimeSeriesCard/TimeSeriesCard.jsx
- src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
#1048
**Summary**
- It was more beneficial to the user to hide zero on the axes and keep the data visualization more focused by default
- Changed default setting to hide zero on x and y axes
- Check the TimeSeriesCards to see that the 0 is hidden by default on stories that have no data near 0
> feat(timeseriescard): hide zero on axis by default

- src/components/Dashboard/__snapshots__/Dashboard.story.storyshot
- src/components/ValueCard/ValueCard.jsx
- src/components/ValueCard/ValueCard.story.jsx
- src/components/ValueCard/ValueCard.test.jsx
- src/components/ValueCard/__snapshots__/ValueCard.story.storyshot
Closes #
**Summary**
- Small fix to make font sizes smaller at Medium and Medium Thin sizes and to always align vertically
- test(story): added a few new card sizes to the stories
- Check the Value Card layout in all the stories and make sure they look ok.
> fix(valuecard): at certain card sizes font sizes were too big

- src/components/TextInput/TextInput.story.jsx
- src/components/TextInput/_text-input.scss
Closes #1031 
**Summary**
Add xxl height to text inputs
- Component already adds size prop to a classname. Just added styles for xxl variant 
- Go to Text input story
- Go to knob and choose xxl for size
- Profit
> 1031 xxl input

- src/components/Card/Card.jsx
- src/components/PageTitleBar/PageTitleBar.jsx
- src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Closes #1120 
**Summary**
Small fix to the prop types that are incorrectly defined.
Removed the default prop type for deprecated prop type to avoid a constant set of warning about it being deprecated even when it wasn't being used.
> chore: updated invalid prop types

- src/components/Card/__snapshots__/Card.story.storyshot
- src/components/Dashboard/__snapshots__/Dashboard.story.storyshot
- src/components/Table/Table.jsx
- src/components/Table/Table.story.jsx
- src/components/Table/TableBody/TableBody.jsx
- src/components/Table/TableBody/TableBodyRow/TableBodyRow.jsx
- src/components/Table/TableCellRenderer/TableCellRenderer.jsx
- src/components/Table/TableCellRenderer/TableCellRenderer.test.jsx
- src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Prereqs: https://github.com/IBM/carbon-addons-iot-react/pull/1134
**Summary**
- Fixes issues with numeric formatting in locales.  I made this feature opt-in so it wouldn't break previous Table users.  If you don't pass a locale prop to the Table, it doesn't locale format your numbers.
- fix(Table): add locale option to table, pass through to TableCellRenderer
- fix(TableCellRenderer): render the numeric value in the current locale with the maximum available amount of decimal points
- Check that the Table i18n story is locale formatting in the thousands correctly.
> fix(table): locale format any number values

- src/components/TimeSeriesCard/TimeSeriesCard.jsx
- src/components/TimeSeriesCard/TimeSeriesCard.test.jsx
- src/components/TimeSeriesCard/timeSeriesUtils.js
- src/components/TimeSeriesCard/timeSeriesUtils.test.js
Closes #1159 
Closes #1161 
**Summary**
- TimeSeriesCard's logic to detect if the values was empty didn't cover all cases so the function was adjusted to handle the new `formatChartData` returned data
- TimeSeriesCard was not passing props correctly for `isLoading` and was rendering an empty div instead of the SkeletonText
- Removed `isValuesEmpty` function in favor of checking if the returned formatted data is empty or not, as `formatChartData` will filter out the empty values instead
- Added test for this use-case
- Added check for SkeletonText in isLoading test for pesky render bug
1.
- Go to TimeSeriesCard and adjust the values array prop to give incomplete data such as `[{deviceId: "robot1"}, …
> fix(timeseriescard): render no data instead of error

- src/components/Dashboard/__snapshots__/Dashboard.story.storyshot
- src/components/TimeSeriesCard/TimeSeriesCard.jsx
- src/components/TimeSeriesCard/TimeSeriesCard.test.jsx
- src/components/ValueCard/ValueRenderer.jsx
- src/utils/__tests__/cardUtilityFunctions.test.js
- src/utils/cardUtilityFunctions.js
Closes #1184
**Summary**
- Value Card was ignoring the passed precision for small cards. We should always respect it
- refactor(TimeSeriesCard): migrate the determinePrecision to the shared utils function instead of having a copy in both ValueRenderer and TimeSeriesCard
- Verify that the testcases pass, it's okay that the Dashboard story updated because we have enough room to render the slightly more precise values.
> fix(valuecard): always use precision if passed

- src/components/TimeSeriesCard/_time-series-card.scss
Closes #1164
**Summary**
- Save the top 50% of the expanded card for the chart
- limit the table to the bottom 50% of the card when in expanded mode
- Verify the TimeSeriesCard is expanded testcases in here: 
http://127.0.0.1:3000/?path=/story/watson-iot-dashboard--full-screen-bar-chart-card
http://127.0.0.1:3000/?path=/story/watson-iot-dashboard--full-screen-line-card
> fix(timeseriescard): fullscreen should put table in bottom half

- src/components/Dashboard/__snapshots__/Dashboard.story.storyshot
- src/components/Table/EmptyTable/EmptyTable.jsx
- src/components/Table/EmptyTable/__tests__/EmptyTable.test.jsx
- src/components/Table/StatefulTable.jsx
- src/components/Table/Table.jsx
- src/components/Table/Table.test.jsx
- src/components/TableCard/__snapshots__/TableCard.story.storyshot
- src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Closes #1187
**Summary**
- There's no good way to hide the Create New or Clear All Filters Button in the emptyState of the table.
- fix(Table): change onEmptyStateAction to actually be optional if not passed, so the button doesn't render if it's not passed
- fix(Table): change buttonLabelWithFilters to be optionally set, if it's not set and the table is filtered, don't show the button (I did this for backwards compatibility, I'd love to hide the button for all filtered tables for everybody, but in-case some user really wanted it, I allow them to set buttonLabelWithFilters to render a custom button)
- Verify that if onEmptyStateAction is passed the button shows, but otherwise it doesn't show.  This …
> fix(table): empty state button always shows

- src/components/SideNav/_side-nav.scss
Closes #1195
**Summary**
- Due to a change in carbon-components for sidenav, we need to have a more specific background color and color override to make our SideNav Menu items be dark themed
- fix(sidenav): make our background color and color for active elements be more specific
- It's actually hard to verify the fix because the error doesn't occur until after you've imported carbon-addons-iot-react
> fix(sidenav): need to override carbon-components active style of menu item

- src/components/TableCard/TableCard.jsx
- src/components/TableCard/TableCard.test.jsx
Closes #1206
**Summary**
- A tablecard threshold could only match a numeric threshold
- fix(tablecard): support case where threshold value matches exact string
- Verify that none of the existing table card snapshots have changed, but that the new testcase has passed.
> fix(tablecard): update find matching thresholds

- src/components/Table/Table.story.jsx
- src/components/Table/TableBody/RowActionsCell/RowActionsCell.jsx
- src/components/Table/TableBody/RowActionsCell/_row-actions-cell.scss
- src/components/Table/TableBody/TableBodyRow/TableBodyRow.story.jsx
- src/components/Table/TableBody/TableBodyRow/__snapshots__/TableBodyRow.story.storyshot
Closes #1177
**Summary**
The title that appears on hover on the overflow button's menu items is [object, object]. This was due to the fact that the `labelText` prop is used as title in Carbon, but we pass in JSX instead of a string.
- requiredTitle is only used for string values
- added our own title for JSX menu items
- updated the story for better testing
1. Go to story watson-iot-table--stateful-example-with-row-nesting-and-fixed-columns
2. Click row action overflow button
3. Verify that all menu items have the correct title on hover
> feat(table): incorrect title of row actions

- src/components/Table/Table.jsx
- src/components/Table/Table.story.jsx
- src/components/Table/Table.test.jsx
- src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Closes #458 
**Summary**
- There is an issue with our pagination that when the table is loaded with a large data set it will try to make select options for the dropdown for each page. This causes the table to crash and never render. 
- Introduction of a `maxPages` prop that is passed along with the `view.pagination` object. This prop will limit the amount of pages that the dropdown will try to render. 
- Updated story to include a maxPages prop so we can see the page limit in the story. 
- Go to [Table story](?path=/story/watson-iot-table--stateful-example-with-expansion-and-column-resize)
- see the pagination size is limited to 2 because of filters.
- Remove filters and see that maxPages is limiting …
> 458 table scalability

- src/components/Table/TableHead/FilterHeaderRow/FilterHeaderRow.jsx
- src/components/Table/TableHead/_table-head.scss
Closes #1108
**Summary**
- super small fix, just needed to override an `overflow: hidden` coming from Carbon styles.
> fix(table): filter dropdown overflow should be visible

- src/components/Table/Table.story.jsx
Closes #1222 
**Summary**
Our current story does not show off the `maxPages` feature. This PR lowers the threshold and adds the prop to the info section of the story.  
- Changed the `maxPages` to 5 and added the prop to the info section in the `table.story.jsx`
- Go to [this story](https://deploy-preview-1223--carbon-addons-iot-react.netlify.app/?path=/story/watson-iot-table--stateful-example-with-expansion-maxpages-and-column-resize)
- Clear filter
- See that the pages in the pagination select dropdown equal 5
> 1222- Add info to Max Pages story

- src/components/Table/TableBody/RowActionsCell/RowActionsCell.jsx
- src/components/Table/TableBody/RowActionsCell/RowActionsCell.test.jsx
- src/components/Table/TableBody/RowActionsCell/_row-actions-cell.scss
Closes #1217
**Summary**
Keyboard navigation fixed for row actions in overflow button.
- made sure overflow button is visible when it has focus
- preselect a menu item so that keyboard navigation works when opening the overflow menu using keyboard (enter key when focused)
- add unit tests
1. Go to story [watson-iot-table--stateful-example-with-expansion-and-column-resize](https://deploy-preview-1221--carbon-addons-iot-react.netlify.app/?path=/story/watson-iot-table--stateful-example-with-expansion-maxpages-and-column-resize)
2. Click on a row or use tab to navigate to a row. 
3. Verify that the you can use tab to focus the row actions overflow button and that it becomes visible
4. Press "enter" or …
> fix(table): keyboard navigation not working on row actions

- src/components/TableCard/TableCard.jsx
- src/components/TableCard/TableCard.story.jsx
- src/components/TableCard/TableCard.test.jsx
- src/components/TableCard/__snapshots__/TableCard.story.storyshot
Closes #1216 
**Summary**
Add a handleExpandedItemLinks function to update expanded row data with links
Add HandleExpandedItemLinks function
Add stories and test cases
In the stories `table with row expansion and link variables` and `table with row expansion and row specific link variables`, verify that the links in the expanded rows navigate you to a new page based on the href value in the expanded rows data.
Fill in row specific variables (ie 'count', 'pressure', 'hour', or 'alert') in the href knob to see the link dynamically change based on row context.
> fix(table-card): support links in expanded rows

- src/components/TileCatalogNew/TileCatalogNew.jsx
- src/components/TileCatalogNew/TileCatalogNew.story.jsx
- src/components/TileCatalogNew/TileCatalogNew.test.jsx
- src/components/TileCatalogNew/_tile-catalog.scss
- src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Closes #1239
**Summary**
Migrates `TileCatalogNew` to use css grid instead of a flex box matrix to allow for responsive realignment.
- Add isLoading state
- Add error state
- Add `minTileWidth` prop to allow users to set their own grid
- Use css grid instead of flex
- Make pagination conditional upon whether there are enough tiles to have 2 or more pages
- Add classname prop
Click through the stories and change knobs to see the various changes in action.
> Migrate TileCatalogNew to grid

- package.json
**Summary**
- Correct `engines` to allow node 10 or 12, ensure node 12 is used when developing locally
- update package.json
- pull down the branch, run the following:
| command | expected result |
| - | - |
| `nvm use 8 && yarn` | ❌ should show failure message |
| `nvm use 10 && yarn` | ✅ should pass |
| `nvm use 12 && yarn` | ✅ should pass |
| `nvm use 14 && yarn` | ❌ should show failure message |
| `nvm use 10 && yarn test:engines` | ❌ should show `check-node-version` failure message |
| `nvm use 12 && yarn test:engines` | ✅ should pass | 
| `nvm use 14 && yarn test:engines` | ❌ should show `check-node-version` failure message |
> fix(node): specify correct version in engines, require 12 for local dev

- src/components/Card/DataStateRenderer.jsx
- src/components/ValueCard/ValueCard.story.jsx
- src/components/ValueCard/__snapshots__/ValueCard.story.storyshot
- src/constants/CardPropTypes.js
- src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Closes #1198
**Summary**
- Change the direction that data state tooltips are rendered on cards
- items_here
- view https://deploy-preview-1278--carbon-addons-iot-react.netlify.app/?path=/story/watson-iot-valuecard--data-state-error-small 
- also view the other data state stories
- the tooltip should render `right` instead of `bottom`
> fix(card): avoid clipping data state renderer error tooltip

- src/components/Table/Table.test.jsx
- src/components/Table/TableBody/TableBodyRow/TableBodyRow.jsx
- src/components/Table/TableCellRenderer/TableCellRenderer.jsx
- src/components/TableCard/__snapshots__/TableCard.story.storyshot
Closes #1262
**Summary**
The renderDataFunction is not included in the CellRenderer which means that apps that use renderDataFunction will miss out on CSS settings causing cell text wrapping and truncation to fail where it could have worked.
**Note**
Note sure if this should be considered breaking functionality since cells that are using renderDataFunction now could be wrapped with these classes  (when the wrapText prop is used) which might affect that cell rendering.
```
.#{$iot-prefix}--table__cell-text--truncate {
@include text-overflow();
display: block;
}
.#{$iot-prefix}--table__cell-text--no-wrap {
white-space: nowrap;
}
```
- Moved renderDataFunction into TableCellRenderer so that the cell from a renderDataFunction will be wrapped by …
> 1262 table cells will overflow under some conditions

- src/components/Table/Table.jsx
- src/components/Table/Table.test.jsx
- src/components/Table/TableBody/RowActionsCell/_row-actions-cell.scss
- src/components/Table/_table.scss
Closes #1085
**Summary**
Row action gradient container should fill the entire height of the table cells
The fix requires the table height to be 0. I've checked that all the stories and they seem to look normal.
- Added css.
- Added unit test
1. go to story watson-iot-table--stateful-example-with-expansion-maxpages-and-column-resize
2. Using chrome dev tools element inspector select the first row and force element state "hover"
3. Again with the element inspector hover over the `row-actions-container__background` and make sure it fills the table cell vertically
> fix(table): row action gradient height should be dynamic

- src/components/List/HierarchyList/HierarchyList.jsx
Closes #1319
**Summary**
Need to preserve the `expandedIds` state so that items don't collapse on update of `defaultSelectedId`.
Keep the previous `expandedIds` when useEffect re-runs based on the `defaultSelectedId` dependancy
Hard to verify in storybook.
In 'with default selectedId' story, paste in a new `defaultSelectedId` and see that the other items do not collapse.
> fix(hierarchylist): preserve expanded state

- src/components/BarChartCard/barChartUtils.js
- src/components/BarChartCard/barChartUtils.test.js
Closes #1312 
**Summary**
- Dataset series labels weren't being displayed so this PR checks to see if there is a label and uses it if true
- Added conditional check for the `series[i].label`
- Added label to existing test
- Go to https://deploy-preview-1313--carbon-addons-iot-react.netlify.app/?path=/story/watson-iot-barchartcard--simple-bar-time-series of netlify preview and see that the label now says `Particles' instead of 'particles'
> fix(barchartcard): use label in simple, time-series

- src/components/ImageCard/Hotspot.jsx
- src/components/ImageCard/ImageHotspots.jsx
Closes #1154
**Summary**
- Removed unused props in ImageCard with hotspots causing errors
- Removed `offsetX` and`offsetY` props being passed down to `Hotspot` in `ImageHotspot.jsx`
- Removed `clickToOpen` prop being passed down to `Tooltip` in `Hotspot.jsx`
- Open Storybook
- Render the ImageCard with hotspots story
- Open console and see no more errors popping up
> fix(image-hotspot): removed unused props

- .github/ISSUE_TEMPLATE/bug-report.md
- .github/ISSUE_TEMPLATE/feature-request-or-enhancement.md
- .github/ISSUE_TEMPLATE/new-component-proposal.md
- .github/ISSUE_TEMPLATE/question.md
**Summary**
- This will help us filter issues that haven't been addressed, validated, estimated, etc.
- add label to all 4 issue templates
> add 'needs triage' label to issue templates

- src/components/Dashboard/__snapshots__/Dashboard.story.storyshot
- src/components/Table/TableHead/TableHead.jsx
- src/components/TableCard/__snapshots__/TableCard.story.storyshot
Closes #1330 
**Summary**
Fixes the clear filter issue that was introduced 
- add key conditionally to filterheaderrow
- go to ?path=/story/watson-iot-table--stateful-example-with-expansion-maxpages-and-column-resize
- open knobs and change hasFilter from onKeyPress to onBlur
- press clear filter button
- see that all filters are cleared.
> Tablefilter fix

- src/components/List/HierarchyList/HierarchyList.jsx
- src/components/List/HierarchyList/HierarchyList.test.jsx
Closes #
**Summary**
- If you switch the defaultSelectedId in the live preview knob here, you'll notice the selected state doesn't get updated
- Small change to set the selectedId if the defaultSelectedId incoming prop changes
- Verify that if you change the defaultSelectedId in the story, the visual selection state is updated
> fix(hierarchylist): set the selected state if defaultSelectedId changes

- src/components/Table/StatefulTable.test.jsx
- src/components/Table/TableHead/FilterHeaderRow/FilterHeaderRow.jsx
- src/components/Table/TableHead/FilterHeaderRow/FilterHeaderRow.test.jsx
Closes #1329
**Summary**
Clear filters would not clear the filter inputs, nor would setting filters to empty array. This change fixes those regressions. 
- Changed the way we are populating state in filterheaderrow 
- wrote test in Statefultable.test
- Go to table story
- Click clear filters button
- you should see the filter inputs clear
- Try adding a new filter.
- filters should work as expected
> fix(filterheaderrow): fix regression with clear filters 

- .eslintrc
- src/components/AddCard/AddCard.jsx
- src/components/Button/Button.jsx
- src/components/Card/Card.jsx
- src/components/Card/CardRangePicker.jsx
- src/components/Card/CardToolbar.jsx
- src/components/ComposedModal/ComposedModal.jsx
- src/components/Header/HeaderAction/HeaderActionMenu.jsx
- src/components/Header/HeaderAction/HeaderActionPanel.jsx
- src/components/IconSwitch/IconSwitch.jsx
- src/components/ListCard/ListCard.jsx
- src/components/PageTitleBar/PageTitleBar.jsx
- src/components/PageWizard/PageWizard.jsx
- src/components/Table/Table.jsx
- src/components/Table/TableBody/TableBodyRow/TableBodyRow.jsx
- src/components/Table/TableHead/ColumnHeaderSelect/ColumnHeaderSelect.jsx
- src/components/Table/TableHead/FilterHeaderRow/FilterHeaderRow.jsx
- src/components/Table/TableHead/TableHeader.js
- src/components/Table/TableToolbar/TableToolbar.jsx
- src/components/Table/TableToolbar/TableToolbarSVGButton.jsx
- src/components/TileCatalog/TileCatalog.jsx
- src/components/TileCatalog/TileGroup.jsx
- src/components/ValueCard/Attribute.jsx
- src/components/ValueCard/UnitRenderer.jsx
- src/components/ValueCard/ValueRenderer.jsx
- src/components/WizardModal/WizardModal.jsx
Closes #799
**Summary**
The classnames import used multiple names depending on the file (classnames, classNames, cx, cn), so the import names were updated so only one name is used (classnames).
- Updated classnames import for a consistent import name
- Opened issue #1325 to track the progress for a potential ESLint rule that will maintain consistent naming for future imports.
- In VSCode, do a project wide search for "classnames"
- This search should show that each time classnames is imported, it will be imported as "classnames"
> feat(classnames): updated classnames import for a consistent import name

- src/components/Table/TableBody/RowActionsCell/RowActionsCell.jsx
- src/components/Table/TableBody/RowActionsCell/_row-actions-cell.scss
- src/components/Table/TableBody/TableBodyRow/__snapshots__/TableBodyRow.story.storyshot
Closes #1314 
**Summary**
- Color was blue by default which did not adhere to the original design
- Swap color to black by default and blue on hover
- Check the row actions story to see that the colors are correct
> fix(rowactioncell): change action color

- src/components/Table/Table.story.jsx
Closes #1242 
**Summary**
Made a note that the sticky header feature for the table is experimental.
- Changed the title for the table sticky header story so it notes that the feature is experimental
- When the storybook is launched (yarn start), scroll down to Table and view the stories within the component. The sticky header story should have (experimental) in the title to indicate.
> feat(story): edited the title for the table sticky header story

- src/components/List/SimpleList/SimpleList.jsx
- src/components/List/SimpleList/SimpleList.test.jsx
Closes #1149 
**Summary**
- SimpleList items were not deselectable, but now can be
- selectedItems.filter had a typo of item.id instead of just item
changed the setSelectedItems and setSelectedItem to check if the item is selected at all, not just the last one selected
- Go to the SimpleList basic story, items should be selectable and deselectable
> fix(simplelist): SimpleList items are now deselectable

- src/components/BarChartCard/BarChartCard.jsx
- src/components/TimeSeriesCard/TimeSeriesCard.jsx
- src/components/TimeSeriesCard/TimeSeriesCard.story.jsx
- src/utils/__tests__/cardUtilityFunctions.test.js
- src/utils/cardUtilityFunctions.js
Closes #1360 
**Summary**
- All values above 1000 were getting rounded down cause the y-axis to show the same values if the values were close enough together
- Updated 1 story to have very high values where this bug appears
- Created a new function called `formatChartNumberWithPrecision` that would only localize and reduce the decimals rather than dividing and rounding down the number in chart cards
- Updated `valueFormatter` name to `chartValueFormatter` to ensure that its understood to be only for charts
- Go to the following story and see that the values on the y-axis and the hovered datapoint tooltip shows the whole value value, instead of rounding it …
> fix(TimeSeriesCard): removed rounding and separator in formatter function

- src/components/Table/Table.test.jsx
- src/components/Table/TableToolbar/TableToolbar.jsx
Closes #1386
**Summary**
- Updates `TableToolbarSearch` to use `defaultValue` as a `key` so that updates to `defaultValue` cause a new instance of `TableToolbarSearch` to be created. This ensures that updates to `defaultValue` are reflected in the UI.
*Additional context*
In most cases in the Carbon codebase, `default*` variables, like `defaultValue` are intended to be single use and applied only once on initial render. In this specific case, updates to `defaultValue` intentionally do not trigger an update - it's not included in the useEffect dependency array. See [the thread here in the resolved conversation at this line](https://github.com/carbon-design-system/carbon/pull/5089/files#diff-e1d0d4ed749b59e29737a31a99c2686aR66) for more info.
- …
> fix(table): TableToolbarSearch rerenders when defaultValue is modified

- src/components/Table/tableReducer.js
Closes #1189
**Summary**
Table filters were failing for numbers and booleans due to the comparison method used.
Converts the user input filter to a number for direct comparison.
Allows false booleans to be compared.
Go to the Table story: stateful-example-with-expansion-and-column-resize and confirm that all of the filter options work properly.
> Table filter numbers and booleans

- src/components/List/ListItem/ListItem.jsx
- src/components/PageWizard/PageWizardStep/PageWizardStep.jsx
- src/components/PageWizard/StatefulPageWizard.jsx
- src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Closes #1227 
**Summary**
- Relax the required proptypes for pagewizardstep as they shouldn't be required
- fix(ListItemWrapper): invalid proptype for children
- fix(PageWizard): remove the required proptypes for the functions as single step page wizards don't need them
- Only propTypes changes, no functional changes
> fix(proptypes): relax proptypes errors on pagewizard

- config/jest/setupTest.js
- package.json
- yarn.lock
Tests are failing in master.
**Summary**
- Defer the loading of the accessibility-checker package due to a race condition causing tests to fail randomly due to network errors. 
- Carbon https://github.com/carbon-design-system/carbon/blob/master/tasks/jest/matchers/toHaveNoDAPViolations.js#L10
- ibm-security https://github.com/carbon-design-system/ibm-security/pull/581
- update dep to latest version
- modify jest test setup file
- status checks should pass
I've opened a bug on the `accessibility-checker` package https://github.com/IBMa/equal-access/issues/143
> fix(tests): defer loading acessibility-checker package

- src/components/Dashboard/DashboardHeader.story.jsx
- src/components/DateTimePicker/DateTimePicker.story.jsx
- src/components/Header/Header.jsx
- src/components/ImageCard/CardIcon.jsx
- src/components/ImageCard/CardIcon.test.jsx
- src/components/SideNav/SideNav.story.jsx
- src/components/SideNav/SideNav.test.jsx
- src/components/Table/Table.story.jsx
- src/components/Table/TableBody/RowActionsCell/RowActionsCell.jsx
- src/components/Table/TableBody/RowActionsCell/RowActionsCell.test.jsx
- src/components/Table/TableBody/TableBodyRow/TableBodyRow.story.jsx
- src/components/Table/TableBody/TableBodyRow/__snapshots__/TableBodyRow.story.storyshot
- src/components/Table/TableCellRenderer/TableCellRenderer.test.jsx
related to #1382 
**Summary**
PR to fix several test log issues. 
- Swapped out a couple icon names that were deprecated from Carbon for their new versions.
- Changed date format for our default Absolute date in DateTimePicker. 
- Changed test for ImageCard to test for implementation instead of looking for the console warning. Then added ignore to test since we will never trigger that if statement in our testing suite
- Added `truncateCellText` to TableCellRenderer
- Go to each test file and run them. You should not see any console statements or deprecation warnings.
> [Repo] 1382 test log cleanup

- .storybook/__snapshots__/Welcome.story.storyshot
- src/components/Accordion/__snapshots__/AccordionItemDefer.story.storyshot
- src/components/ComboBox/__snapshots__/ComboBox.story.storyshot
- src/components/DateTimePicker/__snapshots__/DateTimePicker.story.storyshot
- src/components/GaugeCard/__snapshots__/GaugeCard.story.storyshot
- src/components/List/HierarchyList/HierarchyList.jsx
- src/components/List/HierarchyList/__snapshots__/HierarchyList.story.storyshot
- src/components/List/List.story.jsx
- src/components/List/ListHeader/ListHeader.jsx
- src/components/List/ListItem/__snapshots__/ListItem.story.storyshot
- src/components/List/SimpleList/SimpleList.story.jsx
- src/components/List/SimpleList/__snapshots__/SimpleList.story.storyshot
- src/components/List/__snapshots__/List.story.storyshot
- src/components/ListCard/__snapshots__/ListCard.story.storyshot
- src/components/StorybookSnapshots.test.js
- src/components/Table/TableViewDropdown/__snapshots__/TableViewDropdown.story.storyshot
- src/components/TileCatalogNew/TileCatalogNew.jsx
- src/components/TileCatalogNew/TileCatalogNew.story.jsx
- src/components/TileCatalogNew/TilePagination/TilePagination.jsx
- src/components/TileCatalogNew/__snapshots__/TileCatalogNew.story.storyshot
- src/components/TileGallery/TileGallery.jsx
- src/components/TileGallery/__snapshots__/TileGallery.story.storyshot
- src/components/TimePickerSpinner/__snapshots__/TimePickerSpinner.story.storyshot
- src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Part of #1413
**Summary**
- Re-enables snapshot testing for experimental components
- Disables snapshot testing for TileCatalogNew, SimpleList, and ListItem as they have unique key warnings that require more work to fix. Tracking with #1412 
- Removed Experimental regex from `StorybookSnapshots.test.js`
- Added regex to pass testing on TileCatalogNew, SimpleList, and ListItem
- Added `labelText` prop to List stories to remove warning
- Added keys to SimpleList story action components to remove warning
- Fixed proptype in TileCatalogNew to not require the prop `tiles` to remove warning
- Added warning exception for ComboBox experimental prop to remove warning
- Added exception for HierarchyList's ref and mocked `scrollIntoView` as its not …
> fix(experimental): enabled snapshots for all experimental components

- src/components/BarChartCard/BarChartCard.jsx
- src/components/Table/Table.jsx
- src/components/Table/Table.story.jsx
- src/components/Table/TableToolbar/TableToolbar.jsx
- src/components/TableCard/TableCard.jsx
- src/components/TimeSeriesCard/TimeSeriesCard.jsx
- src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
- yarn.lock
Closes #1448 
**Summary**
- Passed the filteredData back to the `onDownloadCsv` callback so the CSV will be generated with the active filtered data
- Pass `data` prop to TableToolbar
- Added `data` propType to TableToolbar
- Updated the publicAPI snapshot to reflect the new prop
- Changed `onClick` prop of TableToolbarSVGButton to call the `onDownloadCsv` callback with the filtered `data` prop
- Changed all cards that use `onDownloadCsv` to use the new callback `data` argument
- I didn't do anything but `yarn install` from the master branch so I'm not sure where the yarn.lock change came from
1. Go to any story that implements `onDownloadCsv` (I was using TableCard)
2. Click the CSV download toolbar …
> fix(table): pass filteredData to onDownloadCsv

- package.json
- src/components/BarChartCard/BarChartCard.jsx
- src/components/BarChartCard/BarChartCard.story.jsx
- src/components/BarChartCard/__snapshots__/BarChartCard.story.storyshot
- src/components/TimeSeriesCard/TimeSeriesCard.jsx
- src/components/TimeSeriesCard/TimeSeriesCard.story.jsx
- src/components/TimeSeriesCard/__snapshots__/TimeSeriesCard.story.storyshot
- src/constants/CardPropTypes.js
- src/constants/LayoutConstants.js
- src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
- yarn.lock
Closes https://github.com/carbon-design-system/carbon-addons-iot-react/issues/1456
**Summary**
- Adds alpha zoomBar functionality to TimeSeriesCard and BarChartCard using the new `zoomBar` prop
- Restricts the zoomBar to cards of size MEDIUMWIDE, LARGE, LARGEWIDE as the other sizes are too small to render both the chart and the zoomBar
- Note: This feature is experimental in carbon charts
```
zoomBar: {
axes: string,   // defaults to top as thats the only axis supported at the moment
enabled: boolean,
initialZoomDomain: array<string|number>    // same as the current `domainRange` prop
}
```
- Added 2 stories to show the zoomBar feature
- Updated to latest carbon charts to pick up this feature
- Go to …
> feat(TimeSeriesCard/BarChartCard): add zoomBar functionality

- src/components/Table/Table.story.jsx
- src/components/Table/TableBody/RowActionsCell/RowActionsCell.jsx
- src/components/Table/TableBody/TableBodyRow/TableBodyRow.jsx
Closes #1457 
**Summary**
- Allow an empty array to be passed for 'row actions' and have it render the row actions cell with empty actions for that row so the table isn't missing a column for that row
- test(Table.story): have one of the stories skip row actions for a row every four rows
- fix(TableBodyRow): allow empty row actions to actually render the cell
- fix(RowActionsCell): allow empty row actions to actually render the cell so the table looks good
- Test the one updated story: `watson-iot-table--with-row-expansion-and-actions`
> fix(table): allow empty row actions for some rows of a table

- .storybook/__snapshots__/Welcome.story.storyshot
- src/components/FlyoutMenu/index.js
- src/index.js
- src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Continuation of #1306, #1266 
**Summary**
- Add the FlyoutMenu as an export.
- add export, remove some unnecessary empty lines
- status checks should pass, you can pull down and run `yarn build` to validate FlyoutMenu is included as an export. I see it generated locally
> fix(flyoutmenu): add export to index.js

- src/components/Table/Table.story.jsx
- src/components/Table/TableHead/TableHead.jsx
- src/components/Table/TableHead/TableHead.test.jsx
- src/components/Table/TableHead/columnWidthUtilityFunctions.js
- src/components/Table/TableSaveViewModal/TableSaveViewModal.test.jsx
Closes #1428
**Summary**
Adding new column definitions (by adding them to the columns and ordering props) after initial rendering fails when hasResize is true. The same problem appears when removing columns. This issue was identified in the discussion #1358
After the initial rendering the resizable column widths are now updated in the case of
a. The columns and order props are modified, either with new columns or by having columns removed.
b. The columns prop is modified and all the visible columns in that new prop state have a width.
1. Updated a table story to be able to reproduce and test the scenario where columns are added and removed by an application. This is different from toggling the visibility of already defined columns.
2. Fixed …
> fix(table): column resize fails when adding columns

- src/components/ComposedModal/ComposedModal.jsx
- src/components/ComposedModal/ComposedModal.story.jsx
- src/components/ComposedModal/__snapshots__/ComposedModal.story.storyshot
- src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Closes #1471 
**Summary**
- Carbon ComposedModal support node, we should also support, preventing console browser warning.
https://github.com/carbon-design-system/carbon-components-react/blob/master/src/components/ComposedModal/ComposedModal.js
- PropTypes title and label support to node
- We now support custom title/label
> fix(modal): prop types support to node #1471

- src/components/TileCatalog/CatalogContent.jsx
- src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Closes #1475
**Summary**
- Adds the ability for the catalogcontent.description to be a node instead of just a string
- Small change to accept node types for the catalogcontent
> feat(catalogcontent): allow description to be node

- src/components/Table/TableBody/RowActionsCell/RowActionsCell.jsx
- src/components/Table/TableBody/TableBodyRow/__snapshots__/TableBodyRow.story.storyshot
An extra (invalid) prop was being passed to the OverflowMenu if a rowActions had an overflow
**Summary**
- Fixes a propType error that was being thrown because the isRowExpanded prop was being passed all the way through to the <button DOM element if a table row had overflow actions
- fix(RowActionsCell): remove the isRowExpanded prop from the OverflowMenu
- Verify that for table rows with overflow that no proptype errors are shown
> fix(rowactionscell): isrowexpanded proptypes error being thrown for overflowmenu

- src/components/Card/Card.jsx
- src/components/Card/Card.story.jsx
- src/components/Card/CardRangePicker.jsx
- src/components/Card/CardRangePicker.test.jsx
- src/components/Card/CardToolbar.jsx
- src/components/Card/__snapshots__/Card.story.storyshot
- src/constants/CardPropTypes.js
- src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Closes #1485 
**Summary**
- Allows the CardRangePicker to receive custom `timeRangeOptions`
- Added a new prop `timeRangeOptions` that is identical to the current implementation of the default options to Card, CardToolbar, and CardRangePicker (so that it can be passed all the way through)
- Moved the current default options to CardToolbar so they could get their default i18n labels and so that other components using CardToolbar can receive the same default options
- Updated tests to use the new prop
- Added a test to ensure the custom option does display
- Added a story for custom `timeRangeOptions`
- Go to Card / custom range selector story and see that the options are customizable with the knob
> feat(CardRangePicker): allow for custom time range options

- src/components/List/HierarchyList/HierarchyList.jsx
- src/components/List/HierarchyList/HierarchyList.story.jsx
- src/components/List/HierarchyList/__snapshots__/HierarchyList.story.storyshot
- src/components/List/List.jsx
- src/components/List/ListItem/_list-item.scss
- src/components/List/__snapshots__/List.story.storyshot
Closes https://github.com/carbon-design-system/carbon-addons-iot-react/issues/1495
**Summary**
When an `OverflowMenu` is used in the `HierarchyList`, the menu is positioned incorrectly because it it implemented as a portal. As a result it is positioned absolute, relative to the body instead of the container we would expect.
Relevant issue in Monitor: https://github.ibm.com/wiotp/monitoring-dashboard/issues/1125
Relevant issue in Carbon: https://github.com/carbon-design-system/carbon/issues/4755
Adding `data-floating-menu-container` and `style={{ position: 'relative' }}` to a wrapper div forces the menu to be placed back into the DOM where we would expect it, and to be positioned relative to the `HierarchyList` container itself, rather than …
> fix(hierarchy-list): add prop for hierarchy menus

- src/components/List/List.jsx
- src/components/List/List.story.jsx
- src/components/List/ListItem/ListItem.jsx
- src/components/List/ListItem/ListItem.story.jsx
- src/components/List/ListItem/ListItem.test.jsx
- src/components/List/__snapshots__/List.story.storyshot
- src/constants/SharedPropTypes.js
- src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Closes #1518 
**Summary**
Adds the possibility to add one or more tags to an ListItem in a List.
1. Added a new tag prop to the ListItem.jsx and a new ListTagsPropTypes PropType in SharedPropTypes.js since the prop type is shared between List and ListItem
2. Updated ListItem tests and stories
3. Modified the content prop in List.jsx to include an optional tags prop
4. Updated List tests and stories
1. Go to /story/watson-iot-experimental-listitem--basic-w-knobs
2. Enable tags using the knobs, verify that it looks ok
3. Enable all the other features and make sure it all plays well together
4. Verify that the rest of the ListItem stories look good
5. Go to /story/watson-iot-experimental-list--with-tags …
> feat(listitem): add tags

- src/components/Table/StatefulTable.test.jsx
- src/components/Table/Table.story.jsx
- src/components/Table/TableHead/FilterHeaderRow/FilterHeaderRow.jsx
- src/components/Table/TableViewDropdown/__snapshots__/TableViewDropdown.story.storyshot
- src/components/TableCard/__snapshots__/TableCard.story.storyshot
- src/components/TimeSeriesCard/__snapshots__/TimeSeriesCard.story.storyshot
Part of https://github.com/carbon-design-system/carbon-addons-iot-react/issues/1432
**Summary**
Quick fix for a bug a where the multiselect would show a `clearSelection` button even if there were no pre-determined filters applied.
Give an empty multiselect an empty array instead of an empty string.
checkout the 'Stateful Example with multiselect filtering' story and its 'with pre-set' counterpart, to confirm that the multiselect only shows the clear all button if there is a pre-set filter.
> Multiselect table filter default filter fix

- src/components/TimeSeriesCard/TimeSeriesCard.jsx
Closes #1528 
**Summary**
- When null values are passed to TimeSeriesCard, we should display a gap in the line charts where the data is missing to give the user an indication of the null values
Related Carbon Charts PR: https://github.com/carbon-design-system/carbon-charts/pull/464/files
- Remove null filtering of data values
- Add additional conditional to timestamp to make sure the `undefined === undefined` race condition does not occur
- Go to any TimeSeriesCard story and pass it a mix of null and valid values
- You should see a gap in the line where the null values were passed
> fix(TimeSeriesCard): don't filter null values

- src/utils/__tests__/cardUtilityFunctions.test.jsx
- src/utils/cardUtilityFunctions.js
Reference issue: #1527 
**Summary**
- Detailed, thorough unit tests added to card variable-related functions
- Added unit tests for each function and each unique type of card type that uses variables
- Corrected a bug that was found after adding tests. When the target was a number or function, `replace` was still being called causing an error. This was fixed by moving the `string.replace` logic down into the conditionals for each `typeof` 
- Test suite should pass and all `variable` stories should still work for TimeSeriesCard, ValueCard, TableCard, ImageCard
> test(cardVariables): add unit tests

- src/components/TimeSeriesCard/TimeSeriesCard.jsx
- src/components/TimeSeriesCard/TimeSeriesCard.story.jsx
- src/components/TimeSeriesCard/__snapshots__/TimeSeriesCard.story.storyshot
- src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Closes #1531 
**Summary**
- Adds `addSpaceOnEdges` prop to TimeSeriesCard which allows the left and right side of the charts white-space to be customized
- Added propType definition
- Defaults to 1
- Added prop to each TimeSeriesCard story (I don't think this is worthy of an individual story)
- Go to any TimeSeriesCard story thats displaying a chart, then adjust the `addSpaceOnEdges` prop to multiple, different numbers to see the chart adjust the spacing
> feat(TimeSeriesCard): add addSpaceOnEdges prop

- src/components/Table/Table.jsx
- src/components/Table/Table.story.jsx
Closes #1538 
**Summary**
- Recent PR changed how `tableId` is passed to Table's children components. All components were receiving the prop as `tableId={id || tableId}`, but TableBodyRow was receiving it as `tableId={id}`. If `id` was not set by the user, `null` was displayed in the child <td> element
- Change TableBodyRow prop to `tableId={id || tableId}`
- Change 1 story to not pass an id so that this use-case can be tested in the future
- See that the snapshot updated to the default `tableId` (we are already passing id to all other tables so we weren't able to see this bug)
> fix(table): pass id OR tableId to TableBody to fix snapshots

- src/components/BarChartCard/BarChartCard.jsx
- src/components/BarChartCard/barChartUtils.js
- src/components/BarChartCard/barChartUtils.test.js
- src/components/TimeSeriesCard/TimeSeriesCard.jsx
- src/constants/CardPropTypes.js
- src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Closes #1534 
**Summary**
- Stacked bar chart data comes in as an array which was not being handled by the tooltipFormatter. This PR adds a check for an array and passes the actual data, whether its an object or array, correctly to the tooltip formatting flow
- Fixed propTypes for TimeSeriesCards (`tooltipDataFormatPattern`, `showTimeInGMT` were in the content object mistakenly)
- Added `tooltipDataFormatPattern`, `showTimeInGMT` props to BarChartCard
- Updated `tooltipFormatter` to take in above props for formatting
- Removed custom color formatting as carbon charts does this by default now
- Removed default date row from tooltip as we create a custom date ourselves
- Updated tests to reflect changes (beware the diffs are a bit nasty as the …
> fix(BarChartCard): show actual timestamp in tooltip

- src/components/DateTimePicker/DateTimePicker.jsx
- src/components/DateTimePicker/DateTimePicker.test.jsx
- src/components/DateTimePicker/__snapshots__/DateTimePicker.story.storyshot
Closes #1482 #1494
**Summary**
- The external value is passed in as "defaultValue". Updated code to ensure that the external value is properly set and assigned to "lastAppliedValue" as well.
- The absolute value was not being passed to Carbon DatePicker correctly. Current code passes the absolute value startDate and endDate to DatePickerInput as "value" prop. DatePickerInput doesn't have any "value" prop. Passing the start and end date as an array to DatePicker's "value" prop.
- DatePicker dateFormat has been set as "m/d/Y". However, the format of the date that is passed to the "value" prop depends on the "dateTimeMask". So when we set the "dateTimeMask" to anything but "MM/DD/YYYY", the current selection is not set in calendar. Changed code to format the absolute value dates to …
> fix(datetime picker): externally set range not selected in calendar

- .storybook/__snapshots__/Welcome.story.storyshot
- src/components/FilterTags/FilterTags.jsx
- src/components/FilterTags/FilterTags.story.jsx
- src/components/FilterTags/FilterTags.test.jsx
- src/components/FilterTags/__snapshots__/FilterTags.story.storyshot
- src/components/FilterTags/_filter-tags.scss
- src/index.js
- src/styles.scss
- src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Closes #676 
**Summary**
Wrapper to add the functionality of collapsing filter tags that do not fit in their containers into an overflow menu. 
- Added `FilterTags.jsx`, `FilterTags.story.jsx`, `_filter-tags.scss`, and `FilterTags.test.jsx `
- Added import of styles to `styles.scss`
- Added export of this component to `index.js`
- Checkout story that was added for this component.
> Filter tags group initial implementation

- src/components/Dashboard/__snapshots__/Dashboard.story.storyshot
- src/components/TimeSeriesCard/TimeSeriesCard.jsx
- src/components/TimeSeriesCard/__snapshots__/TimeSeriesCard.story.storyshot
- src/components/TimeSeriesCard/_time-series-card.scss
Band-aid fix for #1548 until the carbon charts issue is solved 
Part of https://github.com/carbon-design-system/carbon-addons-iot-react/issues/370
**Summary**
- Themes are incorrect with the zoombar in carbon charts causing the background of the slider view zoombar to be white, meaning it blends in with the card's white background
See https://github.com/carbon-design-system/carbon-charts/issues/750 for more details about the broader issue
- Migrate from styled components to SCSS
- Add styling to fix the background color to be the proper grayish color (I'd like to stay away from the carbon variables as this is a temporary fix)
- Go to TimeSeriesCard - zoombar story, slide the zoom handles over some, …
> fix(TimeSeriesCard): Migrate to SCSS, and force white theme bg in zoombar

- src/components/Table/StatefulTable.jsx
- src/components/Table/StatefulTable.test.jsx
Closes #1551
**Summary**
The props of the elements placed in the customToolbarContent are not updated after the initial render since they are preserved by the state of the StatefulTable. That means that the App cannot update the customToolbarContent elements when the state of the app changes.
- Removed the customToolbarContent from the state management in StatefulTable
- Verify that stories with customToolbarContent are still working
> fix(statefultable): customToolbarContent element props unaffected

- package.json
- yarn.lock
Closes #1522
**Summary**
- Simply updating carbon charts to the latest to get a bug fix for localization in the BarChart and TimeSeriesCard
- Verify the BarChart and TimeSeriesCard stories, verify in the locale story that the number format changes
> chore(charts): upgrade carbon charts to get the latest version

- src/components/BarChartCard/__snapshots__/BarChartCard.story.storyshot
- src/components/Card/Card.jsx
- src/components/Card/_card.scss
- src/components/TimeSeriesCard/TimeSeriesCard.story.jsx
- src/components/TimeSeriesCard/__snapshots__/TimeSeriesCard.story.storyshot
Closes #1574
**Summary**
- The overflow menu is being hidden when the card is expanded, see the bug above
- Put the overflow menu
- Test the TimeSeriesCard isExpanded story and the BarChartCard isExpanded story
> fix(card): adjust overflow z-index inside expanded card

- src/components/Button/_button.scss
Closes #1317
**Summary**
- Icons no longer are laid over the text when in RTL
- update _button.scss
- View the default button story 
- https://deploy-preview-1558--carbon-addons-iot-react.netlify.app/?path=/story/watson-iot-button--default
- Configure an icon to be placed in the button via the knobs
- Click the RTL button/knob
- Icons should be laid out to the left of the text (inverse of when RTL is off) ![image](https://user-images.githubusercontent.com/3360588/91868683-a0e76900-ec3a-11ea-81d6-d5d70ff4fb90.png)
- Other stories should remain unchanged
> fix(button): proper icon placement in RTL

- src/components/ComposedModal/ComposedModal.jsx
- src/components/ComposedModal/ComposedModal.story.jsx
- src/components/ComposedModal/__snapshots__/ComposedModal.story.storyshot
- src/components/ComposedModal/_composed-modal.scss
- src/components/Table/TableManageViewsModal/__snapshots__/TableManageViewsModal.story.storyshot
- src/components/Table/TableSaveViewModal/__snapshots__/TableSaveViewModal.story.storyshot
- src/components/WizardModal/__snapshots__/WizardModal.story.storyshot
Closes #1593
Internal issue:
https://github.ibm.com/wiotp/monitoring-dashboard/issues/1398
**Summary**
- Fix to override the z-index for overflow menu contents and tooltips shown in modals
- fix(composedmodal): use the data attribute to tell the tooltip where to attach for css access, then override the z-index in that case
- Verify the new story that the z-index is higher in the tooltip and overflow menu contents than the modal
> fix(modal): overflow menu and tooltip contents hidden in modal

- src/components/List/List.jsx
- src/components/List/ListItem/ListItem.jsx
- src/components/List/ListItem/ListItem.story.jsx
- src/components/List/ListItem/_list-item.scss
Closes #1603
**Summary**
Adds a `disabled` prop on `ListItem` that disables the item.
- Add `disabled` prop
- Lower opacity for disabled items
Go to the `with disabled` story in `ListItem` and alter the knobs to verify the styling and functionality.
> feat(list-item): add disabled prop and functionality

- src/components/TimeSeriesCard/TimeSeriesCard.jsx
Closes #
**Summary**
- Small fix to addSpaceOnEdges to actually respect a 0 passed
- fix(TimeSeriesCard): need to check addSpaceOnEdges for not nil so that we can respect 0 passed there.
- Pass 0 to addSpaceOnEdges and make sure the space goes away
> fix(timeseriescard): respect 0 for addSpaceOnEdges

- src/components/Table/TableHead/_table-head.scss
Closes #1597
Closes #1587 
**Summary**
- One more fix for the table select all checkbox
- Remove unnecessary padding on the first (empty) `th` that was previously added to patch a modification from a Carbon release ~5 months ago.
- View the [`Table \ Stateful Example with expansion, maxPages, and column resize`](https://deploy-preview-1619--carbon-addons-iot-react.netlify.app/?path=/story/watson-iot-table--stateful-example-with-expansion-maxpages-and-column-resize) story 
- The checkbox should be aligned
- Check _all other table stories_ to ensure checkbox is aligned across various states.
> fix(table): checkbox alignment when expandable rows

- src/components/SuiteHeader/SuiteHeader.jsx
- src/components/SuiteHeader/SuiteHeader.story.jsx
- src/components/SuiteHeader/hooks/suiteHeaderData.fixture.js
- src/components/SuiteHeader/hooks/useSuiteHeaderData.js
**Summary**
- Adding another API call to `useSuiteHeaderData` hook to load the translated strings that will be passed to `SuiteHeader` component.
- Fixing an issue where the settings button in `SuiteHeader` would redirect to the login page instead of the last accessed page when `isAdminView` is set to `true`.
- Please don't mind the changes in `SuiteHeader.story.jsx`, the changes are in a story that is commented out because it is using the useSuiteHeaderData hook (and we had decided to comment out this story because of "missing required prop" errors in tests, caused by async data loading, which causes the component to be loaded without some required props in the first render).
- fixed settings button redirect issue
- added `GET …
> feat(suiteheader): Implementation of i18n support and fixing of a redirect issue

- src/components/CardEditor/__snapshots__/CardEditor.story.storyshot
- src/components/List/HierarchyList/HierarchyList.story.jsx
- src/components/List/HierarchyList/__snapshots__/HierarchyList.story.storyshot
- src/components/List/List.jsx
- src/components/List/ListItem/_list-item.scss
- src/components/List/__snapshots__/List.story.storyshot
- src/components/Table/TableManageViewsModal/__snapshots__/TableManageViewsModal.story.storyshot
Closes #1568
**Summary**
- HierarchyList indentation is improved for when there's a mix of category and non-category items.
- Root level items with no children align with items that have children
- Children items have slightly more indentation than their parent
- Flipped the caret direction to be consistent with sidenav and accordion. When the section is closed, the arrow points down.
- View and validate the new [`HierarchyList \ with mixed hierarchies`](https://deploy-preview-1617--carbon-addons-iot-react.netlify.app/?path=/story/watson-iot-experimental-hierarchylist--with-mixed-hierarchies) story
- Check the other HierarchyList stories to ensure no visual regressions
> fix(list): adjust hierarchy indentations to match spec

- src/components/Table/_table.scss
Closes #1638 
**Summary**
Small fix to add interpolation of a sass variable inside a calc function
- changed _table.scss
- Open up story with empty state and look at the row with class `.iot--empty-table--table-row`. You should see a calc statement for height that has rem value and not the variable.
> fix(table): fix variable that was not being interpolated

- src/components/Table/TableBody/TableBodyRow/TableBodyRow.jsx
- src/components/Table/TableBody/TableBodyRow/__snapshots__/TableBodyRow.story.storyshot
- src/components/TableCard/__snapshots__/TableCard.story.storyshot
Closes #1647 
**Summary**
- To meet the proper design of single-nested hierarchy Table's, this PR adds `font-weight: bold` to parent category/rows
- Add the font-weight based off whether `hasRowNesting: { hasSingleNestedHierarchy: true}` and whether there is children or not (AKA is the row a parent)
- Go to ?path=/story/watson-iot-table--stateful-example-with-single-nested-hierarchy and see that all parents are bold, while all children are regular font-weight
> fix(table): single nested parents should have bold font weight

- .storybook/__snapshots__/Welcome.story.storyshot
- src/components/ErrorBoundry/ErrorBoundry.story.jsx
- src/index.js
- src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Closes #1023
**Summary**
We were previously not exporting Carbon's `ErrorBoundary` and `ErrorBoundaryContext` component. This PR exports and adds the stories to our storybook
- Added `ErrorBoundary`  folder that holds story
- updated index.js to include export for `ErrorBoundary` and `ErrorBoundaryContext`
- Go to ErrorBoundary story and make sure they work. Open up the welcome story dropdown and see that these two components are on the list of Exports.
> 1023 error boundary

- src/components/CardEditor/__snapshots__/CardEditor.story.storyshot
- src/components/List/List.jsx
- src/components/List/__snapshots__/List.story.storyshot
- src/components/Table/TableManageViewsModal/__snapshots__/TableManageViewsModal.story.storyshot
- src/components/WizardModal/WizardModal.test.jsx
Closes #1657 
**Summary**
- Small fix to ensure that non-hierarchical list items have no indent
- modify base indentation logic for list items
- The [`List \ basic single column` story](https://deploy-preview-1660--carbon-addons-iot-react.netlify.app/?path=/story/watson-iot-experimental-list--basic-single-column) should now have no indentation as it used to be before the changes in #1617 
- The PR #1608 was merged right before #1617. [The 1608 deploy preview](https://deploy-preview-1608--carbon-addons-iot-react.netlify.app/?path=/story/watson-iot-experimental-list--basic-single-column) shows the original to compare
> fix(list): correct non-hierarchical list indentation level

- src/components/DateTimePicker/DateTimePicker.jsx
Closes #1592 
**Summary**
Somewhere along the line we lost the ability to add an absolute value. This PR fixes this regression. 
- Change in DateTimePicker.jsx
- go to default story and click on custom. choose absolute and pick a date range. You will see the date range update.
> fix(datetimepicker): fix setting absolute value

- src/components/Table/Table.jsx
- src/components/Table/Table.story.jsx
- src/components/Table/Table.test.jsx
- src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Closes #1464
**Summary**
This fix automatically checks the checkbox if all rows are selected. If some rows are selected, the checkbox gets the Indeterminate state. 
If the `view.table.isSelectAllSelected` is present as a prop then that value will be used instead and if `view.table.isSelectAllIndeterminate` is present that value will be used. See the unit tests for the exact functionality.
Like I commented in the issue itself:
I question if this really is a bug to be fixed? Since the app actually controls the view.table.isSelectAllSelected like the suggested workaround shows I'm not sure it makes sense to handle this value automatically. With this fix implemented, what is the use case of the view.table.isSelectAllSelected (and possibly view.table.isSelectAllIndeterminate) if those values …
> fix(table): auto select the select all checkbox

- src/components/Table/TableBody/TableBodyRow/TableBodyRow.jsx
- src/components/TableCard/__snapshots__/TableCard.story.storyshot
Closes #1666
**Summary**
Removes hasRowNesting={false} from the table tr 
- used the props['data-row-nesting'] for StyledComponents instead
1. Open the browser web tool console 
2. Go to https://deploy-preview-1676--carbon-addons-iot-react.netlify.app?path=/story/watson-iot-table--stateful-example-with-expansion-maxpages-and-column-resize
3. Verify that there is no error message 
4. Expand a row
5. Verify that there is no error message
> fix(table): fixed table stories showing error

- src/components/NavigationBar/__snapshots__/NavigationBar.story.storyshot
- src/components/PageTitleBar/PageTitleBar.jsx
- src/components/PageTitleBar/PageTitleBar.story.jsx
- src/components/PageTitleBar/__snapshots__/PageTitleBar.story.storyshot
- src/components/PageTitleBar/_page-title-bar.scss
- src/components/PageWizard/__snapshots__/PageWizard.story.storyshot
- src/components/SideNav/__snapshots__/SideNav.story.storyshot
- src/components/TileGallery/TileGallery.story.jsx
- src/components/TileGallery/__snapshots__/TileGallery.story.storyshot
- src/components/WizardInline/__snapshots__/WizardInline.story.storyshot
Closes #1661 
**Summary**
- As part of the new DashboardEditor, a new design spec has been created for the header (PageTitleBar). This PR updates the styling to match those new specs
- Updated styles to match spec
- Updated story to match a common DashboardEditor header
- Changed a deprecated icon in the TileGallery stories to a similar valid icon to remove warning in console
- Go to each PageTitleBar story and ensure they match the specified design seen in the above issue
> [PageTitleBar] update style to match new spec

- src/components/BarChartCard/BarChartCard.jsx
- src/components/BarChartCard/barChartUtils.js
- src/components/BarChartCard/barChartUtils.test.js
- src/components/Dashboard/__snapshots__/Dashboard.story.storyshot
- src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Closes #1685 
Closes #1684 
**Summary**
- `className` prop is now added to the top container in BarChartCard
- If `series` is an empty array, show the empty card state
- If `values` is empty, do not generate colors, as theres nothing to add colors to
- Updated tests
- Updated stories
- Added `values: null` to defaultProps to be more explicit
- Add a custom className and see that its attached to the top BarChartCard container
- Set `series: []` and `isEditable: true` and see that the empty state renders
> fix(barchartcard): add classname to top container, allow empty series prop

- src/components/Card/Card.jsx
- src/components/Card/Card.story.jsx
- src/components/Card/__snapshots__/Card.story.storyshot
- src/constants/CardPropTypes.js
- src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Closes #1687
**Summary**
- `onFocus`, `onBlur`, `tabIndex` are now attached to the CardWrapper div for event handling
- Added each to the CardWrapper
- Added each to the propTypes
- Go to Card - basic story and attempt to 'tab' into the Card wrapper. See that `onFocus` is fired when focused. Tab out of the Card wrapper, and see the `onBlur` is fired
> feat(card): add onFocus, onBlur, tabIndex

- .storybook/__snapshots__/Welcome.story.storyshot
- src/index.js
- src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
**Summary**
- @jonguenther pointed out a few components that are available in Carbon but not available through our package
- update index.js exports
- run a local build, these should be there
- the exports table in [the welcome story](https://deploy-preview-1706--carbon-addons-iot-react.netlify.app/?path=/story/0-getting-started--about-storybook) should be updated to show these as available from our package
> feat(exports): update exports to pass through carbon components

- src/components/TableCard/_table-card.scss
Closes #1714 
**Summary**
- Table card has some invalid scss code that breaks dart sass on downstream compile
- Remove the parent selector
- Verify the overflow menu in the table card still works successfully
> fix(tablecard): remove invalid SCSS code

- jest.config.js
- src/components/BarChartCard/BarChartCard.jsx
- src/components/Card/Card.jsx
- src/components/Card/_card.scss
- src/components/Dashboard/DashboardGrid.jsx
- src/components/Dashboard/DashboardGrid.story.jsx
- src/components/Dashboard/DashboardGrid.test.jsx
- src/components/Dashboard/__snapshots__/DashboardGrid.story.storyshot
- src/components/Dashboard/_dashboard.scss
- src/components/GaugeCard/GaugeCard.jsx
- src/components/ImageCard/ImageCard.jsx
- src/components/ListCard/ListCard.jsx
- src/components/PieChartCard/PieChartCard.jsx
- src/components/TableCard/TableCard.jsx
- src/components/TableCard/__snapshots__/TableCard.story.storyshot
- src/components/TileCatalogNew/__snapshots__/TileCatalogNew.story.storyshot
- src/components/TimeSeriesCard/TimeSeriesCard.jsx
- src/components/TimeSeriesCard/__snapshots__/TimeSeriesCard.story.storyshot
- src/components/ValueCard/ValueCard.jsx
- src/constants/CardPropTypes.js
- src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
- src/utils/cardUtilityFunctions.js
- yarn.lock
Closes #1598 
**Summary**
Added resize functionality to all cards when present in a DashboardGrid. The feature is based on the underlying resize functionality of the react-grid-layout which passes down a resize handler to the grid items (cards). The DashboardGrid listens to all resize callbacks and makes sure the only valid card sizes are suggested and available as drop while dragging.
The actual card content is showing during resize and I believe performance is acceptable. In the stories added the card also gets transformed between the defined card sizes during the resize drag process.
- Modified DashboardGrid to manage card resizing using strict card sizes. It now exposes onCardSizeChange and onResizeStop. Both callbacks include the current …
> feat(dashboardgrid): allow resizing by dragging the border

- src/components/CardEditor/CardEditForm/CardEditFormItems/DataSeriesFormItem.jsx
- src/components/CardEditor/CardEditForm/CardEditFormItems/DataSeriesFormItem.test.jsx
Closes #1758 
**Summary**
Show dataSourceIds in the data series dropdown rather than labels
Change itemToString prop to show item.id rather than item.text
Go to a DashboardEditor story and add or select a timeseries card. See that the dropdown is populated by the dataItem dataSourceIds, and the list under it shows the labels.
> fix(card-editor): show ids in data series

- src/components/DashboardEditor/DashboardEditor.jsx
- src/components/DashboardEditor/DashboardEditor.story.jsx
- src/components/DashboardEditor/__snapshots__/DashboardEditor.story.storyshot
- src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Closes #1774 
**Summary**
- DashboardEditor was not passing template layouts to DashboardGrid, meaning it would never respect the given layouts
- Added an `onLayoutChange(newLayout, newLayouts)` callback for consumers
- Passed `layouts` to DashboardGrid correctly
- Added `onLayoutChange` action to stories
1. Go to any DashboardEditor story, add cards, then move them around. Open up the actions tab and see that `onLayoutChange` is being fired with the correct layouts
2. Open the DashboardEditor - initialValue story and see that the layout is not in the classic default state. (they're not perfectly aligned)
> fix(dashboardeditor): create onLayoutChange callback and pass layouts to grid

- src/components/DashboardEditor/DashboardEditor.jsx
- src/components/DashboardEditor/DashboardEditor.story.jsx
- src/components/DashboardEditor/DashboardEditorHeader/DashboardEditorHeader.jsx
- src/components/DashboardEditor/__snapshots__/DashboardEditor.story.storyshot
- src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Closes #
**Summary**
- Adds `isLoading` prop and SkeletonText for loading state
- Added knob to stories
- Added isLoading story
- Check the isLoading story to see that the skeleton is rendering correctly
- Go to any other DashboardEditor story and flip the isLoading knob to see that it renders correctly
> fix(dashboardeditor): add loading state

- src/components/Dashboard/__snapshots__/Dashboard.story.storyshot
- src/components/Dashboard/__snapshots__/DashboardGrid.story.storyshot
- src/components/DashboardEditor/__snapshots__/DashboardEditor.story.storyshot
- src/components/TableCard/TableCard.jsx
- src/components/TableCard/__snapshots__/TableCard.story.storyshot
Closes #1779 
**Summary**
Threshold columns in `TableCards` should filter on a multiselect
Add the `isMultiselect` flag and fix styling.
Go to `TableCard` "table with thresholds" story, click the filter icon, and see that you can filter on multiple selections.
> feat(table-card): add multiselect filter to threshold columns

- .storybook/__snapshots__/Welcome.story.storyshot
- src/components/ColorDropdown/ColorDropdown.jsx
- src/components/ColorDropdown/ColorDropdown.story.jsx
- src/components/ColorDropdown/ColorDropdown.test.jsx
- src/components/ColorDropdown/__snapshots__/ColorDropdown.story.storyshot
- src/components/ColorDropdown/_color-dropdown.scss
- src/components/ComboBox/__snapshots__/ComboBox.story.storyshot
- src/components/Dropdown/__snapshots__/Dropdown.story.storyshot
- src/components/IconDropdown/__snapshots__/IconDropdown.story.storyshot
- src/components/Table/TableViewDropdown/__snapshots__/TableViewDropdown.story.storyshot
- src/index.js
- src/styles.scss
- src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Closes #1761
**Summary**
A color dropdown component for the HotSpotEditorModal.
- Extended the carbon Dropdown to show color squares per item and for the selection
- Added default colors
- Added option to pass in custom colors
- Added callback for when color selection change
- Added a new story
- Verified RL
Check out the stories at
https://deploy-preview-1765--carbon-addons-iot-react.netlify.app/?path=/story/watson-iot-experimental-colordropdown--default-example
> 1761 create a new color dropdown component

- src/components/DataTable/_data-table.scss
Closes #1784
**Summary**
- Removes double padding on header items when embedded in a button.
- Small scss fix.
- Go to https://deploy-preview-1789--carbon-addons-iot-react.netlify.app/?path=/story/watson-iot-table--simple-stateful-example and observe the headers that are left aligned.
> fix(table): fixed left alignment of table headers

- src/components/List/HierarchyList/HierarchyList.jsx
- src/components/List/List.jsx
Closes # internal bug: https://github.ibm.com/wiotp/monitoring-dashboard/issues/1633
**Summary**
- Because of the useEffect comparison, objects that come from redux can cause infinite render loops to happen.
-fix(List): memoize i18n as well.
- Verify searching within HierarchyList still works
> fix(hierarchylist): need to useDeepCompareEffect to stop infinite loop

- src/components/DataTable/_data-table.scss
**Summary**
- Hotfix #1789 to `master` so consumers can get it now
> Hotfix to Master -- fix(table): fixed left alignment of table headers

- src/components/List/ListItem/ListItem.jsx
Closes #
**Summary**
- Change to the default propTypes for rowActions to stop the warning message
> fix(listitem): rowActions should be null by default

- src/components/CardEditor/CardEditForm/CardEditFormItems/DataSeriesFormItem.jsx
- src/components/List/ListItem/ListItem.jsx
- src/components/List/ListItem/ListItem.story.jsx
- src/components/List/ListItem/__snapshots__/ListItem.story.storyshot
- src/components/List/ListItem/_list-item.scss
Closes #
**Summary**
- Fixes two issues,:
one the row actions cause the list values to overlap and the padding wasn't giving enough space
two fixes the warning thrown by the DataSeriesFormItem
- Check the updated story to see the longer list item and notice the proptypes error goes away on the new data series form
> fix(listitem): fix row actions issue

- src/components/List/HierarchyList/HierarchyList.jsx
- src/components/List/ListItem/ListItem.jsx
- src/components/List/ListItem/_list-item.scss
Closes #
**Summary**
- Fixes a bug where the handleSelect would trigger twice and unselect a item if the graph rerendered
- fix(HierarchyList): only trigger handleSelect if the item isn't already selected
- fix(ListItem): default prop should not be array
- fix(listitem.scss): reduce the selected items padding
- Verify all the list stories
> fix(hierarchylist): selection is lost when rerender occurs

- src/components/Dashboard/__snapshots__/Dashboard.story.storyshot
- src/components/Dashboard/__snapshots__/DashboardGrid.story.storyshot
- src/components/ImageCard/Hotspot.jsx
- src/components/ImageCard/ImageHotspots.jsx
- src/components/ImageCard/ImageHotspots.story.jsx
- src/components/ImageCard/ImageHotspots.test.jsx
- src/components/ImageCard/ImageHotspotsRender.test.jsx
- src/components/ImageCard/__snapshots__/ImageCard.story.storyshot
- src/components/ImageCard/__snapshots__/ImageHotspots.story.storyshot
- src/components/ImageCard/_hotspot.scss
- src/styles.scss
Closes #1770
**Summary**
The ImageHotspots is enhanced to support selecting hotspots for editing and adding new ones by clicking on the image. It is **still possible to drag the image** when in isEditable mode which makes sense for precision positioning of new hotspots. 
- Added isEditable prop to ImageHotspots.jsx inorder to enable selection and adding hotshpots
- Added callback for when a hotspot is clicked (selected) in the ImageHotspots.jsx
- Added callback for clicking the image to create a new hotspot ImageHotspots.jsx
- Changed the drag code to start drag on mouse move instead of mouse down in ImageHotspots.jsx
- Added isSelected to Hotspot.jsx
- Refactored the StyledComponents into external css for Hotspot.jsx
- Added a story
- Added …
> feat(imagehotspots): add selecting and creating hotspots

- src/components/CardEditor/CardEditForm/CardEditFormContent.jsx
- src/components/CardEditor/CardEditForm/CardEditFormContent.test.jsx
- src/components/CardEditor/CardEditForm/CardEditFormSettings.test.jsx
- src/components/DashboardEditor/editorUtils.jsx
Closes #https://github.ibm.com/wiotp/monitoring-dashboard/issues/1677
**Summary**
- Fixes an issue where the CardEditFormContent wasn't selecting the correct item by default
- fix(CardEditFormContent): use the passed card.timeRange as default and correctly populate the dropdown and handle the updates
- fix(editorUtils): add the custom raw ranges to the timeRangesToJSON
- verify CardEditFormContent testcases and the CardEditForm stories
> fix(cardEditForm): not using passed timeRange prop in the form

- src/components/CardEditor/CardEditForm/CardEditFormContent.jsx
- src/components/CardEditor/CardEditForm/CardEditFormItems/DataSeriesFormItems/DataSeriesFormContent.jsx
- src/components/CardEditor/CardEditForm/CardEditFormItems/DataSeriesFormItems/DataSeriesFormSettings.jsx
- src/components/CardEditor/CardEditForm/CardEditFormItems/ImageCardFormItems/ImageCardFormContent.jsx
- src/components/CardEditor/CardEditForm/CardEditFormItems/ImageCardFormItems/ImageCardFormSettings.jsx
- src/components/CardEditor/CardEditForm/CardEditFormSettings.jsx
- src/components/CardEditor/CardEditor.jsx
- src/components/DashboardEditor/editorUtils.jsx
- src/components/TimeSeriesCard/TimeSeriesCard.jsx
- src/components/TimeSeriesCard/TimeSeriesCard.story.jsx
- src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Closes #https://github.ibm.com/wiotp/monitoring-dashboard/issues/1659
**Summary**
- Need to move the showLegend prop down to the actual content section of the TimeSeriesCard
- This PR unfortunately does have a dependency on this PR getting integrated first: https://github.com/carbon-design-system/carbon-addons-iot-react/pull/1832
- Verify that the default TimeSeriesCard story here shows the legend:
http://127.0.0.1:3000/?path=/story/watson-iot-timeseriescard--single-point
> fix(cardEditor): the showLegend was in the incorrect place for TimeSeriesCards

- src/components/CardEditor/CardEditForm/CardEditFormItems/ImageCardFormItems/ImageCardFormContent.jsx
- src/components/DashboardEditor/DashboardEditor.jsx
- src/components/DashboardEditor/DashboardEditor.story.jsx
- src/components/DashboardEditor/DashboardEditor.test.jsx
- src/components/DashboardEditor/__snapshots__/DashboardEditor.story.storyshot
- src/components/ImageGalleryModal/ImageGalleryModal.jsx
- src/components/ImageGalleryModal/ImageGalleryModal.test.jsx
- src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Partial/further work of #1786, #1741 
**Summary**
- feat(ImageGallery): links the imageGallery to be used in the DashboardEditor
- fix(ImageCardFormContent): temporarily hide the Edit Image button as the hotspot editing isn't ready yet
- feat(DashboardEditor): show/hide and update the cards based on the ImageGalleryModal
- fix(ImageGalleryModal): should search on id by default since src usually is a base64 encoded string
- Verify you can select images from the ImageGallery in the DashboardEditor
> feat(imagegallery): link the image gallery to the dashboardeditor

- src/components/DashboardEditor/DashboardEditor.story.jsx
- src/components/DashboardEditor/editorUtils.jsx
**Summary**
The TimeSeries cards in the dashboard editor were incorrectly looking at the the `dataSource.range` prop for the `timeRange` on a TimeSeries card.
Remove the timeRange prop definition from the `TimeSeriesCard` render in the dashboard editor
Go to the `DashboardEditor` `With initial values` story and see that the TimeSeriesCard is properly set to `thisWeek` and the time range picker in the cardEditor is pre-populated.
> fix(line-card-range): remove datasource range from editor render of linecard

- src/components/TableCard/TableCard.story.jsx
- src/components/TableCard/__snapshots__/TableCard.story.storyshot
- src/components/TableCard/tableCardUtils.jsx
Closes #1853
**Summary**
- Theres little control over row-specific variables as they're added in the renderDataFunction and can only use the current rows formatting. For example, if a timestamp is already being formatted in another column, the variable will also be formatted, which could cause problems in the URL. For example 7/20/2020 02:00 is not valid in URLs, but it still needs to be formatted in the other column
- This PR solves this issue by first encoding the variable, then passing it to the URL
- Go to /?path=/story/watson-iot-tablecard--with-row-specific-link-variables and see that the `Link` values are being formatted with URL encoding
> fix(TableCard): encode variables for linkTemplate

- src/components/BarChartCard/barChartUtils.test.js
- src/components/DashboardEditor/editorUtils.jsx
- src/components/ImageCard/ImageCard.jsx
- src/components/ImageCard/ImageCard.story.jsx
- src/components/ImageCard/ImageUploader.jsx
- src/components/ImageCard/ImageUploader.test.jsx
- src/components/ImageCard/__snapshots__/ImageCard.story.storyshot
- src/components/ImageCard/_image-uploader.scss
- src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Closes #
**Summary**
- Improves the UX of the image upload and allows consumers to disable/enable the insertImageFromUrl capability
- test(barChartUtils): fix failing testcase
- fix(editorUtils): shouldn't default any yLabel or units for time series cards
- feat(ImageCard): improve UX of the browse image from gallery and allow disabling the inserting from URL functionality
- fix(ImageCard): need to pass the i18n translated labels through to ImageUploader
- test(publicAPI): fix the out of sync messages between ImageCard and ImageUploader default i18n props
- Check the isEditable ImageCard story
> fix(imagecard): improve ux of uploading image

- src/components/DashboardEditor/DashboardEditor.jsx
- src/components/DashboardEditor/__snapshots__/DashboardEditor.story.storyshot
- src/components/DashboardEditor/_dashboard-editor.scss
- src/components/ImageCard/__snapshots__/ImageCard.story.storyshot
Closes #
**Summary**
- Very small fix to add the normal class around the skeleton text and add margin around it
- fix(dashboardEditor): add div and padding
- Verify the isLoading story for DashboardEditor has padding
> fix(dashboardeditor): add padding around skeletontext in loading

- jest.config.js
- src/components/ImageCard/ImageCard.jsx
- src/components/ImageCard/ImageUploader.jsx
- src/components/ImageCard/_image-uploader.scss
- src/constants/CardPropTypes.js
- src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Prereqs #1875 
**Summary**
- fix(ImageCard): add a maxFileSizeInBytes property and enforce it if the image is too large with an error
- Verify that if you try and upload a file larger than a MB you see the error message
> fix(imagecard): enforce maxsize on upload

- src/components/DashboardEditor/DashboardEditor.jsx
- src/components/DashboardEditor/DashboardEditor.story.jsx
**Summary**
Quick fix for the BarCharts to check for `getValidDataItems` for their data preview.
Add a check for `getValidDataItems`
Make sure that you can still see the data preview in the `DashboardEditor` stories
> fix(dashboard-editor): prioritize valid data for barchart previews

- src/components/DashboardEditor/DashboardEditor.jsx
- src/components/DashboardEditor/DashboardEditor.story.jsx
- src/components/DashboardEditor/__snapshots__/DashboardEditor.story.storyshot
- src/components/ImageGalleryModal/ImageGalleryModal.jsx
- src/components/ImageGalleryModal/ImageGalleryModal.story.jsx
- src/components/ImageGalleryModal/ImageGalleryModal.test.jsx
- src/components/ImageGalleryModal/ImageTile.jsx
- src/components/ImageGalleryModal/ImageTile.test.jsx
- src/components/ImageGalleryModal/__snapshots__/ImageGalleryModal.story.storyshot
- src/components/ImageGalleryModal/_image-gallery-modal.scss
- src/components/ImageGalleryModal/_image-tile.scss
- src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Closes #
**Summary**
- feat(imagegallerymodal): allow the deletion in the imagegallery inside the dashboard editor
- feat(DashboardEditor): add onImageDelete callback and new i18n labels imageGalleryDeleteLabelText: PropTypes.string,
imageGalleryDeleteModalLabelText: PropTypes.string,
imageGalleryDeleteModalTitleText: PropTypes.func,
- feat(ImageGalleryModal): support deletion if onDelete is set
- Verify deletion is possible inside the dashboard editor
> feat(imagegallery): add delete option to modal

- src/components/CardEditor/CardEditor.jsx
- src/components/CardEditor/CardGalleryList/CardGalleryList.jsx
- src/components/CardEditor/__snapshots__/CardEditor.story.storyshot
- src/components/CardEditor/_card-editor.scss
- src/components/DashboardEditor/__snapshots__/DashboardEditor.story.storyshot
Closes #1561
**Summary**
- This PR uses a consistently styled header that is part of the `CardEditor` component for both the "Gallery" section and the "Add a card" section. We no longer utilize `SimpleList` header
- Added the "gallery" header section to `CardEditor.jsx`
- change `title` prop for `SimpleList` in `CardGalleryList.jsx`
- add styles to `_card-editor.scss`
- Go to Dashboard editor [story](https://deploy-preview-1870--carbon-addons-iot-react.netlify.app/)
- Click on card type to add. 
- Click on "Add a card" header
- see that styles look the same as production with the change of making the "add to card" header have the same height as the "Gallery" header.
> (feat): Consistent  header for CardEditor 

- src/components/CardEditor/CardEditForm/CardEditForm.jsx
- src/components/DashboardEditor/DashboardEditor.jsx
- src/components/ImageCard/ImageCard.jsx
- src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Closes #
**Summary**
- fix(CardEditForm): hide the i18n and validateUploadedImage props in the modal
- feat(DashboardEditor): need to expose the onValidateUploadedImage to the DashboardEditor like the other callbacks
- fix(imageCard): need to pass along the wrongFileType function to the ImageUploader
- items_here
- tests here
> fix(dashboardeditor): add ability to validate uploaded image

- src/components/ColorDropdown/ColorDropdown.test.jsx
- src/components/Dashboard/__snapshots__/Dashboard.story.storyshot
- src/components/Dashboard/__snapshots__/DashboardGrid.story.storyshot
- src/components/ImageCard/Hotspot.jsx
- src/components/ImageCard/Hotspot.test.jsx
- src/components/ImageCard/HotspotContent.jsx
- src/components/ImageCard/HotspotContent.test.jsx
- src/components/ImageCard/ImageHotspots.jsx
- src/components/ImageCard/ImageHotspots.story.jsx
- src/components/ImageCard/__snapshots__/HotspotContent.story.storyshot
- src/components/ImageCard/__snapshots__/ImageCard.story.storyshot
- src/components/ImageCard/__snapshots__/ImageHotspots.story.storyshot
- src/components/ImageCard/_hotspot.scss
- src/utils/componentUtilityFunctions.js
Closes #1861
**Summary**
Added text based hotspots. The text hotspots will adjust in height and width depending on the content. The styling of the content can be modified using the hotspot config data.
_Hotspot_
- Added `type` prop. Can be fixed, text or variable. Text type is represented by a new selectable div that shows all content directly.
- Added text formatting props with default values. The props are modified and pass to the stylesheets as CSS custom properties.
- Added size measurement for text type hotspots so that height and width can be dynamic 
- Updated stylesheets. Part of the HotspotContent styles are overridden here since we need access to properties of the hotspot (size, padding, border etc).
- added unit tests …
> 1861 hotspot add text style hotspots

- src/components/BarChartCard/BarChartCard.jsx
- src/components/DashboardEditor/DashboardEditor.jsx
- src/components/DashboardEditor/DashboardEditorCardRenderer.jsx
- src/components/DashboardEditor/DashboardEditorCardRenderer.test.jsx
- src/components/DashboardEditor/__snapshots__/DashboardEditor.story.storyshot
- src/components/DashboardEditor/editorUtils.jsx
Need to add lots of memoizing to React Editor components to improve performance
Closes #
**Summary**
- fix(BarChartCard): memoize the sample data creation
- fix(DashboardEditor): wrap all function definitions with useCallback and memoize where possible
- refactor(DashboardEditorCardRenderer): need to change the getCardPreview to a React component so I have more control over memoizing and rerender cycle
- refactor(editorUtils): move the render helper functions to DashboardEditorCardRenderer, ideally they will be all migrated to components rather than render functions
- Verify the DashboardEditor story
> fix(dashboardeditor): need to refactor function to react component so it can be memoized

- src/components/TileGallery/StatefulTileGallery.jsx
- src/components/TileGallery/TileGallery.test.jsx
- src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Closes #1887
**Summary**
- Adds missing `onClick` prop to `galleryItems` in `StatefulTileGallery`
- Add `onClick` prop to `StatefulTileGallery`
- Add test to check `onClick`  action
- Added test to check `onClick` in `StatefulTileGallery`
> fix(statefultilegallery): add missing onclick

- src/components/CardEditor/CardEditForm/CardEditForm.jsx
- src/components/CardEditor/CardEditForm/CardEditFormContent.jsx
- src/components/CardEditor/CardEditForm/CardEditFormItems/DataSeriesFormItemModal.jsx
- src/components/CardEditor/CardEditForm/CardEditFormItems/DataSeriesFormItems/DataSeriesFormContent.jsx
- src/components/CardEditor/CardEditForm/CardEditFormItems/TableCardFormItems/TableCardFormContent.jsx
- src/components/CardEditor/CardEditForm/CardEditFormItems/TableCardFormItems/TableCardFormContent.test.jsx
- src/components/CardEditor/CardEditForm/CardEditFormItems/TableCardFormItems/TableCardFormSettings.jsx
- src/components/CardEditor/CardEditForm/CardEditFormItems/TableCardFormItems/TableCardFormSettings.test.jsx
- src/components/CardEditor/CardEditForm/CardEditFormSettings.jsx
- src/components/CardEditor/CardEditForm/_card-edit-form.scss
- src/components/DashboardEditor/DashboardEditor.jsx
- src/components/DashboardEditor/DashboardEditorCardRenderer.jsx
- src/components/DashboardEditor/editorUtils.jsx
- src/components/DashboardEditor/editorUtils.test.jsx
- src/components/TableCard/__snapshots__/TableCard.story.storyshot
- src/components/TableCard/_table-card.scss
- src/components/TimeSeriesCard/timeSeriesUtils.js
Closes #1739 
**Summary**
- Add support for table cards in the dashboard editor. 
- Added `TableCardFormSettings.jsx`, `TableCardFormContent.jsx`
- updated 'CardEditForm.jsx`, `CardEditFormContent.jsx`, `CardEditFormSettings.jsx`, and `editorUtils.js` to support TableCard
- Go to[ dasbhoard editor story](https://deploy-preview-1889--carbon-addons-iot-react.netlify.app/?path=/story/watson-iot-experimental-dashboardeditor--default) and choose a Table Card. 
- Play around with the form and see changes in the card
> feat: tablecard editing support for dashboard editor

- .vscode/launch.json
- src/components/CardEditor/CardEditForm/CardEditForm.jsx
- src/components/CardEditor/CardEditor.jsx
- src/components/CardEditor/__snapshots__/CardEditor.story.storyshot
- src/components/DashboardEditor/DashboardEditor.story.jsx
- src/components/DashboardEditor/DashboardEditorHeader/DashboardEditorHeader.jsx
- src/components/DashboardEditor/__snapshots__/DashboardEditor.story.storyshot
- src/components/Header/HeaderAction/HeaderAction.jsx
- src/components/Header/HeaderActionGroup.jsx
- src/components/Header/__snapshots__/Header.story.storyshot
- src/components/SideNav/__snapshots__/SideNav.story.storyshot
- src/components/SuiteHeader/__snapshots__/SuiteHeader.story.storyshot
- src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Closes https://github.ibm.com/wiotp/monitoring-dashboard/issues/1699
Closes https://github.ibm.com/wiotp/monitoring-dashboard/issues/1680
**Summary**
- Adding `data-testid` for a few of the component to use it for walkme and also for automated testing. 
- Passing the string literal to the child component.
- Tested the component for which extra properties are added.
> adding data-testid for specific components

- src/components/DashboardEditor/DashboardEditor.story.jsx
- src/components/DashboardEditor/__snapshots__/DashboardEditor.story.storyshot
- src/components/DashboardEditor/_dashboard-editor.scss
Closes #1840
**Summary**
The editor inside of Monitor required the user to scroll because it wasn't taking the suite header into account.
- Calculate height for editor
- Remove the styled `div` that wrapped each story
Go to any editor story and verify that the height is correct and the edit JSON button is responsive.
> style(editor): update height to accomodate suite header

- src/components/HotspotEditorModal/_hotspot-editor-modal.scss
- src/components/ImageCard/ImageHotspots.jsx
- yarn.lock
Closes #1896
**Summary**
- Fixes issue where the scrolling inside the Modal also scrolled the image down
- fix(hotspot): allow only the right-pane to scroll, not the image itself
- Ensure that at small screen sizes where the right-pane is scrolled down, clicking to add hotspots puts them in the right place
> fix(hotspotmodaleditor): stop the image from scrolling

- src/components/SideNav/_side-nav.scss
Closes #1909 
**Summary**
Resolve layout issues with sidebar when using [dir="rtl"]
Add some rules for RTL layouts that weren't handled in the base library. 
Enable RTL mode in storybook and check that menu is on the right side and spacing looks consistent with how it is on the left.
> fix(sidebar): add some rules for handling RTL layouts

- packages/react/src/components/CardEditor/CardEditForm/CardEditForm.jsx
- packages/react/src/components/Table/StatefulTable.test.jsx
- packages/react/src/components/Table/Table.story.jsx
- packages/react/src/components/Table/TableHead/FilterHeaderRow/FilterHeaderRow.jsx
- packages/react/src/components/Table/TableHead/_table-head.scss
Closes #https://github.ibm.com/wiotp/monitoring-dashboard/issues/1906
**Summary**
- we haven't yet built a way for Custom Card types to send along the Setting form they support, until we do, we should hide the Settings tab from CardEditForm
- fix(CardEditForm): hide the Settings tab for the Custom card type
- Verify in the DashboardEditor story that if you add a custom card there is no Setting tab showing in the Form
> fix(cardeditform): custom cards do not yet support Settings panels in our DashboardEditor

- packages/react/src/components/DashboardEditor/DashboardEditor.jsx
- packages/react/src/components/DashboardEditor/DashboardEditorCardRenderer.jsx
- packages/react/src/components/DashboardEditor/DashboardEditorCardRenderer.test.jsx
- packages/react/src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Closes #
**Summary**
- The dashboardEditor should support the renderIconByName function just like the DashboardGrid does, so that downstream consumers can add additional icons to be used for thresholds and hotspots
- fix(DashboardEditor): add the renderIconByName callback
- fix(DashboardEditorCardRenderer): for the ImageCard render fix the default render function if the card can't find the matching icon, and let the passed function override the default function for the
- Verify the renderIconByName function is called, verify that none of the normal ImageCard editing cases are broken
> fix(dashboardeditor): support passing custom icon callback

- packages/react/src/components/CardEditor/CardEditForm/CardEditFormItems/ValueCardFormItems/ValueCardFormSettings.jsx
- packages/react/src/components/HotspotEditorModal/HotspotTextStyleTab/HotspotTextStyleTab.jsx
- packages/react/src/utils/componentUtilityFunctions.js
Closes #
**Summary**
- When NumberInput has a min or max, the input value needs to be checked before applying the `onChange`
- Added a function to check if a number value is valid when optionally given a min or max
- Used the function to check if the number value is valid before applying the onChange
- Go to any DashboardEditor story, add a ValueCard, go to the settings tab in the CardEditForm, and type in valid and invalid numbers to see the input respond correctly. It should only save numbers that are valid (between 16 and 54). If an invalid number / string is given, it will show the invalid text indication and will not save the number
> fix(DashboardEditor): check min and max before applying the number input value

- packages/react/package.json
Manual bump needed to fix our publishing. Somehow our version numbers got out of sync with package
- bumped up version in package.json
> feat(repo): had to do a manual bump as version got out of whack

- packages/react/src/components/List/HierarchyList/HierarchyList.jsx
- packages/react/src/components/List/HierarchyList/HierarchyList.story.jsx
- packages/react/src/components/List/HierarchyList/HierarchyList.test.jsx
- packages/react/src/components/List/HierarchyList/__snapshots__/HierarchyList.story.storyshot
- packages/react/src/components/List/ListItem/ListItem.jsx
- packages/react/src/components/Table/TableBody/TableBodyRow/__snapshots__/TableBodyRow.story.storyshot
- packages/react/src/components/WizardModal/__snapshots__/WizardModal.story.storyshot
**Summary**
- Fix placement of parentheses on conditional check when searching secondaryValue in HierarchyList 
- Add new test to cover searching when `secondaryValue` is a render function when its a child AND when its a parent / doesn't have children
- Update story to have a custom render function on a non-parent and child item
- Update `secondaryValue` prop type to be type `func` as it was meant to be in my previous fix
- Go to ?path=/story/watson-iot-hierarchylist--with-mixed-hierarchies and search for various values
> fix(hierarchylist): update incorrect syntax

- packages/react/src/components/SuiteHeader/SuiteHeader.jsx
- packages/react/src/components/SuiteHeader/SuiteHeader.story.jsx
- packages/react/src/components/SuiteHeader/SuiteHeaderAppSwitcher/SuiteHeaderAppSwitcher.jsx
- packages/react/src/components/SuiteHeader/SuiteHeaderAppSwitcher/SuiteHeaderAppSwitcher.story.jsx
- packages/react/src/components/SuiteHeader/SuiteHeaderAppSwitcher/SuiteHeaderAppSwitcher.test.jsx
- packages/react/src/components/SuiteHeader/SuiteHeaderAppSwitcher/__snapshots__/SuiteHeaderAppSwitcher.story.storyshot
- packages/react/src/components/SuiteHeader/SuiteHeaderLogoutModal/__snapshots__/SuiteHeaderLogoutModal.story.storyshot
- packages/react/src/components/SuiteHeader/SuiteHeaderProfile/SuiteHeaderProfile.jsx
- packages/react/src/components/SuiteHeader/SuiteHeaderProfile/SuiteHeaderProfile.story.jsx
- packages/react/src/components/SuiteHeader/SuiteHeaderProfile/SuiteHeaderProfile.test.jsx
- packages/react/src/components/SuiteHeader/SuiteHeaderProfile/__snapshots__/SuiteHeaderProfile.story.storyshot
- packages/react/src/components/SuiteHeader/__snapshots__/SuiteHeader.story.storyshot
- packages/react/src/components/SuiteHeader/_suite-header.scss
- packages/react/src/components/SuiteHeader/i18n/index.js
- packages/react/src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
**Summary**
- loading states for the `SuiteHeader` component - shows skeleton components when data is not available in the header menus.
- extensibility for the `SuiteHeader` component - adds supports for custom help menu items, custom profile links and custom applications in the app switcher
- tests have been created to test loading states
- an existing story has been extended to include custom entries in the SuiteHeader component action items
Loading states:
Extensibility:
> feat(suiteheader): Support for loading states and extensibility for Help, Profile and Applications menu items

- packages/react/src/components/ValueCard/Attribute.jsx
- packages/react/src/components/ValueCard/ValueCard.jsx
- packages/react/src/components/ValueCard/ValueCard.test.jsx
- packages/react/src/components/ValueCard/__snapshots__/ValueCard.story.storyshot
- packages/react/src/constants/CardPropTypes.js
- packages/react/src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
- yarn.lock
Closes #
**Summary**
- Value card was ignoring the precision value passed in all cases, and unfortunately it was being passed at the card level rather than the attribute level.
- fix(Attribute): move precision to the Attribute level
- fix(ValueCard): remove default precision property at the card level
- fix(CardPropTypes): add precision to the Attribute section
http://127.0.0.1:3000/?path=/story/watson-iot-valuecard--medium-2
- If you go to the Value card story for Medium 2 and change the precision setting inside the attribute, you'll see it get updated, this doesn't work in the previous build of addons
> fix(valuecard): precision is at the attribute level not card level

- packages/react/src/components/CardEditor/CardEditForm/CardEditForm.jsx
- packages/react/src/components/CardEditor/CardEditForm/CardEditForm.test.jsx
- packages/react/src/components/ValueCard/Attribute.jsx
- packages/react/src/components/ValueCard/ValueCard.jsx
- packages/react/src/components/ValueCard/ValueCard.test.jsx
- packages/react/src/components/ValueCard/__snapshots__/ValueCard.story.storyshot
- packages/react/src/constants/CardPropTypes.js
- packages/react/src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
- yarn.lock
Prereqs #2015 
**Summary**
- There was a bug where if the user changed the `content` section of a card in the JSON Editor (for example changing the label) they were not passed along when the JSON Editor was saved and the updated card was submitted.
To see the bug, open the JSON Editor and manually set this card 
https://next.carbon-addons-iot-react.com/?path=/story/watson-iot-experimental-cardeditor--interactive
```
{
"title": "New card",
"size": "SMALL",
"content": "my custom",
"type": "VALUE"
}
```
Notice in the left pane, the content is removed (or if you open the code editor again)
- fix(CardEditForm): handleSubmit we should not override the content section of the CardEditor
- Verify in the …
> fix(cardeditform): if I made changes to the content section in the CardCodeEditor they were not passed along

- .vscode/launch.json
- packages/react/src/components/CardEditor/CardEditForm/CardEditFormItems/DataSeriesFormItemModal.jsx
- packages/react/src/components/CardEditor/CardEditForm/CardEditFormItems/DataSeriesFormItemModal.test.jsx
- packages/react/src/components/DashboardEditor/DashboardEditor.story.jsx
Closes #
**Summary**
- Little bit of a usability problem, the grain selector doesn't make sense at 'input' if no aggregator is selected, I have removed the input grain option and hidden the grain selector if 'none' is set as the aaaggregaator
- fix(launch.json): support the new monorepo structure
- fix(DataSeriesFormModal): remove the input from the grain selector, fix the TextInput prop types warnings thrown because of bad props, only show the grain if the aggregator is not none, and default and clear the grain as the aggregator is changed
- Verify in this story, as you popup the DataItemEditModal and switch the aggregator, that the grain selector disappears and reappears as you change the …
> fix(dataitemmodal): need to hide the grain if no aggregator is selected

- packages/react/src/components/BarChartCard/barChartUtils.js
- packages/react/src/components/CardEditor/CardEditForm/CardEditFormContent.jsx
- packages/react/src/components/CardEditor/CardEditForm/CardEditFormItems/DataSeriesFormItems/DataSeriesFormContent.jsx
- packages/react/src/components/CardEditor/CardEditForm/CardEditFormItems/DataSeriesFormItems/DataSeriesFormContent.test.jsx
- packages/react/src/components/CardEditor/CardEditForm/CardEditFormItems/TableCardFormItems/TableCardFormContent.test.jsx
- packages/react/src/components/CardEditor/CardEditor.jsx
- packages/react/src/components/DashboardEditor/DashboardEditor.jsx
- packages/react/src/components/DashboardEditor/editorUtils.jsx
- packages/react/src/components/DashboardEditor/editorUtils.test.jsx
- packages/react/src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Closes #
**Summary**
- Changing the existing elements of a legacy dashboard causes errors downstream
- fix(dataseriesformcontent): do not change the daataSourceId of existing elements, only when new ones aare generated
> fix(dataseriesformcontent): it should not change existing elements

- packages/react/src/components/Dashboard/_dashboard-grid.scss
- packages/react/src/components/DashboardEditor/DashboardEditor.jsx
- packages/react/src/components/DashboardEditor/DashboardEditor.test.jsx
- packages/react/src/components/DashboardEditor/_dashboard-editor.scss
- packages/react/src/components/StorybookSnapshots.test.js
- packages/react/src/styles.scss
Closes #1987 
**Summary**
- When a card is added, scroll to the bottom of the dashboard grid so that the card is visible. This is done by checking if the scroll height of the grid container has changed, meaning a card has been added, then scrolling to the bottom
- Re-adds dashboard-grid's style file as it got lost in the monorepo merge
- Update the styling for DashboardEditor to only show the background color when breakpoints are being used
- Fix the height of the grid container in DashboardEditor to not have any scroll by default
- Go to any DashboardEditor story, add cards until the visible grid is full, then continue to add cards and ensure you can always see the newly added card
- While in those …
> feat(dashboardeditor): scroll to added cards

- packages/react/src/components/DashboardEditor/__snapshots__/DashboardEditor.story.storyshot
- packages/react/src/components/TableCard/TableCard.jsx
- packages/react/src/components/TableCard/__snapshots__/TableCard.story.storyshot
- packages/react/src/components/TimeSeriesCard/timeSeriesUtils.js
- packages/react/src/components/TimeSeriesCard/timeSeriesUtils.test.js
Closes #
**Summary**
- There were two problems in using the TableCards in the DashboardEditor
- The first was that in certain instances a pageSize of 0 was being passed, which causes the Pagination component from carbon to cycle indefinitely.  Also there was a small bug where the whole table rows wouldn't render and there was whitespace underneath
- The second was that if the columns in the table changed, it would render duplicate columns due to a bug with the underlying Table where if you change the order and number of columns it renders duplicates
- fix(TableCard): use key to throw away the table and rerender if the pageSize or the number of columns change.
- fix(TableCard): we can fit two more rows in the editable card, fix the …
> fix(tablecard): in dashboard editor

- packages/react/src/components/DateTimePicker/DateTimePicker.jsx
- packages/react/src/components/DateTimePicker/DateTimePicker.story.jsx
- packages/react/src/components/DateTimePicker/DateTimePicker.test.jsx
- packages/react/src/components/DateTimePicker/__snapshots__/DateTimePicker.story.storyshot
- packages/react/src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Closes #2085 
**Summary**
- Fixes issues with using multiple DateTimePicker component on same page.
- Added a new required prop "id". It is appended to all the hard coded ids to make them unique. This ensures that there are no duplicate ids if there's more than one DateTimePicker component on the same page.
- Tested the fix in Health application
> fix(datetimepicker): cant use multiple datetimepicker on same page #2085

- packages/react/src/components/Dashboard/__snapshots__/Dashboard.story.storyshot
- packages/react/src/components/Dashboard/__snapshots__/DashboardGrid.story.storyshot
- packages/react/src/components/DashboardEditor/__snapshots__/DashboardEditor.story.storyshot
- packages/react/src/components/RuleBuilder/RuleBuilder.story.jsx
- packages/react/src/components/RuleBuilder/RuleBuilderEditor.story.jsx
- packages/react/src/components/RuleBuilder/__snapshots__/RuleBuilder.story.storyshot
- packages/react/src/components/RuleBuilder/__snapshots__/RuleBuilderEditor.story.storyshot
- packages/react/src/components/ValueCard/Attribute.jsx
- packages/react/src/components/ValueCard/__snapshots__/ValueCard.story.storyshot
- packages/react/src/components/ValueCard/_attribute.scss
Closes #2060 
**Summary**
- Move the icon beside the label instead of below the value
- Fix the spacing and coloring of the trending values
- minor fix for rulebuilder story
- bring valuecard design into alignment with designs
- The https://deploy-preview-2087--carbon-addons-iot-react.netlify.app?path=/story/watson-iot-🚫-dashboard--only-value-cards story should now show the icons to the left of the label on cards with an icon, and the trending values should be vertically aligned and be green or red respectively compared with what is currently on [next](https://next.carbon-addons-iot-react.com/?path=/story/watson-iot-%F0%9F%9A%AB-dashboard--only-value-cards)
> fix(valuecard): fix positioning of icons and color of trending secondary values

- packages/react/package.json
- packages/react/src/components/Dashboard/DashboardGrid.jsx
- packages/react/src/components/Dashboard/DashboardGrid.story.jsx
- packages/react/src/components/Dashboard/__snapshots__/Dashboard.story.storyshot
- packages/react/src/components/Dashboard/__snapshots__/DashboardGrid.story.storyshot
- packages/react/src/components/DashboardEditor/__snapshots__/DashboardEditor.story.storyshot
Closes #
**Summary**
- Persistent bug with react-grid-layout where if the grid doesn't take up the full screen, it doesn't size itself correctly.
- test(DashboardGrid): I added a sidebar to the grid story so this kind of bug would show up in the future
- fix(DashboardGrid): manual workaround to trigger window resize event (Which updates the react-grid-layout) whenever the Dashboard pane resizes. This happens when the two flex items are placed in the same layout next to each other
- http://127.0.0.1:3000/?path=/story/watson-iot-%E2%9A%A0%EF%B8%8F-dashboard-grid--dashboard-default-layouts
If the cards don't scroll off screen to the right, the fix worked
> fix(dashboardgrid): workaround to trigger resize event

- packages/react/src/components/CardEditor/CardEditForm/CardEditFormItems/DataSeriesFormItemModal.jsx
- packages/react/src/components/CardEditor/CardEditForm/CardEditFormItems/DataSeriesFormItemModal.test.jsx
- packages/react/src/components/CardEditor/CardEditForm/CardEditFormItems/DataSeriesFormItems/DataSeriesFormContent.jsx
Closes #
**Summary**
- fix(DataSeriesFormItemModal): table, simple bar, and stacked bar charts may not be time-based in certain cases.  We should be more careful showing the grain and only show it for the real time-based cases
- fix(DataSeriesFormItemContent): when selecting an attribute for a simple bar chart, we should also generate a unique id so that it's clear this was selected by the user.  This allows a non-mean aggregator to be selected for that attribute
- Verify in the DashboardEditor story that if you popup the DataSeriesFormModal for a Simple Bar, Stacked Bar or Table Card attribute that is NOT time-based, that the grain selector is hidden and no grain is set for the item.
- Here are the scenarios, a Simple Bar that's grouped by …
> fix(dataseriesformitemmodal): grain selector is showing incorrectly for certain card types

- packages/react/src/components/Dashboard/DashboardGrid.jsx
Closes #1577
**Summary**
- The setShouldAnimate call was happening after the component unmounted in some cases.  This cancels the function if the component unmounts
- fix(DashboardGrid): cancel function and regen GridLayout when the bit changes
fixes this problem
```
onsole.error
Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.
in DashboardGrid (created by DashboardEditor)
in ErrorBoundary (created by DashboardEditor)
in div (created by DashboardEditor)
in div (created by DashboardEditor)
in div (created by DashboardEditor)
in div (created by DashboardEditor)
``` …
> fix(dashboardgrid): should not set state if component unmounts

- packages/react/src/components/Button/_button.scss
Closes #2114
**Summary**
- Small fix to the padding between the loading and the button text, caused by a change to loading made in carbon-components-react upgrade
- Verify the Loading Button story looks good
> fix(button): update spacing in loading state

- .github/workflows/publish.yml
`test:ci` gives packages explicit control over testing behaviour when running in a workflow. This enables that for the publishing workflow (already enabled for the test workflow)
> fix: use test:ci in the publish workflow

- packages/react/jest.config.js
- packages/react/src/components/Page/PageTitle.test.jsx
Closes #2162 
**Summary**
Dashboard and CardRenderer are deprecated, so ignore from test coverage
> chore(dashboard): ignore Dashboard/CardRenderer coverage

- scripts/release.sh
Adds some conditions to the release script to check if the branch heads are out of sync before we publish. it:
- fetches all remotes
- gets the current commits for local and remote branches
- compares, and exits if they're not equal
> fix(build): skip publishing if the local and remote heads are out of sync

- packages/react/src/components/Card/_data-state-renderer.scss
Closes #2179 
**Summary**
- fixed line height on the valuecard dashes to prevent them from pushing the icons off the card.
1. go to storybook: https://deploy-preview-2185--carbon-addons-iot-react.netlify.app/?path=/story/watson-iot-valuecard--data-state-error-small
2. Click on data state - error - small
3. select dataStateType for either ERROR or NO_DATA
3. The icons should be visible
> fix(value-card): fix error/warning icons not visible on card

- packages/react/src/components/DashboardEditor/DashboardEditorHeader/__snapshots__/DashboardEditorHeader.story.storyshot
- packages/react/src/components/DashboardEditor/__snapshots__/DashboardEditor.story.storyshot
- packages/react/src/components/NavigationBar/__snapshots__/NavigationBar.story.storyshot
- packages/react/src/components/PageTitleBar/PageTitleBar.jsx
- packages/react/src/components/PageTitleBar/PageTitleBar.story.jsx
- packages/react/src/components/PageTitleBar/PageTitleBar.test.jsx
- packages/react/src/components/PageTitleBar/__snapshots__/PageTitleBar.story.storyshot
- packages/react/src/components/PageTitleBar/_page-title-bar.scss
- packages/react/src/components/PageWizard/__snapshots__/PageWizard.story.storyshot
- packages/react/src/components/SideNav/__snapshots__/SideNav.story.storyshot
- packages/react/src/components/TileGallery/__snapshots__/TileGallery.story.storyshot
- packages/react/src/components/WizardInline/__snapshots__/WizardInline.story.storyshot
- packages/react/src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
**Summary**
The sticky header styles where ignoring the suite header because the offset was only setting the position for the dynamic transition from `STATIC` to `CONDENSED` in the `DYNAMIC` headerMode.
- Create a new `stickyHeaderOffset` prop and rename the `headerModeDynamicOffSet` offset to `dynamicTransitionOffset`
- Pass the offsets to the proper `top` attribute
Not much of a change to see in the storybook. This basically just allows the consumer to specify where the sticky headers should "stick".
Make sure that the different headerModes still work properly in the `PageTitleBar` `with dynamic scrolling` story.
> style(page-title-bar): fix offsets

- packages/react/src/components/List/HierarchyList/HierarchyList.jsx
Closes #
**Summary**
- fixes #2193 
- fix(hierarchylist): when searching stop the clone deep, only do a direct clone of the items and children
- verify that you can still search correctly in the HierarchyList story
> fix(hierarchylist): cloneDeep can blow up and clone the whole tree

- packages/angular/package.json
- packages/angular/scripts/vendor.js
- packages/monorepo-utils/README.md
- packages/monorepo-utils/package.json
- packages/styles/package.json
- packages/styles/scripts/copy-styles-from-react.js
- packages/styles/scripts/vendor.js
npm has two different notions of private packages it seems. Packages of the form `my-package-name`, with `"private": true` set in the `package.json` will never be published to npm (this is what we want). Packages of the form `@my-scope/my-package-name`, with `"private": true` however _will_ be published as a "private scoped package" (a specific thing for paid npm accounts). To avoid this I've updated `@ai-apps/monorepo-utils` to be `ai-apps-monorepo-utils`, since this isn't a package that we should publish.
Some info about npms **scoped** private packages: https://docs.npmjs.com/about-private-packages
> fix(repo): un-scope monorepo-utils to prevent npm from trying to publish it

- package.json
- packages/react/package.json
- yarn.lock
Closes #2201 
**Summary**
After moving to the monorepo and adding angular there was a version conflict for @storybook/theming and @emotion/core that prevented the 'Show Info' button from working on React. I set resolutions for the react package in the root package.json, because yarn will ignore resolutions in workspace packages in monorepos. See: https://github.com/yarnpkg/yarn/issues/5039
- added resolutions to the root package.json
- The 'Show Info' button should work in the [deploy preview](https://deploy-preview-2202--carbon-addons-iot-react.netlify.app/?path=/story/0-getting-started--about-storybook) to see code for stories.
> fix(storybook): fix 'show info' button

- packages/react/.storybook/story-styles.scss
- packages/react/src/components/Card/DataStateRenderer.jsx
- packages/react/src/hooks/usePopoverPositioning.jsx
Closes #2192 
**Summary**
- use auto positioning on tooltip to keep it on the screen
- use auto positioning on tooltip
- adjust offset settings to get tooltip to position correctly.
- go to https://deploy-preview-2219--carbon-addons-iot-react.netlify.app/?path=/story/watson-iot-%F0%9F%9A%AB-dashboard--only-value-cards
- shrink the window size
- click the warning icon and confirm the tooltip stays on the screen.
- check the autopositioning stories for flyout menu, tooltip, and overflow menu to ensure it doesn't break existing functionality.
> fix(value-card): use auto positioning tooltip

- packages/react/src/components/Table/Table.jsx
- packages/react/src/components/Table/Table.story.jsx
Closes #1901 
**Summary**
- include search.defaultValue to determine if the "no data" or "no results" message should be displayed
- included search.defaultValue in isFiltered logic on the table
- The [no data story](https://deploy-preview-2231--carbon-addons-iot-react.netlify.app/?path=/story/watson-iot-table--with-no-data) should still show "no data"
- The [no results story](https://deploy-preview-2231--carbon-addons-iot-react.netlify.app/?path=/story/watson-iot-table--with-no-results) should still show "no results"
- In the [Stateful Example with Create & Save Views](https://deploy-preview-2231--carbon-addons-iot-react.netlify.app/?path=/story/watson-iot-table--stateful-example-with-create-save-view …
> fix(table): include search.defaultValue in filtering logic

- packages/react/src/components/TimeSeriesCard/timeSeriesUtils.js
Closes #https://github.ibm.com/wiotp/Maximo-Asset-Monitor/issues/2290
**Summary**
- Fixes issue with the timeSeriesUtils where a chart with all zero values never showed data
- fix(timeSeriesUtils): check inNil rather than the value comparison (which skips for 0)
- Verify if you pass zero values to a TimeSeriesChart that it still renders
- Verify that the existing TimeSeries stories haven't changed
> fix(timeseries): support 0 values in the line chart

- packages/react/src/components/WizardModal/WizardModal.jsx
- packages/react/src/components/WizardModal/__snapshots__/WizardModal.story.storyshot
Closes #1828 
**Summary**
- fix the onBack error by not passing the onBack prop in the spread.
- no more onBack error in the console
- wizard modal should function normally
> fix(wizard-modal): do not pass onBack to ComposedModal

- packages/react/src/components/BarChartCard/BarChartCard.jsx
- packages/react/src/components/TimeSeriesCard/TimeSeriesCard.jsx
- packages/react/src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
**Summary**
Need to give the consumer the ability to set the `legendPosition` on `TimeSeries` and `Bar` cards.
Expose new `legendPosition` prop.
Make sure you can control the legendPosition via the new prop.
Make sure that BarChart and TimeSeries cards still properly show the legend on the bottom by default.
> Expose legend position prop on bar and time cards

- packages/react/src/components/FlyoutMenu/FlyoutMenu.jsx
- packages/react/src/components/FlyoutMenu/FlyoutMenu.story.jsx
- packages/react/src/components/FlyoutMenu/__snapshots__/FlyoutMenu.story.storyshot
- packages/react/src/components/FlyoutMenu/_flyout-menu.scss
- packages/react/src/components/PieChartCard/__snapshots__/PieChartCard.story.storyshot
- packages/react/src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
**Summary**
We need to add the ability to show the onHover tooltips for the `FlyoutMenu` trigger button.
- Add `hideTooltip` prop. (defaults to true)
- Pass the rest of the `buttonProps` through to the trigger button
Go to any `FlyoutMenu` story and use the knobs for `hideTooltip`, `buttonProps`, and `iconDescription`. See that the component is updated accordingly.
Make sure basic functionality is still working properly.
> Flyout menu tooltip option

- packages/react/src/components/TimeSeriesCard/TimeSeriesCard.jsx
Closes #2055 
**Summary**
- `min`/`max` on ticks is used for the minimum/maximum tick value, not the number of ticks to be shown. (See [carbon docs](https://github.com/carbon-design-system/carbon-charts/blob/da7918594ff9c8f8fb74e547ec352a498c7151da/packages/core/src/interfaces/axis-scales.ts#L63)) Switched it to the `number` prop, so that the number of ticks shown changes on different size cards.
- use number instead of min/max for axis ticks
- add LARGETHIN to use only 6 ticks, since at 10 it's very crowded.
- the medium / single line - interval hour story should adjust the number of ticks when changing size between medium/medium wide, large wide, etc.
**Regression Test (how to make sure this PR …
> fix(time-series-card): use number instead of min/max for ticks

- packages/react/src/components/List/HierarchyList/HierarchyList.story.jsx
- packages/react/src/components/List/HierarchyList/__snapshots__/HierarchyList.story.storyshot
- packages/react/src/components/List/ListItem/ListItem.jsx
**Summary**
When a `HierarchyList` category item is selectable, clicking the chevron up or down to expand or collapse the category fires the category item's `onSelect` function.
- Stop the event propagation on the expansion click to prevent the list item from receiving a click event under the chevron icon.
- Go to the `With selectable categories` `HierarchyList` story and see that when you collapse the category, the selected item is preserved and the category item is not selected unless clicked on explicitly.
Make sure expanding and collapsing work as expected.
> fix(list-item): stop propagation for selectable categories

- packages/react/src/components/CardEditor/CardEditForm/CardEditFormItems/DataSeriesFormItemModal.jsx
- packages/react/src/components/CardEditor/CardEditForm/_card-edit-form.scss
- packages/react/src/components/HotspotEditorModal/HotspotEditorDataSourceTab/HotspotEditorDataSourceTab.test.jsx
- packages/react/src/components/HotspotEditorModal/hooks/hotspotStateHook.js
Closes #2045 
**Summary**
- Adds precision to data items on ImageCards in the DashboardEditor
- display precision dropdown on ImageCards
- add precision to the reducer to save its state
- update styles to fix increment/decrement on thresholds
- update test cases to account for the extra buttons in the modal
- Add an image card to the DashboardEditor
- Edit the image
- add Pressure as a data item
- edit Pressure
- Ensure Aggregate/Precision fields are available and persist after change/save
> feat(dashboard-editor): add decimal precision to ImageCards

- packages/react/src/components/CardEditor/CardEditForm/CardEditFormItems/DataSeriesFormItems/DataSeriesFormContent.jsx
Closes #2051 
**Summary**
- always use the dataSourceId in the selectedItems array to ensure the proper labels are used by the dropdown and in the list of selected data points
- use dataSourceId when adding new data items to be used.
- In the [DashboardEditor default story](https://deploy-preview-2241--carbon-addons-iot-react.netlify.app/?path=/story/watson-iot-experimental-dashboardeditor--default) add a TimeSeriesCard and ensure the labels always match in the dropdown and in the list of data items for the card.
> fix(dashboard-editor): always use dataSourceId in selectedData array

- packages/react/src/components/DashboardEditor/DashboardEditor.jsx
- packages/react/src/components/DashboardEditor/editorUtils.jsx
- packages/react/src/constants/CardPropTypes.js
- packages/react/src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Closes #2118 
**Summary**
- When adding a grouped BarChartCard via the dashboard editor, a `categoryDataSourceId` or `timeDataSourceId` must be specified. Since a grouped card doesn't support `timeDataSourceId` yet, I added an i18n prop for a placeholder to assign to the `categoryDataSourceId` to prevent the prop error until the actual group dimension can be selected in card editor form.
- pass a new i18n prop to the DashboardEditor, that can be passed to the getDefaultCard props function and assigned to the `categoryDataSourceId`.
- Fixed the BarChartCard proptypes so that it displays the name of the missing prop not the value to clarify this error in the future
- When adding a Group BarChartCard …
> fix(bar-chart-card): prop error on grouped BarChartCard

- packages/react/src/components/DashboardEditor/DashboardEditor.story.jsx
- packages/react/src/components/DashboardEditor/DashboardEditorCardRenderer.jsx
- packages/react/src/components/DashboardEditor/__snapshots__/DashboardEditor.story.storyshot
Closes #
**Summary**
- Small issue where for default and custom card types, the DashboardEditor was not adding the children prop (which contains the draggable resizable widget)
- fix(DashboardEditorCardRenderer): pass the child prop along as well.
- Verify the DashboardEditor story, when you add an Alert or Custom card they are both resizable
- Verify the other card types are still resizable
> fix(cardrenderer): custom and default cards should be resizable

- .github/workflows/test.yml
This splits up the React and Angular test runs into separate jobs. This should make it clearer which package is failing, lower overall run time, and not gate React PRs on Angular issues and vice-versa.
This also makes use of https://github.com/dorny/paths-filter to skip running react/angular tests based on which files have changed.
> chore(testing): split up react and angular test jobs

- packages/react/src/components/Table/Table.story.jsx
- packages/react/src/components/Table/TableCellRenderer/TableCellRenderer.jsx
- packages/react/src/components/Table/TableCellRenderer/_table-cell-renderer.scss
- packages/react/src/components/Table/TableHead/TableHead.jsx
- packages/react/src/components/Table/TableHead/TableHeader.js
- packages/react/src/components/Table/TablePropTypes.js
- packages/react/src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Closes #https://github.ibm.com/wiotp/Maximo-Asset-Monitor/issues/2221
**Summary**
- Adds new tooltip prop to each table column and it will render this as a description of the tooltip
- feat(TableCellRenderer): preserve the existing TableCell truncation UX inside the Data section, but if the tooltip property is passed, then show a TooltipDefinition (currently only supported for column headers)
- feat(tableCellRenderer.scss): make the header class match for the tooltip
- feat(TableHead/TableHeader): need to allow overflow if a tooltip is being used
- feat(TablePropTypes): expose the tooltip prop on the column
- Check the new story that has a column tooltip
**Regression Test (how to make sure this PR …
> feat(tablecolumn): add optional tooltip to table column

- packages/react/package.json
- packages/react/src/components/Card/Card.jsx
- packages/react/src/components/DashboardEditor/DashboardEditor.story.jsx
- packages/react/src/components/DashboardEditor/__snapshots__/DashboardEditor.story.storyshot
- yarn.lock
Closes #
**Summary**
- I broke the custom card rendering from a function here #2270 , because only the first array child was an actual function now that I'm passing the additional content fields (to support resizing)
- fix(Card.jsx): check the children to see if it's an array and call the first function in an array to render the custom content
- test(DashboardEditor): update the custom card story to actually render custom content from a function to catch this kind of regression in the future
- fix(package.json): react-draggable isn't bringing in fbjs as a dependency so local yarn links fail.  I'm specifying this as a direct dependency of carbon-addons-iot-react now to make sure the local yarn link can build.
**Acceptance Test (how to verify …
> fix(customcard): rendering of custom card was incorrect

- packages/react/src/components/ComboBox/ComboBox.jsx
- packages/react/src/components/ComboBox/ComboBox.story.jsx
- packages/react/src/components/ComboBox/ComboBox.test.jsx
Closes #2041 
**Summary**
- Allows items passed to ComboBox to use numbers as their ids
- Clicking "Option 1" in the Default ComboBox story should fire an onChange action with {id: 0, text: 'Option 1'} without any issues.
- all tests pass and no changes to existing ComboBox stories
> fix(combo-box): allow item ids to be numbers

- packages/react/rollup.config.js
Closes #2319 
**Summary**
Proposed fix for build errors that stem from the addition of the dayjs library. This should solve the immediate issue with our build but we should open up a bug on the dayjs repo. 
@scottdickerson can you please check that this fixes your build issues before we merge.
> fix(repo): ts ext were breaking downstream consumers

- packages/react/src/utils/dayjs.js
Closes #2319 
**Summary**
- Adds `.js` to the end of the dynamic dayjs locale imports to fix an issue where downstream consumers were unable to compile projects with this library
- Link this library to a separate React project (can't be tested with storybook) and ensure the project is able to build and compile with no errors
- Check that locales are still working
> fix(dayjs): dynamic import needs .js

- scripts/release.sh
Script typo is preventing master branch from publishing when updated.
> Update the release script to fix typo

- packages/react/src/components/OverflowMenu/index.jsx
Closes #
**Summary**
- using a wildcard import to pull in getMenuOffset was causing build errors downstream. Reverted back to the original import method and it magically works now. 🤕
> fix(overflow-menu): getMenuOffset import fix

- packages/react/src/utils/dayjs.js
Closes #
**Summary**
- For some reason the utils/dayjs extension doesn't work in downstream consumers (so functions like utc() break)
- fix(utils/dayjs): rename the constant used to extend dayjs on export
- Verify in a built project that TimeSeriesCard can be used in isEditable mode
- Verify the existing TimeSeriesCard stories (especially isEditable) do not break
> fix(dayjs): need to rename the dayjs variable or we lose the extends

- packages/react/src/components/FileUploader/stories/drop-container.jsx
- packages/react/src/components/OverflowMenu/index.jsx
- packages/react/src/components/SuiteHeader/SuiteHeader.test.jsx
Closes #
**Summary**
- use es not lib when importing overflow menu.
> fix(overflow-menu): use es import from carbon

- packages/react/src/components/BarChartCard/__snapshots__/BarChartCard.story.storyshot
- packages/react/src/components/Card/__snapshots__/Card.story.storyshot
- packages/react/src/components/ComboChartCard/__snapshots__/ComboChartCard.story.storyshot
- packages/react/src/components/Dashboard/__snapshots__/Dashboard.story.storyshot
- packages/react/src/components/Dashboard/__snapshots__/DashboardGrid.story.storyshot
- packages/react/src/components/DashboardEditor/__snapshots__/DashboardEditor.story.storyshot
- packages/react/src/components/PieChartCard/__snapshots__/PieChartCard.story.storyshot
- packages/react/src/components/RuleBuilder/__snapshots__/RuleBuilder.story.storyshot
- packages/react/src/components/Table/TableBody/RowActionsCell/RowActionsCell.jsx
- packages/react/src/components/Table/TableBody/TableBody.jsx
- packages/react/src/components/Table/TableHead/TableHead.jsx
- packages/react/src/components/TableCard/__snapshots__/TableCard.story.storyshot
- packages/react/src/components/TimeSeriesCard/__snapshots__/TimeSeriesCard.story.storyshot
Closes #2005 
**Summary**
- omit isDelete, isEdit, and isDivider props from being passed to the button
- fix data-testids on TableBody and TableExpandHeader.
- no errors in the console when isEdit or isDelete is included in a table action when _not_ in the overflow menu.
- no other changes to table
> fix(table): prevent prop warnings and fix testids

- packages/react/package.json
- packages/react/src/components/StorybookSnapshots.test.js
- packages/react/src/components/TimeSeriesCard/TimeSeriesCard.jsx
- packages/react/src/components/TimeSeriesCard/TimeSeriesCard.story.jsx
- packages/react/src/components/TimeSeriesCard/__snapshots__/TimeSeriesCard.story.storyshot
- packages/react/src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
- yarn.lock
Closes #
**Summary**
- Carbon charts has added a thresholds prop and we're exposing this now in the TimeSeriesCard
- fix(package.json): add helper builder react jsx to support builds, they started breaking
- fix(storybooksnapshots): mock the document and window for getComputedStyle
- feat(TimeSeriesCard): add thresholds prop
- view the thresholds story of the TimeSeriesCard
- Verify a few of the other TimeSeriesCard stories
> feat(timeseriescard): expose the thresholds for x and y axis for time series chart

- packages/react/src/components/SuiteHeader/SuiteHeader.jsx
- packages/react/src/components/SuiteHeader/__snapshots__/SuiteHeader.story.storyshot
- packages/react/src/components/SuiteHeader/_suite-header.scss
Closes #
Closes an issue where any open panel (profile or app switcher) was automatically closing when SuiteHeader transitioned from "loading" to "data ready" state.
**Summary**
The use of Carbon's `HeaderContainer` to control the state of the side nav panel was causing the entire tree returned by its "render props" function to remount on every update in `SuiteHeader`'s properties. The solution was to remove the `HeaderContainer` component and manage the side nav toggle state in `SuiteHeader`. There was no possible solution to avoid a complete remounting of the components under `HeaderContainer` if we still used the "render props" approach.
Another change that was necessary was to avoid changing the `actionItems` array length. When API data becomes available, if the user is an admin, then …
> fix(suiteheader): Making the transition of “loading state” to “data ready state” in SuiteHeader seamless

- packages/react/src/components/CardEditor/CardEditForm/CardEditFormContent.jsx
- packages/react/src/components/CardEditor/CardEditor.story.jsx
- packages/react/src/components/CardEditor/__snapshots__/CardEditor.story.storyshot
- packages/react/src/components/ComboBox/__snapshots__/ComboBox.story.storyshot
- packages/react/src/components/HotspotEditorModal/__snapshots__/HotspotEditorModal.story.storyshot
- packages/react/src/components/NavigationBar/__snapshots__/NavigationBar.story.storyshot
- packages/react/src/components/PageTitleBar/__snapshots__/PageTitleBar.story.storyshot
- packages/react/src/components/RuleBuilder/__snapshots__/RuleBuilder.story.storyshot
- packages/react/src/components/TimeSeriesCard/TimeSeriesCard.jsx
- packages/react/src/constants/CardPropTypes.js
- packages/react/src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
- yarn.lock
Closes #
**Summary**
- Previously only the Custom card types could render custom EditSettingsForm sections.  This adds the capability for all card types
- feat(CardEditFormContent): show any custom sections if they are included
- fix(TimeSeriesCard): PropTypes for oneOf were incorrect
- fix(CardPropTypes): document the existing renderEditContent prop
- Verify the new CardEditor story and make sure the custom section shows for the TimeSeriesCard
- Verify that other card types in the CardEditor stories do not render custom content sections
> feat(cardeditor): support custom settings panels for all card types, even default ones

- packages/react/src/components/SuiteHeader/SuiteHeaderAppSwitcher/SuiteHeaderAppSwitcher.jsx
- packages/react/src/components/SuiteHeader/SuiteHeaderAppSwitcher/SuiteHeaderAppSwitcher.test.jsx
- packages/react/src/components/SuiteHeader/SuiteHeaderAppSwitcher/__snapshots__/SuiteHeaderAppSwitcher.story.storyshot
- packages/react/src/components/SuiteHeader/__snapshots__/SuiteHeader.story.storyshot
- packages/react/src/components/SuiteHeader/_suite-header.scss
- packages/react/src/utils/componentUtilityFunctions.js
Closes #2324 
**Summary**
- fixes keyboard navigation in the application switcher by adding keyDown handlers
- fixes nested A tags by changing the inner A tag to a Button.
- add onKeyDown handlers for keyboard navigation
- add keyboard navigation tests
- open the default SuiteHeader story
- click on the 9-dot menu to open to the application switcher panel
- tab navigate to the monitor or health links
- press enter or space to trigger those links
- confirm links take you to the new page
- no other changes to suiteheader.
> fix(suite-header): fix keyboard keyboard navigation in header panel

- packages/react/src/components/ComboChartCard/comboChartHelpers.js
- packages/react/src/components/TimeSeriesCard/TimeSeriesCard.jsx
- packages/react/src/components/TimeSeriesCard/TimeSeriesCard.story.jsx
- packages/react/src/components/TimeSeriesCard/__snapshots__/TimeSeriesCard.story.storyshot
- packages/react/src/components/TimeSeriesCard/timeSeriesUtils.js
- packages/react/src/components/TimeSeriesCard/timeSeriesUtils.test.js
This is a little bit of a workaround for a carbon charts bug, they don't render thresholds if they're off the y-axis graph:
https://github.com/carbon-design-system/carbon-charts/issues/1034
**Summary**
- Set of fixes to the TimeSeriesCard so support the edit/preview case with thresholds
- fix(TimeSeriesCard): sample values generation should not regenerate if the series and thresholds really don't change (do a json comparison). 
- refactor(TimeSeriesCard): remove unused yMaxAdjuster property in options
- workaround(TimeSeriesCard): regenerate the LineChart if the thresholds change. (this is to workaround an opened bug on carbon-charts
- feat(timeSeriesUtils): add thresholds to the generateSampleData function so we can make sure that all the …
> fix(timeseries): card with thresholds should generate sample values between the thresholds

- .github/CODEOWNERS
- .vscode/launch.json
- packages/react/src/components/EmptyState/_emptystate.scss
- packages/react/src/components/Table/ErrorTable/ErrorTable.jsx
- packages/react/src/components/Table/ErrorTable/__tests__/ErrorTable.test.jsx
- packages/react/src/components/Table/README.md
- packages/react/src/components/Table/Table.jsx
- packages/react/src/components/Table/Table.story.jsx
- packages/react/src/components/Table/TablePropTypes.js
- packages/react/src/components/Table/_table.scss
- packages/react/src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Related to https://github.ibm.com/wiotp/Maximo-Asset-Monitor/issues/2330
**Summary**
- Display an error state on any table error messages
- feat(ErrorTable): added to display the error state, with or without error state button and error state element
- feat(EmptyState): left-align the empty state in the table
- chore(codeowners): adding amritha raj to the code owners list
- Able to display custom error component
- Able to display an error message without any error action button
- Able to display an error message with any error action button
- table component should work without any issues.
> feat(errortable): add an error state to the table

- packages/react/src/components/Table/README.md
- packages/react/src/components/Table/StatefulTable.jsx
- packages/react/src/components/Table/StatefulTable.test.jsx
- packages/react/src/components/Table/Table.story.jsx
- packages/react/src/components/Table/Table.test.helpers.js
- packages/react/src/components/Table/Table.test.jsx
- packages/react/src/components/Table/TableBody/TableBody.jsx
- packages/react/src/components/Table/TableBody/TableBodyRow/TableBodyRow.jsx
- packages/react/src/components/Table/baseTableReducer.js
- packages/react/src/components/Table/tableActionCreators.js
- packages/react/src/components/Table/tableReducer.test.jsx
#124
Closes #124
**Summary**
Improved the selection logic for nested rows with multi select according to specs in the issue comment:
_1. Selection states are none (empty), all (filled), partial (dash). There are selection icons for each.
2. Selecting the parent will select all children
3. Unselecting the parent will unselect all children
4. Changing the selection of a child will change the state of the parent to partial
5. Selecting a partial parent will make the parent and children selected_
I interpreted 4 as unselecting a child will set parent to partial if there still are additional children selected. Selecting a child when all other children are selected will select parent as well. 
- Added logic to the TableComponent that handles …
> feat(table): improve nested row selections

- packages/react/src/components/DashboardEditor/DashboardEditor.jsx
- packages/react/src/components/DashboardEditor/DashboardEditor.story.jsx
- packages/react/src/components/DashboardEditor/DashboardEditor.test.jsx
- packages/react/src/components/DashboardEditor/__snapshots__/DashboardEditor.story.storyshot
- packages/react/src/components/PageTitleBar/PageTitleBar.jsx
- packages/react/src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Closes #
**Summary**
- There was a pretty serious issue with the DashboardEditor onEditTitle implementation.  Since the DashboardEditor is the component saving the draft state of the template in it's local state, we can't allow the parent component to change the template title or any new draft changes to the template will be lost
- fix(DashboardEditor): don't allow parents to change the title, only allow them to control whether the title is editable or not.   The DashboardEditor needs to change it's local draft state of the template to have the new title
- fix(PageTitleBar): fix the proptype of the PageTitleBar so that it's valid
- Verify the new isEditable DashboardEditor story actually updates the …
> fix(dashboardtemplateeditor): fix approach for editing title

- packages/react/src/components/SideNav/SideNav.jsx
- packages/react/src/components/SideNav/SideNav.story.jsx
- packages/react/src/components/SideNav/__snapshots__/SideNav.story.storyshot
- packages/react/src/components/SuiteHeader/__snapshots__/SuiteHeader.story.storyshot
- packages/react/src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Closes #2352 
**Summary**
- translateById was removed from the carbon SideNav, but we were still passing it.
- comment out translateById and link to comment in carbon about re-adding it at some point
- stop passing `onClickSideNavExpand` to SideNav in SideNav stories
- add i18n prop for for the SideNav aria-label
- the SideNav story should show no warnings in the console
- The SideNav should continue to work as expected
> fix(side-nav): remove bad props from story and component

- packages/react/src/components/DashboardEditor/DashboardEditor.jsx
- packages/react/src/components/DashboardEditor/DashboardEditor.story.jsx
- packages/react/src/components/DashboardEditor/DashboardEditorHeader/__snapshots__/DashboardEditorHeader.story.storyshot
- packages/react/src/components/DashboardEditor/__snapshots__/DashboardEditor.story.storyshot
- packages/react/src/components/FileDrop/__snapshots__/FileDrop.story.storyshot
- packages/react/src/components/ImageCard/__snapshots__/ImageCard.story.storyshot
- packages/react/src/components/List/HierarchyList/__snapshots__/HierarchyList.story.storyshot
- packages/react/src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Closes #
**Summary**
Need to give the consumer the ability to create their own default card configs.
Add `getDefaultCard` prop to editor
Go to the `With get default card` story and see that the card properly renders a custom default config
Make sure that the card configs (found in the json editor modal) are still the correct defaults for mainstream cards.
> Add getDefaultCard prop to editor

- packages/react/src/components/TableCard/TableCard.jsx
- packages/react/src/components/TableCard/TableCard.story.jsx
- packages/react/src/components/TableCard/TableCard.test.jsx
- packages/react/src/components/TableCard/__snapshots__/TableCard.story.storyshot
- packages/react/src/components/TableCard/tableCardUtils.jsx
- packages/react/src/components/TableCard/tableCardUtils.test.jsx
- packages/react/src/components/TileCatalogNew/__snapshots__/TileCatalogNew.story.storyshot
- packages/react/src/components/TimeSeriesCard/__snapshots__/TimeSeriesCard.story.storyshot
- packages/react/src/utils/__tests__/cardUtilityFunctions.test.jsx
- packages/react/src/utils/cardUtilityFunctions.js
**Summary**
- If `cardVariables` was provided to TableCard, row-specific variables were no longer working correctly. This fix splits the two and assumes that all variables within the table rows are row-specific
- Remove the `with links` story in favor of the `row-specific links` story to avoid confusion
- Added a `keysToSkip` argument to `handleCardVariables` and `getCardVariables` to skip over specific keys such as the TableCard `href`
- also sets up the ability to get better and/or fix this issue: https://github.com/carbon-design-system/carbon-addons-iot-react/issues/1527
- Moved all tableCardUtil tests to the tableCardUtils test file
- Added describe blocks to groups of tests based on the same function and/or topic
- Renamed …
> fix(tablecard): allow row-specific and cardVariables prop

- packages/react/src/components/ImageCard/_hotspot.scss
Closes #1806 
**Summary**
- very simple change to replace hex colors with carbon colors. Just cleaning out the backlog...
- The basic image card story should have standard carbon box-shadow and colors, now.
> fix(hotspot): use carbon colors and mixins for hotspot styles

- packages/react/src/components/HotspotEditorModal/DynamicHotspotSourcePicker/DynamicHotspotSourcePicker.story.jsx
- packages/react/src/components/HotspotEditorModal/HotspotEditorDataSourceTab/HotspotEditorDataSourceTab.story.jsx
- packages/react/src/components/HotspotEditorModal/HotspotEditorDataSourceTab/HotspotEditorDataSourceTab.test.jsx
- packages/react/src/components/HotspotEditorModal/HotspotEditorDataSourceTab/__snapshots__/HotspotEditorDataSourceTab.story.storyshot
- packages/react/src/components/HotspotEditorModal/HotspotEditorModal.story.jsx
Closes #2383
**Summary**
Fixed stories that weren't working for HotspotEditorModal and HotspotEditorDataSourceTab 
- Updated stories to include `dataItemId` for the data items.
- Added the HotspotStateHook to the HotspotEditorDataSourceTab and removed the non working onChange functions
- Updated tests to remove warnings about missing required prop
- Renamed incorrectly named story for HotspotEditorDataSourceTab
- Replaced/removed hotspots in the HotspotEditorDataSourceTab story that were using an element as the content prop, something that we currently don't support. I created an issue (#2384) to sort out how such cases should be handled.
1. Go to …
> fix(hotspoteditormodal): fixed broken stories

- packages/react/src/components/TearSheet/TearSheet.story.jsx
- packages/react/src/components/TearSheet/TearSheet.test.jsx
- packages/react/src/components/TearSheet/TearSheetWrapper.jsx
- packages/react/src/components/TearSheet/__snapshots__/TearSheet.story.storyshot
- packages/react/src/components/TearSheet/tear-sheet-wrapper.scss
- packages/react/src/components/TearSheet/tear-sheet.scss
Closes #2403 
**Summary**
Copied from #2390 
**Summary**
- This fixes an issue where if a content were dynamically added to the TearSheet header, the TearSheet content would expand beyond its container and get cropped by the bottom of the viewport.
- Check the component story. I've added buttons on the tear sheets to include additional content to their header. The tear sheet size should be readjusted to prevent it from being cropped.
The tests below can be checked via story
- Check the stack feature (one tear sheet on top of the other) to see if they still behave like before. 
- Check if the tear sheet's whole content is displayed
> fix(tearsheet): make tearsheet layout more dynamic 

- packages/react/src/components/CardEditor/CardEditForm/CardEditFormItems/DataSeriesFormItemModal.jsx
- packages/react/src/components/CardEditor/CardEditForm/CardEditFormItems/DataSeriesFormItemModal.test.jsx
Closes #2393
**Summary**
Adds isLarge prop to DataSeriesFormItemModal. The prop was expected to be present and working by the HotspotEditorDataSourceTab
- Added prop with default false
1. Verify that that the modals in https://deploy-preview-2394--carbon-addons-iot-react.netlify.app?path=/story/2-watson-iot-experimental-☢%EF%B8%8F-hotspoteditormodal-hotspoteditordatasourcetab--with-preset-values are opened as large modals
1. Go to https://deploy-preview-2394--carbon-addons-iot-react.netlify.app?path=/story/2-watson-iot-experimental-%E2%98%A2%EF%B8%8F-cardeditor--for-time-series
2. Click the edit icon for …
> fix(dataseriesformitemmodal): allowed isLarge prop

- packages/react/package.json
- yarn.lock
Manually bumps version on react package after publish actions got jumbled. updates to yarn lock from a previous update that didn't run yarn install after dep changes.
> fix(repo): verison bump to fix publish failures

- packages/react/src/utils/__tests__/cardUtilityFunctions.test.jsx
- packages/react/src/utils/cardUtilityFunctions.js
Closes #2498
**Summary**
`handleCardVariables` was not handling null values.
- Add a check for the target of `replaceVariables` to be !isNil
Hard to recreate. The test should cover it.
Make sure that stories with variables still work.
> fix(card-variables): handle null values in handle-card-variables

- packages/react/src/components/Table/TableHead/ColumnHeaderRow/_column-header-row.scss
- packages/react/src/components/Table/TableHead/_table-head.scss
Closes #2482 
**Summary**
- Improved the column selection button positioning. Column selection button appears at the end and is not visible on the page when table has many columns until its scrolled and hence its usability is missed.
- added flex-wrap to the table-header-label so that column selection button automatically wraps and is visible even when there are many columns.
- Can be tested in storybook https://deploy-preview-2489--carbon-addons-iot-react.netlify.app/?path=/story/1-watson-iot-table-table--with-resize-and-no-initial-columns
> fix(table): wrap the column selection text

- packages/react/src/components/TimeSeriesCard/TimeSeriesCard.jsx
Closes #
It closes a label truncation issue found in a product that uses the `TimeSeriesChart`
**Summary**
`carbon-charts` supports tooltip label truncation settings. If not passed, the default is to chop any characters after the 14th character in the tooltip label. `TimeSeriesChart` was not overriding tooltip truncation settings, so now the truncation type is set to `'none'`, which means that the tooltip label can stretch the tooltip width as much as necessary for all the content to show without any cropping.
Before the change:
After the change:
All unit tests are still passing and and stories are still working.
> fix(timeseriescard): Passing truncation type 'none' to chart tooltip options so that tooltip labels don’t get truncated.

- packages/react/src/components/TimeSeriesCard/timeSeriesUtils.js
…
Closes #
**Summary**
- Tiny bug where if only one datapoint existed in a TimeSeriesCard with a year interval, it totally skipped the x-axis graph tick
- fix(timeSeriesUtils):  for yearly first tick always show a graph tick value
- Verify that timeSeriesCard with one datapoint and year interval shows x-axis tick.
- verify with multiple years of data that it still looks good
> fix(timeseriescard): xaxis format incorrect with one datapoint in year interval

- packages/react/src/components/CardEditor/CardEditForm/CardEditFormItems/ThresholdsFormItem.jsx
- packages/react/src/components/CardEditor/CardEditForm/CardEditFormItems/ThresholdsFormItem.test.jsx
- packages/react/src/components/CardEditor/CardEditForm/CardEditFormItems/__snapshots__/ThresholdsFormItem.story.storyshot
- packages/react/src/components/CardEditor/CardEditForm/_card-edit-form.scss
Closes #2388 
**Summary**
- Allow text input when threshold comparison is set to '='. Previously only allowed number inputs for all comparitors.
- check current comparison operator and use a TextInput if it is '='
- https://deploy-preview-2668--carbon-addons-iot-react.netlify.app/?path=/story/2-watson-iot-experimental-%E2%98%A2%EF%B8%8F-cardeditor-cardeditformitems-thresholdformitem--example-with-initial-values Try input any text in the third threshold in this story. Change the comparison operator to '>' or '<' and ensure strings are not allowed.
- All other changes to the thresholds should be unaffected.
**Things to look …
> feat(theshold-form-item): allow strings when equal comparison

- packages/react/rollup.config.js
Closes #2671 
**Summary**
- After an upgrade to rollup-plugin-copy the css folders were no longer being copied correctly to be included into the build output
- updated the rollup config to copy css from `tmp/lib/css` to `lib/css` and also from `tmp/lib/css` to simply `./css`
- pull down this branch and locally build the project and ensure the css folder is contained in the output
- no other adverse effects to the build process.
> fix(repo): fix copy plugin to include css

- packages/react/src/components/Table/Table.story.jsx
Closes #2294 
**Summary**
- Fixed table story so that tooltips appear correctly in the sticky header story.
- removed no longer needed menuOffset function preventing tooltips from appearing.
- confirmed this behavior matches original behavior (see https://deploy-preview-906--carbon-addons-iot-react.netlify.app/?path=/story/watson-iot-table--with-sticky-header-and-cell-tooltip-calculation)
- tooltips should now appear and scroll with the table in the [sticky header/tooltip table story](https://deploy-preview-2676--carbon-addons-iot-react.netlify.app/?path=/story/1-watson-iot-table-table--with-sticky-header-experimental-and-cell-tooltip-calculation).
**Regression Test (how to make sure this PR doesn't …
> chore(table): fix sticky header/tooltip story so tooltips appear

- packages/react/src/components/IconDropdown/IconDropdown.jsx
- packages/react/src/components/IconDropdown/IconDropdown.test.jsx
Closes #2448 
**Summary**
- There were <button> within <button> warnings when an icon was selected in the IconDropdown. I've changed the output to only display the <button> when the dropdown is open and then the button is rendered in a different location and the warning is avoided. This was marked as a v3 issue, but no changes were necessary to warrant that, so it's being merged into next.
- only show <button> when dropdown is open.
- no <button> in <button> warnings in test output
- IconDropdown stories still function as expected.
> fix(icon-dropdown): fix <button> in <button> warnings

- packages/react/src/components/Table/StatefulTable.story.jsx
- packages/react/src/components/Table/__snapshots__/StatefulTable.story.storyshot
Closes #2291 
**Summary**
- the https://deploy-preview-2677--carbon-addons-iot-react.netlify.app/?path=/story/1-watson-iot-table-statefultable--stateful-example-with-row-nesting-and-fixed-columns story was pulling props from another location that had been changed for another story. It was also missing props to make it work as described. These have been fixed.
- The bad story should be renamed and new props added to make it match the described and implied behavior.
n/a
> chore(stateful-table): fix table story

- packages/react/__mocks__/@carbon/charts-react/bar-chart-grouped.js
- packages/react/__mocks__/@carbon/charts-react/bar-chart-simple.js
- packages/react/__mocks__/@carbon/charts-react/bar-chart-stacked.js
- packages/react/__mocks__/@carbon/charts-react/combo-chart.js
- packages/react/__mocks__/@carbon/charts-react/line-chart.js
- packages/react/__mocks__/@carbon/charts-react/pie-chart.js
- packages/react/src/components/TimeSeriesCard/TimeSeriesCard.jsx
Closes #2453 
**Summary**
- Testing output was throwing a "Functional components can not be given refs" error when using TimeSeriesCard. This PR fixes it by wrapping the mocked charts with React.forwardRef. This ended up not being a v3 change, so basing it against next.
- add React.forwardRef calls to all mocked carbon charts
- fix useRef references in TimeSeriesCard
- No testing noise when testing TimeSeriesCard (except for testID prop deprecation notices)
- all TimeSeriesCard tests still pass and [stories](https://deploy-preview-2678--carbon-addons-iot-react.netlify.app/?path=/story/1-watson-iot-timeseriescard--multi-line …
> fix(time-series-card): fix refs in mocks for test output

- packages/react/src/components/Table/Table.story.jsx
- packages/react/src/components/Table/TableBody/TableBodyRow/TableBodyRow.jsx
- packages/react/src/components/Table/TableCellRenderer/TableCellRenderer.jsx
- packages/react/src/components/Table/TableCellRenderer/TableCellRenderer.test.jsx
- packages/react/src/components/Table/TablePropTypes.js
- packages/react/src/components/Table/TableSaveViewModal/__snapshots__/TableSaveViewModal.story.storyshot
- packages/react/src/components/Table/__snapshots__/StatefulTable.story.storyshot
- packages/react/src/components/Table/__snapshots__/Table.story.storyshot
- packages/react/src/components/TileGallery/__snapshots__/TileGallery.story.storyshot
Closes #1613 
**Summary**
Objects can now be passed as data values.
- Updates the prop-types to allow objects to be passed as data values for columns
- Throws warnings if objects are passed without a renderDataFunction
- Throws warnings if the column is sortable and objects are passed as data without a sortFunction
- Throws warnings if the column is filterable and objects are passed as data without a filterFunction
- adds tests to confirm these cases
- The table stories now all show an Object Id column. This is the ID pulled from the object via the renderDataFunction.
- All table stories work as expected.
**Things to look …
> feat(table): allow objects to be passed as data

- packages/react/src/components/Header/Header.test.jsx
- packages/react/src/components/Header/HeaderAction/HeaderActionMenu.jsx
- packages/react/src/components/Header/HeaderAction/__snapshots__/HeaderActionMenu.test.jsx.snap
- packages/react/src/components/Header/__snapshots__/Header.story.storyshot
- packages/react/src/components/Header/__snapshots__/Header.test.jsx.snap
- packages/react/src/components/SuiteHeader/SuiteHeader.jsx
- packages/react/src/components/SuiteHeader/SuiteHeader.story.jsx
- packages/react/src/components/SuiteHeader/SuiteHeaderAppSwitcher/SuiteHeaderAppSwitcher.jsx
- packages/react/src/components/SuiteHeader/SuiteHeaderAppSwitcher/__snapshots__/SuiteHeaderAppSwitcher.story.storyshot
- packages/react/src/components/SuiteHeader/__snapshots__/SuiteHeader.story.storyshot
Closes #2450 
**Summary**
- This is being merged into the v3 branch b/c it contains breaking changes.
- SuiteHeader/Header were using `javascript:void(0)` urls in many places. This replaces those with `#` and event.preventDefault() in the click handlers.
- There were also many testing error output causes by <a> within <a> tags, and those were also fixed in this PR. I'll create another issue and backport those changes and make a PR for them into next. 
- replace all instances of `javascript:void(0)` with `#`
- add event.preventDefault() to all click handlers in SuiteHeader
- fix <a> within <a> test errors by using <button> tags in headerPanel.content props.
- no test error outputs for …
> fix(suite-header): no javascript urls in links, fix testing output errors

- packages/react/src/components/Table/Table.story.jsx
- packages/react/src/components/Table/TableHead/TableHead.jsx
- packages/react/src/components/Table/TableHead/TableHead.test.jsx
- packages/react/src/components/Table/TableHead/columnWidthUtilityFunctions.js
Closes #2317
**Summary**
Added fixes to make sure column resize always work after _all_ columns have been hidden. I identified two different scenarios with different solutions that we should verify. Resorting to use min-width as fallback when column widths are missing is not perfect but since this is bit of an edge case I think it is okay.
I kept the code changes isolated to the old resize code since the new behaviour `preserveColumnWidths` did not have these problems. 
* Added fix to `TableHead` and `columnWidthUtilityFunctions.js`
* Added unit tests corresponding two the scenarios
* Added small fix to the story so that knob value "Stateful Table" works as expected
**Scenario 1**
Go to …
> 2317 table column resize fails after all columns have been hidden

- packages/react/src/components/FilterTags/FilterTags.jsx
Closes #2449 
**Summary**
- Forces the overflow item to be an <a> tag to prevent <button> within <button> errors in FilterTags with overflow
- this is considered a breaking changes and is being merged into v3
- overflow items in FilterTags now use a tags
- no <button> within <button> warnings when testing FilterTags
- FilterTag stories still function as expected.
> fix(filter-tags): force <a> tags in overflow menu

- packages/react/src/components/DateTimePicker/DateTimePicker.jsx
Closes #2771 
**Summary**
- DateTimePicker wasn't waiting until the user had finished typing to parse times, so it was throwing invalid dates.
- don't parse absolute times until 5 characters have been typed.
- Open DateTimePicker default story
- Click Custom Range
- click Absolute
- Click two dates (same and different)
- Click the Start time input
- Backspace to clear the box and type a time
- tab to the End time input
- type an end time
- click apply
- The correct chosen date should be visible
- no adverse side-effects for absolute dates.
> fix(date-time-picker): wait until finished typing to parse dates

- packages/react/src/components/SideNav/_side-nav.scss
Closes #2740 
**Summary**
- adds a 300ms delay on the opening transition of the SideNav on hover
- SideNav should not open immediately on hover, but have a slight delay where the mouse needs to rest on it for a moment
- no adverse effects.
> fix(side-nav): add slight delay on hover open transition

- packages/react/src/components/Table/_table.scss
- packages/react/src/components/TableCard/TableCard.story.jsx
Closes #2628 
**Summary**
- used some css wizardry to adjust the padding of the empty-state in medium sized TableCards to make it fit. 
- **Still leaves the question if we need to adjust to PropTypes to allow medium sized TableCards without a warning**
- css only fix for padding
- Empty-State should fit into a MEDIUM/MEDIUMWIDE TableCard now. 
- Check the `with multiple actions` TableCard story, set the 'no data' knob, and change to a MEDIUM/MEDIUMWIDE card
- no adverse EmptyState style changes
> fix(table-card): adjust padding on empty state for medium cards

- packages/react/src/components/SideNav/SideNav.story.jsx
- packages/react/src/components/SideNav/__snapshots__/SideNav.story.storyshot
- packages/react/src/components/Table/TableSaveViewModal/__snapshots__/TableSaveViewModal.story.storyshot
- packages/react/src/components/TileGallery/__snapshots__/TileGallery.story.storyshot
Closes #2645 
**Summary**
It is not a blue border of the "selected current" that we see in the scenario described by the issue. The component in the story is stateless so there is no "selection" taking place when a SideNavMenuItem is clicked. Instead the button inside the clicked SideNavMenuItem gets the focus and activates `.bx--side-nav__link:focus` which is not the same as `bx--side-nav__link--current` although they use the same styling. 
In a scenario where there is a managed state for a SideNav component this problem does not exist, so I created a story that shows this. 
Note that if a user expands a menu group and moves the mouse away without selecting a menu item the group will remain expanded when the Navbar is collapsed again. 
- …
> fix(sidenav): added stateful example in storybook

- packages/react/src/components/Dashboard/__snapshots__/Dashboard.story.storyshot
- packages/react/src/components/Table/__snapshots__/StatefulTable.story.storyshot
- packages/react/src/components/Table/__snapshots__/Table.story.storyshot
- packages/react/src/internal/FullWidthWrapper.jsx
Closes #2470 
**Summary**
- correctly applies FullWidthStyles to all children except DeprecationNotice.
- Table Example with Create & Save Views story should now have full-width styles applied.
- confirm FullWidthStyles are not applied to DeprecationNotices
> fix(internal): fix FullWidthWrapper to use correct styles

- packages/react/src/components/List/SimpleList/SimpleList.jsx
- packages/react/src/components/List/SimpleList/SimpleList.story.jsx
- packages/react/src/components/List/SimpleList/SimpleList.test.e2e.jsx
- packages/react/src/components/List/SimpleList/SimpleList.test.jsx
Closes #2316 
**Summary**
Previously, the whole list needed to be thrown out when any props changed, but now I've added useEffects to update the state as new items are passed or as pageSize change, for example. It should maintain the previous state, so if you were on Page 2 and new items are added you'll stay on Page 2, but if items are removed you'll reset back to page 1. If you previously had a search value and you add more items the search value will be maintained.
- added useEffects to update state when items or pagination props change
- added new tests to cover all this functionality and increase coverage even more
- Open the Basic SimpleList story
- change the number of items rendering to 10
- …
> fix(simple-list): update state properly when external props change

- packages/react/src/components/Table/_table.scss
Closes #2792 
**Summary**
- ~~Unfortunately, I cannot recreate the error in this issue. I rolled back to node-sass 4.14, but existing code still compiles in the test app. I'm making this case change suggested by @davidicus.~~
- node-sass 4.14.1 fails to compile `max`, but by changing it to uppercase `Max` it knows it's a css function and compiles fine.
- change case to force sass to use the css version of `max`
- follow the instructions in [this PR](https://github.com/carbon-design-system/carbon-addons-iot-react/pull/2775) to build a local version of the library, but use `node-sass@4.14.1` to build sass in the consuming application. …
> fix(empty-state): node-sass build errors with `max`

- packages/react/jest.config.js
- packages/react/src/components/Table/tableReducer.test.jsx
Closes #2803
**Summary**
Improved testing coverage for baseTableReducer
- tests here
- tests here
> test(basetablereducer): improved unit testing coverage

- packages/react/src/components/Dashboard/__snapshots__/Dashboard.story.storyshot
- packages/react/src/components/Dashboard/__snapshots__/DashboardGrid.story.storyshot
- packages/react/src/components/DashboardEditor/__snapshots__/DashboardEditor.story.storyshot
- packages/react/src/components/ValueCard/Attribute.jsx
- packages/react/src/components/ValueCard/ValueCard.jsx
- packages/react/src/components/ValueCard/ValueCard.story.jsx
- packages/react/src/components/ValueCard/ValueCard.test.jsx
- packages/react/src/components/ValueCard/ValueRenderer.jsx
- packages/react/src/components/ValueCard/ValueRenderer.test.jsx
- packages/react/src/components/ValueCard/__snapshots__/ValueCard.story.storyshot
- packages/react/src/components/ValueCard/_value-renderer.scss
- packages/react/src/constants/CardPropTypes.js
- packages/react/src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Closes #2376 
**Summary**
- Adds an `onAttributeClick` callback to the ValueCards. This gets passed down to each attribute on the card, and when the attribute is clicked it returns an object with the value and the dataSourceId.
- add onAttributeClick to ValueCard
- update stories with actions
- add tests coverage
- fix style differences between span/button tags
- The ValueCard stories should now have an `onAttributeClick` action that gets called when the value is clicked
- The stories with the callback should have blue text (unless a different color was supplied in the props)
- The styles of next/deploypreview should match …
> feat(value-card): add onAttributeClick callback 

- packages/react/src/components/Table/StatefulTable.test.jsx
- packages/react/src/components/Table/Table.jsx
- packages/react/src/components/Table/Table.story.jsx
- packages/react/src/components/Table/Table.test.jsx
- packages/react/src/components/Table/TableSaveViewModal/__snapshots__/TableSaveViewModal.story.storyshot
- packages/react/src/components/Table/TableSkeletonWithHeaders/TableSkeletonWithHeaders.jsx
- packages/react/src/components/Table/TableSkeletonWithHeaders/_table-skeleton-with-headers.scss
- packages/react/src/components/Table/__snapshots__/Table.story.storyshot
- packages/react/src/components/Table/tableReducer.js
- packages/react/src/components/TileCatalogNew/__snapshots__/TileCatalogNew.story.storyshot
- packages/react/src/components/TileGallery/__snapshots__/TileGallery.story.storyshot
- packages/react/src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Closes #2436 
**Summary**
Previously the isLoading prop only effected the rows, but the header would still display and show columns. This PR allows columns to be an empty array and the isLoading prop will loading skeleton text in place of the column headers. It's customizable via a prop to load X number of columns just like rows.
- added new PropTypes to have loadable columns
- changed `<TableHead>` to only display when the columns array isn't empty.
- changed the `<TableSkeletonWithHeaders>` to match the styles of the `<TableHead>` if no columns are passed and show skeleton text as a placeholder while loading
- add tests cases for both Table/StatefulTable
- added new story to simulate async loading of both columns and data
- updated …
> feat(table): allow lazy-loading of columns

- packages/react/package.json
Closes #2260 
**Summary**
- We were using the `lib` build instead of the `es` build in the browser property of `package.json`. This was forcing everything to be included and breaking tree shaking. The test app was 8.08MB when built and analyzed in its current state, but after the es switch it dropped to 2.1MB. 
- change browser package to use es build
1. Pull this branch down locally
2. create a new directory to hold the built project ie: `mkdir -p ~/tmp/pal-build`
3. run `yarn build`
4. copy built files to project directory created above: `cp -rf package.json umd scss lib es css ~/tmp/pal-build`
5. move to a fresh directory
6. create a test app: `npx create-iot-react-app pal-test`
7. cd into the …
> fix(repo): use es build instead of lib in browser

- packages/react/jest.config.js
- packages/react/package.json
- packages/react/src/components/Table/tableReducer.js
- packages/react/src/components/Table/tableReducer.test.jsx
Closes #2802 
**Summary**
Improved test coverage
- Wrote more tests
- Removed threshold exception for the table reducers
- fix small issue in TABLE_ADVANCED_FILTER_CANCEL
- Unit tests are passing
- tests here
> 2802 table reducer improve test coverage

- packages/react/src/components/Table/Table.jsx
- packages/react/src/components/Table/Table.test.jsx
- packages/react/src/components/Table/TableBody/TableBody.jsx
- packages/react/src/components/Table/TableBody/TableBodyRow/TableBodyRow.jsx
- packages/react/src/components/Table/TableBody/TableBodyRow/TableBodyRow.story.jsx
- packages/react/src/components/Table/TableCellRenderer/TableCellRenderer.jsx
- packages/react/src/components/Table/TableCellRenderer/TableCellRenderer.test.jsx
- packages/react/src/components/Table/TableHead/TableHead.jsx
- packages/react/src/components/Table/TablePropTypes.js
Closes #1652 
**Summary**
The wrap and truncate code and unit tests were refactored as part of PR 1645 but we decided to move the refactoring into a separate issue and add it to the next major release in order to mitigate the risk of regressions. 
* Removed internal props  `wrapCellText` and `truncateCellText` and replaced with `cellTextOverflow`
* Lifted logic from the subcomponents to the table 
* Removed superfluous and old unit tests that were based on checking the presence of prop values
- Verify that the external `wrapCellText` prop still work as expected for the tables
- Verify that the external `wrapCellText` prop …
> refactor(table): refactor wrap truncate code

- packages/react/src/components/Table/Table.test.jsx
- packages/react/src/components/Table/TableBody/RowActionsCell/RowActionsCell.jsx
- packages/react/src/components/Table/TableBody/RowActionsCell/RowActionsCell.test.jsx
- packages/react/src/components/Table/TableHead/TableHead.jsx
- packages/react/src/components/Table/TableHead/TableHead.test.jsx
- packages/react/src/components/Table/TableToolbar/TableToolbar.jsx
Closes #2644 
**Summary**
- adds data-testids to overflow menus in the TableRows, TableHead, and TableToolbar
- adds data-testids to overflow menus in the TableRows, TableHead, and TableToolbar
- tests pass
- no inadvertent removals/changes of testids.
> chore(table): add testids to overflow menus in table

- packages/react/src/components/DateTimePicker/DateTimePicker.jsx
- packages/react/src/components/DateTimePicker/DateTimePicker.test.jsx
Closes #2832
**Summary**
Fix to disabled the apply button when the "last" NumberInput in relative dates is invalid.
- Added check for invalid date and a state to use it 
1. Got story ?path=/story/1-watson-iot-datetime-picker--default
2. Expand DateTimePicker component
3. Click Custom Range
4. Make sure Relative Radio is checked
5. Input an invalid number in the number-input, e.g. empty or minus, plus
6. Verify that the apply button is disabled
7. Change to Custom range: Absolute and verify that the apply button is enabled 
8. Click "Back" and verify that the button is enabled when not in custom range mode …
> fix(datetimepicker): disable apply for invalid values

- packages/react/src/components/ComboBox/_combo-box.scss
- packages/react/src/components/PageTitleBar/_page-title-bar.scss
Closes #2314 
**Summary**
- When using `@console/pal` themes along side `carbon-addons-iot-react` it enables certain feature flags that break webpack builds with OptimizeCSSAssetsPlugin. This adjusts the scss to work correctly in this instance.
- refactor scss variables to prevent failures in building
- Can build production builds of the test app when using `@console/pal` package theme, and `combo-box.scss` as detailed in the issue. Instructions for installing `@console/pal` are found in the issue as well. For steps to setup a test app see https://github.com/carbon-design-system/carbon-addons-iot-react/pull/2775
- ComboBox …
> fix(combo-box): fix scss to not break OptimizeCSSAssets webpack plugin

- packages/react/src/components/Table/Table.jsx
- packages/react/src/components/Table/TablePropTypes.js
- packages/react/src/components/Table/TableToolbar/TableToolbar.jsx
- packages/react/src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Closes #2607
**Summary**
- Allows TableToolbar to send aria-label to the underlying carbon-component.
- Add `toolbarLabelAria` to `Table`'s `i18n` prop and forwards it to `TableToolbar`
- `TableToolbar` now pull `toolbarLabelAria` out of `i18n` to pass to the underlying carbon-component
- snapshots
- Table still Renders
- TableToolbar still Renders
> fix(tabletoolbar): provide aria-label to CarbonTableToolbar

- packages/react/src/components/SuiteHeader/SuiteHeader.jsx
- packages/react/src/components/SuiteHeader/SuiteHeader.mdx
- packages/react/src/components/SuiteHeader/SuiteHeader.test.jsx
- packages/react/src/components/SuiteHeader/SuiteHeaderAppSwitcher/SuiteHeaderAppSwitcher.jsx
Closes #2852 
**Summary**
- Makes it possible to open SuiteHeader links by holding cmd+click or ctrl+click.
- Adds cmd+click / ctrl+click checking to all built-in SuiteHeader links
- Updates docs to make to more clear how this behavior can be controlled on the application side
- added tests for coverage
- holding cmd+click (mac) or ctrl+click (win) should open all SuiteHeader links (Administation, Manage Profile, Help, All Applications, Monitor, Health, etc) in a new window.
- links still open in same window when not hold ctrl or cmd.
> fix(suite-header): all cmd+click/ctrl+click to open new window

- packages/react/src/components/Card/__snapshots__/Card.story.storyshot
- packages/react/src/components/Dashboard/__snapshots__/Dashboard.story.storyshot
- packages/react/src/components/Dashboard/__snapshots__/DashboardGrid.story.storyshot
- packages/react/src/components/DashboardEditor/__snapshots__/DashboardEditor.story.storyshot
- packages/react/src/components/RuleBuilder/__snapshots__/RuleBuilder.story.storyshot
- packages/react/src/components/Table/Table.jsx
- packages/react/src/components/Table/TablePropTypes.js
- packages/react/src/components/Table/TableToolbar/TableToolbar.jsx
- packages/react/src/components/Table/__snapshots__/StatefulTable.story.storyshot
- packages/react/src/components/Table/__snapshots__/Table.story.storyshot
- packages/react/src/components/TableCard/__snapshots__/TableCard.story.storyshot
- packages/react/src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Closes #2607
See #2860
**Summary**
Previously, aria-label could not be specified on TableToolbar, letting Carbon's TableToolbar default it to 'data table toolbar'
This the label should be unqiue, but with multiple Tables with toolbars, it would only ever be 'data table toolbar'
BREAKING CHANGE: TableToolbar with secondaryTitle will now default to using secondaryTitle in the aria-label.
To mitigate this change: set i18n.toolbarLabelAria to "data table toolbar"
This change allows aria-label be be specified via the i18n prop as toolbarLabelAria
If secondaryTitle is used and no i18n.toolbarLabelAria is specified, it will default to using secondaryTitle within aria-label (appending ' Toolbar')
If no secondaryTitle nor i18n.toolbarLabelAria is …
> fix(suite-header): replace javascript urls

- packages/react/src/components/Dashboard/__snapshots__/Dashboard.story.storyshot
- packages/react/src/components/Dashboard/__snapshots__/DashboardGrid.story.storyshot
- packages/react/src/components/ValueCard/Attribute.jsx
- packages/react/src/components/ValueCard/Attribute.test.jsx
- packages/react/src/components/ValueCard/ValueCard.test.jsx
- packages/react/src/components/ValueCard/__snapshots__/ValueCard.story.storyshot
- packages/react/src/components/ValueCard/_attribute.scss
Closes #2377
**Summary**
- The secondary-value-color in ValueCard should be grey(#6F6F6F), instead of the color of the ^ indicator.
- The indicator color when not specified will be display in #6F6F6F color.
- Font size of the secondary value is updated based on design https://ibm.invisionapp.com/d/main/#/console/15373465/319977464 
- Changes done to Attribute component for secondary-value-color and font size changes in ValueCard.
- Go to /?path=/story/1-watson-iot-valuecard--with-trends and verify that the secondary value is displayed in grey(#6F6F6F) whereas the trend indicator icon is displayed in the color as specified in the knob- content.attributes[0].secondaryValue.color
**Regression Test (how …
> style(valuecard): trend text should be grey instead of indicator color

- packages/react/src/components/Table/StatefulTable.story.jsx
- packages/react/src/components/Table/Table.jsx
- packages/react/src/components/Table/TableFoot/TableFoot.jsx
- packages/react/src/components/Table/TableFoot/TableFoot.test.jsx
- packages/react/src/components/Table/__snapshots__/StatefulTable.story.storyshot
- packages/react/src/components/Table/__snapshots__/Table.story.storyshot
Closes #2859 
**Summary**
- When using multiselect and nested rows at the same time, the aggregation label was in the wrong place. This fixes that by using colspan to position the label based on various prop combinations.
- use colspan instead of cells to position label
- Go to [`basic dumb table` story](https://deploy-preview-2898--carbon-addons-iot-react.netlify.app/?path=/story/1-watson-iot-table-table--basic-dumb-table)
- turn on pagination
- experiment with all combinations of `hasRowNesting`, `hasRowExpansion`, and `hasRowSelection`. The 'Total' label should also be aligned with the pagination below. …
> fix(table): aggregation column placement

- packages/react/src/components/PageTitleBar/PageTItleBar.test.e2e.jsx
Closes #2909
**Summary**
- update e2e test to account for minor precision differences in PageTitleBar scroll checking.
- round scroll check to tenths place.
- test pass
- n/a
> fix(page-title-bar): chrome upgrade(?) causes cypress test to fail

- packages/react/src/components/DateTimePicker/DateTimePicker.jsx
- packages/react/src/components/DateTimePicker/DateTimePicker.test.e2e.jsx
- packages/react/src/components/DateTimePicker/DateTimePicker.test.jsx
- packages/react/src/components/DateTimePicker/DateTimePickerV2.jsx
- packages/react/src/components/DateTimePicker/DateTimePickerV2.test.e2e.jsx
- packages/react/src/components/DateTimePicker/DateTimePickerV2.test.jsx
- packages/react/src/components/DateTimePicker/_date-time-picker.scss
- packages/react/src/components/DateTimePicker/_date-time-pickerv2.scss
- packages/react/src/components/TimePickerSpinner/TimePickerSpinner.jsx
- packages/react/src/components/TimePickerSpinner/TimePickerSpinner.story.jsx
- packages/react/src/components/TimePickerSpinner/TimePickerSpinner.test.jsx
- packages/react/src/components/TimePickerSpinner/__snapshots__/TimePickerSpinner.story.storyshot
- packages/react/src/components/TimePickerSpinner/_time-picker-spinner.scss
- packages/react/src/constants/KeyCodeConstants.js
- packages/react/src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Closes #2839 
Improved keyboard input and added a validation state to the onChangeCallback for the TimePickerSpinner.
It turned our that completely preventing all illegal input without crippling the normal UX (text selection, cut, paste, tab focus etc) would be near impossible. So I made the TimePickerSpinner play well with the invalid prop and added the calculated validation result to the onChange callback so that it could be lifted to the parent component. Hence this is an optional built-in validation that still allow for external validation, or none, to be used.
TimePickerSpinner
- added validation and adjusted scss
- kept a small part of the initial effort in preventing invalid input, i.e. to only allow numbers and one colon
- fixed old …
> 2839 time picker spinner improved keyboard input and added error state

- packages/react/src/components/Table/Table.jsx
- packages/react/src/components/Table/Table.test.jsx
- packages/react/src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Closes #2895 
**Summary**
- Added the old table size props and a deprecation warning for them
- add deprecated props and warning
- tests pass
- table still functions as expected
> fix(table): add deprecated table size props and warning

- packages/react/src/components/DateTimePicker/DateTimePicker.jsx
- packages/react/src/components/DateTimePicker/DateTimePicker.test.e2e.jsx
- packages/react/src/components/DateTimePicker/DateTimePicker.test.jsx
- packages/react/src/components/DateTimePicker/DateTimePickerV2.jsx
- packages/react/src/components/DateTimePicker/DateTimePickerV2.test.e2e.jsx
Closes #3007 
**Summary**
- Fixes an issue where changing the month in the DateTimePicker when picking an absolute range would cause it to not show the correct month and lead to a confusing experience.
- added checks to call flatpickr's `jumpToDate` function when selecting dates
- added tests to confirm for both DateTimePicker and DateTimePickerV2
- go to https://deploy-preview-3015--carbon-addons-iot-react.netlify.app/?path=/story/1-watson-iot-datetime-picker--default
- Click "Last 30 minutes"
- Click "Custom Range"
- Click "Absolute"
- Click "Back arrow" to go back to a previous month
- Choose a date -- The month should still be the same month you were in...
- Click "Forward arrow" to go forward to …
> fix(date-time-picker): allow selecting ranges across months

- packages/react/src/utils/dayjs.js
Closes #3032 
**Summary**
- wraps all the locales in an object of functions and calls them all explicitly to be loaded. Additionally, this approach can be modified to export this function and allow consumers to call it and pass an array of locales that they want loaded.
- changes dayjs locale import process
- test app builds and all locales are available and working
- confirm this method also works in codesandbox https://codesandbox.io/s/wonderful-resonance-b7qo0?file=/src/App.js
- locales still work for consuming apps
> fix(day-js): different method of importing locales

- packages/react/src/components/Table/Table.jsx
- packages/react/src/components/Table/Table.story.jsx
- packages/react/src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Closes #2434
**Summary**
- cleans up the state management of aggregations that was in the basic table.
- add onToggleAggregations callback to actions/defaults.
- remove all the useEffects, useStates, etc
- table should no longer automatically manage state for aggregations, but the user should supply the `isHidden` prop to toggle it on/off.
- this is a breaking change for v3.
> fix(table): remove state management of aggregations from table component

- packages/react/src/components/Table/Table.story.jsx
- packages/react/src/components/Table/tableReducer.js
- packages/react/src/components/Table/tableReducer.test.jsx
Closes #2985 
**Summary**
- updates the reducer for the StatefulTable to properly handle changes to rowActions or activeBar.
- update rowEdit example story to be able to choose StatefulTable
- fix StatefulTable reducer to handle changes to rowActions
- go to [Table with full rowEdit example story](https://deploy-preview-3018--carbon-addons-iot-react.netlify.app/?path=/story/1-watson-iot-table-table--basic-table-with-full-row-edit-example)
- change to StatefulTable
- edit various single rows and save and/or cancel
- rows should flip from editable to normal state
- data should be updated correctly on save
- repeat using the full table edit button in the top toolbar
**Regression …
> fix(stateful-table): update reducer for rowEdit actions

- packages/react/src/components/List/List.story.jsx
Closes #2949 
**Summary**
- fixes the clear search `x` by properly checking the state of the value returned in the onChange handler. Since the `List` is stateless, this is just an error in the story not an issue with the component.
- fix story
- Go to [list with search story](https://deploy-preview-3019--carbon-addons-iot-react.netlify.app/?path=/story/1-watson-iot-list--basic-single-column-with-search)
- type `a`
- click `x` to clear search
- ensure list resets
- n/a
> fix(list-story): fix clearing search in story

- packages/react/src/components/Table/StatefulTable.test.jsx
- packages/react/src/components/Table/Table.story.jsx
- packages/react/src/components/Table/Table.test.jsx
- packages/react/src/components/Table/__snapshots__/Table.story.storyshot
Closes #2962 
**Summary**
- removes extraneous uses of isSortable in stories/tests where not appropriate.
- updated stories, tests, snapshots
- isSortable should not appear as knobs in stories
- or in tests except where necessary
- n/a
> chore(table): remove isSortable prop where inappropriate

- packages/react/src/components/Table/StatefulTable.story.jsx
- packages/react/src/components/Table/tableReducer.js
- packages/react/src/components/Table/tableReducer.test.jsx
Closes #2971 
**Summary**
- Fixes the StatefulTable reducer to update the current page in situations where the number of data items is less than what the currently selected page is able to display
- add knob to stateful table example story to display `n` number of items
- update reducer to check current page against number of items and pageSize
- on the [StatefulTable example story](https://deploy-preview-3022--carbon-addons-iot-react.netlify.app/?path=/story/1-watson-iot-table-statefultable--simple-stateful-example)
- turn on pagination
- change to page 3
- change number of items to 5
- check that page reset to page 1
- repeat with various combinations of pageSize, page, and …
> fix(stateful-table): handle resetting pagination when necessary

- packages/react/src/components/List/HierarchyList/HierarchyList.story.jsx
- packages/react/src/components/List/HierarchyList/__snapshots__/HierarchyList.story.storyshot
- packages/react/src/components/List/ListItem/_list-item.scss
Closes #2939 
**Summary**
- small style fix to prevent the flexbox from creeping up in size and causing the secondaryValue to be out of alignment
- add min-width to css
- in the [HierarchyList with large number of items story](https://deploy-preview-3024--carbon-addons-iot-react.netlify.app/?path=/story/1-watson-iot-hierarchylist--with-large-number-of-items)
- item 10 secondary value should be aligned and overflow with ellipsis
- item 20 primary value should be aligned and overflow with ellipsis
- scan List stories to make sure it doesn't cause adverse effects
> fix(list): fix styles to keep secondaryValue aligned when overflowing

- .github/workflows/update-v3.yml
Closes #2969 
**Summary**
- first attempt at automating the creation of a PR to merge `next` into `v3`, each time `next` is updated. This helps prevent massive PRs and keeps `v3` up-to-date automatically. The problem is there's no good way to test this without doing it live that I'm aware of. 😕 
- add new github action for creating a PR to merge next into v3.
- when an update is made to next, a new PR to merge next into v3 should be created.
- all other actions proceed as expected.
> chore(repo): initial action for updating `v3` on `next` changes

- packages/react/src/components/ComboBox/ComboBox.jsx
- packages/react/src/components/Table/StatefulTable.story.jsx
- packages/react/src/components/Table/TableHead/FilterHeaderRow/FilterHeaderRow.jsx
- packages/react/src/components/Table/TableHead/FilterHeaderRow/FilterHeaderRow.test.jsx
- packages/react/src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Closes #1340 
**Summary**
- adds refs to the FilterHeaderRow to apply focus to the first column when the FilterHeaderRow opens
- adds forwardRef to ComboBox
- adds refs to FilterHeaderRow items
- checks type of first filterable column and focuses on it
- open StatefulTable example
- turn on hasColumnSelection and hasFilter
- open filter row
- String column should be focused
- open column selection and move "Status" column to first position
- open Filters
- String column should still be focused
- Repeat moving Select column to first position
- Repeat moving Select column to first position and toggle "force MultiSelect filter" knob to true …
> feat(table): focus on first filterable column when filter row opened

- packages/react/src/components/List/HierarchyList/HierarchyList.jsx
- packages/react/src/components/List/HierarchyList/HierarchyList.story.jsx
- packages/react/src/components/List/HierarchyList/HierarchyList.test.jsx
Closes #1849 
**Summary**
- resets the pagination and search props when the data in the list changes
- add resets to useEffect when data changes
- add knob to large list story to show in storybook
- go to the hierarchylist with large list story
- search for '5'
- go to the next page
- change number of items knob
- HierarchyList should reset back to no search and page 1
- confirm other HierarchyList stories are unaffected
> fix(hierarchy-list): reset pagination and search when data changes

- packages/react/src/components/Table/StatefulTable.story.jsx
- packages/react/src/components/Table/TableCellRenderer/TableCellRenderer.jsx
- packages/react/src/components/Table/TableCellRenderer/TableCellRenderer.test.jsx
- packages/react/src/components/Table/__snapshots__/StatefulTable.story.storyshot
Closes #2937 
**Summary**
- We had previously added definition tooltips to column headers, but there was a minor issue of the native browser title appearing on hover. This fixes that and adds some test cases.
- set `title` prop to undefined when using tooltips in column headers
- add test cases
- remove old enzyme test
- add long text block example to Stateful example story
- ensure native browser tooltip doesn't appear when hovering over a tooltip title in column headers
- ensure titles still work without tooltips
- tooltips still function as expected
> fix(table): don't display native title when using tooltip in header

- packages/react/src/components/Table/TableBody/RowActionsCell/_row-actions-cell.scss
Closes #3014 
**Summary**
- updates CSS to fix artifacting from background gradient on overflow items when rowAction overflow menus are open
- css changes
- go to [StatefulTable with row actions story](https://deploy-preview-3030--carbon-addons-iot-react.netlify.app/?path=/story/1-watson-iot-table-statefultable--stateful-example-with-row-nesting-and-fixed-columns)
- hover first row
- click rowActions overflow menu
- move mouse off of row
- confirm there is no transition of a separate background gradient, but only that of the row
- n/a
> fix(table): fix background gradient artifacting on rowActions open

- packages/react/src/components/OverflowMenu/_overflow-menu.scss
- packages/react/src/components/Table/TableBody/RowActionsCell/RowActionsCell.jsx
- packages/react/src/hooks/usePopoverPositioning.jsx
Closes #3013 #1885 
**Summary**
- The small spacer tab in the overflow menu wasn't quite long enough to fill the space leaving a small gap. This fixes that.
- increase width of spacer tab to match button width
- Go to [StatefulTable with row action](https://deploy-preview-3031--carbon-addons-iot-react.netlify.app/?path=/story/1-watson-iot-table-statefultable--stateful-example-with-expansion-max-pages-and-column-resize) or [OverflowMenu stories](https://deploy-preview-3031--carbon-addons-iot-react.netlify.app/?path=/story/1-watson-iot-overflowmenu--basic)
- open the overflow menu
- the spacer tab should match the width of the button …
> fix(overflow-menu): increase width of the spacer to match button width

- packages/react/src/components/OverflowMenu/_overflow-menu.scss
- packages/react/src/components/PageTitleBar/PageTItleBar.test.e2e.jsx
- packages/react/src/components/PageTitleBar/_page-title-bar.scss
Closes #3012 
**Summary**
- fixes the max height for a couple situations with the PageTitleBar
- fix max height of base breadcrumbs
- fix max height of condensed mode
- fix max height of dynamic mode
- check the [base story](https://deploy-preview-3033--carbon-addons-iot-react.netlify.app/?path=/story/1-watson-iot-pagetitlebar--base) and confirm the breadcrumbs are 32px tall (include padding)
- check the [with dynamic breadcrumbs actions and content story](https://deploy-preview-3033--carbon-addons-iot-react.netlify.app/?path=/story/1-watson-iot-pagetitlebar--with-dynamic-scrolling)
- scroll down to condense the header, confirm it's 40px tall and the buttons are even with the bottom
- check the …
> fix(page-title-bar): fix header top margin and height in condensed mode

- packages/react/src/components/CardEditor/CardEditForm/_card-edit-form.scss
Closes #3052 
**Summary**
- increases the max-width on the threshold items
- increased max-width
- confirm the [card edit form items](https://deploy-preview-3060--carbon-addons-iot-react.netlify.app/?path=/story/2-watson-iot-experimental-%E2%98%A2%EF%B8%8F-cardeditor-cardeditformitems-thresholdformitem--example-with-initial-values) have the proper width
- n/a
> fix(card-edit-form): fix threshold dropdown width

- packages/react/src/components/List/ListItem/_list-item.scss
Closes #3051 
**Summary**
- adjusts css for simple lists with large rows, secondary values, and actions.
- change white-space and width css properties
- secondary values should not be cut off in [this story](https://deploy-preview-3061--carbon-addons-iot-react.netlify.app/?path=/story/1-watson-iot-simplelist--large-row-list-with-multiple-actions). They should also wrap around to the next line if you add to them and make them super long.
- n/a
> fix(simple-list): adjust secondary value css to prevent cut-off

- packages/react/src/components/List/HierarchyList/HierarchyList.jsx
- packages/react/src/components/List/HierarchyList/HierarchyList.test.jsx
- packages/react/src/components/List/ListContent/ListContent.jsx
- packages/react/src/utils/DragAndDropUtils.jsx
Closes #3005 
**Summary**
- previously when a parent was selected and then unselected, all the children would remain checked. This fixes that.
- fix onClick being called twice on label and input
- fix locked rows being selected when parent is checked
- fix children not being unselected when parent is unselected
- move the handleSelect call on the checkbox to onChange instead of onClick
1. https://deploy-preview-3064--carbon-addons-iot-react.netlify.app/?path=/story/1-watson-iot-hierarchylist--with-nested-reorder
2. check a parent
3. uncheck a parent
4. confirm children unselected
1. check a parent with a locked child
2. confirm locked child is not selected
**Regression Test …
> fix(hierarchy-list): uncheck children when parent unchecked

- packages/react/src/components/PageTitleBar/PageTitleBar.jsx
Closes #
**Summary**
- When some of the children components of the content prop of PageTitleBar were null (this is because they're conditional for us) a NPE was being thrown
- Verify child isn't null before checking the type
- View the code
- Verify the original fix is still preserved
> fix(pagetitlebar): child content component might be null

- packages/react/src/components/CardEditor/CardEditForm/CardEditForm.jsx
Closes ##3098
**Summary**
We need to show the ID in the JSON editor. Hiding this is inconsistent with the export feature 
- items_here
1. edit any dashboard
2. edit any card
3. Click JSON Editor
4. The json will have the id field.
- tests here
> fix bug for removing ID from JSON Editor

- packages/react/src/components/Table/TableViewDropdown/TableViewDropdown.jsx
Closes #2423 
**Summary**
- Fixes the `[Object object]` being shown in the browser title tooltip of the TableViewDropdown. This is a stop-gap fix until https://github.com/carbon-design-system/carbon/pull/10188 is released and we can update and incorporate it. 
- uses the custom hook to manually set the title of the selected item to overcome the `itemToString` hacks we're using to show an element in the dropdown.
- in the [table with create save view management story](https://deploy-preview-3126--carbon-addons-iot-react.netlify.app/?path=/story/1-watson-iot-table-table--table-example-with-create-save-views)
- hover over various points on the dropdown
- the title should match the text shown in the …
> fix(table-view-dropdown): fix [Object object] showing in title

- packages/react/src/components/ListBuilder/ListBuilder.story.jsx
Closes #3099 
**Summary**
- simple update to the ListBuilder complex story to filter individual users when adding a group that contains that user.
1. Go to [listbuilder--complex-nested-example](https://deploy-preview-3135--carbon-addons-iot-react.netlify.app/?path=/story/2-watson-iot-experimental-%E2%98%A2%EF%B8%8F-listbuilder--complex-nested-example)
2. Click on the expand "Roles" button
3. Click on the expand "Roles One" button
4. Select item "Misha Knappenberger"
5. Select the whole group "Roles One"
6. Notice how "Misha Knappenberger" was now removed and only appears in Role One
- n/a
> chore(list-builder): fix story for complex nesting add users/groups

- packages/react/src/components/Header/Header.jsx
- packages/react/src/components/Header/Header.test.jsx
- packages/react/src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Closes #1675 
**Summary**
- adds isSideNavExpanded prop to header so that the aria-label on the menu button can be updated when the nav opens and closes
- add isSideNavExpanded prop
- add tests
- check the [side nav ](https://deploy-preview-3137--carbon-addons-iot-react.netlify.app/?path=/story/1-watson-iot-sidenav--side-nav-component) stories
- hover over the side-nav menu button
- should show 'Open menu'
- click to open menu
- hover over the side-nav menu button
- should show 'Close menu'
- n/a
> fix(header): add isSideNavExpanded prop to fix aria-label for button

- packages/react/src/components/Button/_button.scss
- packages/react/src/components/MenuButton/MenuButton.jsx
- packages/react/src/components/MenuButton/MenuButton.story.jsx
- packages/react/src/components/MenuButton/MenuButton.test.jsx
- packages/react/src/components/MenuButton/SingleMenuButton.jsx
- packages/react/src/components/MenuButton/SplitMenuButton.jsx
- packages/react/src/components/MenuButton/_menu-button-shadow-blocker.scss
- packages/react/src/components/MenuButton/_menu-button.scss
- packages/react/src/components/MenuButton/utils.js
- packages/react/src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Closes #3044
**Summary**
Fixed the styling remarks from #3044 and also fixed some additional RTL issued. In order to understand the changes it is easiest to go through the commits one by one.
1. Fixed button and menu item sizes according to the spec  + unit tests
2. Added button variations (kind) according to the spec + unit tests
3. Fixed the shadow from the menu that was incorrectly dropping in the button (complex fix needed) + unit tests
4. Fixed additional RTL issues
Start by reading the spec.
1. Go to https://deploy-preview-3185--carbon-addons-iot-react.netlify.app?path=/story/2-watson-iot-experimental-%E2%98%A2%EF%B8%8F-menubutton--single-menu-button and use the size knob to verify that the …
> 3044 menu button style audit button variations

- packages/react/src/components/Dashboard/Dashboard.story.jsx
- packages/react/src/components/GaugeCard/GaugeCard.story.jsx
- packages/react/src/components/ImageCard/HotspotContent.story.jsx
- packages/react/src/components/Table/Table.story.jsx
- packages/react/src/components/TileGallery/TileGallery.story.jsx
Closes #3194
**Summary**
Fixed stories that had knobs that were "leaking" into the other stories. The problem was that there were knobs defined in objects in the the storybook global scope outside the exported stories. Transformed the objects into functions.
- Transformed the objects into functions.
1. Go to https://deploy-preview-3197--carbon-addons-iot-react.netlify.app?path=/story/0-overview-getting-started--about-storybook and make sure there no knobs are appearing.
1. Go through the stories for GaugeCard, HotspotContent, Table and TileGallery and make sure they work as before.
> 3194 storybook knobs are leaking into all stories

- packages/react/src/components/Table/Table.jsx
- packages/react/src/components/Table/Table.test.e2e.jsx
- packages/react/src/components/Table/TableBody/TableBodyRowRenderer.jsx
Closes #3220 
**Summary**
- The placeholder skeleton column was missing when lazy loading with `hasNestedRows`. This fixes that.
- add check for `hasRowNesting` when including skeleton columns
- go the the basic table story
- turn on hasRowNesting
- turn on hasRowSelection to 'multi'
- turn on shouldLazyRender
- confirm the columns align with header and Object ID column isn't missing a skeleton
- tests here
> fix(table): add skeleton column for nesting rows when lazy loading

- packages/react/src/components/Table/Table.jsx
- packages/react/src/components/Table/TableHead/FilterHeaderRow/FilterHeaderRow.jsx
- packages/react/src/components/Table/TableHead/FilterHeaderRow/FilterHeaderRow.test.jsx
Closes #3210
**Summary**
Fix for keeping filter columns aligned when using options.hasRowNesting
- Updated FilterHeaderRow to handle options.hasRowNesting
- Added unit test
- Fixed options.hasRowNesting that was missing when calculating `totalColumns` in the table. This was not the fix needed for this issue, but it will solve other bugs not yet reported in `ErrorTable` and `EmptyTable`. Other use of `totalColumns` is unaffected from what I could tell.
1. Go to https://deploy-preview-3235--carbon-addons-iot-react.netlify.app/?path=/story/1-watson-iot-table-table--basic-dumb-table
2. Select StatefulTable in knob Stable Type of Table
3. Make sure knob `options.hasRowNesting` is true
4. Make sure the …
> fix(table): add rownesting in total columns calc

- packages/react/src/components/Table/StatefulTable.story.jsx
- packages/react/src/components/Table/Table.story.jsx
- packages/react/src/components/Table/TableBody/RowActionsCell/RowActionsCell.jsx
- packages/react/src/components/Table/TableBody/RowActionsCell/RowActionsCell.test.jsx
- packages/react/src/components/Table/TablePropTypes.js
- packages/react/src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Closes #3208
**Summary**
Adds hidden prop to Table rowActions
- Adds hidden prop and proptype to Table rowActions
- Update Table story example data to include a hidden action and a hidden overflow action
- Update `SimpleStatefulExample` to include a row where all actions are hidden
- Write unit tests
1. Go to https://deploy-preview-3238--carbon-addons-iot-react.netlify.app?path=/story/1-watson-iot-table-statefultable--simple-stateful-example
2. Enable knob hasRowActions
3. Verify that the second row is not showing any row actions at all
4. Verify that there are no actions named "Hidden" visible
5. Verify that there are no overflow actions named "Hidden overflow" visible
**Regression Test (how to make …
> fix(table): add hidden prop to row action

- packages/react/src/components/Table/TableToolbar/TableToolbar.jsx
- packages/react/src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Closes #
**Summary**
- Small proptype fix, same as Bjorn's [PR here](https://github.com/carbon-design-system/carbon-addons-iot-react/pull/3222), but also updates it in the TableToolbar
- TableToolbar proptype fix.
- no proptype warning in storybook
- tests here
> fix(table): fix proptype on TableToolbar, too

- packages/react/src/components/CardEditor/CardEditForm/CardEditFormItems/DataSeriesFormItems/DataSeriesFormContent.jsx
- packages/react/src/components/CardEditor/CardEditForm/CardEditFormItems/TableCardFormItems/TableCardFormContent.jsx
- packages/react/src/components/CardEditor/CardEditForm/CardEditFormItems/ThresholdsFormItem.jsx
- packages/react/src/components/DashboardEditor/editorUtils.jsx
- packages/react/src/components/DateTimePicker/DateTimePicker.jsx
- packages/react/src/components/DateTimePicker/DateTimePickerV2.jsx
- packages/react/src/components/Table/TableColumnCustomization.story.jsx
- packages/react/src/hooks/useUniqueId.jsx
Closes #3258 
**Summary**
- ~updates all uuid imports to use `import uuidv4 from 'uuid/v4';`~
- updates all uuid imports to use `import * as uuid from 'uuid';`
- ~updates all uuid imports to use `import uuidv4 from 'uuid/v4';`~
- updates all uuid imports to use `import * as uuid from 'uuid';`
- tests pass
- tests pass
> fix(repo): change uuid imports to use uuid/v4

- packages/react/src/components/Table/TableBody/RowActionsCell/_row-actions-cell.scss
#3188
Closes #3188 
**Summary**
- Adjust size of loading spinner in row
- Change width and height of loading small from 1.875 to 1 rem
- This matches the carbon size of the loading icon [here](https://react.carbondesignsystem.com/?path=/story/components-loading--default) 
- tests here
> adjust size of loading spinner in row

- packages/react/src/components/List/ListItem/_list-item.scss
#3147
Closes #
**Summary**
- The drag preview was not covering full width for large rows. This is now fixed and accounted for with RTL.
- `_list-item.scss` added sub styles for `--drop-targets`
- Verify on watson-iot-hierarchylist--with-nested-reorder story that the drag preview borders on large rows are correct
- Ensure regular rows dragging looks fine as well as other list actions
> fix width of drag preview on large rows

- packages/react/src/components/Table/TableViewDropdown/TableViewDropdown.jsx
- packages/react/src/components/Table/TableViewDropdown/TableViewDropdown.story.jsx
- packages/react/src/components/Table/TableViewDropdown/TableViewDropdown.test.jsx
- packages/react/src/components/Table/TableViewDropdown/TableViewDropdownContent.mdx
- packages/react/src/components/Table/TableViewDropdown/__snapshots__/TableViewDropdown.story.storyshot
- packages/react/src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Closes #3298
**Summary**
Adds prop `isHidingStandardActions`  to the TableViewDropdown so that it can be turned in to a 
component only allowing selecting existing views.
- Updated story with knob
- Wrote test
- Updated TableViewDropdown
- Updated mdx
1.  Go to story https://deploy-preview-3301--carbon-addons-iot-react.netlify.app?path=/story/1-watson-iot-table-user-view-management-tableviewdropdown--playground
2. Make sure the standard actions (`Save as new view`, `Save changes` and `Manage views`) are showing in the dropdown
3. Enable knob "isHidingStandardActions"
4. Make sure the standard actions are no longer showing …
> feat(tableviewdropdown): add prop isHidingStandardActions

- packages/react/src/components/Table/Table.main.story.jsx
- packages/react/src/components/Table/Table.story.helpers.jsx
- packages/react/src/internal/storyState.js
Closes #3304
**Summary**
Our stories using the StatefulTable had become slow due to the fact that the whole story was re-generated each time a knob was changed. This happened when the story was wrapped in a React element using the story `decorator`, which we did for each story that needed DragAndDrop or needed a react state.
- The Tables are no longer re-generated from scratch when a knob changes. Some knobs still explicitly re-renders the table for demo purposes, e.g. when view related knobs change for the StatefulTable we need to use `key` to get the change picked up.
- Removed DnD wrapper from the decorator and added the `<DragAndDrop>` element in the story itself.
- Created a non-react dependent version of React's `useState` called …
> docs(table): remove react wrapper for table stories

- packages/react/src/components/Table/TableToolbar/TableToolbarAdvancedFilterFlyout.jsx
- packages/react/src/components/Table/TableToolbar/TableToolbarAdvancedFilterFlyout.test.jsx
Closes #3319
**Summary**
Small fix to prevent the TableToolbarAdvancedFilterFlyout.jsx from crashing if the columns prop array is empty
- Unit test is passing
(The bug is not easily testable without modifying the table main story like is being done for #3304)
- Advanced filters work as before
> fix(table): advanced filter crash fix

- packages/react/src/components/Table/TableDetailWizard/__snapshots__/TableDetailWizard.story.storyshot
- packages/react/src/components/WizardInline/WizardFooter/WizardFooter.jsx
- packages/react/src/components/WizardInline/__snapshots__/WizardInline.story.storyshot
- packages/react/src/components/WizardInline/_wizard-inline.scss
- packages/react/src/components/WizardModal/__snapshots__/WizardModal.story.storyshot
Closes #3317 
**Summary**
- removes styled components from WizardFooter
- replaces one styled component div with a div and scss class
- WizardInline story footers match those of next
- WizardInline story footers match those of next
> refactor(wizard-footer): remove styled components

- packages/react/src/components/Table/Table.jsx
- packages/react/src/components/Table/TableSkeletonWithHeaders/TableSkeletonWithHeader.test.jsx
- packages/react/src/components/Table/TableSkeletonWithHeaders/TableSkeletonWithHeaders.jsx
- packages/react/src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Closes #3323
**Summary**
Fixes the number of columns shown for TableSkeletonWithHeader when `rowNesting` is used
- Add fix to TableSkeletonWithHeader and Table
1. Go to https://deploy-preview-3326--carbon-addons-iot-react.netlify.app?path=/story/1-watson-iot-table--playground
2. Click on Tab "Nesting & expansion" and activate knob "Demo nested rows (options.hasRowNesting)"
3. Click on tab "States" and activate knob "Show table loading state (view.table.loadingState.isLoading)"
4. Make sure the number of columns is correct
1.  TableSkeletonWithHeader works as expected
> fix(table): show correct number of columns in tableskeleton

- packages/react/src/components/ProgressBar/ProgressBar.jsx
- packages/react/src/components/ProgressBar/ProgressBar.mdx
- packages/react/src/components/ProgressBar/ProgressBar.story.jsx
- packages/react/src/components/ProgressBar/ProgressBar.test.jsx
- packages/react/src/components/ProgressBar/__snapshots__/ProgressBar.story.storyshot
- packages/react/src/components/ProgressBar/_progress-bar.scss
- packages/react/src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Closes #3339 
**Summary**
- adds `inline` prop to ProgressBar to hide label/icon/helperText and show the value and unit inlined with the bar
- add `inline` prop
- update docs
- add test
- update snapshots
- cleanup code
- go to the [ProgressBar story](https://deploy-preview-3347--carbon-addons-iot-react.netlify.app?path=/story/1-watson-iot-progressbar--default)
- turn on the inline prop
- confirm label and helperText disappear and value is inlined beside the bar with 8px of space in between
- repeat with icons/thresholds
- check RTL
- tests here
> feat(progress-bar): add inline variant

- packages/react/src/components/Table/StatefulTable.jsx
- packages/react/src/components/Table/StatefulTable.test.jsx
Closes #3354
**Summary**
Adds onApplyToolbarAction callback for the StatefulTable
- add callback
- add unit test
1. Go to https://deploy-preview-3355--carbon-addons-iot-react.netlify.app?path=/story/1-watson-iot-table--playground
2. Click on the Title & Toolbar tab
3. Enable knob view.toolbar.toolbarActions
4. Select an action in the toolbar overflow menu
5. Make sure the onApplyToolbarAction is triggered in the Actions tab.
> fix(table): add onapplytoolbaraction to statefultable

- .github/workflows/build.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/format.yml
- .github/workflows/lint.yml
- .github/workflows/test-app.yml
- .github/workflows/test.yml
**Summary**
- Hi there! 👋 This PR adds a setting to the CI workflows to cancel existing jobs for a given PR when a new commit is added. This option helps to reduce the number of runners used across repos as the org is limited to only 20 runners.
- I updated CI status check workflows in `.github/workflows` to use the `concurrency` option from: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#concurrency
- I didn't modify the `codesandbox`, `release`, or `update-v3` workflows
- Go through the commit history of this PR, it should show that jobs for earlier commits have been "skipped" or "cancelled". This will show that the concurrency syntax is working as-intended
- …
> chore(ci): add concurrency option to CI workflows

- packages/react/src/components/PageTitleBar/PageTitleBar.story.jsx
- packages/react/src/components/PageTitleBar/__snapshots__/PageTitleBar.story.storyshot
Closes #3346 
**Summary**
- simple style fix within the story when the inline loader is inside the tooltip
- adds style block to the story to fix the colors of the InlineLoader text when it's collapsed in the tooltip
- go to the with status description and breadcrumbs story
- turn on collapse description knob
- open tooltip
- confirm text is white and readable
- tests here
> fix: minor style update in PageTitleBar storybook

- packages/react/src/components/SideNav/FilterableSideNavMenu.jsx
- packages/react/src/components/SideNav/SideNav.jsx
- packages/react/src/components/SideNav/SideNav.story.jsx
- packages/react/src/components/SideNav/SideNav.test.jsx
- packages/react/src/components/SideNav/__snapshots__/SideNav.story.storyshot
- packages/react/src/components/SideNav/_side-nav.scss
- packages/react/src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Closes #3352
**Summary**
Adds search functionality and the possibility to pin links to the SideNav
- Added search functionality behind prop `hasSearch`. Improves on existing nav search in Maximo by 
- allowing keyboard navigation on search result
- show all the parents of a matched leaf, not just the closest one
- Added unit testing for search
- Added possibility to pin items when prop `hasSearch` is true using link prop `isPinned`
- Added unit tests for pinned items
- Updated story with new knobs and data
The functionality is based on the existing implementation in Maximo with a few differences as mentioned above
**Search**
1. Go to https://deploy-preview-3374--carbon-addons-iot-react.netlify.app?pat …
> 3352 side nav implement search functionality of links

- packages/react/src/components/Table/tableReducer.js
- packages/react/src/components/Table/tableReducer.test.jsx
Closes #3404
**Summary**
- includes updates to view.toolbar.rowEditBarButtons and view.table.singleRowEditButtons when the TABLE_REGISTER action is called
- updated action
- added unit test
1. Go to the PR for the table state stories which contains the same commit but also provides the UI to verify it
https://deploy-preview-3397--carbon-addons-iot-react.netlify.app/?path=/story/1-watson-iot-table--with-data-editing
2. Change to StatefulTable
3. Edit row 2
4. change number to '5'
5. Verify that the save button is now enabled
6. Repeat for multi edit button
- na
> fix(statefultable): include rowedit buttons in tableregister

- packages/react/src/components/SideNav/SideNav.jsx
- packages/react/src/components/SideNav/SideNav.story.jsx
- packages/react/src/components/SideNav/__snapshots__/SideNav.story.storyshot
- packages/react/src/components/SuiteHeader/SuiteHeader.story.jsx
Closes #
**Summary**
- added example of state management in the sidenav with a pinned link
- fixed expand/collapse of sidenav items when closed
- go to [sidenav component with state management](https://deploy-preview-3412--carbon-addons-iot-react.netlify.app/?path=/story/1-watson-iot-ui-shell-sidenav--side-nav-component-with-state)
- open sidenav
- open members
- click link 4
- open sidenav
- open members
- confirm link four is active with blue bar
- hover off sidenav
- confirm sidenav closes and members section collapses when closed with blue bar now beside the icon
- tests here
> fix: sidenav state example with pinned fix open/close on hover

- packages/react/src/components/EmptyState/_emptystate.scss
- packages/react/src/components/Table/Table.story.helpers.jsx
Closes #3415 
**Summary**
-  add`word-break: break-word` for `emptyMessage`
- fixed in `_emptystate.scss`
before:
after:
> fix(table): empty state message with word break

- packages/react/src/components/DataTable/_data-table.scss
- packages/react/src/components/Table/Table.jsx
- packages/react/src/components/Table/Table.main.story.jsx
- packages/react/src/components/Table/Table.story.helpers.jsx
- packages/react/src/components/Table/TableBody/TableBody.jsx
- packages/react/src/components/Table/TableBody/TableBodyRow/TableBodyRow.jsx
- packages/react/src/components/Table/TableBody/TableBodyRow/TableBodyRow.story.jsx
- packages/react/src/components/Table/TableBody/TableBodyRow/TableBodyRow.test.jsx
- packages/react/src/components/Table/TableBody/TableBodyRow/__snapshots__/TableBodyRow.story.storyshot
- packages/react/src/components/Table/TableBody/TableBodyRowRenderer.jsx
- packages/react/src/components/Table/TableHead/TableHead.jsx
- packages/react/src/components/Table/TableHead/_table-head.scss
- packages/react/src/components/Table/TableSaveViewModal/__snapshots__/TableSaveViewModal.story.storyshot
- packages/react/src/components/TileGallery/__snapshots__/TileGallery.story.storyshot
- packages/react/src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Closes #3394 
**Summary**
- single selection with radio button 
- there are 2 ways of single selection, it's either with a radio button or with a blue indicator.
- add radio button when `hasRowSelection` is `single` and  option prop `showRadioButton` is `true`
- tests here
> feat(table): radio button on single select row

- packages/react/src/components/SideNav/SideNav.jsx
- packages/react/src/components/SideNav/__snapshots__/SideNav.story.storyshot
- packages/react/src/components/SuiteHeader/SuiteHeader.jsx
- packages/react/src/components/SuiteHeader/SuiteHeader.story.jsx
- packages/react/src/components/SuiteHeader/__snapshots__/SuiteHeader.story.storyshot
- packages/react/src/components/Table/TableSaveViewModal/__snapshots__/TableSaveViewModal.story.storyshot
- packages/react/src/components/TileGallery/__snapshots__/TileGallery.story.storyshot
- packages/react/src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Closes #3433
**Summary**
Side nav props were not updating the sidenav for SuiteHeader. 
- wrapped `Header` and `SideNav` component with Carbon's `HeaderContainer` component. Replaced the state management for SideNav open state with the ones provided by HeaderContainer component in `SuiteHeader.jsx`
- made the 'Header with side nav' story stateful to demonstrate the sidenav `isActive` state change in `SuiteHeader.story.jsx`
- updated the prop type, `current` which was not being used to `isActive` in `SideNav.jsx`
- Go to 'Header with side nav' story and confirm that `isActive` state is updating appropriately. 
- All of …
> Side nav issue

- packages/react/src/components/SuiteHeader/SuiteHeader.mdx
- packages/react/src/components/SuiteHeader/hooks/useUiResources.js
- packages/react/src/components/SuiteHeader/util/uiresources.js
**Summary**
- Since the `GET /uiresources` API has changed to add support an optional `workspaceId` query parameter, the `uiresources` fetch helper function and the `useUiResources` hook need to forward the new `workspaceId` query parameter to the API call.
- Including an optional `workspaceId` query parameter in the `uiresources` fetch helper and in the `useUiResources` hook.
- Nothing was changed in any component so there is nothing to test in the storybook for this PR
- The files changed in this PR are excluded from unit test list and coverage calculation.
> feat(SuiteHeader): Including an optional workspaceId parameter to the uiresources fetch helper and hook

- packages/react/src/components/Dashboard/Dashboard.test.jsx
- packages/react/src/components/PieChartCard/PieChartCard.test.jsx
- packages/react/src/components/RuleBuilder/RuleBuilder.test.jsx
- packages/react/src/components/Table/StatefulTable.test.jsx
- packages/react/src/components/Table/StatefulTableMockReducers.test.jsx
- packages/react/src/components/Table/Table.test.jsx
- packages/react/src/components/Table/TableFoot/TableFoot.test.jsx
- packages/react/src/components/Table/TableHead/TableHead.jsx
- packages/react/src/constants/CardPropTypes.js
- packages/react/src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Closes #3421
**Summary**
Default prop in `TableHead.jsx` is triggering our proptype warning we have for `testID` prop that is deprecated. 
- Remove default prop for `testID` from `TableHead.jsx`;
- Remove assertions expecting that proptype warning in our test when not specifically passing in a `testID` prop.
- Updated the `PieChartCard` proptypes since it listed `testID` but did not have warning as part of proptype definition. Get's all of CardPropTypes which does have the prop and warning. 
- make sure all test pass. 
> 3421 proptype warning

- packages/react/src/components/CardEditor/CardEditForm/CardEditFormItems/DataSeriesFormItemModal.jsx
- packages/react/src/components/CardEditor/CardEditForm/CardEditFormItems/DataSeriesFormItemModal.test.jsx
- packages/react/src/components/CardEditor/CardEditForm/_card-edit-form.scss
Closes #3468
**Summary**
- Increased modal size from xs -> md
- Modified test case for the md modal size
- Go to any dashboard -> Edit dashboard: eg. https://dashboard-dev.connectedproducts.internetofthings.ibmcloud.com/monitor/Compresser/editSummary/227605/2
- Add a 'Data Table' card
- Select a 'Data item'
- Edit newly added data item
- In the 'Customize data series' modal, click 'Add threshold'
- Enter a value in the number input
- Modal size is larger (md), with no overlap in the number input between the value and +- symbols
- tests here
> fix(DataSeriesFormItemModal): larger form modal

- packages/react/src/components/CardEditor/CardEditForm/CardEditFormItems/DataSeriesFormItemModal.jsx
- packages/react/src/components/CardEditor/CardEditForm/CardEditFormItems/DataSeriesFormItemModal.test.jsx
Closes #3471 
**Summary**
Fix for downsample method dropdown. Downsample methods dropdown should only show on Timeseries card.
- DataSeriesFormItemModal
- DataSeriesFormItemModal.test
- Go to 'Monitor'
-Click on 'any V2 data item'
-Edit dashboard 'Add any card other then a Timeseries card'
-Add a Data item
-Edit the Data Item
-If card is not a Timeseries card downsample method dropdown should not show.
- tests 
- Go to Storybook
- CardEditor
- Select V2 pressure
- Confirm can see Downsample methods dropdown when you edit dataItem
- Now Select 'for Timeseries ' edit data item an confirm you can see Aggregation method …
> fix(DataSeriesFormItemModal):downsample methods for timeseries card

- packages/react/src/components/CardEditor/CardEditor.jsx
Closes #3484 
**Summary**
When opening up the JSON editor in the `DashboardEditor` component we were passing react children to the `JSON.stringify` function which was making it error. This fix excludes those children from the cardConfig object we pass to this function. 
- add "children" to the omit list in `CardEditor.jsx`
1. Go to dashboard [story](
https://deploy-preview-1824--carbon-addons-iot-react.netlify.app/?path=/story/2-watson-iot-experimental-%E2%98%A2%EF%B8%8F-dashboardeditor--with-initial-value)
2. Click on image in the right sidebar gallery
3. Go to new card and upload an image
4. Click on open JSON editor on the right sidebar
5. See JSON editor open up with no errors thrown
> [CardEditor]: remove children from json stringify

- packages/react/src/components/Table/TableHead/FilterHeaderRow/FilterHeaderRow.jsx
Closes #3498 
**Summary**
- added extra cell in FilterHeaderRow for single select when using radio button
- fix(FilterHeaderRow): added extra conditions for single select when using radio button
Filters should be aligned
- tests here
> fix(table): add extra header cell for single select using radio button

- packages/react/src/components/CardEditor/CardEditForm/CardEditFormContent.test.jsx
- packages/react/src/components/CardEditor/CardEditForm/CommonCardEditFormFields.jsx
Closes https://github.com/carbon-design-system/carbon-addons-iot-react/issues/3519
Related to https://github.ibm.com/wiotp/Maximo-Asset-Monitor/issues/4474.
**Summary**
- hide time range selector
- feat(CommonCardEditFormFields): hide time range selector if there is no value. 
- time range selector should be hidden if we don't send or send an empty array
- Dashboard should work without any issues. 
> feat(commoncardeditformfield): hide time range on empty values

- packages/react/src/components/SuiteHeader/MultiWorkspaceSuiteHeader.story.jsx
- packages/react/src/components/SuiteHeader/SuiteHeader.jsx
- packages/react/src/components/SuiteHeader/SuiteHeader.story.jsx
Closes #
**Summary**
- Appending originHref to the logout and logoutInactivity routes so that it is possible for the logout route handler page to extract an origin URL in order to allow for redirection to that page when user reattempts to log in.
- items_here
- No noticeable effect in stories
- Check that page redirections by regular logout and idle user logout now include the `originHref` query parameter with the url of the current page.
- All tests are passing.
> fix(suiteheader): Appending originHref to the logout and logoutInactivity routes

- packages/react/src/components/SuiteHeader/IdleLogoutConfirmationModal/IdleLogoutConfirmationModal.jsx
- packages/react/src/components/SuiteHeader/IdleLogoutConfirmationModal/IdleLogoutConfirmationModal.test.jsx
- packages/react/src/components/SuiteHeader/MultiWorkspaceSuiteHeader.test.jsx
- packages/react/src/components/SuiteHeader/SuiteHeader.jsx
- packages/react/src/components/SuiteHeader/SuiteHeader.test.jsx
**Summary**
- Making sure that `IdleLogoutConfirmationModal` also appends the the originHref to the logout routes when used standalone
- Appending the `originHref` to the logout routes using `new URL()` instead of doing it manually.
- Making sure that `IdleLogoutConfirmationModal` also appends the the `originHref` to the logout routes when used standalone.
- Improving unit tests to validate the existence of the `originHref` query parameters in the logout routes.
- Check that the standalone IdleLogoutConfirmationModal also appends the `originHref` in logout and inactivity logout routes.
- All existing tests are passing. …
> fix(suiteheader): Making sure that IdleLogoutConfirmationModal also appends the the originHref to the logout routes when used standalone

- packages/react/src/components/TimePicker/_time-picker-dropdown.scss
Closes #3528 
**Summary**
- Style scoped to `.#{$iot-prefix}--time-picker` class to prevent it affecting other components like `TextInput`.
- Style moved into `.#{$iot-prefix}--time-picker` class.
1. Go to [TextInput default story](https://next.carbon-addons-iot-react.com/?path=/story/3-carbon-textinput--default)
2. Click on knob to show invalid state
3. Check if the invalid text is displayed
- tests here
> fix(react): scoping style to time picker dropdown

- packages/react/src/components/ReadOnlyValue/ReadOnlyValue.jsx
- packages/react/src/components/ReadOnlyValue/ReadOnlyValue.mdx
- packages/react/src/components/ReadOnlyValue/ReadOnlyValue.story.jsx
- packages/react/src/components/ReadOnlyValue/__snapshots__/ReadOnlyValue.story.storyshot
- packages/react/src/components/ReadOnlyValue/_read-only-value.scss
- packages/react/src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
**Summary**
- Support to send a node in prop value of ReadOnlyValue  component
- Prop support to render a node
- Check that the value prop supports a node to be rendered and 
- Nothing changed in the already supported cases
> feat(readonlyvalue): Read only value updates

- packages/react/src/components/Table/Table.main.story.jsx
- packages/react/src/components/Table/__snapshots__/Table.main.story.storyshot
- packages/react/src/hooks/usePopoverPositioning.jsx
Closes #3359 
**Summary**
- Fix loop in React state update for OverflowMenu when at bottom of the browser.
- Update Storybook to reproduce issue
- Check for previous state before updating overflow direction.
- Go to [this story](https://deploy-preview-3539--carbon-addons-iot-react.netlify.app/?path=/story/1-watson-iot-table--with-inline-actions)
- Resize window vertically so that scrollbar appears.
- Scroll to the bottom of the table.
- Hover on the last row and click on "kebab" menu icon.
- Verify that overflow menu has appeared above the "kebab" menu icon.
- tests here
> [Table]: loop in overflow menu state update

- packages/react/src/components/Card/Card.story.jsx
- packages/react/src/components/Card/Card.test.jsx
- packages/react/src/components/Card/CardToolbar.jsx
- packages/react/src/components/Card/__snapshots__/Card.story.storyshot
Closes https://github.com/carbon-design-system/carbon-addons-iot-react/issues/3526
**Summary**
- adding tooltip to the card extra actions
- feat(card): adding tooltip to the card extra actions
- tooltips can be passed from the props
- card should work with out any issues
> feat(card): adding tooltip to the card extra actions

- packages/react/src/components/Breadcrumb/_breadcrumb.scss
Closes #3499 
**Summary**
- use `display:block` for links when `hasOverflow` is enabled
Before: first and last BreadCrumbItem are overflow:hidden but not showing ellipsis
After: put display:block for link element
- tests here
> fix(breadcrumb): text-overflow: ellipsis not working

- packages/react/src/components/DateTimePicker/DateTimePickerV2WithTimeSpinner.jsx
- packages/react/src/components/DateTimePicker/_date-time-pickerv2.scss
- packages/react/src/components/FlyoutMenu/FlyoutMenu.jsx
- packages/react/src/components/FlyoutMenu/__snapshots__/FlyoutMenu.story.storyshot
- packages/react/src/components/TimePicker/TimePickerDropdown.jsx
- packages/react/src/components/TimePicker/_time-picker-dropdown.scss
- packages/react/src/components/TimePicker/list-spinner.scss
- packages/react/src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Closes #3559 
**Summary**
- clean up styles and make sure style works on dropdown menu ( in FlyOutMenu) and on time spinner ( in TimePickerDropDown). 
If `zIndex` is not passed in on `DateTimePickerV2`, then `zIndex` on time spinner is set to 6000 by default to make sure it show up above the menu
Menu
Time spinner
If `zIndex` is passed in on `DateTimePickerV2`, then `zIndex` on time spinner is set to 600+ 6000 to make sure it show up above the menu
- `tooltipContentClassName` is defined in `DateTimePickerV2` but used in `<FlyOutMenu>`
-  make sure `tooltipContentClassName` class has --zIndex attribute and make we pass style in `<FlyOutMenu>`
- same for `TimePickerSpinner` inside `TimePickerDropDown` …
> fix(datetimepickerv2): styles on DateTimePickerV2 and time picker spinner

- packages/react/src/components/Table/StatefulTable.jsx
- packages/react/src/components/Table/StatefulTable.test.e2e.jsx
- packages/react/src/components/Table/StatefulTable.test.jsx
- packages/react/src/components/Table/Table.jsx
- packages/react/src/components/Table/Table.test.jsx
- packages/react/src/components/Table/TableToolbar/TableToolbar.jsx
- packages/react/src/components/Table/mdx/Searching.mdx
- packages/react/src/components/Table/mdx/Table.mdx
- packages/react/src/components/Table/tableReducer.js
- packages/react/src/components/TileCatalogNew/__snapshots__/TileCatalogNew.story.storyshot
Closes #3368 
**Summary**
- Display `EmptyTable` if search results are empty
- Adjust props in order to display `EmptyTable`
- Enable clearing search input by clicking on "Clear all filter" button in `EmptyTable`
- Update / Add tests
- Update docs
- Go to [this story](https://deploy-preview-3557--carbon-addons-iot-react.netlify.app/?path=/story/1-watson-iot-table--playground)
- In the Knobs section click on `Search` tab
- Enable `options.hasSearch` and `options.hasFastSearch` in order to display search input in the toolbar
- Type some irrelevant value in the search bar
- Verify that `EmptyTable` displayed
- Click on "Clear all filters" button in order to reset search input
- Verify that search input …
> fix(table): empty search result should show EmptyTable

- .gitignore
- packages/react/src/components/TimeSeriesCard/TimeSeriesCard.story.jsx
- packages/react/src/components/TimeSeriesCard/timeSeriesUtils.js
- packages/react/src/components/TimeSeriesCard/timeSeriesUtils.test.js
- packages/react/src/utils/__tests__/cardUtilityFunctions.test.jsx
- packages/react/src/utils/cardUtilityFunctions.js
Closes https://github.com/carbon-design-system/carbon-addons-iot-react/issues/3574
**Summary**
- If there are a number of lines in the time series graph then the alerts are getting displayed on all the lines. Whereas the alerts need to be displayed on specific lines, on which alerts are generated. 
- fix([cardUtilityFunctions) : update the `findMatchingAlertRange` method and added a alertRange filter machanisum
- fix([cardUtilityFunctions.test): moved the `findMatchingAlertRange` and `handleTooltip` test cases from timeSeriesUtil.test and updated the `findMatchingAlertRange` testcases to handle above changes.
- Go to the TimeSeriesCard with alert ranges story --> **Alert ranges are getting …
> fix(timeseriescard): overlay alert for the specific line

- packages/react/src/components/CardEditor/CardEditForm/CardEditFormItems/TableCardFormItems/TableCardFormContent.jsx
- packages/react/src/components/CardEditor/CardEditForm/CardEditFormItems/TableCardFormItems/TableCardFormContent.test.jsx
Closes #3563
Closes https://github.com/carbon-design-system/carbon-addons-iot-react/issues/3389
**Summary**
- Remove threshold attribute for empty threshold lists
- Remove threshold attribute for empty list from content
- Remove unnecessary threshold attribute from content.columns
- Go to 'Dashboard'
- Create new dashboard
- Add 3 data items
- Add some threshold to the data item (Save the dashboard)
- Remove the data item that has threshold
- goto Open JSON editor
- Click save 
- No errors displayed.
- tests here
> fix(tablecardformcontent): discard threshold from columns

- packages/react/src/components/List/ListContent/ListContent.jsx
- packages/react/src/components/List/ListItem/ListItem.jsx
- packages/react/src/components/List/ListItem/ListItem.story.jsx
- packages/react/src/components/List/ListItem/__snapshots__/ListItem.story.storyshot
- packages/react/src/components/List/ListPropTypes.js
- packages/react/src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Closes #3572
**Summary**
- List item to accept new property to display as hover text.
- ListContent to accept `title` and drill prop to ListItem
- ListItem to accept new property `title` and use as hover text
- ListItem to use name when title is empty (null or undefined)
- Set `value` and `title` with different texts.
- Hover over the list item component
- Title content should be displayed as tooltip and Value should be displayed as regular text
- tests here
> feat(listitem): accept hover text

- packages/react/src/components/ComboBox/_combo-box.scss
- packages/react/src/components/ImageCard/_hotspot.scss
- packages/react/src/components/MenuButton/_menu-button-shadow-blocker.scss
- packages/react/src/components/TileCatalog/_catalog-content.scss
- packages/react/src/styles.scss
Closes #3439 
**Summary**
- Replace "/" symbol to `Math.div` in `scss` files
- Enable `sass:math` module (add `@use` directive to stylelint ignore)
- Affected component `ComboBox`
- Affected component `ImageCard`
- Affected component `MenuButton`
- Affected component `TileCatalog`
- Go to [this commit](https://github.com/carbon-design-system/carbon-addons-iot-react/pull/3568/commits/54d1d17de2c4a6a443ee8937984c49613b6b8561)
- Verify that all "/" symbols have been replaced by `*` or `Math.div`
- tests here
> chore(styles): replace divide symbol to math.div

- packages/react/src/components/DashboardEditor/DashboardEditor.jsx
- packages/react/src/components/DashboardEditor/DashboardEditor.test.jsx
- packages/react/src/components/DashboardEditor/DashboardEditorCardRenderer.jsx
- packages/react/src/components/DashboardEditor/__snapshots__/DashboardEditor.story.storyshot
- packages/react/src/components/ImageGalleryModal/ImageGalleryModal.jsx
- packages/react/src/components/ImageGalleryModal/__snapshots__/ImageGalleryModal.story.storyshot
- packages/react/src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Closes https://github.com/carbon-design-system/carbon-addons-iot-react/issues/3555
**Summary**
- send card configuration on card select instead of card id
- feat(dashboardeditor): send card configuration on card select
- on card select the callback function should get the cardConfig instead of just card id
- tests here
> fix(dashboardEditor): send card JSON on card select

- packages/react/src/components/TileCatalog/_catalog-content.scss
- packages/react/src/styles.scss
Closes #3581 
**Summary**
- Remove `@use "sass:math"`
- Replace `math.div` to `*` or `/` operators
- Delete `@use "sass:math"` from root stylesheet
- Go to [this story](https://deploy-preview-3582--carbon-addons-iot-react.netlify.app/?path=/story/1-watson-iot-catalog-marketplace-tilecatalog--default)
- Change screen width and verify that `max-width` property in `iot--sample-tile-title` is changing accordingly
- tests here
> fix(sass): remove @use declaration

- packages/react/src/components/ImageCard/_hotspot-content.scss
- packages/styles/src/components/ImageCard/_hotspot-content.scss
Closes [#4444](https://zenhub.ibm.com/workspaces/maximo-asset-monitor-5cd44ce4baded506ba8ddd5f/issues/wiotp/maximo-asset-monitor/4444)
**Summary**
- Image card - left align hotspot labels
- fix(imagehotspot): image hotspots label left align
- Image card > hotspot data item labels should be left aligned, with the values right aligned
- tests here
> fix(imagehotspot): image hotspots label left align

- packages/react/src/components/CardEditor/CardEditForm/CardEditForm.jsx
- packages/react/src/components/CardEditor/CardEditForm/CardEditFormContent.jsx
- packages/react/src/components/CardEditor/CardEditForm/CardEditFormItems/DataSeriesFormItemModal.jsx
- packages/react/src/components/CardEditor/CardEditForm/CardEditFormItems/DataSeriesFormItemModal.test.jsx
- packages/react/src/components/CardEditor/CardEditForm/CardEditFormItems/DataSeriesFormItems/DataSeriesFormContent.jsx
- packages/react/src/components/CardEditor/CardEditForm/CardEditFormItems/DataSeriesFormItems/DataSeriesFormContent.test.jsx
- packages/react/src/components/CardEditor/CardEditForm/CardEditFormItems/ImageCardFormItems/ImageCardFormContent.jsx
- packages/react/src/components/CardEditor/CardEditForm/CardEditFormItems/TableCardFormItems/TableCardFormContent.jsx
- packages/react/src/components/CardEditor/CardEditForm/CardEditFormItems/TableCardFormItems/TableCardFormContent.test.jsx
- packages/react/src/components/CardEditor/CardEditor.jsx
- packages/react/src/components/CardEditor/CardEditor.story.jsx
- packages/react/src/components/CardEditor/__snapshots__/CardEditor.story.storyshot
- packages/react/src/components/DashboardEditor/DashboardEditor.jsx
- packages/react/src/components/DashboardEditor/DashboardEditor.story.jsx
- packages/react/src/components/DashboardEditor/DashboardEditor.test.jsx
- packages/react/src/components/DashboardEditor/editorUtils.jsx
- packages/react/src/components/HotspotEditorModal/HotspotEditorDataSourceTab/HotspotEditorDataSourceTab.jsx
- packages/react/src/components/HotspotEditorModal/HotspotEditorDataSourceTab/HotspotEditorDataSourceTab.story.jsx
- packages/react/src/components/HotspotEditorModal/HotspotEditorDataSourceTab/HotspotEditorDataSourceTab.test.jsx
- packages/react/src/components/HotspotEditorModal/HotspotEditorModal.jsx
- packages/react/src/components/HotspotEditorModal/HotspotEditorModal.story.jsx
- packages/react/src/components/HotspotEditorModal/HotspotEditorModal.test.jsx
- packages/react/src/components/HotspotEditorModal/HotspotEditorTooltipTab/HotspotEditorTooltipTab.story.jsx
- packages/react/src/components/HotspotEditorModal/HotspotTextStyleTab/HotspotTextStyleTab.story.jsx
- packages/react/src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Closes Monitor - https://github.ibm.com/wiotp/Maximo-Asset-Monitor/issues/4661
**Summary**
- Fixed DataFilter not available for V2 device types under dashboard editor
- fix(dataseriesformcontentmodal): added datafilter for v2 devicetypes
- fix(dataseriesformitemmodal): updated test cases
- Datafilter should be available for v2 device type on click of edit data item after adding it into a card in dashboard editor
- tests here
> Fix data filter for v2 device type

- packages/react/src/components/DateTimePicker/DateTimePickerV2.test.e2e.jsx
- packages/react/src/components/TimePicker/TimePickerDropdown.jsx
- packages/react/src/components/TimePicker/_time-picker-dropdown.scss
Closes #3585 
**Summary**
- Allow user to clean time input value
- Move function to populate current time from `useEffect` hook to `onFocus` callback
- Update test
- Fix recent updates from design audit
- Go to [this story](https://deploy-preview-3586--carbon-addons-iot-react.netlify.app/?path=/story/2-watson-iot-experimental-%E2%98%A2%EF%B8%8F-datetimepickerv2--selected-absolute)
- Enable knob `useNewTimeSpinner`
- Click on input to display dropdown
- Focus on some input
- Press `Backspace` to clear input
- Verify that input was cleared
- tests here
> fix(datetimepickerv2): enable to clear value in new time spinner

- packages/react/src/components/SuiteHeader/IdleLogoutConfirmationModal/IdleLogoutConfirmationModal.jsx
- packages/react/src/components/SuiteHeader/MultiWorkspaceSuiteHeader.test.jsx
- packages/react/src/components/SuiteHeader/SuiteHeader.jsx
- packages/react/src/components/SuiteHeader/SuiteHeader.test.jsx
**Summary**
- When rendering the `IdleLogoutConfirmationModal` component, check if the domain is set. Otherwise the `IdleTimer` may be instantiated with an undefined domain, which will create a cookie in the wrong domain.
- Checking if domain is null or undefined before instantiating the `IdleLogoutConfirmationModal` and `IdleTimer`.
- No functional changes expected in this fix.
- No functional changes expected in this fix.
> fix(SuiteHeader): Protecting the idle timer logic to avoid the creation of a cookie with an empty domain

- packages/react/src/components/TearSheet/TearSheet.story.jsx
Closes #3373 
**Summary**
- Storybook was not generating argsTable for `TearSheet` component
- Fix the bug in `TearSheet` story to make sure props show up in storybook doc.
- Go to TearSheet story
- Click on Doc tab
- Check argsTable should show component props and descriptions
- tests here
> fix(tearsheet): doc not generate props

- packages/react/src/components/CardCodeEditor/CardCodeEditor.test.e2e.jsx
- packages/react/src/components/Table/StatefulTable.jsx
- packages/react/src/components/Table/StatefulTable.test.jsx
- packages/react/src/components/Table/Table.jsx
- packages/react/src/components/Table/Table.main.story.jsx
- packages/react/src/components/Table/Table.story.helpers.jsx
- packages/react/src/components/Table/TableToolbar/TableToolbar.jsx
- packages/react/src/components/Table/tableReducer.js
- packages/react/src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Closes #3597 
**Summary**
- Add prop to `Table` to hide `Clear all filters` button
- Preserve filtering by search when `Clear all filters` button is clicked
- Add `hideClearAllFiltersButton` prop to `Table`
- Update `publicAPI` snapshot
- Modify `tableReducer` to preserve search after all filters have been cleared
- Update tests
- Go to [this story](https://deploy-preview-3600--carbon-addons-iot-react.netlify.app/?path=/story/1-watson-iot-table--playground)
- Disable `hasAdvancedFilter` in the `Sort & filter` knobs tab
- Select `hasFilter` to be `true` in the `Sort & filter` knobs tab
- Enable `hasSearch` and `hasFastSearch` in the `Search` knobs tab
- Type `toyota` in the table search bar
- Click on …
> fix(table): add prop to hide clear all filters button

- packages/react/src/components/DateTimePicker/DateTimePickerV2.jsx
- packages/react/src/components/DateTimePicker/DateTimePickerV2.story.jsx
- packages/react/src/components/DateTimePicker/DateTimePickerV2.test.e2e.jsx
- packages/react/src/components/DateTimePicker/DateTimePickerV2.test.jsx
- packages/react/src/components/DateTimePicker/DateTimePickerV2WithTimeSpinner.jsx
- packages/react/src/components/DateTimePicker/__snapshots__/DateTimePickerV2.story.storyshot
- packages/react/src/components/DateTimePicker/dateTimePickerUtils.js
- packages/react/src/components/TimePicker/TimePickerDropdown.jsx
- packages/react/src/components/TimePicker/_time-picker-dropdown.scss
- packages/react/src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Closes #3595 
**Summary**
- indicate 12 hours or 24 hours by the definition of prop `dateTimeMask`, specifically if the hour mask is `HH`, it means 24 hours, and `hh` means 12 hours , despite of whether  `dateTimeMask` has AM/PM for not. 
- make sure both 12 hours and 24 hours are supported for single select and range select
- updated stories and tests
For example,
If `dateTimeMask` is `YYYY-MM-DD HH:mm` this is 24 hours. The field shows value like `2020-04-01 13:34`. `TimePickerDropDown` is 24hours format like `13:34`.
If `dateTimeMask` is `YYYY-MM-DD HH:mm A` this is 24 hours with AM/PM. The field shows value like `2020-04-01 13:34 PM`. `TimePickerDropDown` is 24hours format like `13:34`.
If `dateTimeMask` is `YYYY-MM-DD hh:mm A` this is 12 hours with AM/PM.  The field shows value like …
> feat(datetimepickerv2): support both 12 and 24 hours time format

- packages/react/src/components/Card/__snapshots__/Card.story.storyshot
- packages/react/src/components/DateTimePicker/DateTimePickerV2.test.jsx
- packages/react/src/components/DateTimePicker/DateTimePickerV2WithTimeSpinner.jsx
- packages/react/src/components/DateTimePicker/DateTimePickerV2WithoutTimeSpinner.jsx
- packages/react/src/components/DateTimePicker/__snapshots__/DateTimePickerV2.story.storyshot
- packages/react/src/components/DateTimePicker/_date-time-pickerv2.scss
Closes #3571 
**Summary**
- There is a hidden ToolTip on the `FlyoutMenu`. We decide to set `overflow:hidden` on the `ToolTip` to make sure it does not take extra space .
- set `overflow:hidden` on ` iot--date-time-picker--trigger-button` and pass it in `FlyoutMenu` as part of the `buttonProps`
- changes in both `DateTimePickerV2WithTimeSpinner` and `DateTimePickerV2WithoutTimeSpinner`
- go to DateTimePickerV2 single select [story](https://deploy-preview-3602--carbon-addons-iot-react.netlify.app/?path=/story/2-watson-iot-experimental-%E2%98%A2%EF%B8%8F-datetimepickerv2--single-select)
- removed `padding: 3rem` on storybook-container 
- set width to 100% on …
> fix(datetimepickerv2): set overflow:hidden on hidden tooltip

- packages/react/src/components/DateTimePicker/DateTimePickerV2.test.jsx
- packages/react/src/components/DateTimePicker/DateTimePickerV2WithTimeSpinner.jsx
- packages/react/src/components/DateTimePicker/DateTimePickerV2WithoutTimeSpinner.jsx
- packages/react/src/components/DateTimePicker/_date-time-pickerv2.scss
Closes #3599 
**Summary**
- invalid text was clickable since it was inside of flyout menu. 
- moved it out so that it is not clickable. 
- fix(DateTimePickerV2WithTimeSpinner): move invalid text out of flyout menu
- fix(DateTimePickerV2WithoutTimeSpinner): move invalid text out of flyout menu
- added unit tests
- go to single select story
- enable invalid prop
- click on invalid text, make sure it does not open the flyout menu.
- tests here
> fix(datetimepickerv2): move invalid text out of flyout menu

- packages/react/src/components/DateTimePicker/DateTimePickerV2WithTimeSpinner.jsx
Closes #3605 
**Summary**
- humanValue on for single select is not too long, we will not show the tooltip which is for the case when humanValue is too long and is overflowed in the dateTimePicker field. 
- added check for single select on the tool tip
- go to single select [story](https://deploy-preview-3606--carbon-addons-iot-react.netlify.app/?path=/story/2-watson-iot-experimental-%E2%98%A2%EF%B8%8F-datetimepickerv2--single-select)
- hover on the field
- make sure no tooltip showed up
- tests here
> fix(datetimepickerv2): not show tooltip for single select

- packages/react/src/components/CardEditor/CardEditForm/CardEditFormItems/TableCardFormItems/TableCardFormContent.jsx
- packages/react/src/components/CardEditor/CardEditForm/CardEditFormItems/TableCardFormItems/TableCardFormContent.test.jsx
Closes #3609
**Summary**
- Remove thresholds of edited column from outer context.
- TableCardFormContent
Go to Setup page in Monitor;
Find an device type;
Click on Setup device type;
Select Dashboards tab;
Create a dashboard;
Add Data table card type;
Add a column;
Click on edit button of the new column;
Add threshold and save it;
Click again on edit button;
Check no duplicate threshold added to list
- tests here
> fix(tablecardformcontent): remove duplicate thresholds

- packages/react/src/components/PageTitleBar/__snapshots__/PageTitleBar.story.storyshot
- packages/react/src/components/SideNav/__snapshots__/SideNav.story.storyshot
- packages/react/src/components/Table/TableBody/TableBodyRow/TableBodyRow.jsx
- packages/react/src/components/Table/TableBody/TableBodyRow/__snapshots__/TableBodyRow.story.storyshot
- packages/react/src/components/Table/TableHead/TableHead.jsx
- packages/react/src/components/Table/__snapshots__/Table.main.story.storyshot
- packages/react/src/components/TableCard/__snapshots__/TableCard.story.storyshot
Closes #3485 
**Summary**
- fix the a11y violation by adding id prop on `TableExpandHeader`
According to the rule [H43: Using id and headers attributes to associate data cells with header cells in data tables](https://www.w3.org/TR/WCAG20-TECHS/H43) 
Header should use `id` prop for the any table cell to reference with. The default header for the first cell in `TableExpandRow` is set to `headers='expand'`. But we did not set an `id` on `TableExpandHeader` for the cell to refer to. 
The solution is to set ` id={`${tableId}-expand`} `on `TableExpandHeader` and `expandHeader={`${tableId}-expand`}` on `TableExpandRow`:
-fix(TableBodyRow): add id prop on TableExpandHeader
- go to table story [with row …
> fix(TableHead): add id prop on TableExpandHeader

- packages/react/src/components/EmptyState/EmptyState.jsx
- packages/react/src/components/EmptyState/EmptyState.story.jsx
- packages/react/src/components/EmptyState/EmptyState.test.jsx
- packages/react/src/components/EmptyState/_emptystate.scss
- packages/react/src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Closes #3545 
**Summary**
- Add 2 new props for arrangement and size
- Add css styles for new props
- Add tests
- Update storyshot
- Go to [this story](https://deploy-preview-3612--carbon-addons-iot-react.netlify.app/?path=/story/1-watson-iot-empty-states--playground)
- Change size from `default` to `small` in the knobs
- Verify applied changes according to [design guidelines](https://pages.github.ibm.com/ai-applications/design/components/empty-states/style)
- Change arrangement from `stacked` to `inline` in the knobs
- Verify applied changes according to [design guidelines](https://pages.github.ibm.com/ai-applications/design/components/empty-states/style)
**Regression Test (how to make sure this PR …
> feat(emptystate): add prop for arrangement and size

- packages/react/src/components/DateTimePicker/DateTimePickerV2WithTimeSpinner.jsx
There was a bug introduced causing invalid state when Input value was empty.
- go to [this](https://deploy-preview-3628--carbon-addons-iot-react.netlify.app/?path=/story/2-watson-iot-experimental-%E2%98%A2%EF%B8%8F-datetimepickerv2--single-select) story
- clear the input
- Input should not be in invalid state
> [DateTimePicker] empty value causing invalid state

- packages/react/src/components/TimePicker/TimePickerDropdown.jsx
- packages/react/src/components/TimePicker/TimePickerDropdown.test.jsx
Closes #3630 
**Summary**
- Fix selecting midnight in dropdown
- Adjust regexp validation for 24 hours format
- Go to [this story](https://deploy-preview-3634--carbon-addons-iot-react.netlify.app/?path=/story/1-watson-iot-timepickerdropdown--default)
- Open knobs panel and select 24-hour format (is24hours)
- Open dropdown and scroll to `00` in the hours scroller
- Verify that time in input and dropdown synced
- tests here
> fix(datetimepicker): adjust regexp validation for midnight

- packages/react/src/components/Table/tableReducer.js
- packages/react/src/components/Table/tableReducer.test.jsx
Closes #3491 
**Summary**
- Preserve filtering by search after sorting reset
- Replace sorting function in table reducer to sorting with filtering
- Go to [this story](https://deploy-preview-3640--carbon-addons-iot-react.netlify.app/?path=/story/1-watson-iot-table--playground)
- In the `Sort & filter` knobs enable `isSortable`
- In the `Search` knobs enable `hasSearch` and `hasFastSearch`
- Type some word in the search bar
- Click on some column to sort it
- Verify that column was sorted by ascending on the first click, by descending on the second click and returned back to default sort value on the third click
- tests …
> fix(table): preserve search filter after resetting sorting

- packages/react/src/components/Card/Card.test.e2e.jsx
- packages/react/src/components/Card/Card.test.jsx
- packages/react/src/components/Card/CardTitle.jsx
- packages/react/src/components/Card/__snapshots__/Card.story.storyshot
- packages/react/src/components/Card/_card-title.scss
- packages/react/src/components/ComboChartCard/__snapshots__/ComboChartCard.story.storyshot
- packages/react/src/components/Dashboard/__snapshots__/Dashboard.story.storyshot
- packages/react/src/components/Dashboard/__snapshots__/DashboardGrid.story.storyshot
- packages/react/src/components/GaugeCard/__snapshots__/GaugeCard.story.storyshot
- packages/react/src/components/Tooltip/index.jsx
Closes #3645 
**Summary**
- Updates for tooltips inside `CardTitle` component
1. Add `cursor: pointer` for truncated card title and subtitle with tooltip
2. Add window scroll listener to close tooltips
3. Replace `autoOrientation` prop in Carbon `Tooltip` to custom hook in order to adjust positioning
1. Go to the story [Card / Card / with ellipsed title tooltip & external tooltip](https://deploy-preview-3649--carbon-addons-iot-react.netlify.app/?path=/story/1-watson-iot-card-card--with-ellipsed-title-tooltip-external-tooltip)
1.1 Hover on card title and subtitle
1.2 Verify that cursor has changed to `pointer`
2. Go to the story [Card / Card / with ellipsed title tooltip & external …
> fix(card): tooltips enhacements

- packages/react/src/components/DateTimePicker/_date-time-pickerv2.scss
- packages/react/src/components/TimePickerSpinner/_time-picker-spinner.scss
Closes #3648 
**Summary**
- Position time picker in `DateTimePicker` to the center
- Add styles that explicitly position time picker to the center
- _The issue is not reproducable in Storybook_
- The issue happens due to other styles from different components in Graphite
- Local installation of PAL into Graphite shows that proposed fix would solve the issue
- tests here
> fix(datetimepickerv2): add styles to center time picker spinner

- packages/react/src/components/DateTimePicker/DateTimePickerV2.story.jsx
- packages/react/src/components/DateTimePicker/DateTimePickerV2WithTimeSpinner.jsx
- packages/react/src/components/DateTimePicker/DateTimePickerV2WithoutTimeSpinner.jsx
- packages/react/src/components/DateTimePicker/__snapshots__/DateTimePickerV2.story.storyshot
- packages/react/src/components/DateTimePicker/_date-time-pickerv2.scss
Closes #3619 
**Summary**
- If a child element sets `outline`, css` :focus `does not work on either child or parent element anymore in firefox.  
- The previous invalid style was applied to `${iotPrefix}--date-time-picker__box`, it sets `outline` to `$danger-01`. If I set :focus or :focus-visible on the same element. The outline stays `$danger-01`. And the parent `:focus outline` not working either. 
- I have to move the invalid style to the parent wrapper to make it work in firefox.
- move class to the wrapper element
- update the single select story to make sure tab key works
Tab key
- go to single select story
- check the invalid check box in knobs
- click on the text "DateTimePickerV2 Single …
> fix(DateTimePickerV2): :focus not working in firefox

- packages/react/src/components/Card/Card.test.e2e.jsx
- packages/react/src/components/Card/CardTitle.jsx
- packages/react/src/hooks/usePopoverPositioning.jsx
Closes #3682
**Summary**
- Add prop for auto alignment
- Modify `usePopoverPositioning` hook to calculate appropriate alignment for tooltip
- Add tests for tooltip in `Card`
- Go to [this story](https://deploy-preview-3683--carbon-addons-iot-react.netlify.app/?path=/story/1-watson-iot-card-card--with-ellipsed-title-tooltip-external-tooltip)
- In the knobs area change card size to `SMALL`
- Click on truncated card title
- Verify that tooltip is aligned to `start`
- tests here
> fix(card): auto alignment for title tooltip

- packages/react/src/components/SuiteHeader/IdleLogoutConfirmationModal/IdleLogoutConfirmationModal.jsx
- packages/react/src/components/SuiteHeader/IdleLogoutConfirmationModal/IdleLogoutConfirmationModal.test.jsx
- packages/react/src/components/SuiteHeader/MultiWorkspaceSuiteHeader.story.jsx
- packages/react/src/components/SuiteHeader/MultiWorkspaceSuiteHeader.test.jsx
- packages/react/src/components/SuiteHeader/SuiteHeader.jsx
- packages/react/src/components/SuiteHeader/SuiteHeader.test.jsx
- packages/react/src/components/SuiteHeader/hooks/useUiResources.js
- packages/react/src/components/SuiteHeader/util/uiresources.js
- packages/react/src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
**Summary**
- In `SuiteHeader` component, the following query parameters are now being appended to the logout (and inactivity logout) URL: `originIsAdmin` (when the page that triggered the logout was an admin page), `originWorkspaceId` (when the page that triggered the logout was a workspace-based page) and `originAppId` (when the page that triggered the logout was an application page).
- In `uiresources` API helper and `useUiResources` hook, support has been added for the `appId` parameter so that apps that instantiate `SuiteHeader` can pass the `appId` to the API that will be used by the component when assembling the logout URL (to include the `originAppId` parameter).
- Adjusting unit tests to account for the new query parameters added to the logout URL.
**Acceptance Test (how to …
> fix(suiteheader): Including some new query parameters to the logout URL in SuiteHeader and adding support to appId parameter in uiresources API

- packages/react/src/components/Table/baseTableReducer.js
- packages/react/src/components/Table/tableReducer.js
- packages/react/src/components/Table/tableReducer.test.jsx
Closes #3686 
**Summary**
- Reset table state after filtering and row selection has been cleared.
- Modify `tableReducer.js`
- Add tests
- Go to [this story](https://deploy-preview-3687--carbon-addons-iot-react.netlify.app/?path=/story/1-watson-iot-table--playground)
- In `Sort & filter` tab enable `hasFilter: true`
- In `Selections & actions` tab enable `useRadioButtonSingleSelect` and `hasRowSelection: multi`
- Apply some filter, for example `Select` column
- Select some row or click select all rows
- Unselect chosen rows
- Reset the filter
- Verify that table data returned to initial state
- tests here
**Things to look …
> fix(table): reset filter after selecting a row

- packages/react/src/components/Card/Card.test.e2e.jsx
- packages/react/src/components/Card/CardTitle.jsx
- packages/react/src/components/ComboChartCard/__snapshots__/ComboChartCard.story.storyshot
- packages/react/src/components/Dashboard/__snapshots__/Dashboard.story.storyshot
- packages/react/src/components/Dashboard/__snapshots__/DashboardGrid.story.storyshot
- packages/react/src/components/DashboardEditor/__snapshots__/DashboardEditor.story.storyshot
- packages/react/src/components/PageTitleBar/__snapshots__/PageTitleBar.story.storyshot
- packages/react/src/components/PieChartCard/__snapshots__/PieChartCard.story.storyshot
- packages/react/src/components/SideNav/__snapshots__/SideNav.story.storyshot
- packages/react/src/components/Table/Pagination.jsx
- packages/react/src/components/Table/TableToolbar/TableToolbar.jsx
- packages/react/src/components/Table/TableToolbar/TableToolbarAdvancedFilterFlyout.jsx
- packages/react/src/components/Table/TableToolbar/TableToolbarSVGButton.jsx
- packages/react/src/components/Table/TableToolbar/_table-toolbar.scss
- packages/react/src/components/Table/__snapshots__/Table.main.story.storyshot
- packages/react/src/components/Table/__snapshots__/TableColumnCustomization.story.storyshot
- packages/react/src/components/Table/__snapshots__/TableUserViewManagement.story.storyshot
- packages/react/src/components/Table/_pagination.scss
- packages/react/src/components/Table/_table.scss
- packages/react/src/components/TableCard/__snapshots__/TableCard.story.storyshot
- packages/react/src/components/TimeSeriesCard/__snapshots__/TimeSeriesCard.story.storyshot
- packages/react/src/globals/_mixins.scss
**Summary**
Changed approach to previous issues:
- #3682 Card tooltip - add throttle to scroll event listener (initial render of a tooltip caused micro-scrolling event, therefore tooltip closed itself, throttle for 10ms prevents this)
- #3278 Pagination in table - decrease padding slightly between `608px` and `500px` instead of hiding items per page block
- Carbon tooltips in table - change direction from `top` to `bottom` in table toolbar (due to `overflow: hidden`)
- Card tooltip: add `setTimeout` to add scroll event listener
- Table pagination: update css styles
- Tooltips in table toolbar: add props to change direction to `bottom`
**Card tooltip**
- Go to [this …
> fix(table): pagination, toolbar toolips; (card): tooltip

- packages/react/src/components/DashboardEditor/editorUtils.jsx
- packages/react/src/components/DashboardEditor/editorUtils.test.jsx
Closes https://github.com/carbon-design-system/carbon-addons-iot-react/issues/3674
**Summary**
- Within Dashboard Editor, a data table card with existing columns does not update the card JSON when the "Group by" multi-select has new items selected which are also added as columns. Similarly, when unchecking items from "Group by" multi-select they are not removed from groupBy array.
- fix(editorutils): update columns destination property when group by multiselect changes
- fix(editorutils): add test scenario for data table card data grouping
- adding/removing group by data items should correctly reflect in the card json
- …
> fix(editorUtils): update card JSON when group by multiselect changes

- packages/react/src/components/DateTimePicker/DateTimePickerV2WithTimeSpinner.jsx
- packages/react/src/components/DateTimePicker/DateTimePickerV2WithoutTimeSpinner.jsx
Closes #3703 
**Summary**
- When both top and bottom has not enough height for FlyoutMenu, it should open downwards.
- DateTimePickerV2WithoutTimeSpinner.jsx
- DateTimePickerV2WithTimeSpinner.jsx
- go to single select [story](https://deploy-preview-3704--carbon-addons-iot-react.netlify.app/?path=/story/2-watson-iot-experimental-%E2%98%A2%EF%B8%8F-datetimepickerv2--single-select)
- make sure the view is short, not enough for flyout menu from both top and bottom direction
- check flyout menu opens downwards instead of upwards
Before:
https://user-images.githubusercontent.com/24279794/214896543-e55bbecf-bbea-450f-b2fc-93533539e003.mov
After: 
https://user-images.githubusercontent.com/24279794/214896603-5 …
> fix(DateTimePickerV2): fix Flyoutmenu open direction

- packages/react/src/components/SuiteHeader/hooks/useUiResources.js
- packages/react/src/components/SuiteHeader/hooks/useUiResources.test.js
**Summary**
- Fixing the promise flow in the cached data flow of useUiResources (it was missing an await) and the `finally` statement was being called right away. It needs to be executed only after both callbacks are fired in `getCachedUiResourcesData()`.
- Added some tests to make sure that the loading state is true in the initial state of the hook
- Tested in an application with access to the GET /uiresources API and it was possible to notice that the loading state is true until the first callback of getCachedUiResourcesData() is fired.
> fix(suiteheader) Fixing the promise flow in the cached data flow of useUiResources (it was missing an await)

- packages/react/src/components/DashboardEditor/DashboardEditor.jsx
Closes #3672
**Summary**
- Fixed issue when removing image from image card
- [fix(dashboardeditor): fixed issue when removing image from image card](https://github.com/carbon-design-system/carbon-addons-iot-react/pull/3673/commits/b1164c7deb001ae4a0c55cc0ab3e221d29776455)
- Dashboard editor > Add image card > Drag or click to upload new image > Select an image with an invalid name eg. image$copy.png
- Click Save and close on top of the dashboard > Error will be displayed because of invalid image name, this is normal
- Now remove image from card > select another one > click Save and close again > Only new image should be uploaded and the dashboard should save without errors
**Regression Test (how to …
> fix(dashboardeditor): fixed issue when removing image from image card

- packages/react/src/components/FilterTags/FilterTags.jsx
- packages/react/src/components/FilterTags/FilterTags.test.jsx
- packages/react/src/components/FilterTags/_filter-tags.scss
- packages/react/src/components/Table/Table.jsx
- packages/react/src/components/Table/Table.main.story.jsx
- packages/react/src/components/Table/Table.story.helpers.jsx
- packages/react/src/components/Table/TablePropTypes.js
- packages/react/src/components/Table/mdx/Table.mdx
- packages/react/src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Closes #3710
**Summary**
- Add i18n prop for text in OverflowMenu displayed for truncated FilterTags
- Add i18n prop to FilterTags component
- Add default i18n prop for FilterTags inside Table component
- Update tests and docs
- Go to [this story](https://deploy-preview-3713--carbon-addons-iot-react.netlify.app/?path=/story/1-watson-iot-table--with-filtering)
- Enable: `hasAdvancedFilters`
- Click on `Enable overflow menu in filter tags for advanced filters`
- Re-enable `hasAdvancedFilters` in order to reset memoized filters
- See OverflowMenu for truncated filters displayed as `+1` (resize screen horizontally if it's not displayed) …
> feat(filtertargs): add prop for overflow menu text

- lerna.json
- packages/react/package.json
Last merge failed to publish due to duplicate version. This PR bumps up the version to the next patch.
> 8.10 - Fix version issue 

- packages/react/src/components/DateTimePicker/DateTimePickerV2.test.jsx
- packages/react/src/components/DateTimePicker/DateTimePickerV2WithTimeSpinner.jsx
- packages/react/src/components/DateTimePicker/dateTimePickerUtils.js
- packages/react/src/components/Header/_header.scss
Closes #3741
**Summary**
New check for date time mask is throwing error when `hasTimeInput` is used and  mask is provided that does not include time. This PR puts in an additional check to ensure that there is a value before running check.  
- Add check in our utilities file in `dateTimePickerUtils.js`
- Add check in our DateTimePicker file in `DateTimePickerV2WithTimeSpinner.jsx`
- Add test to ensure this functionality is covered in `DateTimePickerV2.test.jsx`
> fix(datetimepicker): add check for mask value

- packages/react/src/components/SuiteHeader/IdleLogoutConfirmationModal/IdleLogoutConfirmationModal.jsx
- packages/react/src/components/SuiteHeader/IdleLogoutConfirmationModal/IdleLogoutConfirmationModal.test.jsx
- packages/react/src/components/SuiteHeader/MultiWorkspaceSuiteHeader.test.jsx
- packages/react/src/components/SuiteHeader/SuiteHeader.jsx
- packages/react/src/components/SuiteHeader/SuiteHeader.test.jsx
Closes #
**Summary**
- Fixing an issue in the idle timeout confirmation dialog where changes in the current url (like appending a query parameter) without reloading the page caused the idle timer to restart and enter an invalid state where the countdown dialog would show up frozen. 
- Assembling the `originHref` parameter to be added to the logout URLs in such a way that the current page's query parameters are not included. An easier solution would be to just remove `originHref` for good, since MAS is no longer using it, but we cannot assume that other consumers of the component aren't using it, so it is better to keep it in order to not introduce breaking changes.
- Adding a null check in `surveyData` to avoid runtime errors if this property …
> fix(idlelogoutconfirmationmodal): Fixing an issue in the idle timer logic when query parameters are appended to the page

- packages/react/src/components/Card/Card.story.jsx
- packages/react/src/components/Card/Card.test.e2e.jsx
- packages/react/src/components/Card/CardToolbar.jsx
- packages/react/src/components/Card/_card-toolbar.scss
Closes #3733
**Summary**
- Auto-expand overflow menu (in card toolbar) depending on the content
- Replace width property with min-width
- Add max-width to 350px (min screen on mobile breakpoint)
- Go to [this story](https://deploy-preview-3759--carbon-addons-iot-react.netlify.app/?path=/story/1-watson-iot-card-card--with-ellipsed-title-tooltip-external-tooltip)
- In the knobs area change extra actions to multiple
- In "Multiple extra action" field add some long text to "itemText" property
- Open overflow menu in card toolbar
- Verify that overflow menu has expanded to fit content (max 350px)
- tests here
**Things to look …
> feat(card): set max width to extra actions overflow menu

- packages/react/src/components/Header/HeaderAction/HeaderActionPanel.jsx
- packages/react/src/components/SuiteHeader/SuiteHeader.test.jsx
- packages/react/src/components/SuiteHeader/suiteHeaderUtils.js
Closes #3755 
**Summary**
- __on Safari__
- Close header panel if clicked outside of the panel
- Add event listener to `document` to toggle panel state
- Add tests
- __on Safari__
- Go to [this story](https://deploy-preview-3758--carbon-addons-iot-react.netlify.app/?path=/story/1-watson-iot-ui-shell-suiteheader-multi-workspace--admin-page)
- Click on app switcher to open panel
- EDIT: <s>Click on any other header action</s> Click anywhere outside panel
- Verify that panel closed
- Click again on app switcher
- Navigate to some workspace
- Verify that panel is not closing on internal click events
- tests here
**Things to …
> fix(headeraction): close panel on other action click

- packages/react/src/components/Breadcrumb/Breadcrumb.jsx
- packages/react/src/components/Breadcrumb/Breadcrumb.story.jsx
- packages/react/src/components/Breadcrumb/Breadcrumb.test.e2e.jsx
- packages/react/src/components/Breadcrumb/__snapshots__/Breadcrumb.story.storyshot
- packages/react/src/components/Breadcrumb/_breadcrumb.scss
- packages/react/src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Closes #3700 
**Summary**
- Add prop to disable truncation
- Reset `flex-shrink` property in order to disable truncation
- Go to [this story](https://deploy-preview-3752--carbon-addons-iot-react.netlify.app/?path=/story/1-watson-iot-breadcrumb--with-truncation)
- Verify that first item is not truncated
- Add long text to "Breadcrumb 1 text" knob and short text to "Breadcrumb 2 text" knob
- Set "Disable truncation knob" to `last`
- Verify that last breadcrumb is not truncated
- tests here
> feat(breadcrumb): add option to disable truncation

- packages/react/src/components/DateTimePicker/DateTimePicker.jsx
- packages/react/src/components/DateTimePicker/DateTimePicker.test.jsx
- packages/react/src/components/DateTimePicker/DateTimePickerV2.jsx
- packages/react/src/components/DateTimePicker/DateTimePickerV2.test.jsx
Closes #3757 
**Summary**
- We need to make sure locale is 2 letters. If use passes in locale like "en-us", we make sure we use `en` instead of `en-us`
- Add locale checks for `DateTimePicker` and `DateTimePickerv2`
- go to single select story
- change locale to 'en-us'
- make sure no errors show up in the console
- tests here
> fix(datetimepickerv2): make sure locale is 2 letters

- packages/react/src/components/Table/TableBody/_table-dnd.scss
- packages/react/src/components/Table/TableBody/useTableDnd.jsx
Closes #3775
**Summary**
This fixes bug #3775.
Updates the CSS for table DnD to position initially show the overlay as display:none and at 0,0 so that it won't cause scrolling or be visible until needed.
In Storybook, view ?path=/story/1-watson-iot-table--with-drag-and-drop.
Check that there is NO vertical scrollbar (ensure "always show scrollbars" is on for your OS).
Start a drag and check that none appears.
Existing unit tests.
> fix(table): scrollbar shows when drag and drop starts

- packages/react/src/components/DateTimePicker/DateTimePickerV2.test.jsx
- packages/react/src/components/DateTimePicker/dateTimePickerUtils.js
Closes #3762 
**Summary**
- `TimePickerDropDown` follows the carbon guideline to show  placeholder text like `hh:mm XM` if it is 12hours format. To be consistent, we update DateTimePickerV2 single select placeholder text to show `XM` instead of `a` or `A`. 
- It should look like `YYYY-DD-MM hh:mm XM`
- Update in parseValue() in dateTimePickerUtils.js, specifically to single select. 
- go to single select [story](https://deploy-preview-3778--carbon-addons-iot-react.netlify.app/?path=/story/2-watson-iot-experimental-%E2%98%A2%EF%B8%8F-datetimepickerv2--single-select)
- update dateTimeMask knob to use 12 hour format like `YYYY-DD-MM hh:mm A`
- open flyout menu
- click on clear button
- check placeholder …
> fix(DateTimePickerv2): update placeholder text to show XM instead of 'a' or 'A'

- .github/CODEOWNERS
Monitor still heavily relies on this component. Amritha has asked to be added as code owner to help with their development. This component is still in experimental.
> chore(codeowners): add amritha as codeowners for this piece

- packages/react/src/components/Table/Table.main.story.jsx
- packages/react/src/components/Table/TableHead/ColumnHeaderRow/ColumnHeaderRow.jsx
- packages/react/src/components/Table/TableHead/FilterHeaderRow/FilterHeaderRow.jsx
- packages/react/src/components/Table/TableHead/TableHead.jsx
- packages/react/src/components/Table/TableSaveViewModal/__snapshots__/TableSaveViewModal.story.storyshot
- packages/react/src/components/Table/__snapshots__/Table.main.story.storyshot
- packages/react/src/components/TileGallery/__snapshots__/TileGallery.story.storyshot
Closes #3781
**Summary**
When drag and drop is enabled for the table and extra column is injected into the tbody to house the "drag handle". In the normal table header and extra, empty cell/column is added to line up and match the number of columns in the body. This is the same technique used for the "checkbox" select columns.
The issues was that not all headers were updated. There is are "filter" and "select columns" headers that can be added to the table. They were not updated with the extra column, so were not aligned right.
The fix is just to pass the "hasDragAndDrop" prop into those components and add the extra cell there when enabled.
ColumnHeaderRow.jsx and FilterHeaderRow.jsx were updated with that change.
Other changes are just to …
> fix(table): add column for DnD in the filter/manage columns headers

- packages/react/src/hooks/usePopoverPositioning.jsx
Closes #3784 
Closes #3773 
**Summary**
- From [Graphite bug](https://jsw.ibm.com/browse/GRAPHITE-62232)
- Disable auto-positioning when dropdown has equal space on the top and on the bottom of the input.
- Add `break` statement if dropdown overflow direction is `top-bottom`
- Couldn't reproduce the issue in Cypress. Tested manually.
- Go to [this story](https://deploy-preview-3786--carbon-addons-iot-react.netlify.app/?path=/story/2-watson-iot-experimental-%E2%98%A2%EF%B8%8F-datetimepickerv2--single-select)
- Using devtools add `padding-top: 10rem` to element with className `storybook-container`
- Resize screen vertically to see that dropdown auto-positions itself without errors
**Regression Test …
> fix(datetimepickerv2): auto position inf loop

- packages/react/package.json
- packages/react/src/components/PageTitleBar/PageTitleBar.jsx
- packages/react/src/components/PageTitleBar/PageTitleBar.test.e2e.jsx
- packages/react/src/components/PageTitleBar/PageTitleBar.test.jsx
- packages/react/src/components/PageTitleBar/__snapshots__/PageTitleBar.story.storyshot
- packages/react/src/components/PageTitleBar/_page-title-bar.scss
- packages/react/src/components/PageWizard/__snapshots__/PageWizard.story.storyshot
Closes #3785 
**Summary**
Fix of incorrect behavior of moving the `PageTitleBar` description to a tooltip when content was provided. It is now displayed below the title and only moved to the tooltip if the `collapsed` prop is passed.
I've also added a feature requested by @JordanWSmith15 where the condensed variation of the title bar (with breadcrumbs) now contains the tooltip as well so the description can be easily accessed.
- PageTitleBar logic fix to show description when content is provided and only move it to Tooltip if the condensed prop is true
- Tooltip with description added to condensed variation of page title bar to be easily accessed when header is "Dynamic" or "Condensed"
- Unit tests added and updated
- Snapshots updated
- …
> fix: PageTitleBar description 

- packages/react/src/components/Table/StatefulTable.test.jsx
- packages/react/src/components/Table/tableReducer.js
Closes #3790
**Summary**
- Select all checkbox state on initial render if some rows are selected
- Fix condition for indeterminate checkbox state
- Add unit test
- Go to [this story](https://deploy-preview-3801--carbon-addons-iot-react.netlify.app/?path=/story/1-watson-iot-table--with-selection-and-batch-actions)
- Verify that Select all checkbox is in indeterminate state
- tests here
> fix(table): select all checkbox state on initial render

- packages/react/src/components/Header/HeaderAction/HeaderAction.jsx
- packages/react/src/components/Header/HeaderAction/HeaderActionMenu.jsx
- packages/react/src/components/Header/HeaderAction/HeaderActionPanel.jsx
- packages/react/src/components/Header/HeaderPropTypes.js
- packages/react/src/components/Header/__snapshots__/Header.story.storyshot
- packages/react/src/components/Header/__snapshots__/Header.test.jsx.snap
- packages/react/src/components/SideNav/__snapshots__/SideNav.story.storyshot
- packages/react/src/components/SuiteHeader/MultiWorkspaceSuiteHeader.test.jsx
- packages/react/src/components/SuiteHeader/__snapshots__/MultiWorkspaceSuiteHeader.story.storyshot
- packages/react/src/components/SuiteHeader/__snapshots__/SuiteHeader.story.storyshot
Closes #3793
**Summary**
- Add `id` provided via props or generated based on index to header action items
- Add id prop Header component
- Update prop types / tests
- Go to [this story](https://deploy-preview-3796--carbon-addons-iot-react.netlify.app/?path=/story/1-watson-iot-ui-shell-suiteheader-multi-workspace--admin-page)
- Using dev tools verify that header action items has unique id
- tests here
> feat(SuiteHeader): add unique id to action items

- packages/react/src/components/Header/Header.test.e2e.jsx
- packages/react/src/components/Header/HeaderAction/HeaderActionMenu.jsx
- packages/react/src/components/Header/HeaderAction/__snapshots__/HeaderActionMenu.test.jsx.snap
- packages/react/src/components/Header/__snapshots__/Header.story.storyshot
- packages/react/src/components/Header/__snapshots__/Header.test.jsx.snap
- packages/react/src/components/Header/_header.scss
- packages/react/src/components/PageTitleBar/PageTitleBar.test.e2e.jsx
- packages/react/src/components/SuiteHeader/MultiWorkspaceSuiteHeader.test.jsx
- packages/react/src/components/SuiteHeader/SuiteHeader.test.jsx
- packages/react/src/components/SuiteHeader/SuiteHeaderAppSwitcher/SuiteHeaderAppSwitcher.jsx
- packages/react/src/components/SuiteHeader/SuiteHeaderAppSwitcher/__snapshots__/SuiteHeaderAppSwitcher.story.storyshot
- packages/react/src/components/SuiteHeader/__snapshots__/MultiWorkspaceSuiteHeader.story.storyshot
- packages/react/src/components/SuiteHeader/__snapshots__/SuiteHeader.story.storyshot
Closes #GRAPHITE-64846
**Summary**
- While running the a11y scan for `TabListTemplate` component in [Graphite storybook](https://pages.github.ibm.com/maximo-app-framework/graphite/main/react/storybook/?path=/story/templates-%F0%9F%96%A5-tablisttemplate--tablisttemplate) following violations were found and this PR is to fix those accessibility scan violations.
- To fix violations removed `role='menuitem'` from HeaderActions which is used in `<button />` and causing violations in a11y scans.
- Can be tested in storybook by running scan in Accessibility tab.  Functionally `Header` and `SuitHeader` should work as before.
- No …
> 3804 suite header and header action fix accessibility scan violations

- packages/react/src/components/Table/Table.jsx
- packages/react/src/components/Table/Table.test.jsx
[GRAPHITE-49742](https://jsw.ibm.com/browse/GRAPHITE-49742)
**Summary**
- If number of items in the table is more then `maxPages * paginationProps.pageSize`, then display SimplePagination without dropdowns
- Update Table pagination
- Update unit tests
- Go to [this story](https://deploy-preview-3808--carbon-addons-iot-react.netlify.app/?path=/story/1-watson-iot-table--with-pagination)
- In the knob area update `totalItems` to any number higher then 1000
- Verify that simple pagination appear with correct number of items
- tests here
> Fix table simple pagination

- packages/react/src/components/Header/Header.test.e2e.jsx
- packages/react/src/components/Header/HeaderAction/HeaderActionPanel.jsx
- packages/react/src/components/Header/__snapshots__/Header.story.storyshot
- packages/react/src/components/Header/__snapshots__/Header.test.jsx.snap
- packages/react/src/components/SuiteHeader/SuiteHeader.test.jsx
- packages/react/src/components/SuiteHeader/__snapshots__/MultiWorkspaceSuiteHeader.story.storyshot
- packages/react/src/components/SuiteHeader/__snapshots__/SuiteHeader.story.storyshot
[GRAPHITE-65278](https://jsw.ibm.com/browse/GRAPHITE-65278)
**Summary**
- Remove unnecessary aria-label on header panel
- Delete aria-label from header panel
- Update tests
- Go to [this story](https://deploy-preview-3812--carbon-addons-iot-react.netlify.app/iframe.html?id=1-watson-iot-ui-shell-suiteheader-multi-workspace--admin-page&args=&viewMode=story)
- Run IBM Accessibility Checker
- Verify no error in `The ARIA attributes 'aria-label' are not valid for the element <div> with implicit ARIA role 'generic'`
- tests here
> fix(HeaderActionPanel): remove unnecessary aria-label

- packages/react/src/components/SuiteHeader/SuiteHeaderAppSwitcher/MultiWorkspaceSuiteHeaderAppSwitcher.jsx
- packages/react/src/components/SuiteHeader/SuiteHeaderAppSwitcher/SuiteHeaderAppSwitcher.jsx
- packages/react/src/components/SuiteHeader/SuiteHeaderAppSwitcher/__snapshots__/MultiWorkspaceSuiteHeaderAppSwitcher.story.storyshot
- packages/react/src/components/SuiteHeader/SuiteHeaderAppSwitcher/__snapshots__/SuiteHeaderAppSwitcher.story.storyshot
- packages/react/src/components/SuiteHeader/__snapshots__/MultiWorkspaceSuiteHeader.story.storyshot
- packages/react/src/components/SuiteHeader/__snapshots__/SuiteHeader.story.storyshot
[GRAPHITE-63825](https://jsw.ibm.com/browse/GRAPHITE-63825)
**Summary**
- Firefox only: disable focus on header panel menu when panel is closed
- Add dynamic `tabIndex` for header panel menu when panel is closed
- Update snapshots
- In Firefox
- Go to [this story](https://deploy-preview-3813--carbon-addons-iot-react.netlify.app/iframe.html?id=1-watson-iot-ui-shell-suiteheader-multi-workspace--admin-page&args=&viewMode=story)
- Enable Mac Voice Over or JAWS
- Put focus on App Switcher button
- Press tab one more time
- Verify that Screen Reader announces leaving the page and don't read panel menu items
- tests here
**Things …
> fix(appswitcher): firefox focus

- packages/react/src/components/SuiteHeader/MultiWorkspaceSuiteHeader.story.jsx
- packages/react/src/components/SuiteHeader/SuiteHeader.jsx
- packages/react/src/components/SuiteHeader/SuiteHeader.mdx
- packages/react/src/components/SuiteHeader/SuiteHeader.story.jsx
- packages/react/src/components/SuiteHeader/SuiteHeader.test.jsx
- packages/react/src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
from Graphite
**Summary**
- Add extra prop to hide menu button
- Add `hideMenuButton` prop that removes menu button regardless of side nav props
- Add UT
- Update docs, storybook
- Go to [this story](https://deploy-preview-3815--carbon-addons-iot-react.netlify.app/?path=/story/1-watson-iot-ui-shell-suiteheader-multi-workspace--header-with-side-nav)
- Enable `hideMenuButton` knob
- Verify that menu button disappeared
- tests here
> feat(SuiteHeader): add option to hide menu

- packages/react/src/components/Table/_table.scss
Closes #3814
**Summary**
- Add min width for last pinned column
- Add min width css property to the last table cells
- Go to [this story](https://deploy-preview-3816--carbon-addons-iot-react.netlify.app/?path=/story/1-watson-iot-table--playground)
- In "Selections & actions" enable `hasRowActions`
- In "Column configuration" set `hasResize` and `pinColumn` last
- Verify that last column is pinned and visible
- tests here
> fix(table): add min width for pinned last column

- packages/react/src/components/ValueCard/ValueCard.story.jsx
- packages/react/src/components/ValueCard/ValueCard.test.jsx
- packages/react/src/components/ValueCard/ValueContent.jsx
- packages/react/src/components/ValueCard/__snapshots__/ValueCard.story.storyshot
[GRAPHITE-65817](https://jsw.ibm.com/browse/GRAPHITE-65817)
**Summary**
- Disable showing preview stub in edit mode
- Update ValueCard component to display value (if exists) instead of preview stub in edit mode
- Go to [this story](https://deploy-preview-3818--carbon-addons-iot-react.netlify.app/?path=/story/1-watson-iot-card-valuecard--editable)
- Verify that data is displayed in card, even though it is in edit mode
- Remove values from the knob
- Verify that preview stub "--" appeared when values do not exist
- tests here
> feat(ValueCard): disable preview in edit mode
