- .github/CODEOWNERS
need to update the codeowners file to auto generate approval
> Fix the CODEOWNERS file

- .github/CODEOWNERS
- .prettierrc.json
- .travis.yml
- package.json
- rollup.config.js
- src/components/ButtonEnhanced/ButtonEnhanced-story.js
- src/components/ButtonEnhanced/ButtonEnhanced-test.js
- yarn.lock
**Summary**
- Every push to development, we will automatically run testcases
- When a PR is promoted to master, it will also automatically publish a new release to git and npm
- build(.travis.yml): basic drop of CI build to trigger testcases and deployment through semantic-release
- build(package.json): add semantic release plugins for git and npm
> build(ci): add ci integration 

- .github/CONTRIBUTING.MD
- .github/README.MD
- .gitignore
- .travis.yml
- package.json
- yarn.lock
**Summary**
- Automatically publish storybook to github pages after every build: https://ibm.github.io/carbon-addons-iot-react/
- doc(README.MD) Update the README.MD to be targeted to consumers of the library, move all the setup stuff to the CONTRIBUTING.MD
- fix(package.json): add the missing webpack peer dependency into the devDependencies
- Notice the storybook publish, follow the instructions in the README to make sure they work.
> build(storybook): auto publish storybook after each build

- .github/README.MD
- .travis.yml
- jest.config.js
- package.json
- yarn.lock
**Summary**
- add badges for the travis build status and code coverage reporting to coveralls
- build(travis.yml): add coverage uploading to coveralls
- View the readme to see the badgess
> build(badges): add badges for coverage and build status

- .eslintrc
- src/components/Table/FilterHeaderRow/FilterHeaderRow-test.js
- src/components/Table/FilterHeaderRow/FilterHeaderRow.js
- src/components/Table/Table-story.js
- src/components/Table/Table.js
- src/components/__snapshots__/StorybookSnapshots-test.js.snap
**Summary**
- More table filter work
- fix clear single filter
- fix clear all filters
- calm eslint down a bit on destructuring
- wrap each table story with a decorator instead of explicit `<div>`s
- #7 
- Filter clearing fully works now in the storybook
> fix(table): Clear filter(s) functionality

- src/components/Table/Table-story.js
- src/components/Table/Table.js
- src/components/__snapshots__/StorybookSnapshots-test.js.snap
**Summary**
- Added column sort (basic lexicographic compare, no custom sorts yet)
- (see commits in PR)
- (none)
- View the "Table --> sort" story in storybook, verify that the 1st, 3rd, and 4th columns are sortable.
> feat(table): added column sort

- .travis.yml
- package.json
- yarn.lock
**Summary**
- `storybook-deployer` hasn't properly deployed the storybook to `gh-pages` in quite a while
- replace `storybook-deployer` with Travis CI's pages deployment provider
> fix(deploy): use travis pages deploy instead of buggy storybook-deployer

- src/components/Table/Table-test.js
- src/components/Table/Table.js
- src/components/__snapshots__/StorybookSnapshots-test.js.snap
- src/utils/componentUtilityFunctions.js
**Summary**
Added test for Table component.
Make sure all checks pass.
> chore(table): increase test coverage

- README.MD
**Summary**
- Minor fix on subtitle on string #32 (proposal)
- There is no previous issues related with this pull request
- There is no previous issues related with this pull request
- There is no break on code. Just a minor fix on certain subtitle on this `readme.md`
> Minor fix on subtitle

- .storybook/addons.js
- .storybook/config.js
- package.json
- src/components/ProgressIndicator/ProgressIndicator-story.js
- src/components/ProgressIndicator/ProgressIndicator.js
- src/components/ProgressIndicator/ProgressStep.js
- src/components/__snapshots__/StorybookSnapshots-test.js.snap
- yarn.lock
**Summary**
- Add ProgressIndicator component and story
- ProgressIndicator component
https://github.com/IBM/carbon-addons-iot-react/issues/31
> Wizard inline

- src/components/Table/Table-story.js
**Summary**
- teeny little bug with our stateful storybook where we weren't rendering indeterminate state correctly.
- Check that the Stateful storybook keeps the indeterminate state correctly.
> fix(table): small fix to stateful indeterminate state

- src/components/WizardInline/Wizard.css
- src/components/WizardInline/WizardContent/WizardContent.jsx
- src/components/WizardInline/WizardFooter/WizardFooter.jsx
- src/components/WizardInline/WizardHeader/WizardHeader.jsx
- src/components/WizardInline/WizardInline.jsx
- src/components/WizardInline/WizardInline.story.jsx
- src/components/WizardInline/WizardLeftSidebar/WizardSidebar.jsx
- src/components/__snapshots__/StorybookSnapshots.test.js.snap
**Summary**
- Add WizardInline component
- WizardInline component
- tests here
> feat(wizardinline): add wizardinline component

- src/components/Table/FilterHeaderRow/FilterHeaderRow.jsx
- src/components/Table/Table.jsx
- src/components/Table/Table.test.jsx
- src/components/Table/TableHead/TableHead.jsx
- src/components/__snapshots__/StorybookSnapshots.test.js.snap
- src/index.js
**Summary**
- first just splitting table into separate tablehead component that can be directly instantiated
- items_here
- tests here
> refactor(tablehead): split table into tablehead component

- src/components/Table/Table.jsx
- src/components/Table/Table.story.jsx
- src/components/__snapshots__/StorybookSnapshots.test.js.snap
**Summary**
- Add loading state to table with configurable row count
- add loading state to Table
- update loading story
- update snapshots
- Closes IBM/carbon-addons-iot-react#29
- all changes viewable in the storybook
> feat(table): loading state implementation and story

- src/components/Table/StatefulTable.jsx
- src/components/Table/Table.jsx
- src/components/Table/Table.story.jsx
- src/components/Table/Table.test.jsx
- src/components/Table/TableBody/TableBody.jsx
- src/components/Table/TableBody/TableBodyRow/TableBodyRow.jsx
- src/components/Table/TableBody/TableBodyRow/TableBodyRow.test.jsx
- src/components/__snapshots__/StorybookSnapshots.test.js.snap
- src/utils/componentUtilityFunctions.js
**Summary**
- Should be sending an onRowClicked event that's seprarate from the onRowExpanded or onRowSelected event
- add onRowClicked event
- Closes IBM/carbon-addons-iot-react#67
- Check the storybooks and make sure the onRowClicked event is being sent when clicking on the row.
> feat(table): add onRowClicked callback

- src/components/Table/StatefulTable.jsx
**Summary**
- simple fix to send the selected ids along with the batch action that was clicked to the onApplyBatchAction callback
- Closes IBM/carbon-addons-iot-react#68
- Test that when batch actions were used that the selectedIds are also sent along
> feat(table): send the selected ids along with the batch action

- src/components/Table/Table.jsx
- src/components/Table/TableToolbar/TableToolbar.jsx
- src/components/__snapshots__/StorybookSnapshots.test.js.snap
- src/styles/styles.js
- Add active style to ToolbarAction
- Closes IBM/carbon-addons-iot-react#70
- In the stateful story, switch between the two toolbars and notice that the icon fill changes to blue for the active one.
> fix(table): highlight selected toolbar toggle button

- src/components/StorybookSnapshots.test.js
- src/components/Table/Table.jsx
- src/components/Table/Table.story.jsx
- src/components/Table/Table.test.jsx
- src/components/Table/TableBody/TableBodyRow/TableBodyRow.jsx
- src/components/Table/TableCellRenderer/TableCellRenderer.jsx
- src/components/Table/TableHead/FilterHeaderRow/FilterHeaderRow.jsx
- src/components/Table/TableHead/FilterHeaderRow/FilterHeaderRow.test.jsx
- src/components/Table/TableHead/TableHead.jsx
- src/components/Table/TableHead/TableHead.test.jsx
- src/components/Table/TablePropTypes.js
- yarn.lock
**Summary**
- allow users to specify their own row height and column width for their tables
- test(storybooksnaps): unfortunately storybook doesn't like styled components and throws a console error which I can ignore.  I don't want to fail the testcase because of that.
- feat(table): pass all props that are passed to our Table to the underlying CarbonTable, this allows users to easily use all the CarbonTable features and set a className for the table that they can use to perform their own styling
- test(table): add 3 stories to show how to apply each custom style to the table
- Closes IBM/carbon-addons-iot-react#36
- Closes IBM/carbon-addons-iot-react#46
- check the 3 new stories, …
> feat(table): variable sizes for row and column

- src/index.js
**Summary**
- small fix, we just forgot to export StatefulTable for consumption
> fix(table): export StatefulTable

- src/components/Table/StatefulTable.jsx
**Summary**
- Prevent a a console error from being thrown if a consumer doesn't specify callback actions.
> fix(table): add better stateful table default prop checks

- src/components/Table/tableReducer.js
**Summary**
- Fix console errors for consumers who don't define optional props sort, filters, toolbar
> fix(table): improve null checks for stateful table reducers

- .eslintrc
- package.json
- src/components/NavigationBar/NavigationBar.jsx
- src/components/NavigationBar/NavigationBar.story.jsx
- src/components/Page/PageWorkArea.jsx
- yarn.lock
**Summary**
- Add workarea with overlay to navigation bar 
- Add workarea with overlay to navigation bar to prevent using the main view of the app while working in the work area
- Closes IBM/carbon-addons-iot-react#33
- Test the navigation bar story with workarea example
> feat(navbar): add workarea and overlay to navbar

- src/components/Table/StatefulTable.jsx
- src/components/Table/StatefulTable.test.jsx
- src/components/Table/StatefulTableMockReducers.test.jsx
- src/components/Table/Table.jsx
- src/components/Table/TableBody/RowActionsCell/RowActionsCell.jsx
- src/components/Table/TableBody/RowActionsCell/RowActionsCell.test.jsx
- src/components/Table/tableReducer.js
- src/components/Table/tableReducer.test.js
**Summary**
- bug where you couldn't pass a custom icon to the row action
- pass through the action props to the underlying button
- Check the existing row actions stories
> fix(rowactions): support custom icons

- README.MD
- package.json
**Summary**
- A couple super minor things to improve developer experience
- add `yarn start`, just a proxy for `yarn storybook`
- add `yarn test:update` to easily update snapshots without re-running failing snapshot tests via `test:watch`
- small documentation edit
> chore(devexp): nice to haves

- src/components/Table/StatefulTable.jsx
- src/components/Table/Table.jsx
- src/components/Table/Table.story.jsx
- src/components/Table/TableHead/ColumnHeaderRow/ColumnHeaderRow.jsx
- src/components/Table/TableHead/FilterHeaderRow/FilterHeaderRow.jsx
- src/components/Table/TableHead/TableHead.jsx
**Summary**
- add lightweight prop to table
- table
- tests here
> Lightweight table

- .storybook/webpack.config.js
- src/components/ProgressIndicator/ProgressIndicator.jsx
- src/components/WizardModal/WizardModal.jsx
- src/components/WizardModal/WizardModal.test.jsx
**Summary**
- need to add clickable indicator and call the validate function before moving to the next screen onclick
- fix(progress): added cursor styles to clickable indicators
- fix(validate): call validate if moving forward by clicking on a step
- test the Wizard Modal fixtures
> fix(wizardmodal): need to validate on click

- src/components/Table/Table.story.jsx
**Summary**
Cleaned up Table story (updated names, removed some test columns from the stateful example)
> chore(table): clean column definitions and naming in story

- src/components/Table/Table.jsx
- src/components/Table/Table.story.jsx
- src/components/Table/TableToolbar/TableToolbar.jsx
**Summary**
- Table content scroll, header should be fixed.
- Table content scroll
- Closes IBM/carbon-addons-iot-react#77
- Table container full width with more column than default should have the scroll
- Table container with max width (not full page) should have the scroll
> fix(table): properly support horizontal scroll

- src/components/Table/Table.jsx
- src/components/Table/Table.story.jsx
- src/components/Table/TableBody/RowActionsCell/RowActionsCell.jsx
- src/components/Table/TableBody/TableBody.jsx
- src/components/Table/TableBody/TableBodyRow/TableBodyRow.jsx
- src/components/Table/TableHead/FilterHeaderRow/FilterHeaderRow.jsx
- src/components/Table/TableHead/FilterHeaderRow/FilterHeaderRow.test.jsx
- src/components/Table/TableHead/TableHead.jsx
- src/components/Table/TablePropTypes.js
- src/components/Table/TableToolbar/TableToolbar.jsx
**Summary**
- Need to expose translatable labels for all components and features of the table
- added props through the entire chain to translate labels
- Closes IBM/carbon-addons-iot-react#71
- Try out the new story on stateful table with I18N strings and notice that they're all changed.
> fix(table): add translatable label props for all components and features of the table

- src/components/Table/Table.jsx
- src/components/Table/Table.story.jsx
- src/components/Table/TablePropTypes.js
- src/components/Table/TableToolbar/TableToolbar.jsx
- src/components/Table/baseTableReducer.js
**Summary**
- Small change to make the search placeholder easier to use
- Fix to the story to remove an unused prop for overflowActions
- Test the I18N story
> fix(table): gvt prop redesign to make it easier to consume

- src/components/Table/Table.jsx
- src/components/Table/Table.story.jsx
- src/components/Table/TablePropTypes.js
**Summary**
- fixes to the props to the empty state labels
> refactor(table): make it easier to translate the empty state labels

- src/components/Table/Table.jsx
- src/components/Table/Table.story.jsx
- src/components/Table/TableToolbar/TableToolbar.jsx
**Summary**
- fix prop capitalization to match
> fix(table): searchPlaceHolder capitalization

- rollup.config.js
- src/components/Header/Header.jsx
- src/components/HeaderMenu/HeaderMenu.test.jsx
- src/index.js
**Summary**
- expose the header component in our main index so downstream consumers can pick it up
- Closes IBM/carbon-addons-iot-react#142
- Pull the header to reuse
> fix(index): expose the header component so it can be reused

- .storybook/addons.js
- .storybook/config.js
- package.json
- yarn.lock
**Summary**
- Add the RTL plugin to our storybook
- Closes IBM/carbon-addons-iot-react#113
- Verify that the RTL plugin is in the storybook and works correctly
> test(storybook): add rtl support to storybook

- src/components/Page/PageHero.jsx
- src/components/ProgressIndicator/ProgressIndicator.jsx
- src/components/ProgressIndicator/ProgressIndicator.test.jsx
- src/components/Table/TableBody/TableBodyRow/TableBodyRow.test.jsx
- fix(PageHero): need to rename the component in the story
- fix(progressindicator): set to first step if none are passed
- test(progressindicator): add testcases to cover progress indicator
- test(tablerow): add more testcases to cover table row actions
- Verify the progress indicator stories in the storybook
> test(progress/table): add additional testcases

- src/components/Page/PageWorkArea.test.jsx
- src/index.js
**Summary**
- Exporting the PageWorkArea component so other teams can use and adding testcases
> fix(workarea): export so other teams can use

- src/index.js
**Summary**
- Need to export the wizardinline component so I can import it from external repos
> fix(wizardinline): need to export inline wizard for reuse

- package.json
**Summary**
- storybook dep is in wrong place
> fix(package): storybook rtl should be in dev deps

- src/components/BaseModal/BaseModal.story.jsx
- src/components/BaseModal/BaseModal.test.jsx
- src/components/ProgressIndicator/ProgressIndicator.jsx
- src/components/ProgressIndicator/ProgressIndicator.story.jsx
- src/components/ProgressIndicator/ProgressIndicator.test.jsx
- src/components/SimplePagination/SimplePagination.test.jsx
**Summary**
- test(basemodal): add additional testcases and stories
- test(progressindicator): add additional testcases
- fix(progressindicator): inherit would never get used
- test(simplepagination): add testcases
> test(progressindicator): add additional testcases to cover code

- rollup.config.js
- src/index.js
fixing export for Sidenav component
> refactor(sidenav): export component

- .github/ISSUE_TEMPLATE.MD
**Summary**
- adding a code sandbox to our issue template
> docs(issue): update with code sandbox link

- src/components/Table/AsyncTable/AsyncTable.jsx
- src/components/Table/StatefulTable.jsx
- src/components/Table/Table.jsx
- src/components/Table/Table.story.jsx
- src/components/Table/TableBody/RowActionsCell/RowActionsCell.jsx
- src/components/Table/TableToolbar/TableToolbar.jsx
**Summary**
- Add custom toolbar content next to the toolbar actions
- fix(onApplyRowAction): change the callback format to match onApplyBatchAction
- feat(table): add customToolbarContent
- Closes IBM/carbon-addons-iot-react#132
- Check the new custom toolbar story at bottom of the Table story list
> feat(table): add custom toolbar content next to the toolbar actions

- package.json
- rollup.config.js
- src/components/Table/TableToolbar/TableToolbar.jsx
- yarn.lock
**Summary**
- Update the table to the new column selection icon
- replaced the old column icon with the new one from carbon elements
- Closes IBM/carbon-addons-iot-react#134
- Verify the Stateful Table icon looks good for Column Selection
> feat(table): update to the new column icon

- src/components/Table/AsyncTable/AsyncTable.jsx
- src/components/Table/StatefulTable.jsx
- src/components/Table/Table.jsx
- src/components/Table/Table.story.jsx
- src/components/Table/TableBody/TableBody.jsx
- src/components/Table/TableBody/TableBodyRow/TableBodyRow.jsx
- src/components/Table/TableBody/TableBodyRow/TableBodyRow.test.jsx
- src/components/Table/TableHead/ColumnHeaderRow/ColumnHeaderRow.jsx
- src/components/Table/TableHead/ColumnHeaderRow/ColumnHeaderRow.test.jsx
- src/components/Table/TableHead/FilterHeaderRow/FilterHeaderRow.jsx
- src/components/Table/TableHead/TableHead.jsx
- src/components/Table/TableSkeletonWithHeaders/TableSkeletonWithHeaders.jsx
- src/components/Table/TableToolbar/TableToolbar.jsx
- src/components/Table/baseTableReducer.js
- src/components/Table/tableActionCreators.js
- src/components/Table/tableReducer.js
- src/components/Table/tableReducer.test.js
- src/styles/styles.js
**Summary**
- Add sticky selection to the table
- Add single selection to table
- Extend reducer to StatefulTable, enabling single selection
- Add new single selection story
- Update Snapshots, Tests
- Closes #202 
- check out the `with single selection` story, make sure the proper actions fire
- ensure there's no regressions in `with multi select and batch actions`
> feat(table): add single selection and associated story

- README.MD
- src/components/COMPONENT_TEST.md
**Summary**
- added a md file that shows the types of formal tests our components have been thru
- added docs for the component testing
- Closes IBM/carbon-addons-iot-react#156
- verify the new README links to the test statements
> docs(test): add test statements to our documentation

- src/components/StructuredList/StructuredList.jsx
- src/components/StructuredList/StructuredList.story.jsx
**Summary**
- Overflow text not displayed on hover
- Add `title` attribute to render browser tooltip
- Closes IBM/carbon-addons-iot-react#218
- Validate tooltip on cell text hover
> fix(structuredlist): add title to cell to render browser tooltip

- src/components/Table/Table.story.jsx
- src/components/Table/TableBody/RowActionsCell/RowActionsCell.jsx
**Summary**
- Three style fixes made to the table actions, see the bug list
- Add padding between them, make sure the buttons show when focused on, even if the row isn't hovered over, and fix the hover state of the overflow menu
- Closes IBM/carbon-addons-iot-react#199
- Closes IBM/carbon-addons-iot-react#207
- Closes IBM/carbon-addons-iot-react#208
- Verify the row actions cell in the table
> fix(table): row actions style bugs need to show

- src/components/FileDrop/index.js
- src/components/ProgressIndicator/ProgressIndicator.jsx
- src/components/ProgressIndicator/ProgressIndicator.story.jsx
- src/components/ResourceList/index.js
- src/components/SideNav/SideNav.test.jsx
- src/components/StructuredList/index.js
- src/index.js
**Summary**
- ProgressIndicator vertical design 
- New prop for vertical design 
- ProgressIndicator can be changed to vertical mode
> feat(progressindicator): vertical mode

- src/components/ProgressIndicator/ProgressIndicator.jsx
- src/components/ResourceList/index.js
- src/components/SideNav/SideNav.test.jsx
- src/components/StructuredList/index.js
- src/components/Table/TableDetailWizard/StatefulTableDetailWizard.jsx
- src/components/Table/TableDetailWizard/StatefulTableDetailWizard.test.jsx
- src/components/Table/TableDetailWizard/TableDetailWizard.jsx
- src/components/Table/TableDetailWizard/TableDetailWizard.story.jsx
- src/components/Table/TableDetailWizard/TableDetailWizard.test.jsx
- src/components/Table/TableDetailWizard/TableDetailWizardHeader/TableDetailWizardHeader.jsx
- src/components/Table/TableDetailWizard/TableDetailWizardHeader/TableDetailWizardHeader.test.jsx
- src/components/Table/TableDetailWizard/TableDetailWizardSidebar/TableDetailWizardSidebar.jsx
- src/components/WizardInline/WizardLeftSidebar/WizardSidebar.jsx
**Summary**
- New component - table detail wizard
ps. this PR depends on https://github.com/IBM/carbon-addons-iot-react/pull/210
- new component
- updates on tests cases
- Validate the component.
> Table detail wizard

- src/components/Table/Table.story.jsx
**Summary**
- Remove the table with async actions story as this is too advanced a usecase I think.
- docs(table): add better information and documentation to the table story to explain how to use the table
- Read the stateful story details and notice they should give more information
> docs(table): update our story docs to make this easier to use

- src/components/Header/HeaderMenu.jsx
- src/components/SideNav/AriaPropTypes.js
- src/components/SideNav/CarbonSideNav.jsx
**Summary**
Several copyright headers were mistakenly checked in
> chore(clean): remove source headers

- src/components/Page/PageHero.jsx
- src/components/Page/PageHero.story.jsx
- src/components/Page/PageHero.test.jsx
- src/components/Page/PageSwitcher.jsx
**Summary**
Add support for `selectedIndex` prop on PageHero switcher and refactor some props
> fix(pagehero): add selectedIndex to switcher and refactor props

- .github/ISSUE_TEMPLATE/ISSUE_TEMPLATE.MD
- .github/ISSUE_TEMPLATE/component-request-template.md
**Summary**
Add component request to issue template and update original to use the new format
- added ISSUE_TEMPLATE folder and moved issue templates to there
> feat(issues): added component request to issue template 

- package.json
- src/components/Table/Table.jsx
- src/components/Table/TableBody/TableBody.jsx
- yarn.lock
**Summary**
- Add lazy rendering support for Table component.
- Closes IBM/carbon-addons-iot-react#242
> feat(table): lazy rendering support

- src/components/WizardInline/WizardInline.jsx
**Summary**
- Class selector scope
- items_here
- tests here
> fix(wizard): class scope

- .storybook/webpack.config.js
- package.json
- src/components/Card/Card.jsx
- src/components/Card/Card.story.jsx
- src/components/Card/Card.test.jsx
- src/components/Dashboard/Dashboard.jsx
- src/components/Dashboard/Dashboard.story.jsx
- src/components/ValueCard/ValueCard.jsx
- src/components/ValueCard/ValueCard.story.jsx
- src/components/ValueCard/ValueCard.test.jsx
- src/constants/LayoutConstants.js
- src/constants/PropTypes.js
- src/utils/componentUtilityFunctions.js
- yarn.lock
**Summary**
- Add experimental data-viz components for dashboarding cases.  Dashboard Layout Engine and Value Cards
> feat(data-vis): add experimental data viz components for dashboarding

- src/components/Table/TableBody/TableBodyRow/TableBodyRow.jsx
**Summary**
Added on the StyledRowSingleSelection
bug
259
- tests here
> fix: StyledRowSingleSelection: added cursor as pointer

- src/components/StructuredList/StructuredList.jsx
- src/components/StructuredList/StructuredList.story.jsx
**Summary**
- summary_here
- items_here
- tests here
> fix(structured): only enable hover tooltip for content string/number

- package.json
- rollup.config.js
- src/index.js
- yarn.lock
**Summary**
- Wasn't exporting or building the experimental components.  Need to do this so I can consume them downstream in our Dashboard
- Verify that the components can be imported with a local yarn link
> fix(dashboard): need to export the components

- README.MD
- package.json
- src/components/Dashboard/Dashboard.jsx
- src/components/Dashboard/Dashboard.story.jsx
- src/components/Dashboard/DashboardHeader.story.jsx
- yarn.lock
**Summary**
- add doc updates to explain new test procedures
- fix(dashboard): stop dashboard from animating on initial render
> docs(readme): test updates

- src/components/Card/Card.jsx
- src/components/Dashboard/Dashboard.story.jsx
- src/constants/PropTypes.js
**Summary**
- Added tooltip prop to card
> Add Card tooltip

- config/jest/setup.js
- src/components/Dashboard/Dashboard.jsx
- src/components/Dashboard/Dashboard.story.jsx
- src/components/Dashboard/Dashboard.test.jsx
- src/constants/PropTypes.js
**Summary**
- Dashboard better validation and loading state
- feat(dashboard): add simple loading state, improve value cards next to pass through loading state
> Fix dashboard error

- src/components/Card/Card.jsx
- src/components/Dashboard/Dashboard.jsx
- src/components/Dashboard/Dashboard.story.jsx
- src/components/TableCard/TableCard.jsx
- src/components/TableCard/TableCard.story.jsx
- src/components/TableCard/TableCard.test.jsx
- src/constants/PropTypes.js
- src/utils/sample.jsx
**Summary**
- Fixed a style issue where table wasn't filling available card height
- Refactored props for TableCard to simplify (only pass data + columns underneath content prop, rather than the full Table prop interface)
- Some updates to the Dashboard story
> Table card prop refactor and styles fixes + dashboard story updates

- src/components/Dashboard/DashboardHeader.jsx
- src/components/ValueCard/ValueCard.jsx
- src/components/ValueCard/ValueCard.story.jsx
- src/constants/PropTypes.js
**Summary**
- Add empty states to the value card
- add skeleton text for the Dashboard Header if the Last Updated is loading
- Add empty states for the Value card
- Check the empty states for the Value card
> fix(card): value card empty state

- src/components/Dashboard/Dashboard.jsx
- src/components/Table/Table.jsx
- src/components/TableCard/TableCard.jsx
- src/components/TableCard/TableCard.story.jsx
- src/components/TimeSeriesCard/TimeSeriesCard.jsx
- src/components/ValueCard/ValueRenderer.jsx
**Summary**
- Minor fixes to time series, table, and value cards (see commits for more information)
> Minor card fixes

- src/components/Card/Card.jsx
- src/components/Dashboard/Dashboard.story.jsx
- src/components/ValueCard/Attribute.jsx
- src/components/ValueCard/UnitRenderer.jsx
- src/components/ValueCard/ValueCard.jsx
- src/components/ValueCard/ValueCard.story.jsx
- src/components/ValueCard/ValueRenderer.jsx
- src/constants/PropTypes.js
**Summary**
truncate long values and long titles in value cards (with long overlays)
- Check all the Card and Value Card stories
> fix(valuecard): truncate long values and long titles in valuecards

- config/jest/setup.js
- src/components/Card/Card.jsx
- src/components/ValueCard/Attribute.jsx
- src/components/ValueCard/ValueCard.jsx
- src/components/ValueCard/ValueCard.story.jsx
- Change the attribute layout based on width of the small card
> fix(valuecard): add borders and flip order for large width

- src/components/ValueCard/ValueCard.jsx
- src/components/ValueCard/ValueRenderer.jsx
**Summary**
-  small fix to handle undefined units
- Check the value card flyover with undefined units
> fix(valuecard): handle null units in flyover

- src/components/ValueCard/Attribute.jsx
- src/components/ValueCard/ValueCard.story.jsx
- src/components/ValueCard/ValueRenderer.jsx
- src/constants/PropTypes.js
**Summary**
- Added thresholding to value cards
> feat(valuecard): thresholds

- src/components/Card/Card.jsx
- src/components/ValueCard/Attribute.jsx
- src/components/ValueCard/ValueCard.jsx
- src/components/ValueCard/ValueCard.story.jsx
- src/components/ValueCard/ValueRenderer.jsx
- src/constants/LayoutConstants.js
- src/constants/PropTypes.js
**Summary**
-  Set of fixes to ValueCards
- fix(Card): adjusted padding and alignment of content
- fix(Attribute): added small value rendering 
- fix(Attribute): added tooltip for constraint
- fix(Attribute): used title/label instead of secondary value to render Text titles for small cards
- fix(ValueCard): only render one attribute for small cards
- fix(ValueCard): pass isSmall title downstream for smaller Attribute values
- Check all the Value Card stories for styles
> Feat valuecards thresholds

- src/components/Card/Card.jsx
- src/components/Dashboard/Dashboard.jsx
- src/components/Dashboard/Dashboard.story.jsx
- src/components/ListCard/ListCard.jsx
**Summary**
- add i18n labels to top-level Dashboard and pass through to Card strings that need translation
- Check the new i18n stories for dashboard
> Fix dashboard i18n

- src/components/Card/Card.jsx
- src/components/Dashboard/Dashboard.jsx
- src/constants/PropTypes.js
fix the proptypes in Card and a typo in the defaultProps for Card
> fix(dashboard): i18n need to come in as props

- package.json
- src/components/Card/Card.jsx
- src/components/Dashboard/Dashboard.jsx
- src/components/Dashboard/Dashboard.test.jsx
- src/components/TimeSeriesCard/TimeSeriesCard.jsx
- src/components/ValueCard/ValueCard.jsx
- src/components/ValueCard/ValueCard.story.jsx
- src/components/ValueCard/ValueCard.test.jsx
- src/constants/PropTypes.js
- yarn.lock
**Summary**
- Make attributes a child of the content object
- Verify all the ValueCard stories
> fix(valuecard): attribute field should be child of content

- src/components/Card/Card.jsx
- src/components/Dashboard/Dashboard.story.jsx
- src/components/ListCard/ListCard.jsx
- src/components/TableCard/TableCard.jsx
- src/components/ValueCard/ValueCard.jsx
- src/components/ValueCard/ValueCard.story.jsx
- src/components/ValueCard/ValueCard.test.jsx
- src/constants/LayoutConstants.js
**Summary**
- Added a dashboard story to help test a variety of permutations of value cards across sizing breakpoints
- Includes minor refactoring
> Add value card gallery dashboard story

- package.json
- src/components/TimeSeriesCard/TimeSeriesCard.jsx
if values not set
**Summary**
- small fix to handle when values is null
> fix(linechart): npe on values

- src/components/ValueCard/Attribute.jsx
- src/components/ValueCard/ValueCard.jsx
- src/components/ValueCard/ValueCard.story.jsx
- src/components/ValueCard/ValueRenderer.jsx
**Summary**
- small fixes to truncation in xsmallwide cards and precision in xsmall cards
- small fix to the HR color to match that of the structured list
- added extra testcases to cover the two possible layouts of xsmallwide cards
- Verify the Value cards
> fix(valuecard): fix to support precision 1 for all cards

- .github/ISSUE_TEMPLATE/standard-issue-template.MD
**Summary**
- Fix issue template so it will appear in the options for templates on issue request
> fix(issues): rename issue template

- src/components/Card/Card.jsx
- src/components/ValueCard/ValueCard.jsx
- src/components/ValueCard/ValueCard.story.jsx
**Summary**
- Show a preview of the card's future contents when isEditable is true
- Verify the newly added storybook story for editable value cards
> feat(valuecard): show preview when isEditable is true

- src/components/Dashboard/Dashboard.jsx
- src/components/Dashboard/DashboardHeader.jsx
- src/components/FileDrop/FileDrop.jsx
- src/components/FileDrop/FileDrop.story.jsx
**Summary**
- two small fixes to dashboard and filedrop
- fix(filedrop): handle multiple false correctly if you try and import multiple different files
- fix(dashboard): hide the last updated section if dashboard is in the editable state
- test the filedrop (single) and dashboard editable stories
> fix(dashboard): small dashboard and file drop fixes to support the Dashboard editor

- src/components/Page/EditPage.jsx
- src/components/Page/EditPage.story.jsx
- src/components/Page/PageHeader.jsx
- src/components/Page/PageHeader.story.jsx
- src/components/WizardInline/WizardHeader/WizardHeader.jsx
**Summary**
- feat, add new edit page component to support Editing an Object in a Fullscreen view, requested by Luke
- Test new Edit Page story, verify the existing WizardInline story
> feat(editpage): new edit page component

- src/components/Page/EditPage.jsx
- src/components/Page/PageHeader.jsx
- src/components/WizardInline/WizardHeader/WizardHeader.jsx
- src/index.js
Forgot to export edit page in the index
> fix(editpage): need to export it so it can be used downstream

- src/components/Dashboard/Dashboard.jsx
- src/components/Page/EditPage.jsx
Also fixes console log error with our prop types
> fix(editpage) should not dismiss page if an error is thrown

- README.MD
**Summary**
- some minor updates to the readme, improved formatting
- need to trigger a breaking change since we haven't thus far in the `beta` branch commit history.
- IBM/carbon-addons-iot-react#304
> docs(readme): update for beta, trigger breaking change

- src/components/TimeSeriesCard/TimeSeriesCard.jsx
- src/components/TimeSeriesCard/TimeSeriesCard.story.jsx
- src/components/TimeSeriesCard/timeSeriesUtils.js
- src/components/TimeSeriesCard/timeSeriesUtils.test.js
**Summary**
- Updates in component timeseries chart card
- Custom line color
- Y-axis label format for large/small values
- X-axis label format for hour interval in different days
- Unit on y-axis labels
- New stories for use cases
> Updates on timeseries chart

- src/components/Table/TableBody/RowActionsCell/RowActionsCell.jsx
**Summary**
- summary_here
- items_here
- Closes IBM/carbon-addons-iot-react#345
- tests here
> fix(table): pass disabled property to OverflowMenuItem

- src/components/Card/Card.jsx
- src/components/Dashboard/Dashboard.story.jsx
- src/components/TimeSeriesCard/TimeSeriesCard.story.jsx
- src/constants/PropTypes.js
**Summary**
- Pass `timeRange` enum prop through to card in order to update the time range select
> fix(timeseriescard): pass timeRange enum down to card

- src/components/FileDrop/FileDrop.jsx
- src/components/Page/EditPage.jsx
**Summary**
- fixes to FileDrop and EditPage needed to support Editable Dashboards
- fix(FileDrop): translate the untranslated labels
- feat(FileDrop): pass through the classname to allow custom layouts
- fix(EditPage): Footer should be fixed to bottom of screen
> fix(editpage): style fixes needed for editable page

- src/components/ValueCard/ValueCard.jsx
- src/index.js
**Summary**
- Export a method so that downstream consumers can run their own validation
> feat(valuecard): export max attribute count for value card

- README.MD
**Summary**
- Minor update to provide a message regarding `beta`
> docs(readme): add beta message

- src/components/Dashboard/Dashboard.story.jsx
- src/components/TimeSeriesCard/TimeSeriesCard.jsx
**Summary**
- Re-render chart when data has changed
- items_here
- tests here
> chore(render): fix on re-render the chart to get latest data

- src/components/TimeSeriesCard/TimeSeriesCard.story.jsx
add locale parameter and extra testcase and force a build
> feat(timeseries): add locale parameter

- src/components/TimeSeriesCard/TimeSeriesCard.jsx
See below I was getting Null Pointers when rendering the initial TimeSeries Chart
> fix(timeseries): NPE check missing

- src/components/TimeSeriesCard/TimeSeriesCard.jsx
- src/components/TimeSeriesCard/TimeSeriesCard.story.jsx
Empty state was bouncing when memoizing
> fix(timeseries): prevent bounce on empty state by memoizing

- src/components/Card/Card.jsx
- src/components/Card/Card.story.jsx
- src/components/Dashboard/Dashboard.story.jsx
- src/utils/sample.jsx
- yarn.lock
**Summary**
- Adds support for additional time ranges in Card Header
- Adjust a time series range in the Dashboard `basic` story.
> feat(card): add time range and period options

- package.json
- src/components/TimeSeriesCard/TimeSeriesCard.jsx
- src/components/TimeSeriesCard/TimeSeriesCard.story.jsx
**Summary**
- Small updates to the labels based on interval, to maximize space (see images below)
- Check the timeseries stories
> fix(timeseries): adjust labels based on interval, update carbon charts

- src/components/Table/StatefulTable.jsx
- src/components/TileCatalog/StatefulTileCatalog.jsx
- src/components/TimeSeriesCard/TimeSeriesCard.jsx
1.  Console error about missing width/height prop
2. Locale set default to `en`
3. Tooltip formatter when high numbers and when unit  prop provided
> Feat timeseries carbon charts - issues fixes

- src/constants/PropTypes.js
**Summary**
- update PropTypes for card for range, interval
> chore(card): update prop types to match new enums for range

- package.json
- src/components/Card/Card.jsx
- src/components/Card/Card.story.jsx
- src/components/Table/StatefulTable.jsx
- src/components/TileCatalog/StatefulTileCatalog.jsx
- src/components/TimeSeriesCard/TimeSeriesCard.jsx
- src/components/TimeSeriesCard/TimeSeriesCard.story.jsx
**Summary**
- Small UX change to close the Range Picker once you've selected a range, since it's currently the only thing in there.  Also cleaned up a couple of console errors.
- Test out the new range picker stories for the Card
> fix(timeseries): hide the range after selection

- src/components/TimeSeriesCard/TimeSeriesCard.jsx
- src/components/TimeSeriesCard/TimeSeriesCard.story.jsx
**Summary**
- Y-Axis not overlapping on 0 y-axis
- Updates for Y max value in data points
> Feat timeseries carbon charts

- src/components/TimeSeriesCard/TimeSeriesCard.story.jsx
**Summary**
- The fix is actually contained in Claudia's previous commit, this push is just to trigger the release build
> fix(timeseries): small fix to y-axis labels to stop overlap

- src/components/TimeSeriesCard/TimeSeriesCard.jsx
- src/components/TimeSeriesCard/TimeSeriesCard.story.jsx
**Summary**
-  Timeseries chart
- Simple xlabels updates
> fix(chart): fix on xlabels

- src/components/Hero/Hero.jsx
- src/components/Hero/Hero.story.jsx
- src/components/Table/StatefulTable.jsx
- src/components/TileCatalog/StatefulTileCatalog.jsx
- src/components/TimeSeriesCard/TimeSeriesCard.jsx
**Summary**
- New Hero component
1. Simple with description
2. Hero with breadcrumb
3. Hero with breadcrumb and secundary navigator
> Hero component

- src/components/Hero/Hero.jsx
- src/components/Hero/Hero.story.jsx
- src/components/SecondaryNavigator/SecondaryNavigator.jsx
- src/components/SecondaryNavigator/SecondaryNavigator.story.jsx
- yarn.lock
**Summary**
- New SecondaryNavigator component
- Updated Hero to use Breadcrumb
- Verify the Hero and SecondaryNavigator stories
> feat(secondarynavigator): new component and updated Hero to use breadcrumb

- src/components/Hero/Hero.jsx
**Summary**
- Minor updates to hero margins
> fix(hero): update margins

- src/components/Dashboard/Dashboard.jsx
- src/constants/LayoutConstants.js
**Summary**
- export image card type
> fix(imagecard): add image card export type

- src/components/ImageCard/ImageCard.jsx
**Summary**
- ImageCard should be expandable
- Closes IBM/carbon-addons-iot-react#399
- Render an image card inside a dashboard and click on expand button
> feat(imagecard): add expand button

- package.json
- src/components/StructuredList/StructuredList.story.jsx
- src/components/Table/Table.story.jsx
- yarn.lock
**Summary**
Upgraded `@storybook/addons-info` to alpha version to get fix for code blocks in our stories
- Upgraded `package.json` to alpha version
- Added back code blocks for `StructuredList.story.jsx` and `Table.story.jsx`
- Closes IBM/carbon-addons-iot-react#325
- Check out the stories for the two components above and you should see code blocks. Not all stories have code blocks, FYI
> Upgrade storybook

- src/components/Dashboard/DashboardHeader.jsx
- src/components/Hero/Hero.jsx
- src/components/Table/StatefulTable.jsx
- src/components/TileCatalog/StatefulTileCatalog.jsx
- src/components/TimeSeriesCard/TimeSeriesCard.jsx
- src/constants/PropTypes.js
**Summary**
- Fix to the Dashboard title to match our other Page Hero size
- fix(Hero): Uniqueify breadcrumb elemnt
- fix(TimeSeriesCard): allow blank value
- fix(*) a few reformatting things by prettier
- Verify Dashboard and Cards stories
> fix(console): throwing unnecessary console errors in the card and page hero components

- src/components/Hero/Hero.jsx
- src/components/Hero/Hero.story.jsx
- src/components/Table/TableSkeletonWithHeaders/TableSkeletonWithHeaders.jsx
**Summary**
- Add isLoading prop to Hero
- fix(TableSkeletonHeaders): assume 10 rowcount if not passed
- Check out new isLoading story for Hero
> feat(hero): support isLoading prop

- README.MD
**Summary**
- Add a netlify badge to our `master` readme as a thanks for Netlify upgrading our team to the [free open source plan](https://www.netlify.com/legal/open-source-policy/)
> chore(readme): add netlify badges to master

- package.json
- src/components/ImageCard/ImageCard.jsx
- src/components/ImageCard/ImageCard.story.jsx
- yarn.lock
**Summary**
- Add hotspots support to ImageCard
- Closes IBM/carbon-addons-iot-react#411
- Verify if ImageCard storybook contains hotspots
> feat(imagecard): hotspots support

- config/jest/setup.js
- package.json
- src/components/Table/Table.jsx
- src/components/Table/TableHead/TableHead.jsx
- src/components/Table/TableToolbar/TableToolbar.jsx
- src/components/TableCard/TableCard.jsx
- src/components/TableCard/TableCard.story.jsx
- src/components/TimeSeriesCard/timeSeriesUtils.js
- src/components/TimeSeriesCard/timeSeriesUtils.test.js
- yarn.lock
**Summary**
- improve the isEditable state to match the mockup for TableCard that Cynthia supplied
- fix(TableCard.story): removed story that was throwing console error until we can support this usecase without throwing console error
- Verify the isEditable state
> fix(tablecard): improve isEditable state for timestamp columns

- src/components/ImageCard/ImageCard.jsx
- src/components/ImageCard/ImageCard.story.jsx
**Summary**
- add placeholder image when the image card is in edit mode and no image has been uploaded
- check the new isEditable story
> fix(imagecard): show placeholder in edit mode

- package.json
- yarn.lock
**Summary**
- summary_here
- items_here
- tests here
> fix(imagecard): update to get some fixes

- src/components/Dashboard/Dashboard.story.jsx
- src/components/ImageCard/ImageCard.jsx
**Summary**
- Fixes ImageCard fullscreen button
- Open Dashboard storybook and click on ImageCard fullscreen button
> fix(imagecard): add fullscreen callback

- src/components/Table/TableToolbar/TableToolbar.jsx
- src/components/TableCard/TableCard.jsx
- src/components/TimeSeriesCard/timeSeriesUtils.js
- src/components/TimeSeriesCard/timeSeriesUtils.test.js
**Summary**
- Icon filter updated
- The timestamp is shown as `D MMMM YYYY HH:mm`
- Editable showing fake data
> Table card fixes

- package.json
- src/components/ImageCard/ImageCard.jsx
- yarn.lock
**Summary**
- Temporarily hide minimap
- Run storybooks and see that minimap is hidden for ImageCard
> fix(imagecard): temporarily hide minimap

- package.json
- src/components/ImageCard/ImageCard.jsx
- yarn.lock
**Summary**
- Fix minor issues with ImageCard movement controls
- Closes https://github.ibm.com/wiotp/monitoring-dashboard/issues/193
- Closes https://github.ibm.com/wiotp/monitoring-dashboard/issues/194
- Try to move an image using Storybook
> feat(imagecard): add movement

- src/components/Table/AsyncTable/AsyncTable.jsx
- src/components/Table/StatefulTable.jsx
- src/components/Table/tableActionCreators.js
- src/components/Table/tableReducer.js
- src/components/TableCard/TableCard.jsx
- src/components/TableCard/TableCard.story.jsx
- src/utils/componentUtilityFunctions.js
- src/utils/sample.jsx
- Table component support timestamp sort
-  Clear button overlay on filter (Fix)
-  Table card support `threshold`
- Table card support export content in CSV
*Filter Fix*:
> Table card

- src/components/WizardInline/WizardInline.jsx
- src/components/WizardInline/WizardInline.story.jsx
**Summary**
- moving the wizard error to the top of the wizard
- Look at the wizardinline error story
> fix(wizardinline): error is hidden at the bottom of the scrollable wizard

- src/components/Dashboard/Dashboard.jsx
- src/components/Dashboard/Dashboard.story.jsx
**Summary**
- add a prop in `Dashboard` to conditionally render a left sidebar
- View the 'sidebar' story.  Ensure the 'basic' story renders normally.
> feat(dashboard): add sidebar prop

- src/components/ImageCard/Hotspot.jsx
- src/components/ImageCard/ImageCard.jsx
**Summary**
- summary_here
- items_here
- tests here
> fix(build): fix the build for imagecard

- src/components/Card/Card.jsx
**Summary**
- Remove card border
- Card should no longer have border
> fix(card): remove border

- src/components/ImageCard/Hotspot.jsx
- yarn.lock
**Summary**
- Enable hotspots clicks in ImageCard
- Closes https://github.ibm.com/wiotp/monitoring-dashboard/issues/207
- Run storybook and click on a hotspot using ImageCard
> fix(imagecard): add pointer events to hotspots

- src/components/Page/PageHeader.jsx
- src/components/Table/TableHead/TableHead.jsx
- src/components/TableCard/TableCard.jsx
- src/components/TimeSeriesCard/TimeSeriesCard.jsx
- src/components/TimeSeriesCard/TimeSeriesCard.story.jsx
- src/components/TimeSeriesCard/timeSeriesUtils.js
- src/components/TimeSeriesCard/timeSeriesUtils.test.js
- src/components/WizardInline/WizardHeader/WizardHeader.jsx
- src/components/WizardInline/WizardInline.jsx
- src/constants/PropTypes.js
- yarn.lock
Allow the title attribute to be optional
improve the time series card's sample data to take interval into account
> fix(wizardinline): allow title to be optional

- src/components/ImageCard/ImageHotspots.jsx
**Summary**
- Fix minimap and guide position when moving image.
- Move image using Storybook and watch if the minimap position is corresponding to the actual view area.
> fix(imagecard): fix minimap and guide position

- src/components/Dashboard/Dashboard.story.jsx
**Summary**
- Add hotspots to ImageCard in Dashboard storybook.
- Run Dashboard storybook and check if ImageCard has hotspots on it.
> feat(imagecard): add hotspots to image card in dashboard

- src/components/Card/Card.jsx
- src/components/Dashboard/Dashboard.jsx
**Summary**
- Modified expanded card to render at 100% width/height with 50px padding
> fix(card): fix expanded card rendering

- src/components/ImageCard/ImageHotspots.jsx
**Summary**
- Make container background color configurable.
- Change container background color using ImageCard storybook.
> feat(imagecard): add background color as prop

- src/components/ImageCard/ImageCard.jsx
- src/components/ImageCard/ImageHotspots.jsx
- src/components/ImageCard/ImageHotspots.story.jsx
**Summary**
- Simplify code and fix a small bug on image resizing for fullscreen.
> Imagecard fullscreen

- src/components/Table/TableBody/TableBodyRow/TableBodyRow.jsx
**Summary**
- fix the extraneous isRowSelection event
> fix(table): remove extraneous isRowSelection attribute for console

- src/components/ImageCard/ImageHotspots.jsx
**Summary**
- Change ImageCard zoom to target center and not top left.
- Run ImageCard using storybook and zoom in.
> fix(imagecard): fix zoom target to center

- README.MD
**Summary**
- Minor update, self explanatory title
- update readme.md
> chore(readme): update links, references, install notes for 1.x branch

- src/components/Dashboard/DashboardHeader.jsx
- src/components/ImageCard/ImageHotspots.jsx
- src/components/Table/StatefulTable.jsx
- src/components/TableCard/TableCard.jsx
- src/components/TableCard/TableCard.story.jsx
- src/components/TableCard/TableCard.test.jsx
- src/components/TileCatalog/StatefulTileCatalog.jsx
- src/components/TimeSeriesCard/TimeSeriesCard.jsx
- src/constants/PropTypes.js
**Summary**
- fix(DashboardHeader): don't show loading text if there's no LastUpdatedLabel
- fix(TableCard): the highest severity matching threshold should be shown
- fix(TableCard): The Column based threshold doesn't show on column 0
- Also a few prettier fixes to TileCatalog
- Test the table card threshold stories
> fix(tablecard): fix issues with multi-column thresholding

- src/components/ImageCard/Hotspot.jsx
**Summary**
- updated styling for hotspots
> Update image card hotspot styling

- src/components/Page/EditPage.jsx
- src/components/WizardInline/WizardInline.jsx
- src/components/WizardInline/WizardInline.story.jsx
**Summary**
- Adds breadcrumb support to the wizard
- feat(EditPage): allow the onSave handler to return false to prevent the Page from closing
- Verify the WizardInline stories
> feat(wizardinline): add first class breadcrumb support to wizard

- src/components/Dashboard/Dashboard.jsx
- src/components/Dashboard/Dashboard.story.jsx
- src/components/Dashboard/DashboardHeader.jsx
- src/components/Dashboard/DashboardHeader.story.jsx
**Summary**
- feat(Dashboard): add optional actions to the Dashboard and header
- Test Dashboard Actions Story
> feat(dashboard): add optional actions to header

- src/components/Dashboard/DashboardHeader.jsx
- src/components/Page/EditPage.jsx
**Summary**
- fix an alignment in the dashboard header
- fix editpage so I can set buttons relative to it
> fix(dashboard): fix a few styles

- src/components/Card/Card.jsx
- src/components/TimeSeriesCard/TimeSeriesCard.jsx
- src/constants/PropTypes.js
**Summary**
- send a better description for the card icon description
- fix the linechart in isEditable to hide the tooltip
> fix(cards): a few fixes for linechart and card

- src/components/Table/Table.story.jsx
- src/components/Table/TableBody/TableBody.jsx
- src/components/Table/TableBody/TableBodyRow/TableBodyRow.jsx
- src/components/Table/TableBody/TableBodyRow/TableBodyRow.story.jsx
- src/components/Table/TablePropTypes.js
- src/components/Table/baseTableReducer.js
**Summary**
- add capability to the Table card to have unselectable rows (by making isSelectable=false)
- Test out the two new stories with isSelectable true for Table rows
> feat(table): add ability to have unselectable rows

- src/components/TimeSeriesCard/TimeSeriesCard.jsx
**Summary**
- Timeseries card month locale.
> I18n support

- src/components/Dashboard/Dashboard.jsx
**Summary**
- Correct prop type
> Correct prop type

- src/components/Dashboard/Dashboard.jsx
> Prop type correct

- README.MD
**Summary**
The README.md needs a link to the storybook subdomain for ease of access.
> Update Readme to include storybook subdomain

- src/components/Dashboard/DashboardHeader.jsx
- src/components/Dashboard/DashboardHeader.story.jsx
**Summary**
- Support of custom component in dashboard header action.
> fix(dashboard): dashboard header support custom action component

- src/components/TableCard/TableCard.jsx
- src/constants/PropTypes.js
**Summary**
- Empty label with a new JSON prop
- Number of rows when expanded 20
> New prop for custom empty label, expanded row number

- src/components/Card/Card.jsx
**Summary**
- Time grain font size to 12px
- Hide time grain when pass minimum width. 
- When time grain hidden, arrow tooltip change to the time grain.
> Value card fix

- src/components/Table/TableBody/TableBodyRow/TableBodyRow.jsx
**Summary**
Add unique IDs to each table cell, so that automatiion can effectively target each cell.
- Closes IBM/carbon-addons-iot-react#409
- inspect table cells.  Each cell should have an id in the form `cell-ROWID-COLUMNID`
> fix(table): #409 add unique ids to the table cells

- .storybook/webpack.config.js
- src/components/ImageCard/ImageControls.jsx
- src/components/ImageCard/ImageHotspots.jsx
- src/components/ImageCard/Minimap.jsx
- src/components/TableCard/TableCard.jsx
fix(webpack): stop the warning message on recompile
refactor(ImageHotspots): refactor the ImageHotspots into separate components
fix(TableCard): improve performance by only rendering the data once
> fix(card): improve performance of hotspots and tablecard with useMemo

- README.MD
**Summary**
- Syntax issues on line 89 & 97
- There is no change from previous PR
- No previous PR related
- There is no break on code, so there are not collateral damage threat
> Syntax issues on line 89 & 97

- .github/CONTRIBUTING.MD
update contributing guidelines to mention the need for specs to be submitted prior to acceptance
> update contributing guidelines

- src/components/Dashboard/CardRenderer.jsx
- src/components/Dashboard/Dashboard.jsx
add caching layer to the Cards being rendered by the Dashboard
> fix(dashboard): improve performance by adding caching

- package.json
- src/components/Dashboard/CardRenderer.jsx
- src/components/TimeSeriesCard/TimeSeriesCard.jsx
- yarn.lock
fix(onCardAction): cannot attach useCallback there because it becomes shared across all cards
> fix(cardrenderer): further improvements to card renderer

- package.json
- rollup.config.js
- src/components/Dashboard/Dashboard.jsx
- src/components/Dashboard/Dashboard.story.jsx
- src/components/ValueCard/ValueCard.jsx
- src/index.js
- src/utils/cardUtilityFunctions.js
- src/utils/schemas/__test__/validators.test.js
- src/utils/schemas/dashboard.example.json
- src/utils/schemas/dashboardContent.json
- src/utils/schemas/imageCardContent.json
- src/utils/schemas/tableCardContent.json
- src/utils/schemas/timeSeriesCardContent.json
- src/utils/schemas/validators.js
- src/utils/schemas/valueCardContent.json
- yarn.lock
**Summary**
- Card Action (open and close being done in the dashboard level)
- Card Action - time grain change - recieve a callback from parent
- Moving JSON validator and tests to the repo
- Make sure the card action open/close keep working and don't lose any feature.
> Support custom card

- src/components/Dashboard/Dashboard.jsx
- src/index.js
- src/utils/__tests__/cardUtilityFunctions.test.js
- src/utils/cardUtilityFunctions.js
- yarn.lock
fix(dashboard): rewire the onCardAction support correctly
fix(cardUtilityFunctions): add support the the lastQuarter, nextQuarter and export the determineCardRange utility for downstream consumers
> fix(dashboard): fix card range actions

- src/components/Card/Card.jsx
- src/components/Dashboard/Dashboard.story.jsx
- src/components/TableCard/TableCard.jsx
- src/constants/PropTypes.js
support dynamically determining the correct amount of rows for an expanded fullscreen tablecard
> fix(tablecard): show max number of rows on fullscreen card

- .github/CONTRIBUTING.MD
**Summary**
- Improved commit formatting and dependency management info
- Closes #585 
- @stuckless let me know if you have any additional thoughts for improvement
> docs(contributing): additional commit and dependency info

- src/components/Dashboard/CardRenderer.jsx
- src/components/Dashboard/Dashboard.jsx
- src/components/Dashboard/Dashboard.story.jsx
- src/components/ImageCard/ImageCard.jsx
- src/components/ImageCard/ImageCard.story.jsx
- src/components/ValueCard/ValueCard.jsx
- src/constants/PropTypes.js
- src/index.js
- src/utils/__tests__/cardUtilityFunctions.test.js
rewriting the dashboard components to make it easier to add a card that will load it's data
> refactor(dashboard): rewriting these components

- src/components/Dashboard/Dashboard.jsx
fix proptypes error
**Summary**
- summary_here
- items_here
- tests here
> fix(dashboard): proptypes error

- src/components/Table/AsyncTable/AsyncTable.jsx
- src/components/Table/EmptyTable/EmptyTable.jsx
- src/components/Table/Table.jsx
- src/components/Table/Table.story.jsx
- src/components/Table/TableBody/RowActionsCell/RowActionsCell.jsx
- src/components/Table/TableBody/RowActionsCell/RowActionsCell.test.jsx
- src/components/Table/TableBody/TableBody.jsx
- src/components/Table/TableBody/TableBodyRow/TableBodyRow.story.jsx
- src/components/Table/TableBody/TableBodyRow/__snapshots__/TableBodyRow.story.storyshot
- src/components/Table/TablePropTypes.js
- src/components/TableCard/__snapshots__/TableCard.story.storyshot
**Summary**
Add unique IDs to row action overflow menu trigger so that automation can easily find and trigger the overflow menu.
#595
> feat(table): add id to overflow menu trigger

- src/index.js
Closes #537 
**Summary**
- Add an export we missed from the Carbon v10 migration proxy/re-export of Carbon components.
> feat: export NotificationActionButton

- package.json
- src/components/TimeSeriesCard/TimeSeriesCard.jsx
- src/components/TimeSeriesCard/timeSeriesUtils.js
- src/components/TimeSeriesCard/timeSeriesUtils.test.js
handle the case where all the values have a null value, show no data for this time range in the chart
> fix(timeseries): handle if all data is null

- src/components/Card/Card.story.jsx
- src/components/Dashboard/CardRenderer.jsx
- src/components/Dashboard/Dashboard.jsx
- src/components/Dashboard/Dashboard.story.jsx
- src/components/TableCard/TableCard.jsx
**Summary**
- summary_here
- doc(Dashboard): improve the dashboard story documentation on how to extend
- doc(Card): improve the Card story documentation on how to build a custom card
- fix(TableCard): stop the console error on isExpanded
- fix(CardRenderer): check that setupCard exists before calling
- Closes IBM/carbon-addons-iot-react#622
- Verify that all the Card and Dashboard stories work correctly
> fix(tablecard): fix isExpanded console error and improve dashboard docs

- src/components/Table/Table.jsx
- src/components/Table/Table.story.jsx
- src/components/Table/TablePropTypes.js
- src/components/Table/TableToolbar/TableToolbar.jsx
**Summary**
- Add i18n strings to table
- copy from master
- Closes IBM/carbon-addons-iot-react#590
- tests here
> Table i18n denny

- .storybook/webpack.config.js
- package.json
- src/components/Card/Card.story.jsx
- src/components/Card/__snapshots__/Card.story.storyshot
- src/components/Dashboard/CardRenderer.jsx
- src/components/Dashboard/Dashboard.jsx
- src/components/Dashboard/Dashboard.story.jsx
- src/components/Dashboard/__snapshots__/Dashboard.story.storyshot
- src/components/ImageCard/ImageCard.jsx
- src/components/ImageCard/ImageCard.story.jsx
- src/components/ImageCard/ImageHotspots.jsx
- src/components/ImageCard/__snapshots__/ImageCard.story.storyshot
- src/components/TableCard/TableCard.jsx
- src/components/TableCard/__snapshots__/TableCard.story.storyshot
- src/components/TimeSeriesCard/TimeSeriesCard.jsx
- src/components/TimeSeriesCard/__snapshots__/TimeSeriesCard.story.storyshot
- src/components/TimeSeriesCard/timeSeriesUtils.js
- src/components/TimeSeriesCard/timeSeriesUtils.test.js
- src/components/ValueCard/ValueCard.jsx
- src/constants/PropTypes.js
- src/index.js
- src/utils/__tests__/cardUtilityFunctions.test.js
- yarn.lock
**Summary**
- merged all the latest changes and fixes to the dashboards and cards from the 1.1 stream
- Closes IBM/carbon-addons-iot-react#622
- To verify, run through all the Dashboard and Card stories and make sure they work
> chore(merge): forward merge all dashboard fixes from 1.1

- src/components/Table/TableToolbar/TableToolbar.jsx
Closes #
**Summary**
- fix table i18n string for Clear All Filters
- Clear All Filters text
- tests here
> fix(table): fix i18n string

- package.json
- src/components/TableCard/TableCard.jsx
- src/components/TimeSeriesCard/TimeSeriesCard.jsx
- yarn.lock
Closes #
**Summary**
- The table cards severity column needs to be wider
> fix(tablecard): make the severity wider

- .github/CODEOWNERS
**Summary**
-  Add @jessieyan as a reviewer
> chore(codeowners): add jessie

- src/components/PageWizard/PageWizard.jsx
- src/components/PageWizard/_page-wizard.scss
**Summary**
small fixes:
- use `onSubmit` if it is the last step in the wizard
- add padding above action buttons
- no need to test, no current stories use `onSubmit`
> fix(pagewizard): use proper callback for submit

- .storybook/__snapshots__/Welcome.story.storyshot
- src/index.js
**Summary**
- Export experimental components (ListCard / StatefulPageWizard)
> Export experimental components (ListCard / StatefulPageWizard)

- src/components/TimeSeriesCard/TimeSeriesCard.jsx
fixes timechart but where the charts are not updating
> fix(timeseries): bug where the charts do not update successfully

- src/components/TimeSeriesCard/TimeSeriesCard.jsx
Need to order sort the data from the API layer...
> fix(timeseries): need to sort the data from the API layer

- src/components/Button/Button.jsx
- src/components/Dashboard/__snapshots__/Dashboard.story.storyshot
- src/components/PageTitleBar/PageTitleBar.jsx
- src/components/PageTitleBar/PageTitleBar.story.jsx
- src/components/PageTitleBar/PageTitleBar.test.jsx
- src/components/PageTitleBar/__snapshots__/PageTitleBar.story.storyshot
- src/components/PageTitleBar/_page-title-bar.scss
- src/components/PageWizard/PageWizard.jsx
- src/components/PageWizard/PageWizard.story.jsx
- src/components/SideNav/__snapshots__/SideNav.story.storyshot
- src/components/TableCard/__snapshots__/TableCard.story.storyshot
- src/internal/deprecate.js
**Summary**
- Deprecated `tabs` prop in favor of `content`
- Removed required restriction on `Button` onClick
- Verify Button and PageTitleBar stories.
> fix(pagetitlebar): deprecate tabs prop

- src/components/TimeSeriesCard/TimeSeriesCard.jsx
- src/components/TimeSeriesCard/TimeSeriesCard.story.jsx
- src/components/TimeSeriesCard/timeSeriesUtils.js
- src/components/TimeSeriesCard/timeSeriesUtils.test.js
- src/constants/PropTypes.js
- src/utils/schemas/dashboardContent.json
- src/utils/schemas/tableCardContent.json
- src/utils/schemas/timeSeriesCardContent.json
- src/utils/schemas/validators.js
- yarn.lock
Adds new alert ranges feature with tooltip markup
- feat(timeseries): add alert ranges prop that will highlight a range of data
- fix(timeseries): remove extra whitespace
- fix(timeseries): hide legend if there's only one line
- test the new timeseries story for alert ranges, verify that no legend is rendered if there's only one line on the chart
> feat(timeseries): add in alert ranges

- package.json
- yarn.lock
fix need to upgrade the carbon charts to the next dot release
> chore(charts): upgrade charts to latest release

- src/components/ImageCard/ImageHotspots.jsx
- src/components/ImageCard/ImageHotspots.test.jsx
Improve testing around the image hotspot ahdnlers
> test(imagehotspots): add testcases to cover imagehotspots handlers

- src/components/Button/Button.jsx
- src/components/Button/__snapshots__/Button.story.storyshot
- src/components/ComposedModal/__snapshots__/ComposedModal.story.storyshot
- src/components/Page/__snapshots__/EditPage.story.storyshot
- src/components/PageTitleBar/__snapshots__/PageTitleBar.story.storyshot
- src/components/PageWizard/PageWizard.story.jsx
- src/components/Table/TableDetailWizard/__snapshots__/TableDetailWizard.story.storyshot
- src/components/WizardInline/__snapshots__/WizardInline.story.storyshot
- src/components/WizardModal/__snapshots__/WizardModal.story.storyshot
Make sure loading spinner within the height inside a button
Closes #709
> fix(button): loading maintains same height in button

- .github/CODEOWNERS
**Summary**
- add Marcelo as CODEOWNER
> chore(codeowners): add Marcelo

- src/components/TimeSeriesCard/TimeSeriesCard.jsx
- src/components/TimeSeriesCard/TimeSeriesCard.story.jsx
- src/utils/sample.jsx
- src/utils/schemas/__test__/validators.test.js
- src/utils/schemas/tableCardContent.json
- src/utils/schemas/timeSeriesCardContent.json
Our card validators need to support raw data with no aggregators
> feat(card): support raw data with no aggregators

- jest.config.js
**Summary**
- Quick fix for a couple items causing tests to fail currently in `master`. I'm not sure why Travis didn't catch these in #721
> fix(test): add coverage exceptions uncaught in #721

- src/components/Card/Card.jsx
- src/components/Dashboard/CardRenderer.jsx
- src/components/Dashboard/Dashboard.jsx
- src/components/Table/StatefulTable.jsx
- src/components/Table/Table.jsx
- src/components/Table/Table.story.jsx
- src/components/Table/TablePropTypes.js
- src/components/Table/TableToolbar/TableToolbar.jsx
- src/components/TableCard/TableCard.jsx
- src/components/TimeSeriesCard/TimeSeriesCard.jsx
- src/utils/componentUtilityFunctions.js
- src/utils/schemas/timeSeriesCardContent.json
Closes #642
**Summary**
- See detailed list
- fix(validators): add dataFilter support to validator
- refactor(Table): add download content support to main table, you can use your own download engine to process the handler
- feat(Card): Add default indicator on range picker
- Test the TableCard stories for the download icon
> fix(card): several fixes to the cards and enhancements

- src/components/Dashboard/__snapshots__/Dashboard.story.storyshot
- src/components/DataTable/_data-table.scss
- src/components/Table/Table.jsx
- src/components/Table/Table.story.jsx
- src/components/Table/Table.test.jsx
- src/components/Table/TablePropTypes.js
- src/components/Table/TableToolbar/TableToolbar.jsx
- src/components/TableCard/__snapshots__/TableCard.story.storyshot
#689
Closes #
**Summary**
Right align the search icon and toggle open when clicked to display a search component.
Show table row count and should be appear on the left. i.e "Results: X", where X is equal to the number of rows in the table.
This field (Row count) should be configuration via boolean property and Result Label should allow to change.
src/components/Dashboard/__snapshots__/Dashboard.story.storyshot
src/components/DataTable/_data-table.scss
src/components/Table/Table.jsx
src/components/Table/Table.story.jsx
src/components/Table/Table.test.jsx
src/components/Table/TablePropTypes.js
src/components/Table/TableToolbar/TableToolbar.jsx
src/components/Table/__snapshots__/Table.story.storyshot …
> feat(table): 3287-TableSearch_RowCount

- src/components/Card/Card.jsx
for some weird reason the automated release didn't trigger with the previous commit
> fix(card): push another fix to trigger a 1.x release

- src/components/Card/CardRangePicker.jsx
- src/components/Card/CardToolbar.jsx
Small fix where after the timerange is selected it should show on the card
> fix(cardrange): wasn't showing selected timerange

- src/components/Table/Table.story.jsx
- src/components/Table/TableBody/TableBodyRow/TableBodyRow.jsx
- src/components/Table/TableCellRenderer/TableCellRenderer.jsx
Closes #
**Summary**
- Bug where if a boolean value was passed to the table, it wouldn't render
- Test the table stories you'll see a new boolean column
> fix(table): if cell has boolean value it doesn't show in the table

- .travis.yml
- package.json
semantic releases latest beta version was failing to publish (I think due to a bug) this locks our release publish at our tested semantic-release level.
> fix(release): fixing semantic release

- src/components/PageWizard/PageWizard.jsx
- yarn.lock
Closes #
**Summary**
- add `lowContrast` to `InlineNotification` used in PageWizard
- PageWizard
- PageWizard
> fix(inlinenotification): use lowContrast inline notification

- .storybook/__snapshots__/Welcome.story.storyshot
- jest.config.js
- src/components/Page/EditPage.jsx
- src/components/Page/EditPage.story.jsx
- src/components/Page/__snapshots__/EditPage.story.storyshot
- src/index.js
Closes #
**Summary**
- Formally deprecate Edit Page
- The Edit Page was removed before deprecation
- Check the Edit Page stories that they show deprecation
> fix(editpage): deprecate edit page

- .storybook/__snapshots__/Welcome.story.storyshot
- src/index.js
Closes #
**Summary**
- should export the csv download handler in case others want to use it with their table card
> feat(csvdownload): export sharable csv download handler

- src/components/Card/Card.jsx
- src/components/Card/Card.test.jsx
- src/components/Card/CardRangePicker.jsx
- src/components/Card/CardToolbar.jsx
- src/components/Card/__snapshots__/Card.story.storyshot
- src/components/Card/_card.scss
- src/components/Dashboard/__snapshots__/Dashboard.story.storyshot
- src/components/Dashboard/__snapshots__/DashboardGrid.story.storyshot
- src/components/DataTable/_data-table.scss
- src/components/ImageCard/__snapshots__/ImageCard.story.storyshot
- src/components/Table/Table.jsx
- src/components/Table/Table.story.jsx
- src/components/Table/Table.test.jsx
- src/components/Table/TableToolbar/TableToolbar.jsx
- src/components/Table/TableToolbar/_table-toolbar.scss
- src/components/TableCard/TableCard.jsx
- src/components/TableCard/TableCard.story.jsx
- src/components/TableCard/TableCard.test.jsx
- src/components/TableCard/__snapshots__/TableCard.story.storyshot
- src/components/TimeSeriesCard/__snapshots__/TimeSeriesCard.story.storyshot
- src/components/ValueCard/__snapshots__/ValueCard.story.storyshot
- src/constants/PropTypes.js
- src/styles.scss
- yarn.lock
Closes #820 
New functionality Screenshot (See header):
**Summary**
- Refactored TableCard to receive the CardToolbar as `customToolbarContent`. The `customToolbarContent` was moved to the right of the Table's actions.
- Added the ability to add a `secondaryTitle` and `tooltip` as a smaller header, which deprecates the current `hasRowCountInHeader` prop as secondaryTitle is more general.
- Added deprecation notice to hasRowCountInHeader
- Removed the Toolbar and ToolbarItem from Card as they are deprecated and have no use
- Updated CardToolbar to use larger buttons to reflect the functionality that TableCard has, as well as enlarge the click-space
- Changed all images to use the same 20x20 size
- Updated affected tests to reflect new class names and components
- Updated snapshots to …
> feat(tablecard): combined CardHeader with TableHeader #820

- jest.config.js
Closes #856
**Summary**
Temporarily add list in test exceptions. Will add most test coverage in #878
> fix[list]: add list in test exceptions

- src/components/Card/Card.jsx
- src/components/Card/__snapshots__/Card.story.storyshot
- src/components/Dashboard/Dashboard.story.jsx
- src/components/Dashboard/__snapshots__/Dashboard.story.storyshot
- src/components/Dashboard/__snapshots__/DashboardGrid.story.storyshot
- src/components/ImageCard/__snapshots__/ImageCard.story.storyshot
- src/components/TableCard/__snapshots__/TableCard.story.storyshot
- src/components/TimeSeriesCard/TimeSeriesCard.jsx
- src/components/TimeSeriesCard/TimeSeriesCard.story.jsx
- src/components/TimeSeriesCard/__snapshots__/TimeSeriesCard.story.storyshot
- src/components/ValueCard/__snapshots__/ValueCard.story.storyshot
- src/constants/PropTypes.js
Closes #
**Summary**
- Small change to fix the stories for TimeSeriesCards.  They were in the wrong language. Also moved down the Locale story to the end.
- fix(TimeSeriesCard): the chartType propType should be inside the content object to be consistent with other cards
- Check the timeseries stories that were changed to make sure they're in the correct language
> test(timeseries): update timeseries story cards

- jest.config.js
- src/components/List/List.test.jsx
- src/components/List/ListHeader/ListHeader.test.jsx
- src/components/List/ListItem/ListItem.jsx
- src/components/List/ListItem/ListItem.test.jsx
- src/components/List/SimpleList/SimpleList.story.jsx
- src/components/List/SimpleList/SimpleList.test.jsx
Closes #878 
**Summary**
- Add more tests for List, ListHeader, ListItem and SimpleList component
> fix(list): Improve List test coverage

- src/components/Table/TableHead/FilterHeaderRow/FilterHeaderRow.jsx
- src/components/TableCard/__snapshots__/TableCard.story.storyshot
Closes #
**Summary**
Sort the dropdowns when filtering in table components such that it is case in-sensitive and is alphabetical.
src/components/Table/TableHead/FilterHeaderRow/FilterHeaderRow.jsx
Added a memoized function to alphabetically sort the options list.
In your local dev environment, add options in the constant "selectData" in Table.story.jsx
View the table component and see that the options are now sorted alphabetically.
Before:
After:
> fix(filter-header-row): alphabetically sort dropdowns when filtering

- src/components/Table/_table.scss
Closes #
**Summary**
- Weird bug caused by our overflow setting on the toolbar where batch actions occasionally partially disappear.  Removing our toolbar overflow fixes the issue.
> [Table]: fix toolbar partially disappearing bug intermittently

- src/constants/PropTypes.js
**Summary**
Add a size proptype for TableCard, only supporting sizes LARGE and LARGEWIDE.
> fix(table-card): add proptype size validation for table-card

- src/components/List/ListItem/_list-item.scss
Closes #988 
**Summary**
Update content height to 100% to avoid unnecessary scrollbars
> fix(listitem): update height on list item

- src/components/TileCatalog/TileCatalog.jsx
- src/components/TileCatalog/TileGroup.jsx
- src/components/TileCatalog/__snapshots__/TileCatalog.story.storyshot
- src/components/TileCatalog/_tile-group.scss
- src/globals/_vars.scss
- src/styles.scss
**Summary**
Moves TileGroup component from `styled-components` to `scss`
Navigate to TileCatalog and verify that the styling is still correct.
> chore(tile-group): migrate tile-group to scss

- src/components/WizardModal/WizardModal.jsx
- src/components/WizardModal/__snapshots__/WizardModal.story.storyshot
- src/components/WizardModal/_wizard-modal.scss
- src/styles.scss
Closes #452
**Summary**
- the wizard modal (title, content, spacing, buttons) was broken on RTL
- moved away from styled component to pure css
> fix(wizard-modal): added support for RTL

- src/components/ProgressIndicator/ProgressIndicator.jsx
- src/components/ProgressIndicator/__snapshots__/ProgressIndicator.story.storyshot
- src/components/ProgressIndicator/_progress-indicator.scss
- src/components/Table/TableDetailWizard/__snapshots__/TableDetailWizard.story.storyshot
- src/components/WizardInline/__snapshots__/WizardInline.story.storyshot
- src/components/WizardModal/__snapshots__/WizardModal.story.storyshot
Closes #471
**Summary**
- Pass on the horizontal and vertical progress indicators
- added specific scss + unspecific for the skeleton which is inherited directly from Carbon
> fix(progress-indicator): add support for RTL

- src/components/Button/_button.scss
- src/components/WizardModal/_wizard-modal.scss
Closes #445
**Summary**
- introduces support for RTL on buttons
- removed button specific css from the wizard modal now that it's global
- verify visually
> fix(button): support RTL mode

- .github/CODE_OF_CONDUCT.md
- .storybook/Welcome.story.jsx
- .storybook/__snapshots__/Welcome.story.storyshot
- .storybook/welcome-story.css
- src/components/TableCard/__snapshots__/TableCard.story.storyshot
**Summary**
- To retain our status on Netlify's free open source plan, we need a link on the main page of the site, and a code of conduct
- add link to welcome story
- copy the Carbon code of conduct, tweak links and verbiage for our project
- welcome story should have a link
- review the COC and bring up any concerns if you have them
> feat(project): add code of conduct, netlify badge

- src/components/Breadcrumb/Breadcrumb.jsx
#1158
Closes #
**Summary**
- summary_here
- items_here
- tests here
> fix(breadcrumb): browsers that do not support ResizeObserver

- src/components/Header/Header.jsx
- src/components/Header/Header.story.jsx
- src/components/Header/__snapshots__/Header.story.storyshot
- src/components/Header/_header.scss
- src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Closes #1182
**Summary**
- Adds a new optional subtitle to our header, mostly used for Application Suite type usecases
- feat(Header): support new subtitle rendering
- fix(Header): remove hardcoded bx in class names
- Verify all the header stories
> feat(header): add optional subtitle for MAS suite type products

- src/components/Table/TableHead/_table-head.scss
Closes #1108
**Summary**
- Table filter combobox was showing underneath the table
- fix(tablehead): small fix to the tablehead overflow class override
- Verify the Column Filters with options show in dropdown
> fix(tableheader): overflow of combo box

- src/components/DateTimePicker/DateTimePicker.jsx
- src/components/TileCatalogNew/TileCatalogNew.jsx
Closes #
**Summary**
Adds unique keys to avoid errors
> Add unique keys to TileCatalog grid

- src/components/Header/Header.jsx
- src/components/Header/Header.story.jsx
- src/components/Header/__snapshots__/Header.story.storyshot
- src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Closes #1298 
**Summary**
- appSwitcherLabel prop included in `Header.jsx` component
- AppSwitcher label knob included in `Header.story.jsx`
- fix(header): appSwitcherLabel prop added
- fix(header): added appswitcherlabel knob
- Change AppSwitcher label in Header story
> Fix(Header): appSwitcherLabel prop added

- package.json
- src/components/List/List.story.jsx
- yarn.lock
Closes #1106
**Summary**
- Replaced filterDeep with someDeep for added performance in List
**Update**
- Fixed a bug whereby multiple children with the same id were treated as one object. Added `${team}-${player}` to child elements and for their evaluation (pointed out by @tay1orjones )
> fix(list): replaced filterdeep with somedeep

- config/stylelint/sassMsgFormatter.js
**Summary**
- @rawa-resul noticed his linting was failing due to `TITLE` being undefined
- copy the `TITLE` from the test file into the primary file
- status checks should pass
> fix(sassformatter): title was undefined

- src/components/Table/TableDetailWizard/TableDetailWizardHeader/_table-detail-wizard-header.scss
- src/components/Table/TableDetailWizard/TableDetailWizardSidebar/_table-detail-wizard-sidebar.scss
- src/components/Table/TableDetailWizard/_table-detail-wizard.scss
Closes #450
**Summary**
- Tweaked and fixed RTL issues in TableDetailWizard
> TableDetailWizard RTL fix

- package.json
- yarn.lock
Closes #1466 
**Summary**
- Updates carbon charts to pick up this fix: https://github.com/carbon-design-system/carbon-charts/pull/737
- Updates carbon/charts and carbon/charts-react
- No acceptance test here, but this has already been tested in Monitor where the bug was occurring
> fix(carbon-charts): update to get zoombar bug fix

- .storybook/__snapshots__/Welcome.story.storyshot
- src/components/List/List.jsx
- src/components/Table/TableManageViewsModal/SharedTableManageViewsModalPropTypes.js
- src/components/Table/TableManageViewsModal/TableManageViewsList.jsx
- src/components/Table/TableManageViewsModal/TableManageViewsModal.jsx
- src/components/Table/TableManageViewsModal/TableManageViewsModal.story.jsx
- src/components/Table/TableManageViewsModal/TableManageViewsModal.test.jsx
- src/components/Table/TableManageViewsModal/__snapshots__/TableManageViewsModal.story.storyshot
- src/components/Table/TableManageViewsModal/table-manage-views-list.scss
- src/components/Table/TableManageViewsModal/table-manage-views-modal.scss
- src/index.js
- src/styles.scss
- src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Closes #1308
**Summary**
A highly customisable modal built for managing table views. The component is built as component outside the actual table but only make sense in the context of table view management.
Default:
Heavily customised:
1. Created component TableManageViewsModal that lets a user list, search, filter and take actions on views. The state needed for search, pagination etc is handled by the application via callbacks.
2. Created a TableManageViewsList component as a subcomponent of the TableManageViewsModal that in turn uses the List compoinent.
3. Created 2 stories as a sub section of the table stories. One that demonstrates and with info explains the full usage and the other how to customise the modal. 
4. Wrote unit tests …
> feat(table): Manage view modal

- src/components/Table/Table.test.jsx
Closes #1193 
**Summary**
This PR adds test to confirm that recent changes had resolved this issue. 
- added test to Table.test.jsx
- All test should pass.
> fix(table): added test to check for bug #1193

- .github/ISSUE_TEMPLATE/bug-report.md
- .github/ISSUE_TEMPLATE/feature-request-or-enhancement.md
- .github/ISSUE_TEMPLATE/new-component-proposal.md
- .github/ISSUE_TEMPLATE/question.md
Closes #1546 
**Summary**
Need to update issue templates to accommodate the Angular specific issues. 
- Added question about which package the issue pertains to on each template
> repo - add new templates for the repo to allow for angular

- .kodiak.toml
**Summary**
- Enables [Kodiak](https://kodiakhq.com/) to automate some of our pull request workflow.
- Pull requests that have the `status: ready to merge 🎉` label applied will automatically be updated with latest from master and automatically merged once all status checks have passed.
> chore(repo): enable kodiak

- src/components/List/SimpleList/SimpleList.jsx
- src/components/List/SimpleList/SimpleList.story.jsx
- src/components/List/SimpleList/__snapshots__/SimpleList.story.storyshot
- src/components/ListCard/ListCard.jsx
- src/components/ListCard/ListCard.story.jsx
- src/components/ListCard/__snapshots__/ListCard.story.storyshot
- src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Closes #1689
Closes #1690 
Closes #1691 
**Summary**
- Adds empty state for ListCard if there is no data
- Merges `i18n` prop with defaultProps `i18n`
- Adds ability to hide the pagination in SimpleList
- Added story for empty state ListCard
- Added story for hidden pagination in SimpleList
- Go to ListCard - empty story to see empty state
- Go to SimpleList - hidden pagination story to see hidden pagination AND there is only 1 `i18n` prop being passed here so this also verified the merged i18n
> [ListCard / SimpleList] bug fixes

- src/components/Table/TableHead/TableHead.jsx
- src/components/TableCard/TableCard.test.jsx
Closes #1699
**Summary**
Small fix to handle resize of TableCard
- Small fix to check for undefined
- Added unit test 
1. Go to 'https://deploy-preview-1700--carbon-addons-iot-react.netlify.app/?path=/story/watson-iot-tablecard--table-with-multiple-actions'
2. Change size to LargeWide
3. Change size to Large
4. Make sure there is no error
> fix(tablehead): fixed crash after resize

- src/components/BarChartCard/BarChartCard.jsx
- src/components/BarChartCard/barChartUtils.js
- src/components/BarChartCard/barChartUtils.test.js
Closes #1773
**Summary**
- Fixes bar chart null pointer
- fix(BarChartCard): handle null data
- fix(BarChartUtils): handle null data but valid series returns null
- tests here
> fix(barchart): handle null data correctly when we do have series

- package.json
- yarn.lock
Closes #
**Summary**
- Upgrades to the latest carbon charts
-  Regression test of the chart cards
> fix(charts): there was a null pointer in the carbon charts zoom bar fix

- src/components/List/HierarchyList/HierarchyList.jsx
- src/components/List/List.jsx
Closes # internal monitoring bug 1622
This is just a hotfix to master for the PR:
https://github.com/carbon-design-system/carbon-addons-iot-react/pull/1794
> Hotfix to Master -- fix(hierarchylist): need to useDeepCompareEffect to stop infinite loop

- src/components/CardEditor/CardEditForm/CardEditFormItems/DataSeriesFormItem.jsx
- src/components/List/HierarchyList/HierarchyList.jsx
- src/components/List/ListItem/ListItem.jsx
- src/components/List/ListItem/ListItem.story.jsx
- src/components/List/ListItem/__snapshots__/ListItem.story.storyshot
- src/components/List/ListItem/_list-item.scss
Closes #
**Summary**
- Hotfixes the recent hierarchy list changes for selection and not truncating long text to master
- See the commit history
- Regression test the hierarchy list and list stories
> Hotfix hierarchy list

- src/components/CardEditor/CardEditForm/CardEditFormContent.jsx
- src/components/CardEditor/CardEditForm/CardEditFormItems/ImageCardFormItems/ImageCardFormContent.jsx
- src/components/CardEditor/CardEditForm/CardEditFormItems/ImageCardFormItems/ImageCardFormContent.test.jsx
- src/components/CardEditor/CardEditForm/_card-edit-form.scss
- src/components/CardEditor/CardEditor.story.jsx
- src/components/CardEditor/__snapshots__/CardEditor.story.storyshot
- src/components/DashboardEditor/DashboardEditor.jsx
Closes #
**Summary**
- feat(imagecardformcontent): support a button that clears the selected image
- refactor(dashboardeditor): better support selecting the image from the gallery
- Verify the story selecting an image from the gallery works
- Verify the new story of CardEditor for Image sends the onChange event correctly
> feat(imagecardformcontent): support clearing the image

- src/components/BarChartCard/barChartUtils.js
- src/components/BarChartCard/barChartUtils.test.js
Closes #
**Summary**
- fix barChartUtils to correctly handle if a null is passed for values
-fix(barChartUtils): check for nulls before trying to work with the values
- Verify that the new testcases run correctly
> fix(barchart): handle null values

- src/components/SuiteHeader/util/suiteHeaderData.fixture.js
- src/components/SuiteHeader/util/suiteHeaderData.js
**Summary**
- Adding **MRO Inventory Optimization** and **Asset Performance Management for Energy and Utilities** to `SuiteHeader` data
> feat(suiteheader): mroio and apm data

- jest.config.js
- src/components/ImageCard/ImageCard.jsx
- src/components/ImageCard/ImageCard.story.jsx
- src/components/ImageCard/ImageUploader.jsx
- src/components/ImageCard/__snapshots__/ImageCard.story.storyshot
- src/components/List/HierarchyList/__snapshots__/HierarchyList.story.storyshot
- src/constants/CardPropTypes.js
- src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Closes #
**Summary**
- feat(imagecard): allow custom validation message to be returned to prevent uploading the image
- feat(imagecard): allow callback function to be called to validate the uploaded file
- Try and upload a file in the new story that forces an upload error
> fix(imagecard): prevent collisions if file already exists

- .github/workflows/publish.yml
- packages/react/package.json
- scripts/release.sh
Future TODO: non-user admin account. carbon-bot perhaps?
Thanks to https://github.community/t/how-to-push-to-protected-branches-in-a-github-action/16101/35 for the solution 🤞
> Fix publish

- scripts/release.sh
Login borrowed from Carbon Charts: https://github.com/carbon-design-system/carbon-charts/blob/master/scripts/deploy.sh#L25-L26
> fix npm authentication

- packages/react/package.json
Closes #1977
**Summary**
- Downstream products cannot import build
> fix(build): update main and module in package.json

- packages/react/src/components/Table/StatefulTable.test.jsx
- packages/react/src/components/Table/Table.story.jsx
- packages/react/src/components/Table/TableHead/FilterHeaderRow/FilterHeaderRow.jsx
- packages/react/src/components/Table/TableHead/_table-head.scss
Closes #1988
**Summary**
- Change the table's multiselect filter to support typing to filter
- feat(FilterHeaderRow): switch from MultiSelect to MultiSelect.Filterable
- Verify the isMultiSelect table story
> feat(table): use MultiSelect.Filterable for the multiselect columns

- packages/react/src/components/CardEditor/CardEditForm/CardEditFormItems/DataSeriesFormItems/DataSeriesFormContent.jsx
- packages/react/src/components/CardEditor/CardEditForm/CardEditFormItems/TableCardFormItems/TableCardFormContent.jsx
- packages/react/src/components/CardEditor/CardEditForm/CardEditFormItems/TableCardFormItems/TableCardFormContent.test.jsx
- packages/react/src/components/DashboardEditor/DashboardEditor.story.jsx
- packages/react/src/components/DashboardEditor/editorUtils.jsx
- packages/react/src/components/DashboardEditor/editorUtils.test.jsx
- packages/react/src/components/TableCard/TableCard.jsx
- packages/react/src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Closes #
**Summary**
- Set of fixes related to table card in editor
- fix(TableCardFormContent): don't set an empty array of thresholds
- fix(TableCard): use the Column label in the threshold column, not the datasourceid
- fix(TableCard): show the dynamic threshold column in the editor preview
- Verify that in the tablecard editor, if you add a threshold you see the new column
> fix(tablecard): show column label in threshold column

- packages/react/src/components/RuleBuilder/RuleBuilderEditor.test.jsx
- packages/react/src/components/RuleBuilder/utils.js
- packages/react/src/components/RuleBuilder/utils.test.js
Closes #2040 
**Summary**
- summary_here
- items_here
- tests here
> fix(rulebuilder): pad id generator to fix intermittent failing test

- packages/react/jest.config.js
- packages/react/src/components/TileCatalog/TileCatalog.test.jsx
Closes #2164 
**Summary**
add test to increase branching coverage on the CatalogContent component
> chore(catalog-content): raise test coverage

- packages/react/src/components/BarChartCard/__snapshots__/BarChartCard.story.storyshot
- packages/react/src/components/Card/__snapshots__/Card.story.storyshot
- packages/react/src/components/ComboChartCard/__snapshots__/ComboChartCard.story.storyshot
- packages/react/src/components/Dashboard/__snapshots__/Dashboard.story.storyshot
- packages/react/src/components/Dashboard/__snapshots__/DashboardGrid.story.storyshot
- packages/react/src/components/DashboardEditor/__snapshots__/DashboardEditor.story.storyshot
- packages/react/src/components/PieChartCard/__snapshots__/PieChartCard.story.storyshot
- packages/react/src/components/RuleBuilder/__snapshots__/RuleBuilder.story.storyshot
- packages/react/src/components/Table/EmptyTable/EmptyTable.jsx
- packages/react/src/components/Table/Pagination.jsx
- packages/react/src/components/Table/Table.jsx
- packages/react/src/components/Table/TableBody/TableBody.jsx
- packages/react/src/components/Table/TableHead/ColumnHeaderRow/ColumnHeaderRow.jsx
- packages/react/src/components/Table/TableHead/FilterHeaderRow/FilterHeaderRow.jsx
- packages/react/src/components/Table/TableHead/TableHead.jsx
- packages/react/src/components/Table/TableHead/TableHeader.js
- packages/react/src/components/Table/TableSkeletonWithHeaders/TableSkeletonWithHeaders.jsx
- packages/react/src/components/Table/TableToolbar/TableToolbar.jsx
- packages/react/src/components/TableCard/__snapshots__/TableCard.story.storyshot
- packages/react/src/components/TimeSeriesCard/__snapshots__/TimeSeriesCard.story.storyshot
- packages/react/src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Closes #2191 
**Summary**
- added testID and data-testid to various table components to give better test access
> chore(table): add data-testid to main components

- packages/angular/package.json
- packages/angular/scripts/sync-version.js
- packages/angular/src/package.json
Just a small PR to ensure that Angular publishes correctly in the future.
> chore(angular): ensure publishConfig and version is synced

- packages/react/src/components/FileUploader/FileUploader.story.jsx
Closes #2030 
**Summary**
- Stories that use hooks must be wrapped with a createElement decorator, or nest the component inside another component in the story.
- wrap the Example application with drag and drop file uploader with a createElement decorator 
- Ensure the Example application with drag and drop file uploader works properly.
> fix(file-uploader): fix broken example story

- packages/react/package.json
Closes #2238, closes #2207 
**Summary**
Changed the package.json to point to our package entry point. 
To test check the netlify builds. They should all be working now.
> fix(build): change the index source in package.json

- packages/react/src/components/DateTimePicker/DateTimePicker.jsx
- packages/react/src/components/DateTimePicker/DateTimePicker.story.jsx
- packages/react/src/components/DateTimePicker/__snapshots__/DateTimePicker.story.storyshot
- packages/react/src/components/List/HierarchyList/__snapshots__/HierarchyList.story.storyshot
- packages/react/src/components/List/List.jsx
- packages/react/src/components/List/SimpleList/__snapshots__/SimpleList.story.storyshot
- packages/react/src/components/SimplePagination/SimplePagination.jsx
- packages/react/src/components/SimplePagination/SimplePagination.story.jsx
- packages/react/src/components/SimplePagination/__snapshots__/SimplePagination.story.storyshot
- packages/react/src/components/SimplePagination/_simple-pagination.scss
- packages/react/src/components/Table/TableManageViewsModal/__snapshots__/TableManageViewsModal.story.storyshot
- packages/react/src/components/TileCatalog/__snapshots__/TileCatalog.story.storyshot
- packages/react/src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Closes #
**Summary**
- add total item counts to the simple pagination component and hide custom range links if not required.
- fix(SimplePagination) : Add total items count
- fix(DateTimePicker): hide custom range link if not required
- fix(List): return the parent id
- DateTimePicker and SimplePagination component works without any issues
> fix(SimplePagination) : Add total items count

- packages/react/.storybook/__snapshots__/Welcome.story.storyshot
- packages/react/src/index.js
- packages/react/src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Closes #2250 
**Summary**
- export settings from the index for consumers
- export setting
- ensure settings is available as a named export for consumers
> feat(repo): export settings to consumers

- packages/react/src/components/Table/README.md
- packages/react/src/components/Table/Table.story.jsx
Closes #2189 
**Summary**
- added README.md and wrapped stories with withReadme to display content on the Readme tab.
> chore(table): initial addition of documentation

- packages/react/src/components/Dashboard/__snapshots__/Dashboard.story.storyshot
- packages/react/src/components/EmptyState/EmptyState.jsx
- packages/react/src/components/RuleBuilder/__snapshots__/RuleBuilder.story.storyshot
- packages/react/src/components/Table/EmptyTable/EmptyTable.jsx
- packages/react/src/components/Table/EmptyTable/__tests__/EmptyTable.test.jsx
- packages/react/src/components/Table/Table.jsx
- packages/react/src/components/Table/Table.story.jsx
- packages/react/src/components/TableCard/__snapshots__/TableCard.story.storyshot
- packages/react/src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Related https://github.ibm.com/wiotp/Maximo-Asset-Monitor/issues/2275
**Summary**
- Update the empty state based on new designs
- fix(EmptyTable): add empty state on no filter data or no data
- fix(EmptyState): add button kind to display the button type
- tests here
- Table should work without any issues.
> fix(emptytable): update the empty table state for filter usecase

- packages/react/src/components/List/List.story.jsx
- packages/react/src/components/List/__snapshots__/List.story.storyshot
- packages/react/src/components/List/_list.scss
Closes #1479
Closes #2115 
**Summary**
- Small fix to position the pagination correctly on a list of full height in a fixed height container. See the new `with pagination` list story. The pagination should be positioned correctly unlike the screenshot on the original issue.
- pagination is at the bottom of the list.
- all other stories should remain unaffected.
> fix(list): page position on list of full height in fixed container

- packages/react/jest.config.js
- packages/react/src/components/Table/TableBody/RowActionsCell/RowActionsCell.jsx
- packages/react/src/components/Table/TableBody/RowActionsCell/RowActionsCell.test.jsx
Closes #2507
**Summary**
Improved test coverage, rewrote enzyme tests and solved bug
- improved tests coverage
- rewrote enzyme tests using testing library
- solved a bug with rendering icons by names that was revealed when testing more of the code. The bug needed to be solved in order to get the coverage high enough.
- Check that the tests makes sense
n/a
> 2507 row actions cell improve unit test coverage

- packages/react/jest.config.js
- packages/react/src/components/Table/Table.test.helpers.js
- packages/react/src/components/Table/Table.test.jsx
Closes #2586
**Summary**
Improved unit test coverage
1. Improved unit test coverage 
2. rewrote a test from enzyme to testing library 
3. increased threshold
Verify test code
n/a
> 2586 table improve unit test coverage

- .github/PULL_REQUEST_TEMPLATE.MD
- .github/workflows/publish.yml
Closes #2426 
**Summary**
- adding a checklist for reviewers to use for PRs
- Updated our publish github action to remove the testing calls since we are testing multiple times beforehand.
> Remove test from publish flow and add checklist to PR template

- packages/react/src/components/Dashboard/__snapshots__/Dashboard.story.storyshot
- packages/react/src/components/Dashboard/__snapshots__/DashboardGrid.story.storyshot
- packages/react/src/components/DashboardEditor/__snapshots__/DashboardEditor.story.storyshot
- packages/react/src/components/TableCard/TableCard.jsx
- packages/react/src/components/TableCard/__snapshots__/TableCard.story.storyshot
Closes - Monitor reported issue
**Summary**
- Table card not showing a horizontal scrollbar
- Fix Table card height to show a vertical scrollbar
Before:
Afte changes:
- Fix on table classes used in TableCard
- Use of `prefix` in TableCard file instead of `bx`.
- Update correctly the `numberOfRowsPerPage` for the amount that fits on the page.
- Make sure table card show scrollbar
- N/A
> Table card scroll

- packages/react/src/components/SuiteHeader/SuiteHeader.mdx
- packages/react/src/components/SuiteHeader/hooks/useUiResources.js
**Summary**
Including documentation changes for `SuiteHeader` to mention the new supported property `idleTimeoutData`.
> fix(suiteheader): Minor documentation changes in SuiteHeader.mdx

- packages/react/src/components/Card/_card.scss
Closes #
**Summary**
- a bad import caused consumer builds to break. This fixes that scss import.
- fixed mixin import in `_card.scss`
- use `yarn link` to pull this pr into a working application. It should build and run without throwing an error about a bad scss import.
> fix(card): fix mixin import

- packages/react/src/components/Table/StatefulTable.jsx
- packages/react/src/components/Table/StatefulTable.story.jsx
- packages/react/src/components/Table/Table.jsx
- packages/react/src/components/Table/tableReducer.js
Closes #1906 
**Summary**
- If all items on the last page of a Stateful table were deleted the page would show empty and the pagination bar would disappear. This PR uses the `TABLE_APPLY_ACTION` action to also update the pagination to reflect the changes in data on delete actions.
- update `pagination.totalItems` on delete
- check if the current page is greater than the expected total number of page after the deletion and update the current page if necessary
- pass the updated totalItems to the view.pagination prop instead of the initial totalItems passed to the table.
- On the [simple stateful table](https://deploy-preview-2667--carbon-addons-iot-react.netlify.app/?path=/story/1-watson-iot-table-stat …
> fix(stateful-table): update pagination properly on deletes

- packages/react/src/components/SuiteHeader/util/IdleTimer.js
Closes #
**Summary**
- `IdleTimer.js` listens for mouse and keyboard events, but it needs to also listen for mobile touch events.
- Added listeners for `touchstart`, `touchend`, `touchcancel` and `touchmove`.
- Existing tests passed.
- All tests passed.
> Idle timer mobile support

- packages/react/src/components/Header/Header.story.jsx
- packages/react/src/components/Header/Header.test.jsx
- packages/react/src/components/Header/HeaderAction/HeaderActionMenu.jsx
- packages/react/src/components/Header/HeaderAction/__snapshots__/HeaderActionMenu.test.jsx.snap
- packages/react/src/components/Header/__snapshots__/Header.story.storyshot
- packages/react/src/components/Header/__snapshots__/Header.test.jsx.snap
- packages/react/src/components/SuiteHeader/__snapshots__/SuiteHeader.story.storyshot
Closes #2447
**Summary**
- backports fixes that aren't breaking from #2679 into next.
- fixes tests to prevent <a> within <a> errors in test output
- fixes onKeyDown handler and empty href for HeaderActionMenu buttons.
- no <a> within <a> test output messages
- header stories work as expected.
> fix(header): fix header testing noise, onKeyDown handlers

- packages/react/.storybook/__snapshots__/Welcome.story.storyshot
- packages/react/src/index.js
- packages/react/src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Closes #2672 
**Summary**
- exports RuleBuilder from index
- exports RuleBuilder from index
- run build locally and ensure RuleBuilder is included in es/lib output.
- No other changes.
> fix(rule-builder): export RuleBuilder in index

- packages/react/jest.config.js
- packages/react/src/components/Table/TableSaveViewModal/TableSaveViewModal.test.jsx
Closes #2522 
**Summary**
- added tests to increase coverage
- added tests to increase coverage
- test coverage is not above 90%
- n/a
> chore(testing): increase coverage on TableSaveViewModal

- packages/react/src/components/List/List.test.jsx
- packages/react/src/components/TileCatalogNew/TileCatalogNew.jsx
- packages/react/src/components/TileCatalogNew/TileCatalogNew.test.jsx
- packages/react/src/components/TileCatalogNew/__snapshots__/TileCatalogNew.story.storyshot
- packages/react/src/components/TileCatalogNew/_tile-catalog.scss
Closes #1966 
**Summary**
- previously these components just had test written to get coverage, but weren't actually real functionality. That's fixed now and coverage is also still over 90%
> testing(list/tile-catalog-new): improve quality of tests for these components

- packages/react/src/components/RuleBuilder/_rule-builder.scss
Closes #2404 
**Summary**
- the fixed height was causing the background not to expand as the content did. Now the RuleBuilder with existing rules story should not overflow.
- minor css fix
- no overflows from the tab container anymore
- n/a
> fix(rule-builder): fix minor css to prevent container overflowing

- packages/react/src/components/EmptyState/EmptyState.jsx
- packages/react/src/components/EmptyState/__snapshots__/EmptyState.story.storyshot
- packages/react/src/components/EmptyState/_emptystate.scss
- packages/react/src/components/Table/__snapshots__/Table.story.storyshot
Closes #2595 
**Summary**
- minor updates to padding/margins to match design specs
- minor updates to padding/margins to match design specs
- updated snapshots
- should match design provided in original issue.
- tests here
> fix(empty-state): minor empty state design updates

- packages/react/src/components/Table/TableHead/_table-head.scss
Closes #1683
**Summary**
The issue was actually already solved by #2669 so it was no longer reproducible, but there were some leftover css using variables no longer present so I clean that up here.
- Remove CSS that was using custom properties (variables) no longer available
- Verify that there is no CSS max-width on the column header elements with class `bx-table-header-label` in the table stories
- Table stories unchanged
> fix(table): removed css that did not and should not work

- packages/react/src/components/DateTimePicker/DateTimePickerV2.jsx
- packages/react/src/components/DateTimePicker/DateTimePickerV2.test.e2e.jsx
- packages/react/src/components/DateTimePicker/DateTimePickerV2.test.jsx
Closes #2801 
**Summary**
- Improves coverage on DateTimePickerV2 with more e2e and jest tests.
> test(date-time-picker-v2): improve coverage

- packages/react/jest.config.js
- packages/react/src/components/List/ListItem/ListItem.test.jsx
Closes #2799
**Summary**
Added more tests 
- tests here
- tests here
> test(listitem): added more tests

- packages/react/src/components/SuiteHeader/IdleLogoutConfirmationModal/IdleLogoutConfirmationModal.test.jsx
Closes #2800 
**Summary**
- increases coverage to 90%+
> test(idle-logout-confirmation-dialog): improve test coverage

- packages/react/jest.config.js
- packages/react/package.json
- packages/react/src/components/ComboChartCard/comboChartHelpers.js
- packages/react/src/components/ComboChartCard/comboChartHelpers.test.js
- packages/react/src/components/TimeSeriesCard/timeSeriesUtils.js
Closes #2804
**Summary**
- Increased summary
- Cleaned up non functioning code
- Removed code for zooming that didn't work because it was immediately overwritten and even if it would not be overwritten it was not working. I think that it was old copy/pasted code from the BarChartComponent. 
- unit tests working
- Verify ComboChart stories 
> 2804 combo chart helpers improve unit test coverage

- packages/react/src/components/Header/_header.scss
Closes #2841 
**Summary**
- add specificity to the header icons and fixed the focus state to remove the blue and match the white focus state
- css changes
- use dev tools to add a new css rule for `.bx--btn--primary { background-color: red; }` and confirm that rule does not override the black design color.
- no other side effects
> fix(suite-header): btn--primary icon colors

- packages/react/jest.config.js
- packages/react/package.json
Closes #2821, #2469
**Summary**
- Bump jest and global test coverage to 90%. 
- Add exceptions for jest items that are covered by e2e tests.
> chore(repo): bump test coverage to 90%+

- packages/angular/src/date-time-picker/custom-date-time.component.ts
- packages/angular/src/date-time-picker/date-time-absolute.component.ts
- packages/angular/src/date-time-picker/date-time-picker.component.ts
- packages/angular/src/date-time-picker/date-time-picker.stories.ts
Closes #2829
**Summary**
- summary_here
- items_here
- tests here
- tests here
> fix(datetimepicker): support blocking dates

- package.json
- packages/react/cypress/support/commands.js
- packages/react/package.json
- packages/react/src/components/DateTimePicker/DateTimePicker.jsx
- packages/react/src/components/DateTimePicker/DateTimePicker.test.e2e.jsx
- packages/react/src/components/DateTimePicker/DateTimePickerV2.jsx
- packages/react/src/components/DateTimePicker/DateTimePickerV2.test.e2e.jsx
- packages/react/src/components/DateTimePicker/DateTimePickerV2.test.jsx
- yarn.lock
Closes #2868  
**Summary**
- Fixes the input focusing events so that versions of flatpickr newer than 4.6.1 can be used.
- changed `focus()` events to `click()` events to properly set focus on "from" input or "to" inputs
- updated tests to confirm this behavior
- You can change the selected range in the preselected absolute range story
- keyboard navigation still works
- tests pass
- DateTimePicker works as expected in other stories
> fix(date-time-picker): flatpickr 4.6.9 fix

- packages/react/src/components/Table/AsyncTable/AsyncTable.jsx
- packages/react/src/components/Table/AsyncTable/asyncTableReducer.js
- packages/react/src/components/Table/Table.mdx
Closes #2855
**Summary**
Fixed pagination and filters for the async table.
- Fixed pagination in the AsyncTable and the asyncTableReducer
- Remove some old comments
- Fixed filters in the AsyncTable
- Updated the docs
- Verify that filters and pagination works in this story https://deploy-preview-2915--carbon-addons-iot-react.netlify.app?path=/story/1-watson-iot-table-table--filtered-sorted-paginated-table-with-asynchronous-data-source
- Verify the new documentation text
- Other AsyncTable functionality works as expected
> fix(asynctable): pagination and filters working

- packages/react/src/components/ComboBox/ComboBox.story.jsx
- packages/react/src/components/ComboBox/__snapshots__/ComboBox.story.storyshot
Closes #2914 
**Summary**
- adds missing props to ComboBox stories
- add props
- check new props are there
- n/a
> chore(combo-box): update stories with missing props

- packages/angular/src/index.ts
Closes #
**Summary**
- summary_here
- items_here
- tests here
- tests here
> fix(rule-builder): export rule-builder so it can be used

- packages/react/package.json
- packages/react/src/components/PieChartCard/PieChartCard.jsx
- yarn.lock
Closes #3169 
**Summary**
- Upgrades to the newest version of @carbon/charts
- Upgrades to the newest version of @carbon/charts
- check charts in storybook to ensure no issues
- check charts in storybook to ensure no issues
> feat: upgrade @carbon/charts

- packages/react/src/components/Table/TableToolbar/_table-toolbar.scss
Closes # [3177](https://github.com/carbon-design-system/carbon-addons-iot-react/issues/3177)
**Summary**
Margin in table#toolbar is not correct in RTL mode 
Added margin-right style in element : html[dir="rtl"] .bx--action-list .bx--btn .bx--btn__icon
- tests here
- tests here
> fix(table): margin between trash icon and delete on toolbar

- packages/react/.storybook/__snapshots__/Welcome.story.storyshot
- packages/react/src/components/ProgressBar/ProgressBar.jsx
- packages/react/src/components/ProgressBar/ProgressBar.mdx
- packages/react/src/components/ProgressBar/ProgressBar.story.jsx
- packages/react/src/components/ProgressBar/ProgressBar.test.a11y.jsx
- packages/react/src/components/ProgressBar/ProgressBar.test.jsx
- packages/react/src/components/ProgressBar/__snapshots__/ProgressBar.story.storyshot
- packages/react/src/components/ProgressBar/_progress-bar.scss
- packages/react/src/components/ProgressBar/thresholdPropTypes.js
- packages/react/src/components/RuleBuilder/__snapshots__/RuleBuilder.story.storyshot
- packages/react/src/components/Table/TableSaveViewModal/__snapshots__/TableSaveViewModal.story.storyshot
- packages/react/src/components/TileGallery/__snapshots__/TileGallery.story.storyshot
- packages/react/src/components/ValueCard/Attribute.jsx
- packages/react/src/hooks/useMatchingThreshold.js
- packages/react/src/hooks/useMerged.js
- packages/react/src/hooks/useMerged.test.js
- packages/react/src/index.js
- packages/react/src/styles.scss
- packages/react/src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Closes #3215 
**Summary**
- Adds the new ProgressBar component--which I'm not sure is a good name for this component--the ability to change the colors based on threshold levels seems lend more to a StatusBar component (perhaps?). It is built on the experimental Carbon ProgressBar, adds the text value label and icon (when needed) to the top-right side of the component, and gives the ability to pass an array of thresholds. These thresholds match what is already in place with ValueCards with a couple minor differences. The comparison can be a simple `>`, `>=`, `=`, `<`, `<=`, or it can be a function. The addition of the function allows for more complex comparisons like "greater-than-or-equal-to X AND less-than-Y". Also, the color can be provided as a simple string hex color, or as an object …
> feat(progress-bar): initial addition of new progress bar component

- packages/react/src/components/Table/Table.jsx
- packages/react/src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Closes #3221
**Summary**
Small fix to use correct PropType for the table `data` prop
na
- tests here
> fix(table): fix incorrect data proptype

- packages/react/src/components/Table/Table.main.story.jsx
- packages/react/src/components/Table/Table.story.helpers.jsx
- packages/react/src/components/Table/TableBody/TableBodyRow/__snapshots__/TableBodyRow.story.storyshot
- packages/react/src/components/Table/TableSaveViewModal/__snapshots__/TableSaveViewModal.story.storyshot
- packages/react/src/components/Table/__snapshots__/Table.main.story.storyshot
- packages/react/src/components/Table/__snapshots__/Table.story.storyshot
- packages/react/src/components/Table/__snapshots__/TableColumnCustomization.story.storyshot
- packages/react/src/components/Table/mdx/RowExpansion.mdx
- packages/react/src/components/Table/mdx/Table.mdx
- packages/react/src/components/TableCard/__snapshots__/TableCard.story.storyshot
- packages/react/src/components/TileCatalogNew/__snapshots__/TileCatalogNew.story.storyshot
- packages/react/src/components/TileGallery/__snapshots__/TileGallery.story.storyshot
- packages/react/src/components/TimeSeriesCard/__snapshots__/TimeSeriesCard.story.storyshot
- packages/react/src/components/WizardModal/__snapshots__/WizardModal.story.storyshot
Closes #3252
**Summary**
Creates a story for row expansion and updates the docs. Part of #2820
- New story
- Update docs
- Fix to turn off Table playground story knobs in production
- Small story code cleanup
- Test the story
- Proof read the docs
- n.a.
> 3252 table create story for row expansion

- packages/angular/src/date-time-picker/custom-date-time.component.ts
- packages/angular/src/date-time-picker/date-time-absolute.component.ts
- packages/angular/src/date-time-picker/date-time-picker.component.ts
Closes #2930 
**Summary**
- summary_here
- items_here
- tests here
- tests here
> fix(dateTimePicker): modify custom range issue

- packages/react/docs/guides/onboarding.md
Closes #3173 
**Summary**
- A list of common styles and issues to help new developers be on-boarded to this codebase.
- added on-boarding docs 
- check for typos or missing information you think is relevant
- n/a
> docs(repo): initial onboarding documentation

- packages/react/src/components/ProgressBar/ProgressBar.jsx
- packages/react/src/components/ProgressBar/ProgressBar.mdx
- packages/react/src/components/ProgressBar/ProgressBar.test.jsx
- packages/react/src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Closes #
**Summary**
- Another small addition necessary for the StatusBar in graphite
- add className prop
- add tests
- add to docs
- tests pass
- tests here
> feat(status-bar): add className prop

- packages/react/.storybook/main.js
- packages/react/netlify.toml
- packages/react/package.json
- yarn.lock
Closes #3344 
**Summary**
- use storybook-addon-turbo-builds to optimize the netlify build process. This uses esbuild instead of terser for minification and turns off sourcemaps for production builds.
- I also modified the netlify configs slightly. I added `--ignore-scripts` to the `YARN_FLAGS` env variable. This prevents the post-install scripts that generate the `styles` package from running, since we don't need to generate that every time for React builds. I also changed the actual build command to only trigger the react build with `NODE_ENV=production yarn --cwd packages/react build:storybook`
- install storybook-addons-turbo-builds
- remove sourcesmaps for production builds in webpackFinal
- …
> chore(repo): try esbuild storybook plugin to speed up builds

- packages/react/src/components/Table/tableReducer.js
- packages/react/src/components/Table/tableReducer.test.jsx
Closes #3342 
**Summary**
- updates the tableReducer function to allow searching by "false" boolean values
- updates reducer
- add test case
- open the table playground
- turn on search
- search by "false"
- confirm rows with "false" boolean values appear in results
- confirm no adverse effects to search
> fix(table): allow searching by "false" boolean values

- packages/react/src/components/ResourceList/ResourceList.jsx
- packages/react/src/components/ResourceList/ResourceList.test.jsx
- packages/react/src/components/ResourceList/__snapshots__/ResourceList.story.storyshot
- packages/react/src/components/ResourceList/_resourcelist.scss
- packages/react/src/styles.scss
Closes #3312 
**Summary**
convert style component to scss fro Resourcelist
- added new scss file
- removed 3 style components from Resourcelist
- tests here
- tests here
> fix(resourcelist): convert style component to scss

- packages/react/src/components/ReadOnlyValue/ReadOnlyValue.jsx
- packages/react/src/components/ReadOnlyValue/ReadOnlyValue.mdx
- packages/react/src/components/ReadOnlyValue/ReadOnlyValue.story.jsx
- packages/react/src/components/ReadOnlyValue/ReadOnlyValue.test.jsx
- packages/react/src/components/ReadOnlyValue/__snapshots__/ReadOnlyValue.story.storyshot
- packages/react/src/components/ReadOnlyValue/_read-only-value.scss
- packages/react/src/styles.scss
Closes #3124
**Summary**
- New component that displays information that is not editable in a similar structure as text inputs.  Though the information cannot be edited, a user can copy the displayed information.
**Stacked:**
**Inline:**
- New component ReadOnlyValue
- Validate that the components work and is presented as the [design specs](https://pages.github.ibm.com/ai-applications/design/components/read-only-value/style) 
- N/A
> feat(readonlyvalue): new component readonlyvalue

- packages/react/.storybook/__snapshots__/Welcome.story.storyshot
- packages/react/src/index.js
- packages/react/src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
**Summary**
- Missed new component export
- export component
- N/A
- N/A
> Export readonlyvalue

- packages/react/package.json
- yarn.lock
App team reported that their bundler was not resolving this package. This fix brings in the updated package to help resolve the issue. 
Closes https://github.com/davidicus/use-lang-direction/issues/10
**Summary**
- updated version of `use-lang-direction` package
- updated `package.json`
- all test should still pass where we test direction. 
- Table should still look normal in RTL
> chore(use-lang-direction):update package

- packages/react/src/utils/cardTypeUtilityFunctions.js
Closes #
**Summary**
- Small correction on use of color from chart content
- fix(cardtype): fix on color variable name
- 
- Sparkline should be gradient
- N/A
> fix(cardtype): fix on color variable name

- .github/CODEOWNERS
Closes #3391 
**Summary**
- Update list of code owners
> 3391 reviewers

- .gitignore
Needed to add build folders to gitignore
> chore(repo): add to gitignore for build folders

- packages/react/src/components/CardEditor/CardEditForm/CardEditFormItems/DataSeriesFormItemModal.jsx
- packages/react/src/components/CardEditor/CardEditForm/CardEditFormItems/DataSeriesFormItemModal.test.jsx
- packages/react/src/components/CardEditor/CardEditor.story.jsx
- packages/react/src/components/DashboardEditor/DashboardEditor.story.jsx
- packages/react/src/components/DashboardEditor/editorUtils.jsx
- packages/react/src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Closes #3427 
**Summary**
changed downsample implementation 
- Added Version prop and removed hasDownsampleMethods from DataSeriesFormItemModal 
- tests here
- tests here
> chore(Card Editor) Fix downsample methods

- packages/react/src/components/Table/TableToolbar/TableToolbarAdvancedFilterFlyout.jsx
- packages/react/src/components/Table/TableToolbar/TableToolbarAdvancedFilterFlyout.test.jsx
Closes #3437
**Summary**
- Add fix to display the selected filter when is a date picker.
- Display selected filter on date picker field after applying the filter.
- Navigate to the advanced filter and try to filter data using the date picker.
- Apply the filter.
- Open again the filters. Should display the previously selected filter instead of clearing the values.
- Is not a breaking change.
> fix(table): show selected filter in date picker

- packages/react/src/components/Card/Card.jsx
- packages/react/src/components/Card/__snapshots__/Card.story.storyshot
- packages/react/src/components/ComboChartCard/__snapshots__/ComboChartCard.story.storyshot
- packages/react/src/components/ListCard/__snapshots__/ListCard.story.storyshot
- packages/react/src/components/MeterChartCard/__snapshots__/MeterChartCard.story.storyshot
- packages/react/src/components/PieChartCard/__snapshots__/PieChartCard.story.storyshot
- packages/react/src/components/SparklineChartCard/__snapshots__/SparklineChartCard.story.storyshot
- packages/react/src/components/StackedAreaChartCard/__snapshots__/StackedAreaChart.story.storyshot
**Summary**
- EmptyState component need body as mandatory parameter. So setting it as empty string. One can over ride this value with optional `overrides?.errorMessage?.prop?.body`props. 
- fix(card): add default empty body to empty state component
- All the dashboards and card rendering work without any issue
- All the dashboards and card rendering work without any issue
> fix(card): add default empty body to empty state component

- packages/react/src/components/Dashboard/__snapshots__/Dashboard.story.storyshot
- packages/react/src/components/TableCard/TableCard.jsx
- packages/react/src/components/TableCard/TableCard.story.jsx
- packages/react/src/components/TableCard/__snapshots__/TableCard.story.storyshot
- packages/react/src/components/TileCatalogNew/__snapshots__/TileCatalogNew.story.storyshot
- packages/react/src/components/TileGallery/__snapshots__/TileGallery.story.storyshot
- packages/react/src/components/TimeSeriesCard/__snapshots__/TimeSeriesCard.story.storyshot
**Summary**
- We need to support table card with no range, the way we have it today even if it's supposed to be false it fallback to true. Fixed that.
- fix(tablecard): fix on support false value for table range
- chore(snapshots): snapshots updates
- TableCard when have availableActions range prop set to false, not render the range toolbar component
- TableCard should keep working as expected.
> Prevent range to always exist in TableCard

- packages/react/src/components/SuiteHeader/_suite-header.scss
**Summary**
- Fix for suite header, when a user without admin access was still being able to see admin icon
- CSS update
- Check that when routes admin not provided the admin icon is not being shown
- N/A
> fix(suiteheader): suite header css class fix

- packages/react/src/components/Header/_header.scss
Closes #3488 
**Summary**
- set `overflow-y: scroll`on AppSwitcher container. 
- added `overflow-y: scroll` to `bx--app-switcher` class in _header.scss
- go to SuiteHeader story and click on default story
- add a few more application in the `applications` prop
- click on application icon in the right corner and see if scroll bar works to show the bottom application
> fix(header): added overflow-y on app switcher

- packages/angular/package.json
- packages/react/package.json
Closes #3455
**Summary**
Copied from issue #3455
glob-parent npm package in version 5.1.2 is used as dependency of @carbon/telemetry@0.0.0-alpha.6 package used in this project.
Solution
Update @carbon/telemetry to version 0.1.0 to mitigate this problem
- updated package.json for both react and angular packages
- tests here
- tests here
> chore(deps): update telemetry due to security vulnerability

- packages/react/src/components/DateTimePicker/DateTimePicker.story.jsx
- packages/react/src/components/DateTimePicker/__snapshots__/DateTimePicker.story.storyshot
- packages/react/src/components/TimePickerSpinner/TimePickerSpinner.story.jsx
- packages/react/src/components/TimePickerSpinner/__snapshots__/TimePickerSpinner.story.storyshot
Closes #3517 
**Summary**
- TimePickerSpinner has stand-alone story, on its own level
- [chore(time picker spinner): move story to upper level](https://github.com/carbon-design-system/carbon-addons-iot-react/commit/2fa14e110783d599dcdeea36bb67c60baba3d4c3)
- [chore(storyshots): update](https://github.com/carbon-design-system/carbon-addons-iot-react/commit/40d98692dce55e32be5f56dc5188a9036a925d8e)
- TimePickerSpinner Story
- Date time range selector Story
- tests here
> chore(time picker spinner): move story to upper level

- packages/react/src/components/SideNav/_side-nav.scss
Closes #3525 
**Summary**
- Search input was blocked by side menu links
- fix(sidenav): update the z-index on search 
Before:
After:
> fix(sidenav): fix the issue search bar blocked by menu links

- packages/react/src/components/CardEditor/CardEditForm/CardEditFormItems/DataSeriesFormItems/DataSeriesFormContent.jsx
- packages/react/src/components/CardEditor/CardEditForm/CardEditFormItems/TableCardFormItems/TableCardFormContent.jsx
- packages/react/src/components/CardEditor/CardEditForm/CardEditFormItems/TableCardFormItems/TableCardFormContent.test.jsx
- packages/react/src/components/CardEditor/CardEditForm/CardEditFormItems/ThresholdsFormItem.jsx
- packages/react/src/components/DashboardEditor/editorUtils.jsx
- packages/react/src/components/DashboardEditor/editorUtils.test.jsx
- packages/react/src/components/DateTimePicker/DateTimePicker.jsx
- packages/react/src/components/DateTimePicker/DateTimePickerV2.jsx
- packages/react/src/components/DateTimePicker/DateTimePickerV2WithTimeSpinner.jsx
- packages/react/src/components/DateTimePicker/DateTimePickerV2WithoutTimeSpinner.jsx
- packages/react/src/components/Table/TableColumnCustomization.story.jsx
- packages/react/src/hooks/useUniqueId.jsx
Closes https://github.com/carbon-design-system/carbon-addons-iot-react/issues/3554
**Summary**
- add meta data of the data source
- feat(editorutils): Added eventName, dataItemType, columnType, uuid, kpiFunctionDto,hasStreamingMetricEnabled property of the dataItems in the meta data.
- removed * import of uuid package
- tests here
- tests here
> feat(editorutils): add meta data of the data source

- packages/react/src/components/DashboardEditor/DashboardEditor.jsx
Closes https://github.com/carbon-design-system/carbon-addons-iot-react/issues/3555
**Summary**
- send card configuration on card select instead of card id
- feat(dashboardeditor): send card configuration on card select
- tests here
- tests here
> feat(dashboardeditor): send card configuration on card select

- packages/react/src/components/Card/__snapshots__/Card.story.storyshot
- packages/react/src/components/DateTimePicker/DateTimePicker.jsx
- packages/react/src/components/DateTimePicker/DateTimePicker.story.jsx
- packages/react/src/components/DateTimePicker/DateTimePicker.test.jsx
- packages/react/src/components/DateTimePicker/DateTimePickerV2.jsx
- packages/react/src/components/DateTimePicker/DateTimePickerV2.story.jsx
- packages/react/src/components/DateTimePicker/DateTimePickerV2.test.jsx
- packages/react/src/components/DateTimePicker/DateTimePickerV2WithTimeSpinner.jsx
- packages/react/src/components/DateTimePicker/DateTimePickerV2WithoutTimeSpinner.jsx
- packages/react/src/components/DateTimePicker/__snapshots__/DateTimePicker.story.storyshot
- packages/react/src/components/DateTimePicker/__snapshots__/DateTimePickerV2.story.storyshot
- packages/react/src/components/DateTimePicker/_date-time-picker.scss
- packages/react/src/components/DateTimePicker/_date-time-pickerv2.scss
- packages/react/src/components/DateTimePicker/dateTimePickerUtils.js
- packages/react/src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Closes #3558 #3569
**Summary**
- Support invalid state and an invalid helper text in `DateTimePicker` and `DateTimePickerV2` 
- Support disabled state in `DateTimePicker` and `DateTimePickerV2` 
- added `invalid`, `invalidText`, `invalidLabel` props in `DateTimePicker` 
- added `invalid`, `invalidText` props in `DateTimePickerV2` 
- updated `disabled` props to disable menu button 
- updated stories to reflect the new props
DateTimePicker
DateTimePickerV2
- tests here
> Invalid and disabled props in DateTimePicker and DateTimePickerV2

- packages/react/package.json
- packages/react/src/components/CardEditor/CardEditForm/CardEditForm.jsx
- packages/react/src/components/CardEditor/CardEditForm/CardEditFormContent.jsx
- packages/react/src/components/CardEditor/CardEditForm/CardEditFormItems/DataSeriesFormItemModal.jsx
- packages/react/src/components/CardEditor/CardEditForm/CardEditFormItems/DataSeriesFormItems/DataSeriesFormContent.jsx
- packages/react/src/components/CardEditor/CardEditForm/CardEditFormItems/ImageCardFormItems/ImageCardFormContent.jsx
- packages/react/src/components/CardEditor/CardEditForm/CardEditFormItems/TableCardFormItems/TableCardFormContent.jsx
- packages/react/src/components/CardEditor/CardEditor.jsx
- packages/react/src/components/DashboardEditor/DashboardEditor.jsx
- packages/react/src/components/HotspotEditorModal/HotspotEditorDataSourceTab/HotspotEditorDataSourceTab.jsx
- packages/react/src/components/HotspotEditorModal/HotspotEditorModal.jsx
- packages/react/src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Closes #
**Summary**
- updating the dashboard editor functions in actions props with default noop functions. 
- test(dashboardeditor): adding noop on dashboard editor functions
- tests here
- tests here
> test(dashboardeditor): adding noop on dashboard editor functions

- .github/stale.yml
Set up config file as per [README.md](https://github.com/probot/stale)
> [stale-bot]: add config to auto close old PRs

- packages/react/package.json
**Summary**
This packages is part of the `@carbon/telemetry` packages. Their latest code has a range that includes this problematic version. This PR adds a resolution to our package.json to a version past the vulnerability. 
- update `packages/react/package.json` to include resolution for `got`
All checks should pass and our test app should build
> REPO: update `got` package past vulnerability

- packages/react/src/components/BarChartCard/barChartUtils.js
Closes Monitor - https://github.ibm.com/wiotp/Maximo-Asset-Monitor/issues/4717
**Summary**
- summary_here
- [fix(barchartutils): condition check for categorydatasourceid rather than assigning undefined
- tests here
- tests here
> fix(barchartutils): condition check for categorydatasourceid

- packages/react/docs/guides/onboarding.md
Part of #3172 
**Summary**
- Add info about tech stack and libraries
- Update `onboarding.md`
- tests here
- tests here
> docs(onboarding): tech stack and libraries

- packages/react/src/components/Table/Table.jsx
- packages/react/src/components/Table/TableHead/FilterHeaderRow/FilterHeaderRow.jsx
- packages/react/src/components/Table/TableHead/TableHead.jsx
- packages/react/src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
**Summary**
- Update prop type for filter row icon
- Replace `PropTypes.node` with `PropTypes.oneOf([PropTypes.func, PropTypes.object])`
- Update `publicAPI` snapshot
- tests here
- tests here
> fix(table): update prop types for filter row icon

- packages/react/src/components/ReadOnlyValue/ReadOnlyValue.jsx
- packages/react/src/components/ReadOnlyValue/ReadOnlyValue.mdx
- packages/react/src/components/ReadOnlyValue/ReadOnlyValue.story.jsx
- packages/react/src/components/ReadOnlyValue/ReadOnlyValue.test.jsx
- packages/react/src/components/ReadOnlyValue/ReadOnlyValuePropTypes.js
- packages/react/src/components/ReadOnlyValue/__snapshots__/ReadOnlyValue.story.storyshot
- packages/react/src/components/ReadOnlyValue/_read-only-value.scss
- packages/react/src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Closes #3655 
**Summary**
- Add prop for loading state
- Add `isLoading` prop to component
- Add `skeletonLoadingLabel` and `skeletonLoadingValue` for configuration
- Update stories, add new story `with async data load`
- Update `publicAPI`
- Update docs
- Go to [ReadOnlyValue / multiple values - stacked](https://deploy-preview-3679--carbon-addons-iot-react.netlify.app/?path=/story/1-watson-iot-readonlyvalue--multiple-values-stacked)
- In the knob tab "Other" enable `isLoading`
- Verify loading state
</br>
- Go to [ReadOnlyValue / multiple values - inline](https://deploy-preview-3679--carbon-addons-iot-react.netlify.app/?path=/story/1-watson-iot-readonlyvalue--multiple-values-inline)
- In the knob …
> feat(readonlyvalue): add loading state

- packages/react/src/components/CardEditor/CardEditForm/CardEditFormItems/DataSeriesFormItems/DataSeriesFormSettings.jsx
- packages/react/src/components/CardEditor/CardEditForm/CardEditFormItems/DataSeriesFormItems/DataSeriesFormSettings.test.jsx
- packages/react/src/components/CardEditor/__snapshots__/CardEditor.story.storyshot
Closes #3680
**Summary**
- Set empty string in case of null or undefined values
- DataSeriesFormSettings: use nullish coalescing operator to set empty strings
- Render component with all attributes from content filled
- Re-render component with some of them missing
- tests here
> fix(dataseriesformsettings): Set empty strings for missing values

- packages/react/src/components/CardEditor/CardEditForm/CardEditFormItems/DataSeriesFormItemModal.jsx
**Summary**
- merge the duplicate code into one if block to reduce number of lines
- refactor(dataseriesformitemmodal): merge the duplicate code into one if block
> refactor(dataseriesformitemmodal): merge the dublicate code into one if block

- packages/react/package.json
- packages/react/src/components/OverflowMenu/OverflowMenu.test.jsx
- packages/react/src/components/OverflowMenu/_overflow-menu.scss
- packages/react/src/components/OverflowMenu/index.jsx
- packages/react/src/components/Table/Table.jsx
- packages/react/src/components/Table/Table.story.helpers.jsx
- packages/react/src/components/Table/TablePropTypes.js
- packages/react/src/components/Table/TableToolbar/TableToolbar.jsx
- packages/react/src/components/Table/TableToolbar/_table-toolbar.scss
- packages/react/src/components/Table/mdx/Table.mdx
- packages/react/src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
- yarn.lock
Closes #3714 
**Summary**
- Add prop to enable label text in `OverflowMenu` button
- Add prop for `OverflowMenu` component
- Add i18n prop for `Table` component
- Update docs
- Update public API
- Go to [this story](https://deploy-preview-3718--carbon-addons-iot-react.netlify.app/?path=/story/1-watson-iot-table--playground)
- In the "i18n" knob write some text in `batchActionsOverflowMenuText`
- In the "Selections & actions" knob enable `useRadioButtonSingleSelect` and reselect `hasRowSelection: multi`
- Select some row
- Verify that overflow button in batch actions has label
- tests here
**Things to look for during …
> feat(overflowmenu): add support for button label

- packages/react/src/components/SuiteHeader/_suite-header.scss
Closes #3694
**Summary**
- Align icon buttons vertically in SuiteHeader
- Remove overlapping background in order to display border-bottom
- Update styles for SuiteHeader
- Go to [this story](https://deploy-preview-3708--carbon-addons-iot-react.netlify.app/?path=/story/1-watson-iot-ui-shell-suiteheader-multi-workspace--header-with-custom-action-items)
- Verify that all icons aligned vertically
- Verify that header has persistent border-bottom
- tests here
> fix(suiteheader): icon vertical alignment

- .github/workflows/test-app.yml
- packages/react/src/utils/__tests__/cardUtilityFunctions.test.jsx
- packages/react/src/utils/cardUtilityFunctions.js
Closes #3725
**Summary**
- Add handler to prevent break for hotspot content with threshold and no readings
- cardUtilityFunctions: Add handler to null input for findMatchingThresholds method
- test-app.yml: set node version due to [build error](https://github.com/carbon-design-system/carbon-addons-iot-react/actions/runs/4224697760/jobs/7336233752)
1. Go to Dashboard editor
2. Create an image card and add image to it
3. Edit image to include a hotspot anywhere in the image
4. Give it a name, description and icon.
5. Select a datasource to associate the hotspot and edit the data item to add a threshold to it.
6. Save dashboard
7. Find the dashboard in monitor and click in the hotspot icon
**Regression …
> fix(cardutilityfunctions): add null handler

- packages/react/src/components/DateTimePicker/DateTimePicker.test.e2e.jsx
- packages/react/src/components/DateTimePicker/DateTimePickerV2.story.jsx
- packages/react/src/components/DateTimePicker/DateTimePickerV2.test.e2e.jsx
- packages/react/src/components/DateTimePicker/DateTimePickerV2WithTimeSpinner.jsx
- packages/react/src/components/DateTimePicker/dateTimePickerUtils.js
Closes #
**Summary**
- fix dayjs() locale issue in dateTimePickerUtiles.js
- Go to single select story
- change locale to `jp` or `ko`
- see date and time work properly
https://user-images.githubusercontent.com/24279794/222791825-ab816a21-73d6-4979-87a1-98a28a26a060.mov
> fix(datetimepickerv2): fix locale issue

- packages/react/src/components/Table/TableHead/ColumnHeaderRow/ColumnHeaderRow.jsx
**Summary**
- Removed white space
- Remove white space from HeaderRow component
- tests here
- tests here
> fix(table): remove unnecessary space

- packages/react/src/components/Header/HeaderAction/HeaderActionPanel.jsx
- packages/react/src/components/Header/HeaderPropTypes.js
- packages/react/src/components/SuiteHeader/__snapshots__/MultiWorkspaceSuiteHeader.story.storyshot
**Summary**
- Fix prop type id issue.
- Move `id` prop-type from HeaderActionPropTypes to HeaderActionPanel since HeaderActionPropTypes are common with HeaderAction component.
- tests here
- tests here
> fix(SuiteHeader): header action panel proptypes 

- packages/react/src/components/Table/Table.jsx
[GRAPHITE-65019](https://jsw.ibm.com/browse/GRAPHITE-65019)
**Summary**
- Change `title` for close button in filter tag
- Replace filter tag string with i18n label
- Go to [this story](https://deploy-preview-3811--carbon-addons-iot-react.netlify.app/?path=/story/1-watson-iot-table--with-filtering)
- Enable `hasAdvancedFilter` in the knobs
- Hover over close icon in the filter tag
- Verify that `Clear filter` tooltip appeared
- tests here
> fix(table): change filter tag close button title
